### ISSUE TITLE
Alternative to Regular Expressions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#1]
Regular expressions in step definitions should always be part of Cucumber, but we should provide a simpler alternative for those who wish. Good Gherkin shouldn't require the complexities of RegExp anyway - if it does it's usually a sign the Gherkin is too complicated.

There are already several alternative pattern syntaxes out there, which has been discussed in [this thread](https://groups.google.com/forum/#!msg/cukes/0j_5u9zkZng/1rbOOVDzHMcJ).

There are also some interesting alternatives on [this c2 page](http://c2.com/cgi/wiki?AlternativesToRegularExpressions) and [this HN thread](https://news.ycombinator.com/item?id=9751555).

Some things to consider:

* Cucumber should be able to print snippets in the new expression syntax
* A spec and common test suite for different implementations
* The various language implementations should live in separate repos
* It should compile down to RegExp (probably)

### Completion

The new syntax must be implemented on the following platforms before we can close this issue

* [ ] cucumber-ruby
* [ ] cucumber-jvm
* [ ] cucumber-js
* [ ] specflow

**Comment by mattwynne** [comment]
See also https://github.com/cucumber/cucumber-ruby/pull/708

**Comment by jbpros** [comment]
See https://github.com/cucumber/cucumber-js/issues/218 too

**Comment by aslakhellesoy** [comment]
The [Cucumber Expressions](http://docs.cucumber.io/cucumber-expressions) library is complete enough to start integrating into Cucumbers now, so I'll close this.
