### ISSUE TITLE
Remove unnecessary tags from cucumber HTML Report

### ISSUE THREAD

**Issue by Aswini999** [cucumber/cucumber#101]
## Summary

Is it possible to have a option to remove tags from Cucumber HTML/Json Report if there are multiple tags for a scenario or scenario outline?. Displaying all tags to a scenario leads to unnecessary misunderstandings.

## Expected Behavior
It will be good to have only tags specified  with option `--tags <tagname>` is displayed in report

## Environment
* Version used:2.4.0
* Operating System and version: Windows 7
* Link to your project:

**Comment by KyleFairns** [comment]
In some ways I would agree with you, but in other ways I do not concur.

Many others that use cucumber still want all of the tags to be displayed within the report, for knowledge purposes,, however in the JSON, perhaps a new section could be added on exactly how the cucumber file was run, by taking the CLI arguments given and putting this in the 0th item in the JSON:

```json
[ 
   {
    "info": {
      "cucumber_location": "node_modules/.bin/cucumber-js",
      "formatters": {
          "pretty": true,
          "json": "./reports/reports.json"
       },
       "tags": "not @skip and (@foo or @bar)",
       "other argument in command line": "etc"
     }
   },
  "The rest of the suite here"
]
```

More items would later be able to be put into the `info` section of the JSON file if needed, and it would add the functionality that you want, without removing the functionality that may be required by other users.

**Comment by mattwynne** [comment]
Please note that our medium-term strategy is for the current JSON formatters to be replaced by the [event protocol](https://github.com/cucumber/cucumber/tree/master/event-protocol) which is still currently under development. If you're interested in this, you may want to follow along with [the discussion](https://github.com/cucumber/cucumber/labels/event-protocol) about the structure and content of the protocol.

**Comment by aslakhellesoy** [comment]
Closing this as the existing HTML reporters are being phased out and will be replaced by a new, cross platform HTML formatter
