### ISSUE TITLE
cucumber-gherkin-13.0.0/lib/gherkin/query.rb:19:in `update_feature'

### ISSUE THREAD

**Issue by matheuspiculi** [cucumber/cucumber#1041]
undefined method `tags' for nil:NilClass (NoMethodError)
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/query.rb:19:in `update_feature'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/query.rb:8:in `update'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core/gherkin/parser.rb:23:in `block in document'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:32:in `yield'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:32:in `block (2 levels) in messages'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:79:in `yield'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:79:in `block (2 levels) in sources'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:78:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:78:in `block in sources'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:25:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:25:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:25:in `block in messages'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core/gherkin/parser.rb:21:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core/gherkin/parser.rb:21:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core/gherkin/parser.rb:21:in `document'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:33:in `block in parse'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:32:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:32:in `parse'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:24:in `compile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-4.0.0/lib/cucumber/runtime.rb:78:in `run!'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-4.0.0/lib/cucumber/cli/main.rb:29:in `execute!'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cucumber-4.0.0/bin/cucumber:9:in `<top (required)>'
C:/Ruby25-x64/bin/cucumber:23:in `load'
C:/Ruby25-x64/bin/cucumber:23:in `<main>'

**Comment by vincent-psarga** [comment]
Hi,

Could you give us some extra information about this, like the version of `cucumber-ruby` you are using ? We've had this issue with `4.0.0.rc.3` if I recall correctly but this should be fixed in the final `4.0.0` release.

Could you also include your `Gemfile` content ?

Thanks
