### ISSUE TITLE
html report is not working in Cucumber 6.0.0

### ISSUE THREAD

**Issue by dhana-r** [cucumber/cucumber#1045]
## Summary

**In cucumber 6.0.0, The html report from the default cucumber plugin is not rendering**

## Expected Behavior

When I used cucumber 6.0.0 library for my cucumber test, the default html report plugin is generating reports which should be rendered in a browser without issue

## Current Behavior

But the browser(tired in chrome, edge and firefox)  is rendering blank page, on checking the console messages in developer tools I could see below error messages. Note the test works properly in cucumber 5.7.0
```
Uncaught SyntaxError: Invalid regular expression: /[\�\&\?\`\>\^\<\
\"\	\_\|\'\*\\\:\,\@\$\=\!\{\[\(\#\%\.\+\}\]\)\;\/]|??|=?|fj|>?|<?/: Nothing to repeat
    at new RegExp (<anonymous>)
    at u ((index):207)
    at Object.19../maps/entities.json ((index):207)
    at i ((index):207)
    at (index):207
    at Object.20../decode ((index):207)
    at i ((index):207)
    at (index):207
    at Object.5../foreignNames.json ((index):207)
    at i ((index):207)
```
## Steps to Reproduce (for bugs)

1. Create a selenium(v3.141.59) web test with cucumber-java & cucumber-junit(v6.0.0)
2. ensure you enable plugins html, json and pretty as below
`plugin = {"html:target/reports/cucumber-html-report.html",
                "json:target/reports/cucumber.json",
                "pretty"},`
3. run using junit 4.13 runner
4. check the html report in browser

## Context & Motivation

Want to use the Cucumber 6 version

## Your Environment

* Version used: 6.0.0
* Operating System and version: Windows 10 pro
* Link to your project: NA
Kindly let me know if more information is needed

**Comment by mpkorstanje** [comment]
We'll be need a more information to reproduce the problem. Looking at the error message I think you have an interesting regex somewhere. Could you eliminate some features scenarios and steps until you can reproduce the error with a minimal amount of step definitions.

**Comment by dhana-r** [comment]
Attached zipped sample maven project. 
Kindly refer cucumber-html-report sub module and also the reports , which is causing issue, are present inside the target folder.


[Bug-cucumber-html-report.zip](https://github.com/cucumber/cucumber/files/4766133/Bug-cucumber-html-report.zip)

**Comment by mpkorstanje** [comment]
Looking at the contents of `cucumber-html-report.html` it would appear that you are using an older version of `io.cucumber:html-formatter`. 

This can only happen if you have explicitly declared this as a dependency. Because `cucumber-html` is a transitive dependency, even if you do not declare it Maven will still download the correct version for you.

You should remove the `html-formatter` as a dependency from your project as well as any other `io.cucumber` dependencies. The only exceptions being `cucumber-java` and `cucumber-junit`.

**Comment by dhana-r** [comment]
Thanks @mpkorstanje for the explanation. But it puzzles me in my dependencies(i.e. from parent module) I don't have any html-formatter dependency, it has only cucumber-java and cucumber-junit. In fact shared the entire project. If you don't mind can you kindly point to the exact mistake in the pom ? I don't want to waste your time but I could n't find it myself.

**Comment by mpkorstanje** [comment]
You didn't include the parent pom in the zip file. Could you share an executable version of your project?

**Comment by dhana-r** [comment]
Sorry, I thought I zipped entire project including parent but missed it. Below is the parent pom.
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>cucumber-report</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <cucumberVersion>6.0.0</cucumberVersion>
        <seleniumVersion>3.141.59</seleniumVersion>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumberVersion}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumberVersion}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${seleniumVersion}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>
    </dependencies>
    <packaging>pom</packaging>

    <modules>
        <module>cucumber-html-report</module>
        <module>cucumber-pretty-report</module>
        <module>cucumber-json-report</module>
        <module>cucumber-xml-report</module>
        <module>cucumber-progress-report</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>test-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

**Comment by mpkorstanje** [comment]
Ah thanks. But this pom would appear to be part of a larger project. At a glance it does look like the dependencies are done right. Would you mind reporting the output from:

```
import java.nio.charset.Charset;
import java.io.InputStreamReader;
import java.io.FileInputStream;

public class PrintCharSets {
        public static void main(String[] args) throws Exception {
                System.out.println("file.encoding=" + System.getProperty("file.encoding"));
                System.out.println("Charset.defaultCharset=" + Charset.defaultCharset());
                System.out.println("InputStreamReader.getEncoding=" + new InputStreamReader(new FileInputStream("pom.xml")).getEncoding());
        }
}
```

**Comment by dhana-r** [comment]
It looks like UTF-8 encoding.
Below is the output:

> file.encoding=UTF-8
>Charset.defaultCharset=UTF-8
>InputStreamReader.getEncoding=UTF8

**Comment by dhana-r** [comment]
Interesting when I run the same inside my cucumber test, I see Cp1252

> file.encoding=Cp1252
Charset.defaultCharset=windows-1252
InputStreamReader.getEncoding=Cp1252

**Comment by mpkorstanje** [comment]
Does the problem go away if you provide `-Dfile.encoding=UTF-8 ` to the JVM that runs your Cucumber tests?

**Comment by dhana-r** [comment]
No, I am seeing the regex error still. Below is output of print statements
>file.encoding=UTF-8
Charset.defaultCharset=windows-1252
InputStreamReader.getEncoding=Cp1252

**Comment by dhana-r** [comment]
Hi @mpkorstanje , is this fix available for use ?

**Comment by mpkorstanje** [comment]
Soon enough.

**Comment by dhana-r** [comment]
Thanks, Kindly let me know which version I should use when it is available.

**Comment by mpkorstanje** [comment]
Should be fixed in v6.1.1 and available from maven central in a few hours.

**Comment by mpkorstanje** [comment]
Let me know if still fails. I can't reproduce this without a Windows machine.

**Comment by dhana-r** [comment]
thanks mate, sure will keep you posted

**Comment by dhana-r** [comment]
It works after the fix. thanks once again

**Comment by Iserbest02** [comment]
"Pretty" keyword looks missing on the syntax. Idk if that could help. 
Plugin={"pretty", "html:target/cucumber reports}
