### ISSUE TITLE
testdata .ndjson files non-compliant with specifications

### ISSUE THREAD

**Issue by WannesFransen1994** [cucumber/cucumber#1046]
## Summary

Using the testdata folder for testing, where i'm reading in the X.ndjson files and try to parse them with elixir's ex_ndjson. This library is very standard compliant and thus crashing, as in the  [spec](https://github.com/ndjson/ndjson-spec) is written that json should not contain newlines or carriages.

Quote (3.1 `serialization`):
```
The JSON texts MUST NOT contain newlines or carriage returns.
```

reference on the issue where this is somewhat discussed: [https://github.com/ndjson/ndjson-spec/issues/25#issuecomment-480424333](https://github.com/ndjson/ndjson-spec/issues/25#issuecomment-480424333)

Sample json file: [https://github.com/cucumber/cucumber/blob/master/gherkin/testdata/good/background.feature.pickles.ndjson](https://github.com/cucumber/cucumber/blob/master/gherkin/testdata/good/background.feature.pickles.ndjson)

## Context & Motivation

Elixir implementation. While i'd like to try to use https://github.com/gasparnagy/berp, it doesn't have an Elixir implementation yet so for now I'm writing a custom test that checks those files. [ex_ndjson](https://github.com/amrfaissal/ex_ndjson) is spec-complaint and thus crashes when parsing those .ndjson files.

quickfix in my tests (not the most beautiful code, but hey for now it works):
```
:os.cmd('cat #{path} | jq --unbuffered -c . > #{path}.copy')
File.rename!("#{path}.copy", path)
```

**Comment by aslakhellesoy** [comment]
I think we prettify the ndjson with `jq` at some point before writing it to disc. I'm guessing we did that to make it human readable.

I agree we should convert it back to proper ndjson. And if anyone needs to make it human readable they can just pipe it through `jq`

**Comment by aslakhellesoy** [comment]
@WannesFransen1994 Berp has been used to generate parsers for 9 languages (see `gherkin/*/*.razor`).

Berp is language agnostic - it defers to a template written by the user to generate code. It therefore works with any language, including Elixir.

**Comment by aslakhellesoy** [comment]
BTW - you'll find more testdata in `compatibility-kit/javascript/features/*/*.ndjson` - these also have results.

**Comment by WannesFransen1994** [comment]
Thank you for taking time to look at this.

It seems my understanding of Berp was wrong then. Sorry for that! I'll take another look at it!

Also thanks for the extra link to the compatibility-kit/... . This will definitely help me!

**Comment by mpkorstanje** [comment]
The cck output is a collection of messages that represents the executions of cucumber implementations. I don't think they'll be suitable to verify the correctness of a gherkin parser.
