### ISSUE TITLE
gherkin: Encoding issues on Windows

### ISSUE THREAD

**Issue by enkessler** [cucumber/cucumber#1065]
## Summary

I recently upgraded from the `gherkin` gem to the `cucumber-gherkin` gem. My tests, which previously ran fine on Windows, are now encountering encoding problems on Windows in features files with 'special' characters. It appears to be because the text that I am giving to `cucumber-gherkin` is encoded as IBM437 but the gem is trying to treat it like UTF-8. The `gherkin` gem did not have this problem.

## Expected Behavior

`cucumber-gherkin` would be able to handle IBM437 encoded text.

## Current Behavior

It does not.

~~~
Encoding::CompatibilityError - incompatible encoding regexp match (UTF-8 regexp with IBM437 string)
~~~

Full build here: https://ci.appveyor.com/project/enkessler/cuke-linter/build/job/5fasigic69qgaawu

## Possible Solution

No idea. I didn't see anything in the Changelog that indicated encoding was being handled any differently for newer versions of the gem.

## Steps to Reproduce (for bugs)

The feature file in question is this one: https://github.com/enkessler/cuke_linter/blob/master/testing/cucumber/features/linters/background_does_more_than_setup.feature

and you can see the problem occur when using `cucumber-gherkin` on Windows (https://ci.appveyor.com/project/enkessler/cuke-linter/build/job/5fasigic69qgaawu), as opposed to Linux/OSX (https://travis-ci.org/github/enkessler/cuke_linter/builds/698142017).

If you have access to a Windows machine, simply clone the [cuke_linter](https://github.com/enkessler/cuke_linter) repo and run the Cucumber tests (using `bundle exec cucumber`) and the problem will occur.

## Context & Motivation

While I understand that string encoding is a big, important _thing_, I did not, as a user of this gem, have to worry about it before and I would rather not have to start worrying about it now.

## Your Environment

* Version used: `cucumber-gherkin` 13.0.0
* Operating System and version: Windows 10
* Link to your project: https://github.com/enkessler/cuke_linter

**Comment by mpkorstanje** [comment]
Gherkin only works with `UTF-8` encoding.

There are some hacks in different Cucumber implementations to specify other file encodings through a magic comment. These aren't part of Gherkin though.

**Comment by enkessler** [comment]
So I was, essentially, previously relying on un-official/coincidental behavior? Okay, fair enough. In that case, I'll enforce UTF-8 on my end.

Thanks for the information.

**Comment by mpkorstanje** [comment]
Thats what I get from looking at Cucumber JVM v1. Though JVM only supports one encoding internally. Ruby supports multiple internal encodings. So you may have to dig into ruby and see what was setup there.
