### ISSUE TITLE
datatable/java: Support `Optional<T>`

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#1091]
## Summary

I would like to be able to use a table with type `List<Map<Optional<String>, Optional<String>>`, ect. This will allow me to deal more gracefully with empty table cells (null values).

**Comment by rasklaad** [comment]
Do you mind if take this?

**Comment by aslakhellesoy** [comment]
Please do @rasklaad!

**Comment by AnEmortalKid** [comment]
@aslakhellesoy i think this is closed by #1182
