### ISSUE TITLE
Proposal: remove pending steps

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#11]
I don't see any real difference between pending steps and undefined steps. For both, the step hasn't been implemented.

**Comment by mattwynne** [comment]
interesting challenge!

I guess undefined is specifically interesting when you're re-wording things and you end up disconnecting a gherkin step from its definition. I rarely use pending much, but undefined wouldn't make sense as the name for a matched-but-incomplete step (to me).

**Comment by charlierudolph** [comment]
I'm suggesting removing support for defining an incomplete step.

**Comment by aslakhellesoy** [comment]
A pending step is similar to a failing step. It throws an exception, it just so happens that it's a special exception that  doesn't cause red/exit 1 (unless you run with `--strict`)

Are you suggesting removing this special exception?

**Comment by charlierudolph** [comment]
Yes. Pending steps just put incomplete code in the codebase when its not needed. 

When you are ready to implement a step, copy the snippet and write the needed code. 
If you're not ready to implement the step, don't copy the snippet.

If we don't want step snippets to pass by default, we can have them fail
