### ISSUE TITLE
Cannot find the cucumber-json-formatter binaries

### ISSUE THREAD

**Issue by jasondborneman** [cucumber/cucumber#1105]
## Summary
Cucumber-Ruby 4.1
re: [https://github.com/cucumber/cucumber/tree/master/json-formatter#cucumber-json-formatter](https://github.com/cucumber/cucumber/tree/master/json-formatter#cucumber-json-formatter)

This probably isn't even an issue, maybe a documentation issue instead. I can't seem to find the cucumber-json-formatter binaries anywhere. They certainly aren't being installed in the bin directory for cucumber ruby 4.1. Only thing in bin/ is the cucumber executable itself. Is there a way to install this, via a standalone gem, or that it should be in the binaries for the cucumber-ruby distribution?

## Expected Behavior

Should be able to install/access cucumber-json-formatter on the platform of my choice since --format json is going away in 5.x

## Current Behavior

Can't find cucumber-json-formatter binary anywhere.

~~~
~~~

## Possible Solution

Could the binary be either made a part of a standalone gem or included with the cucumber distribution(s) such as cucumber-ruby? Heck, even makign it available via brew/yum/whatever install could be workable too, although not as clean as just making it an installable gem with a binary or included with the cuke distribution.

## Context & Motivation

With --format json going away, it should be easy as pie to find/run the cucumber-json-formatter binary that consumes cucumber message formatted files and spits out json formatted files that are backwards compatible with --format json
## Your Environment

* Version used: cucumber-ruby 4.1
* Operating System and version: MacOSX 10.14.6
* Link to your project: Private project for my company, can't link

**Comment by vincent-psarga** [comment]
The binaries are located here: https://github.com/cucumber/cucumber/releases/tag/cucumber-json-formatter%2Fv5.1.0

Shall I move this issue to `cucumber-ruby` by the way ? I think I should make the deprecation warning more explicit on the way to find the JSON formatter (but this may also be the case for cucumber-jvm ? ).
Also, we need to make clear that JSOn formatter needs to know what kind of input format is used (see https://github.com/cucumber/cucumber-ruby/issues/1439)

**Comment by jasondborneman** [comment]
I'm good to move it to wherever you all think it best belongs. I think this is just a documentation/deprecation warning issue that could be more explicit like you said. Thanks!!

**Comment by jasondborneman** [comment]
What about making it easier to install? Is there somethign that could be done about that in `cucumber-ruby` at least? Right now I'm trying to figure out how to make my infrastructure as code (AWS + Ansible for TeamCity agents that run my tests) pull down the right executable so its available. Might just do a wget or something to the url at this point, maybe that's the recommended solution.

**Comment by jasondborneman** [comment]
Last thing, maybe some README on how to use it? I'm on a Mac, by TeamCity agents are AMazon Linux, and I'm not sure which one of these to download or how to execute them on either platform. I've tried a smattering of options from the downloads on my Mac and I always get command not found even when I try to execute it in the folder I downloaded it to.

Thanks for your patience.

**Comment by vincent-psarga** [comment]
> What about making it easier to install?

The reason why we wrote the tool in Go is to ensure that there's no real installation needed (well, you still need to download it obviously :D but once you have it, it's ready to run).

I'm not sure what would be the best way to get it installed via Ansible, I guess wget or cUrl would work fine.

**Comment by jasondborneman** [comment]
yeah that's what I'm leaning towards at this point. It'd be nice to have a way to ensure you're always getting the latest rather than having to update my Ansible to point to a newer wget url, but if that's what it takes we'll do it

Thanks for your time!

**Comment by vincent-psarga** [comment]
> It'd be nice to have a way to ensure you're always getting the latest rather than having to update my Ansible to point to a newer wget url, but if that's what it takes we'll do it

What would be really interesting is to ensure that it gets the latest version supporting the message version used in the report, maybe not the latest version.
That needs more reflexion in fact :)

**Comment by PramodKokadwar** [comment]
cucumber-json-formatter : The term 'cucumber-json-formatter' is not recognized as the name of a cmdlet
