### ISSUE TITLE
Tags "not allowable type" in runner class since update to Cucumber 6

### ISSUE THREAD

**Issue by vzenzo** [cucumber/cucumber#1106]
When trying to run a test I get Error:(27, 14) java: annotation value not of an allowable type

In my dependencies I have updated Cucmber from 5.6.0 to 6.2.1 and since then I cannot build my project as in runners it does not support tags.

I get error  Error:(27, 14) java: annotation value not of an allowable type

![image](https://user-images.githubusercontent.com/52910214/86949388-dbf38180-c14e-11ea-9939-a58dbc2c5891.png)

**Comment by mpkorstanje** [comment]
If you click through in your IDE to the source you'll see that `tags` is a `String` parameter rather then `String[]` parameter.  So you can drop the the `{` and `}`. 

https://github.com/cucumber/cucumber-jvm/blob/a62780cbb82a628e246b70edc86fa597eb91d049/junit/src/main/java/io/cucumber/junit/CucumberOptions.java#L78

**Comment by vzenzo** [comment]
> If you click through in your IDE to the source you'll see that `tags` is a `String` parameter rather then `String[]` parameter. So you can drop the the `{` and `}`.
> 
> https://github.com/cucumber/cucumber-jvm/blob/a62780cbb82a628e246b70edc86fa597eb91d049/junit/src/main/java/io/cucumber/junit/CucumberOptions.java#L78

I have dropped {} and it still doesn't work

![image](https://user-images.githubusercontent.com/52910214/86950563-933cc800-c150-11ea-842c-44d0f25a41be.png)

 Is this some kind of new thing? Everything worked perfectly fine until I've decided to move to cucumber 6.
I've found some documentation on removing cucumber options and tag syntax but with no info on how affects us moving from previous versions. If this is something new I'll stick to cucumber 5 until 6 gets more info on it

**Comment by camohub** [comment]
If {@whatever} is invalid how to write more than one tags? I mean tags = {"@tag1", "@tag2"} ?

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber/tree/master/tag-expressions
