### ISSUE TITLE
react: Features should be identified by their name

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#1113]
![image](https://user-images.githubusercontent.com/6946919/87243306-41888c00-c435-11ea-8291-8aac2f78460b.png)

The html report lists feature by their file name. While useful this information isn't the primary way of identifying a feature. Additionally the file uri is very repetitive with only a little bit of distinct information at the end. This makes the report harder to read.

I think it'd be better to use the feature name here: 

![image](https://user-images.githubusercontent.com/6946919/87243346-a6dc7d00-c435-11ea-94a8-5a1106d8023a.png)

**Comment by aslakhellesoy** [comment]
Bump
