### ISSUE TITLE
messages: SourceReference should support non-uri based resources

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#1119]
Cucumber messages uses `SourceReference` to provide a pointer to the file containing the step definitions.  This pointer consists of a uri and a location.

```proto
message SourceReference {
  string uri = 1;
  Location location = 2;
}
```

For example:

```json
{
  "stepDefinition": {
    "id": "1",
    "pattern": {
      "source": "a step passes",
      "type": "CUCUMBER_EXPRESSION"
    },
    "sourceReference": {
      "uri": "features/hooks/hooks.ts",
      "location": {
        "line": 7
      }
    }
  }
}
```

This poses a problem in Java because class files can not easily be mapped to URIs and line numbers are not readilly available. 

Instead class files have a canonical name or fully qualified class name (fqn). In combination with the method name this provides a accurate location for method in java. For example `com.example.MyStepDefinitions.given_a_step_definition(String)`. As a result Cucumber JVM currently doesn't include source references (https://github.com/cucumber/cucumber-jvm/issues/2058).

And while it would be possible to put the fqn in the uri field, we chose to use protobuf for two reasons:

1) To provide a schema for Cucumbers JSON output.
2) To provide a consistent output across Cucumber implementations.

By providing an fqn when a uri is implied we negate both of these advantages.

## Suggestion 1: Add a JavaMethod type ##

To alleviate this I would suggest adopting `SourceRefence` to reference either a uri or a java method reference

```proto
message SourceReference {
  oneof resource {
    string uri = 1;
    JavaMethod java_method = 3;
  }
  Location location = 2;

}

message JavaMethod {
  string class_name = 1;
  string method_name = 2;
  repeated string method_parameter_type = 3;
}
```

And while `JavaMethod` might seem overly implementation specific, there is no good general way to represent this. So it is better to be specific and add more types as they present themselves to avoid creating unexpected problems for consumers.

## Suggestion 2: Invent a URI scheme ##

Alternatively rather then putting the fqn directly into the uri field it could be prefixed with `cucumber-jvm:step-definition`. For example `cucumber-jvm:step-definition:com.example.MyStepDefinitions.given_a_step_definition(String)`. However this means we are making up protocols and don't make it apparent from the schema definition that these protocols might exist.

The down side here is that all the other implementaitons do not include a uri scheme, use relative uris and assume when not scheme is provided it is a file. This makes adding any other form or uri more difficult.

**Comment by vincent-psarga** [comment]
Maybe "methodPath" instead of "javaMethod" ? We could use the same kind of representation in Ruby using `Module::Class.name` for example (although for Ruby URI is better).

I think the first solution is better as we might extend later with a third alternative if needed.

**Comment by mpkorstanje** [comment]
I'd rather add a new type for different languages and then use what ever the language uses to identify locations in its code. That way consumers don't have to guess about the format.
