### ISSUE TITLE
Examples alternative for several arguments cartesian product.

### ISSUE THREAD

**Issue by Arlabunakty** [cucumber/cucumber#112]
## Question

Writing test I've met an unpleasant thing with Scenario Outline and size of examples table.
My use case is running operation on data set with different arguments and number of arguments is 5 and they are:
    * DB -> 8 different databases
    * column -> 10 columns
    * argument_0 -> 8 different values
    * argument_1 -> 4 different values
    * argument_2 -> 2 different values

So I have a Example table with 10 * 8 * 4 * 2 rows. And my IDEA is a bit complicated scrolling it and doing different comment/uncomment lines.

Could I implement a thing similar to Examples block, but it would look like

Example pairs:
```
{
"DB": [MySQL_qanorthwind_cs,SQLServer_NGP,PostgreSQL_qanorthwind_cs,PostgreSQL_qanorthwind_cs_9_0,Infobright_logidatahub,Vertica_vmart_71,Oracle_LOGIXML],
  "column":[Fifty_years,Twenty_years,Ten_years,Five_years,One_year,Six_months,Three_months,One_month,One_week,One_day],
   "argument_0": [1,3,4,7,14,30,60,90],
    "argument_1": [h,m,s,ms],
    "argument_2": [true,false],
}
```
And it should have the same behavior as example:

```
Examples:
      | DB                                     | binning_column | bin_width | bin_unit | outlier |
      | MySQL_qanorthwind_cs | One_week_left_outlier | 1 | h | true |
      | MySQL_qanorthwind_cs | One_week_left_outlier | 1 | h | false |
      | MySQL_qanorthwind_cs | One_week_left_outlier | 1 | m | true |
      | MySQL_qanorthwind_cs | One_week_left_outlier | 1 | m | false |
      | MySQL_qanorthwind_cs | One_week_left_outlier | 1 | s | true |
      | MySQL_qanorthwind_cs | One_week_left_outlier | 1 | s | false |
.....
      | Oracle_LOGIXML | One_day_null | 90 | h | true |
      | Oracle_LOGIXML | One_day_null | 90 | h | false |
      | Oracle_LOGIXML | One_day_null | 90 | m | true |
      | Oracle_LOGIXML | One_day_null | 90 | m | false |
      | Oracle_LOGIXML | One_day_null | 90 | s | true |
      | Oracle_LOGIXML | One_day_null | 90 | s | false |
```

Could you recommend the best way I could reduce examples to something like "Example pairs"

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
