### ISSUE TITLE
gherkin: Rules can not be tagged

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#1123]
```feature
Feature: A feature with a single rule

  @RuleTag
  Rule: A rule

    Example: An example of this rule
      Given a single scenario
      When it is executed
      Then nothing else happens
```

Results in: 

```
Caused by: io.cucumber.core.gherkin.FeatureParserException: Failed to parse resource at: classpath:io/cucumber/junit/platform/engine/rule.feature
(4:3): expected: #TagLine, #ScenarioLine, #Comment, #Empty, got 'Rule: A rule'
```

Because rules are a container for scenarios it would make sense to be able to tag a rules and that way tag a collection of scenarios.

**Comment by mpkorstanje** [comment]
See also: https://github.com/cucumber/cucumber/issues/1123

**Comment by sebrose** [comment]
Is the recursive link in  the previous comment intentional, @mpkorstanje ?

**Comment by aslakhellesoy** [comment]
He probably meant #1092

**Comment by aslakhellesoy** [comment]
This will be fixed by #1356

**Comment by testgitdl** [comment]
When will this be released? We need to have tags also for rules. Thanks!

**Comment by luke-hill** [comment]
Hi @testgitdl this is done and released in a much older version of gherkin. Gherkin v18. There also was some big bug fixes to ruby in a later version: https://github.com/cucumber/common/blob/main/gherkin/CHANGELOG.md#fixed-5

See here: https://github.com/cucumber/common/blob/main/gherkin/CHANGELOG.md#1800---2021-03-24
