### ISSUE TITLE
Rename Transform to Parameter

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#114]
## Summary

The term *parameter* is more descriptive than *transform*.

First off, parameters don't necessarily transform anything - their transform functions may be an identity function (leaving the string unchanged). Some parameters only apply a more restrictive pattern than `.+`, for example `[A-Z]\w+`.

Moreover, *transform* describes *what*, i.e. a custom parameter type, with a specific name. Using the term *transform* says more about the implementation of this feature. 
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by aslakhellesoy** [comment]
Fixed by 5feacc737bc756c436c137699a4da0616e97c25b

**Comment by mattwynne** [comment]
@aslakhellesoy can I ask you to try and prefix your issue names with the sub-project, as well as adding the label? It makes it much easier to parse my email notifications and know which ones I want to open and read.

**Comment by aslakhellesoy** [comment]
I'll do that for future ones. Can I ask you to rename the existing ones?

**Comment by mattwynne** [comment]
Done!
