### ISSUE TITLE
cucumber-json-formatter does not convert ndjson to json correctly - missing screenshot

### ISSUE THREAD

**Issue by KirstenLangendorf** [cucumber/cucumber#1157]
## Summary

when using the cucumber-json-fomatter as described https://github.com/cucumber/cucumber/tree/master/json-formatter#cucumber-json-formatter the json file doesn't contain the same content as the ndjson - e.g. screenshot is missing.

## Expected Behavior

I execute (see attached files in Archive.zip):
bundle exec cucumber -x -f message ./features/VL-18.feature -o ./cucumber-report/VL-18.ndjson  
to get the .ndjson file

Then I do the conversion:
cat ./cucumber-report/VL-18.ndjson | cucumber-json-formatter --format ndjson > ./cucumber-report/VL-18.json

the screenshot should be in the the json file.

[Archive.zip](https://github.com/cucumber/cucumber/files/5121591/Archive.zip)

## Current Behavior

I execute:
bundle exec cucumber -x -f message ./features/VL-18.feature -o ./cucumber-report/VL-18.ndjson  
to get the .ndjson file

Then I do the conversion:
cat ./cucumber-report/VL-18.ndjson | cucumber-json-formatter --format ndjson > ./cucumber-report/VL-18.json

the screenshot is not in the json file, but in the ndjson (and attached html).

## Possible Solution

this seems to be a bug?

## Steps to Reproduce (for bugs)

see above

## Context & Motivation

Need the json to import in xray 

## Your Environment

Implementation | cucumber-ruby - 4.1.0
-- | --
ruby - 2.6.3
darwin19 - Darwin Kernel Version 19.6.0:  root:xnu-6153.141.1~1/RELEASE_X86_64
universal

**Comment by aslakhellesoy** [comment]
Thanks for posting this. Will have a look after my holidays unless someone else beats me to it!

**Comment by KirstenLangendorf** [comment]
I seem to have fixed the problem.

When taking screenshots and attaching them I have to encode the .png pictures. For some reason I need to decode before attaching to get the right info both when making a cucumber hml report and the json. Here is the code for the screenshots (The e_or_a parameter will resolve to Expected or Actual):
    screenshot_file_name = "#{Time.now.strftime("#{e_or_a}_%d_%m_%Y__%H_%M_%S")}.png" 
     save_screenshot(screenshot_file_name)
     screenshot_path = Capybara::save_path+screenshot_file_name
     image = open(screenshot_path, 'rb', &:read)
     encoded_image = Base64.encode64(image)
     attach(Base64.decode64(encoded_image), "image/png;base64")
kr Kirsten

**Comment by aslakhellesoy** [comment]
Hi @KirstenLangendorf. Glad you found a workaround.

It shouldn't be necessary to base64 encode and decode the image though. This should work:

```ruby
screenshot_file_name = "#{Time.now.strftime("#{e_or_a}%d%m_%Y__%H_%M_%S")}.png"
save_screenshot(screenshot_file_name)
screenshot_path = Capybara::save_path+screenshot_file_name
attach(File.open(screenshot_path), 'image/png')
```

If that doesn't work for you, please reopen this issue so we can investigate.

**Comment by KirstenLangendorf** [comment]
Hi,

Tried the above and it works. Thanks. I missed the File.open.

**Comment by Alexey-Stepanov** [comment]
@aslakhellesoy I observe the same issue:

- the File.open. is not missed
- cucumber-messages.ndjson contains screenshot
- cucumber-results.json does not contain any screenshot

Could you please help with this?

**Comment by KirstenLangendorf** [comment]
just cheked by running again:
1. if I execute without the file.open in the attachment statement, then the ndjson contains the attached image but the json doesn't as reported.
2. if I execute with the file.open in the attachment statement, then the json contains the attached image (see attached)
[VL-2.json.zip](https://github.com/cucumber/cucumber/files/5156368/VL-2.json.zip)

**Comment by Alexey-Stepanov** [comment]
Then something else is different
I noticed that your .ndjson file from Archive.zip has "mediaType":"image/png;base64" while mine "mediaType":"image/png"
Does it matter?

**Comment by KirstenLangendorf** [comment]
No I don't think so.

**Comment by Alexey-Stepanov** [comment]
When using VL-18.ndjson from the attached Archive.zip
`cat VL-18.ndjson | cucumber-json-formatter --format ndjson > cucumber-results.json`

cucumber-results.json does not contain any "embeddings" field

**Comment by Alexey-Stepanov** [comment]
Should I create a new issue or let's reopen this one?

**Comment by aslakhellesoy** [comment]
Feel free to create a new issue, but please make it a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) with the following:

* Single feature file with single scenario
* Single image file (no capybara or selenium code for screenshotting)
* Single step definition that calls `attach` with the image file

**Comment by Alexey-Stepanov** [comment]
Looks like the issue has nothing to do with feature file, image file of even step definition that calls `attach`
Because **cucumber-messages.ndjson** successfully created and contains "attachment" field with the encoded image inside (both from Archive.zip and from my local machine). I tried to convert ndjson from Archive.zip attached by @KirstenLangendorf and still no luck. And the same with my own ndjson. I even tried to convert the same ndjson on another machine with Debian OS and still the same - the output JSON does not have embeddings. What can go wrong here? Is there older versions of cucumber-json-formatter just to try this option?

**Comment by Alexey-Stepanov** [comment]
> Feel free to create a new issue

Here it is: https://github.com/cucumber/cucumber/issues/1172

**Comment by Alexey-Stepanov** [comment]
The issue occurs only when calling **attach** from hooks.rb in `After do |scenario|`
At the same time, screenshot successfully created when calling **attach** from step definition (i.e. cucumber-json-formatter works as expected in this case)

@aslakhellesoy is it supported to use **attach** from hooks.rb?
