### ISSUE TITLE
Glue code not found when Anonymous Parameter Types are used

### ISSUE THREAD

**Issue by malavanzb** [cucumber/cucumber#1159]
Glue code not found when Anonymous Parameter Types are used
Upon execution everything is working fine but feature file is prompting error message saying glue code not found and I not able to step into the definition.

feature file:
![image](https://user-images.githubusercontent.com/70305562/91380277-9c622100-e7f2-11ea-8be3-eebd7e48eae0.png)

Step definition:
![image](https://user-images.githubusercontent.com/70305562/91380347-bf8cd080-e7f2-11ea-9db6-6f1ba63132ab.png)

TypeRegistry:
![image](https://user-images.githubusercontent.com/70305562/91380409-e21ee980-e7f2-11ea-808f-657165737953.png)

## Expected Behavior
should be able to step into definition using ctrl + click

**Comment by malavanzb** [comment]
![image](https://user-images.githubusercontent.com/70305562/91496582-5fe20400-e88a-11ea-80f2-9a1938e6a875.png)

**Comment by malavanzb** [comment]
![image](https://user-images.githubusercontent.com/70305562/91496652-7c7e3c00-e88a-11ea-993e-62bff4c3f868.png)

**Comment by aslakhellesoy** [comment]
I assume this is a bug report about the IDEA Cucumber plugin, and not about how Cucumber executes the scenario.

Please report bugs about the IDEA Cucumber plugin in the IDEA [issue tracker](https://youtrack.jetbrains.com/issues/IDEA).
