### ISSUE TITLE
cucumber/gherkin/go Build fails on Darwin/386 cross compile

### ISSUE THREAD

**Issue by dmboyd** [cucumber/cucumber#1170]
## Summary

Gherkin Build fails on Darwin/386 cross compile for go

## Expected Behavior

make should build a go executable

## Current Behavior
Build fails when attempting to make
`1 errors occurred:
--> darwin/386 error: exit status 2
Stderr: cmd/go: unsupported GOOS/GOARCH pair darwin/386

make[1]: *** [dist/cucumber-gherkin-darwin-amd64] Error 1`

## Possible Solution

This appears to be related to the following issue with an upstream dependency within the go makefile default.mk

https://github.com/mitchellh/gox/issues/146

A potential fix would be to remove the dependency on the outdated github.com/aslakhellesoy/gox repository and enumerate cross compilation targets directly within the default.mk file

## Steps to Reproduce (for bugs)

run make from the /gherkin sub directory

## Your Environment

* Version used: 15.0.2
* Operating System and version: MacOS 10.14.6

**Comment by aslakhellesoy** [comment]
We need to use my fork of gox until my [pull requests](https://github.com/mitchellh/gox/pulls/aslakhellesoy) are merged. I guess I'll have to update my fork with the latest from `mitchellh/gox`.

Have you tried building it in the docker image? Launch it with `make docker-run`.

**Comment by aslakhellesoy** [comment]
Our [docker image](https://github.com/cucumber/cucumber-build/blob/main/Dockerfile) uses go 1.13.8 - I guess ubuntu apt packages are lagging behind a bit.

Eventually it will catch up, and then our builds will fail in docker too.

I agree we should drop the dependency on gox - the main repo (which my fork is uptodate with) appears to be abandoned. Enumerating the targets sounds better.

Would you be interested in sending a PR for that?

**Comment by dmboyd** [comment]
I'll send through a PR. How far back in golang release numbers should the build support (when enumerating supported envs)? 1.12-1.15?

**Comment by aslakhellesoy** [comment]
Lovely thanks!

I think we can expect a minimum of 1.13.8 (what the docker image has), and up to the current stable one?
