### ISSUE TITLE
messages library for Elixir 

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#1174]
TODOs:

- [x] (WF) Sent PR with code
- [x] (WF) Set up Keybase account, dm login to core team
- [x] (VP) Set up cukebot account on `hex.pm` and register `cucumber` org
- [ ] (AH) Implement publish targets in `Makefile`
- [x] (CB) Add Elixir to [cucumber-build](https://github.com/cucumber/cucumber-build/)
- [x] (AH) Add slack channels, `#committers-elixir` and set up GitHub to post updates to `#bots-elixir`
- [ ] (AH) Add new elixir issue label

**Comment by WannesFransen1994** [comment]
extra TODO:
* [ ] rename packages
