### ISSUE TITLE
create-meta travis incorrect assumption

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#1178]
Travis CI integration assumes you are using github which is not a requirement.

https://github.com/cucumber/cucumber/blob/master/create-meta/ciDict.json#L95

Travis works with GitHub, Bitbucket, GitLab, Assembla

https://docs.travis-ci.com/user/tutorial

**Comment by aslakhellesoy** [comment]
Whoops - that's not good! I'll have a look.

**Comment by aslakhellesoy** [comment]
I don't think Travis exposes the Git remote in any environment variables: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

It's probably better to set it to null. Alternatively we could poke around in `.git/config` and/or try to execute `git remote get-url origin` as a fallback.

WDYT @vincent-psarga @mpkorstanje ?

**Comment by mpkorstanje** [comment]
> It's probably better to set it to null

Agreed.

> Alternatively we could poke around in .git/config and/or try to execute git remote get-url origin as a fallback.

That's making allot of assumptions. Of the top of my head:

- There is a `.git`.
- The `.git` directory is readable by the current user/process/ect
- There is a remote configured
- `.git` is in the root of the project (not true for a mono-repo)
- Cucumber is executed in the root of the project (not true for a mono-repo, or a multi-module maven project)

And all these assumptions will make it harder to debug why a specific project just isn't working while another one with the same CI in the same organization is. It will be easier to explain that Travis exposes the Git remote in any environment variables.

**Comment by aslakhellesoy** [comment]
Yeah I like that. How about `CUCUMBER_GIT_REMOTE_URL`?

**Comment by mpkorstanje** [comment]
Not a big fan of putting stuff directly in the properties root. How about `CUCUMBER_PUBLISH_GIT_REMOTE_URL`? That way we identify the specific component that uses this.

**Comment by aslakhellesoy** [comment]
I suggest we just remove support for Travis. They’re pulling the plug on Open Source support....

**Comment by mpkorstanje** [comment]
No objections. We have no way to test this now. Some one with access to Travis would have to submit a PR.
