### ISSUE TITLE
Problems with glue between feature file and steps class file after updating project to latest version.

### ISSUE THREAD

**Issue by fmah123** [cucumber/cucumber#1186]
The problems I am having is that even when I follow start up guides correctly I find that when I update Step definitions class the feature file doesn't recognise the step definition class anymore. The BDD steps all highlight stating 'Undefined step reference'. 
[iceland_automation_tests.zip](https://github.com/cucumber/cucumber/files/5242028/iceland_automation_tests.zip)

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/tools/cucumber-open/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
