### ISSUE TITLE
gherkin/objective-c: Parser usage documentation needs improvement

### ISSUE THREAD

**Issue by JacobHearst** [cucumber/cucumber#1196]
## Disclaimer
I have limited experience working in Swift and 0 experience working with Objective-C. It is entirely possible (and very likely) that I'm not doing something super obvious or that I'm misunderstanding something.

## Summary
I'm currently working on a Swift project that involves the parsing of Gherkin files. I would very much like to use the existing Obj-c parser that lives in this repo. I've been struggling to do so for a few reasons:

1. There is no documentation that I could find specifying exactly what code needs to be included to use the library. Do I need the whole sub-repo? Do I need just the files under `objective-c/Gherkin`? For now I've gone with the latter which seems to _mostly_ work.
2. The snippet of obj-c code in `gherkin/README.md` from what I can tell doesn't reflect the library's actual implementation, specifically on the line that reads `GHGherkinDocument * result = [parser parseContent:content];`

## Environment
Because I'm attempting to use this library in a Swift environment I feel that I should document here how I've gotten to where I am now.

I'm developing with Swift 5.2.4 in XCode 11.7. To add the library to my project I cloned [the objective-c repo](https://github.com/cucumber/gherkin-objective-c) and copied the entire `Gherkin` directory into my target. I created an Objective-c bridging header which contains the following line: `#import "GHParser+Extensions.h"`. In my Swift file I have the following code:

    let featureFilePath = "someFile.feature"
    var content: String?

    do {
        content = try String(contentsOfFile: featureFilePath, encoding: .utf8)
    } catch let error {
        print(error)
    }

    if (content?.trimmingCharacters(in: .whitespacesAndNewlines).count ?? 0) == 0 {
        print("No content")
        return
    }

    let parser = GHParser()
    let result = parser.parseContent(content)

## Expected Behavior
The behavior I would expect from the above code is that my feature file is parsed and the results are stored in the `result` variable.

## Current Behavior
What I'm seeing instead is that the method `parseContent()` doesn't exist on GHParser. I took a peek inside the GHParser .h and .m files and the only 'parse' methods I see are the two `parseWithTokenScanner()`.

**Comment by aslakhellesoy** [comment]
Hi @JacobHearst

We haven't had a maintainer of `gherkin/objective-c` for 3-4 years. We've kept the code in the source tree in case someone wants to pick it up, but it isn't currently part of the build.

The maintained versions are java/go/ruby/javascript/dotnet - and they have evolved quite a bit since the objective-c implementation stopped being maintained.

I've got 0 experience with Swift/ObjC myself, and I don't have capacity to help out with it either I'm afraid.

If someone could help bring the codebase uptodate with the other maintained implementations we could re-enable it.

The structs generated by the parser are now based on protobuf (see the messages library), so that would probably be the best place to start.

**Comment by JacobHearst** [comment]
An update as I've dug around a bit more, there _is_ in fact a definition for `parse()` that accepts a string, it lives in the `GHParser+Extensions` .h and .m files

**Comment by JacobHearst** [comment]
For anybody else that needs to work with this parser in their code, the following snippet worked for me:

~~~
let featureFilePath = "someFile.feature"
var content: String?

do {
    content = try String(contentsOfFile: featureFilePath, encoding: .utf8)
} catch let error {
    print(error)
}

if (content?.trimmingCharacters(in: .whitespacesAndNewlines).count ?? 0) == 0 {
    print("No content")
    return
}

let parser = GHParser()
parser.parse(withTokenScanner: GHTokenScanner(contentsOfFile: content))
~~~

**Comment by ltpquang** [comment]
@aslakhellesoy hi, any differences between https://github.com/cucumber/gherkin-objective-c and `gherkin/objective-c`? I'm quite interesting in this, maybe I will try to take a look.

**Comment by aslakhellesoy** [comment]
> any differences between https://github.com/cucumber/gherkin-objective-c and gherkin/objective-c

The former is a read-only mirror of the latter. Changes/PRs should be made against this repo.
