### ISSUE TITLE
Question about follow Gherkin Updates

### ISSUE THREAD

**Issue by p2635** [cucumber/cucumber#1212]
I'm sorry if I have placed this question in the wrong place. I tried emailing SmartBear but they just said "Unfortunately, we do not offer any technical support to open source customers. You will need to check on the community forum for an answer to your query.".

Today I skimmed the page about Gherkin on https://cucumber.io/docs/gherkin/reference/, I knew about most of it already before reading it.

However, there were some things that were new to me:
* The But keyword
* The asterisk *
* The 'Rule' keyword (introduced since v6 of Gherkin)

My question is, how do I follow the latest updates with Gherkin? I don't want to keep having to check the page, my ideal case would be some kind of email subscription or RSS feed. I guess I could follow the releases here as well but it would be overkill to see everything.

**Comment by luke-hill** [comment]
If you just monitor the gherkin repo. Or the gherkin changelog, that might be a good place to start?

The changelog is available here: https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md

There are also read-only mirrors for each gherkin flavour. For example https://github.com/cucumber/gherkin-ruby

Given this is a question not an issue directly, and there are other areas alongside the ones you've mentioned. I'm going to close this.
