### ISSUE TITLE
Language codes in gherkin-languages.json

### ISSUE THREAD

**Issue by nvmkpk** [cucumber/cucumber#1221]
## Summary
It appears the language codes used in `gherkin-languages.json` file do not follow ISO language codes (ISO 639-X). Using the ISO language codes is more common in most software development. Any plans on changing the codes?

**Comment by aslakhellesoy** [comment]
The `gherkin-languages.json` file uses [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) and falls back to [ISO 639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) for languages that don't exist in ISO 639-1. One example is [ast](https://github.com/cucumber/cucumber/blob/350f303290029eaedbcf08618d2c4f6eb2f4b865/gherkin/gherkin-languages.json#L186) for Asturian.

Some codes, such as [cy-GB](https://github.com/cucumber/cucumber/blob/350f303290029eaedbcf08618d2c4f6eb2f4b865/gherkin/gherkin-languages.json#L516) might be wrong (I think that one should be `cy` (ISO 639-1) or `cym` (ISO 639-2).

What discrepancies have you found?

P.S. Some languages are unofficial/made-up/fun such as [en-pirate](https://github.com/cucumber/cucumber/blob/350f303290029eaedbcf08618d2c4f6eb2f4b865/gherkin/gherkin-languages.json#L975) and [en-lol](https://github.com/cucumber/cucumber/blob/350f303290029eaedbcf08618d2c4f6eb2f4b865/gherkin/gherkin-languages.json#L876) where we've made up codes.

**Comment by nvmkpk** [comment]
One for sure is for `Telugu`. The ISO 639-1 code for it is `te` but the json file has it as `tl`.

**Comment by aslakhellesoy** [comment]
Happy to take a pr for that
