### ISSUE TITLE
parser: Allow Rule tag after Then keyword

### ISSUE THREAD

**Issue by drweb86** [cucumber/cucumber#1226]
## Summary

Rule tags are not supported in Feature files (Gherkin 6) when they are after Then keyword

## Expected Behavior

Put content to feature file and it will be correctly working upon parsing
```
Feature: Feature 1

  Rule: Rule 1

    Scenario: Rule 1's schenario
        Then Test

  Rule: Rule 2

    Scenario: Rule 2's schenario
```

Error:
```
expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Rule: 
    at Scripts\node_modules\cucumber\lib\cli\helpers.js:110:13
    at Array.forEach (<anonymous>)
    at getTestCases (node_modules\cucumber\lib\cli\helpers.js:81:10)
```

If i rewrite that like this
```
Feature: Feature 1

  Rule: Rule 1

    Scenario: Rule 1's schenario

  Rule: Rule 2

    Scenario: Rule 2's schenario
```
it will be parsed successfully .

## Possible Solution

After end of one scenario (with Then), a new Rule can appear with its own scenarios, so i guess it should be allowed, if it sin't already

## Steps to Reproduce (for bugs)

1. Paste mentioned to feature file.
2. Add tag
3. Run Cucumber on tag.

## Context & Motivation

We have lot's of scenarious in single file. We want to have a possibility to group them (instead of creating separate files, which are used a lot in the project)

## Your Environment

Node.JS

**Comment by luke-hill** [comment]
So the behaviour you describe is available in Gherkin, and in my project (Cucumber-Ruby). I have 3/4 rules (All under feature). I am using Cucumber v4 (Ruby), which under the hood consumed gherkin v14 (This was released in the Summer).

Gherkin v6 is very old. Yes it was the first one to introduce `Rule` as a keyword. But is there any chance you could use something more up to date? Gherkin v7 (The next major), was released over a year ago, and Gherkin has an aggressive major release cycle (As a lot of it is language related).

As a bare minimum, if you can show this not working in Gherkin v14 (I think that might be NodeJS cucumber version 7), then let me know. But can you try upgrade some of your dependencies?

**Comment by aslakhellesoy** [comment]
Can you update the Summary please? I think you left some bits out.

BTW, Gherkin is currently at version 15 ;-)

**Comment by aslakhellesoy** [comment]
I'm also a bit confused about "BTW this is working" followed by "Error".

If there is an error, surely it's not working?

**Comment by drweb86** [comment]
I have Cucumber packages like this
```
    "cucumber": "6.0.5",
    "cucumber-junit-formatter": "0.2.2",
    "cucumber-pretty": "6.0.0",
    "cucumber-tsflow": "3.2.0",
```
So i guess i ought to update them and recheck if the issue is still there

**Comment by aslakhellesoy** [comment]
Can you please clarify what Gherkin causes a parse error?

**Comment by drweb86** [comment]
This is the exact file, simplified that causes error.
```
Feature: Test

    Scenario: Test
        Then  Test

  Rule: Test

```
Error
```
(6:3): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Rule: Test'
```

@aslakhellesoy , I'll update the repro feature file, because i missed Then there

**Comment by aslakhellesoy** [comment]
Cucumber.js 6.0.5 uses Gherkin `^5.0.0`:

https://github.com/cucumber/cucumber-js/blob/v6.0.5/package.json#L168

Please upgrade to Cucumber.js v7.0.0-rc.0 which uses Gherkin `^15.0.2`:

https://github.com/cucumber/cucumber-js/blob/94b7f6ea9aa2141aa660a7e8dace7f5e8d9e1333/package.json#L169

You'll find a migration guide [here](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#700-rc0-2020-09-14).

**Comment by drweb86** [comment]
Thank you!
