### ISSUE TITLE
build: maybe use npm workspaces

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber#1259]
## Summary

Npm 7 has a new workspaces feature to support projects with multiple libraries.

The documentation is pretty sparse at this point, but anyway:

- https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md
- https://docs.npmjs.com/cli/v7/using-npm/workspaces

I think this might be a good fit for the monorepo, in terms of:

- Declaring and installing common tooling dependencies like typescript and eslint once at the root level
- Reliably linking between dependencies locally

Wanted to get any initial feedback before I start experimenting, especially potential downsides. One I think would need to be addressed would be how to continue supporting [building a subset](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING_NEW.md#building-a-subset) of the monorepo for just a particular package.

Thanks!

**Comment by aslakhellesoy** [comment]
This is done!
