### ISSUE TITLE
cucumber-expressions: unable to differentiate between float and int for steb disambiguation

### ISSUE THREAD

**Issue by mrklkrl** [cucumber/cucumber#1261]
In the original cucumber (non @cucumber/cucumber), I could associate multiple step-definitions with the same gherkin statement and the correct step definition would be called based on type inference. for example, I could have:

```
  Scenario Outline: set a param on a device
    When I set <parameter> to <value>

  Examples:
  | parameter | value |
  | "age"     | 32    |
  | "weight"  | 180.0 |
```

I could have in my step_defintions

```
When('I set {string} to {int}', function (intParam, val) {...}
```
and
```
When('I set {string} to {float}', function (stringParam, val) {...}
```
and cucumber was able to find these by type inference. It worked well and allowed for a lot of code reuse. 

However, when I do the same thing with @cucumber/cucumber, I get ambiguity failures because of the function overloading. This means I now need to have multiple gherkin statements where before I only needed one.

I would propose an option to infer type. I believe cucumber-ruby has a "--guess" option.

*edit*
It seems like there is simply an issue with cucumber differentiating between ints and floats in the .feature.

**Comment by davidjgoss** [comment]
I think this will be an issue across cucumber-expressions implementations and I'm not sure there is really a solution.

(Please reopen if I'm wrong)
