### ISSUE TITLE
Functionality to distinguish steps with same name

### ISSUE THREAD

**Issue by vineethmaller** [cucumber/cucumber#1270]
Issue: Need functionality to distinguish steps with same name but different functionality located in a separate class or package

## Summary

Need functionality to distinguish steps with same name but different functionality located in a separate class or package.

## Expected Behavior

Cucumber should be able to distinguish steps not just based on the uniqueness of its name but also it's path.

## Current Behavior

Currently cucumber does not support multiple steps with the same name even if they are separated by classes or packages. 
This forces users to give steps long names which are inconsistent, non-standard and unreadable. 

Example:
**And** _user enters \<accountNumber\> in debit account field in Payments page in Netbank_

## Possible Solution

A possible solution is to use a new keyword("**IN**" or "**AT**") to distinguish steps by a particular class with it's relative path.

Example: **IN**
**And** _user enters \<accountNumber\> in debit account field_ **In** _Netbank/PaymentSteps_

Example: **AT**

**Given** _user has opened Netbank_
...
**And** _user clicks Make transfer option_
**At** _Netbank/PaymentSteps_
**And** _user enters \<accountNumber\> in debit account field_
...

## Context & Motivation

I am using Cucumber and selenium for automated testing of a website. This website has multiple pages whose functionalities need to be tested. Some of these pages have similar overall sub functions or design, this warrants steps with identical names even though they are separated using the Page Object model.

**Comment by luke-hill** [comment]
You would solve this in one of two ways (I have a similar problem)

1) You amend the step name to - `I enter the accountNumber on the registration page account field` (This is the approach I use).

2) You amend your POM to pass through the concept of a current page. And always activate based on current page (This was the former approach at my company which I've got rid of)

**Comment by vineethmaller** [comment]
@luke-hill Option 1 would not work as we have created a framework for automated testing of multiple websites. Most of them have a registration page.
Option 2 is not clear for me, could you elaborate or point me to a resource for lookup.

These are messy roundabouts to solve the issue, I'd rather make this a feature that adds value.

**Comment by luke-hill** [comment]
For option 1) You alter the text as mentioned. It would work by simply amending your step to be more descriptive.

For option 2) You simply pass in some flag either in a before step, a hook step, a tag. Or some discernible piece of logic. Then you can through any of these means target a specific POM class.

Essentially this logic already exists in a multitude of ways. It's not something we would add additional logic for. On the docs site we have examples of BeforeSteps (In some languages, NOT all), as well as using naming to be more verbose.

Cucumber tags have existed for years, so you can use a tagged step to triage something. Or you could directly use a background step to load the page you wish to test as an instance variable, and then use that concept to be tested.
