### ISSUE TITLE
gherkin(TypeScript): IGherkinOptions need `createReadStream` property

### ISSUE THREAD

**Issue by christian-bromann** [cucumber/cucumber#1284]
## Summary

For context: I am currently trying to update Cucumber in the WebdriverIO framework.

When creating a `gherkinMessageStream` the `fromPaths` method requires an `IGherkinOptions` interface in which `createReadStream` is optional, e.g.

```ts
const gherkinMessageStream = GherkinStreams.fromPaths(this._specs, {
    defaultDialect: this._cucumberOpts.featureDefaultLanguage,
    newId: () => this._cid
})
```

This fails if the `path` array not is empty in `pipeSequentially`.

## Expected Behavior

I must miss something here because TypeScript should actually fail compile if `IGherkinOptions` is defined as:

```ts
export default interface IGherkinOptions {
  defaultDialect?: string
  includeSource?: boolean
  includeGherkinDocument?: boolean
  includePickles?: boolean
  newId?: IdGenerator.NewId
  createReadStream?: (path: string) => Readable
}
```

and `fromPaths` is implemented as such:
```ts
function fromPaths(
  paths: ReadonlyArray<string>,
  options: IGherkinOptions
): Readable {
  const pathsCopy = paths.slice()
  options = makeGherkinOptions(options)
  const combinedMessageStream = new PassThrough({
    writableObjectMode: true,
    readableObjectMode: true,
  })

  function pipeSequentially() {
    const path = pathsCopy.shift()
    if (path !== undefined) {
      const parserMessageStream = new ParserMessageStream(options)
      parserMessageStream.on('end', () => {
        pipeSequentially()
      })

      const end = pathsCopy.length === 0
      // Can't use pipeline here because of the { end } argument,
      // so we have to manually propagate errors.
      options
        .createReadStream(path)
        .on('error', (err) => combinedMessageStream.emit('error', err))
        .pipe(new SourceMessageStream(path))
        .on('error', (err) => combinedMessageStream.emit('error', err))
        .pipe(parserMessageStream)
        .on('error', (err) => combinedMessageStream.emit('error', err))
        .pipe(combinedMessageStream, { end })
    }
  }
  pipeSequentially()
  return combinedMessageStream
}
```

It should fail at 
```ts
      options
        .createReadStream(path)
```

because `createReadStream` is potentially undefined.

## Current Behavior

~~~
~~~

While I am sure my integration is not yet working and I am missing some peaces I am expecting not to see an error like this with the new TypeScript interfaces.

## Possible Solution

Not sure how the error happens in the first place. Haven't had the chance to dig into it, therefor I can't provide a solution yet.

## Steps to Reproduce (for bugs)

Run:

```ts
GherkinStreams.fromPaths(['/foo/bar'], {
    defaultDialect: 'en',
    newId: () => 'someid'
})

## Context & Motivation

<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment

<!--- If you're reporting a bug, include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Operating System and version:
* Link to your project:

**Comment by aslakhellesoy** [comment]
I'll have a look at a fix for this.

The reason that TypeScript isn't complaining about a potentially `undefined` value is that we have a tsconfig that is too lax. We'd like to improve that, but it's a fair amount of work since it will affect the whole monorepo. See #1138 for more details.

**Comment by christian-bromann** [comment]
Thank you for the fix 👍

**Comment by aslakhellesoy** [comment]
Thanks for reporting and please submit a new issue if you have other issues.
