### ISSUE TITLE
it is not a valid e-mail but it is accepted 

### ISSUE THREAD

**Issue by sinanoral** [cucumber/cucumber#1295]
![image](https://user-images.githubusercontent.com/73873025/103642452-346fd400-4f64-11eb-99fa-0630c843a885.png)

**Comment by nhojpatrick** [comment]
@sinanoral yep definitely a bug but not with the open source cucumber project which is managed here https://github.com/cucumber/. You'll need to contact SmartBear to get that part of the website fixed, see https://cucumber.io/contact-us/.

**Comment by nhojpatrick** [comment]
@sinanoral fyi I have emailed info@smartbear.com with link to this defect.
