### ISSUE TITLE
react: Search button does not work and causes page to reload

### ISSUE THREAD

**Issue by hWorblehat** [cucumber/cucumber#1298]
## Summary
In the SearchBar, clicking the search button does not update the search query, and instead causes the page to reload. As a workaround, hitting `Enter` while focus is on the search text box correctly updates the query.

This was tested in the page generated using the `html-formatter` subproject. I haven't tested the component in a wider context.

## Expected Behavior

When clicking the button, the search query should update. If using inside the `FilteredResults` element, the feature list should be filtered and highlighted accordingly.

## Current Behavior

The page reloads.

## Possible Solution

I believe the problem stems from the fact that the text input and button are defined inside an HTML form, and the button is bound to the `submit` action of the form. Thus, in addition to the "onClick" action, it triggers an HTML form submission causing the page to reload, which clears the "query" state from the parent react element.

To fix, either the elements could be unbound from the default form submission (i.e. `Event.preventDefault()`), or the search bar could make explicit use of HTML form submission as means of communicating the search query to the wider app (see #1302 for a suggestion regarding this second option).

## Steps to Reproduce (for bugs)

1. Run `html-formatter.js` against a messages file containing at least one document.
2. Open the resulting html file.
3. Enter a search term in the search box
4. Click the search button

## Context & Motivation

I came across this bug by accident, while trying to modify the page generated by `html-formatter` to accept queries via the document URL search parameter. I attempted to add a script element to the page that filled the search box and simulated the button click. An ideal solution for me would also provide some other hook into the search form without having to simulate user input. However, I accept that such a request would significantly widen the scope of this issue.

Regardless, to me this seems like a straight-up UI bug.

## Your Environment

* Version used: 11.0.2 (html-formatter 11.0.4)
* Operating System and version: Linux (Manjaro; Gnome); Firefox 84.0.1 & Chromium 87.0.4280.88

**Comment by davidjgoss** [comment]
I've seen this too, will investigate.

**Comment by luke-hill** [comment]
This is present in cucumber ruby 4.1 as well (Mentioned this to you earlier as one of the few minor things).

**Comment by hWorblehat** [comment]
@davidjgoss 

> I've seen this too, will investigate.

Thanks for taking a look. I believe the PR I linked should fix it, although it may also be possible to fix with a lighter-touch change. However, I'd quite like some of the changes in #1299 as #1302 builds on top of it (a new feature that I would like).

Let me know what you think.

@luke-hill

> This is present in cucumber ruby 4.1 as well

Ultimately, this is bug in the react components, so whichever flavor of Cucucmber you use to generate web pages will show this bug.

**Comment by davidjgoss** [comment]
Ah sorry @hWorblehat, didn’t spot the PR at first. I’ll give that a review
