### ISSUE TITLE
[wire] No matching end_scenario

### ISSUE THREAD

**Issue by tobhahn** [cucumber/cucumber#131]
When running a scenario outline with a background but without any examples using the wire protocol, cucumber sends a begin_scenario over the wire, but no matching end_scenario. This leads to inconsistent state on the wire server (the app under test) side.

Example: 

Given this feature

```gherkin
Feature:

 Background:

 Scenario Outline:
   Given an undefined step
```

and a wire server waiting to execute steps sent via the wire protocol,
when I run this scenario
then the wire server should receive a matching `end_scenario` command for every `begin_scenario` command, i.e. either one `begin_scenario` and one `end_scenario` or no `begin_scenario` and no `end_scenario`. 

Currently, the wire server receives a `begin_scenario`, runs the appropriate hooks, but does not reset the app into a known good state because it does not receive the matching `end_scenario`. This leads to undefined behavior in the wire server.

Note:
Issue #112 is a different bug which is also specific to having a background with no matching scenario over the wire protocol.

**Comment by mattwynne** [comment]
Seems similar to #813

**Comment by mattwynne** [comment]
As of 2.0, this will no longer happen as that Gherkin won't generate a Test Case. There will be no test case, so no `begin_scenario` or `end_scenario`.
