### ISSUE TITLE
cucumber-expressions: regexp uniqueness constraint in transforms is unnecessary

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber#132]
## Summary

There is no need to enforce uniqueness of regular expressions between custom parameter types.

## Current Behavior

When using cucumber.js-2.0.0-rc.8, the following code:

```javascript
defineParameterType({
  regexp: /[A-Z]\w+/,
  transformer: name => name,
  typeName: 'name'
})

defineParameterType({
  regexp: /[A-Z]\w+/,
  transformer: name => world.fetchPerson(name),
  typeName: 'person'
})
```

Triggers the following error:

```
Error: There is already a parameter with regexp [A-Z]\w+
    at set (/Users/jbpros/Projects/cucumber-pro/node_modules/cucumber-expressions/dist/parameter_type_registry.js:132:45)
```

## Desired Behavior

These two transforms are expected to return related things: the first one returns the name of a person, the second one returns an instance of the person, based on their name. Therefore, they both need to use the same regular expression.

I would expect the code above to not throw any error, the constraint on regular expression uniqueness between parameter types to not be enforced. Two reasons for that:

1. The types are always explicit in step definition expressions, therefore I think there is no ambiguity possible when identifying types and their transform functions.
2. Enforcing regular expressions uniqueness is not robust anyway. I was able to circumvent this uniqueness constraint by using two different regular expressions exposing the exact same rules:
  - `/[A-Z]\w+/`
  - `/[A-Z]\w{1,}/`

## Possible Solution

I think we can safely remove this check on regular expression uniqueness as long as type names are uniquely identified.

**Comment by aslakhellesoy** [comment]
I agree.

The Cucumber Expressions library is also responsible for producing expressions for undefined steps.

In doing that, it will suggest `I have a {color} ball` for an undefined step `I have a blue ball`, if there is a parameter type registered that matches `blue`.

What should it suggest if there are multiple parameter types that match?

**Comment by jbpros** [comment]
I literally realised this 10 minutes ago while playing with step defs 😃  *les grands esprits se rencontrent*.

I'm not sure what we should do. We could suggest alternative expressions. e.g. in cucumber.js's output:

```
(...)
Undefined. Implement with one of the following snippets:

       Given('I have a {color} ball', async function (color) {
         return 'pending'
       })

       Given('I have a {cssColor} ball', async function (cssColor) {
         return 'pending'
       })
```

It could potentially lead to an explosion of alternatives, if there are several params that have multiple matching types.

**Comment by charlierudolph** [comment]
Just checking how we are dealing with the following case:

Given the transformations:
```javascript
defineParameterType({
  regexp: /[A-Z]\w+/,
  transformer: name => name,
  typeName: 'name'
})

defineParameterType({
  regexp: /[A-Z]\w+/,
  transformer: name => world.fetchPerson(name),
  typeName: 'person'
})
```
And some other step defined with a regular expression
```javascript
Given(/^Some other step "([^"]+)"$/, /* */)
```

If the captured value matches both transformations, and thus is an ambiguous transformation, are we currently throwing an error?

**Comment by aslakhellesoy** [comment]
Great question! The implementation in #186 just grabs one of them - I think the first.

I think it would be better to do what you suggested, throw an exception. The exception could say that matching is ambiguous and cannot proceed, and suggest how to fix it.

That suggestion could be to use a Cucumber Expression instead of a Regular Expression, because this problem only applies to Regular Expressions:

```
The step text `Some other step "Bob"` has ambiguous parameters. I cannot decide between `person`,`name`.

You can resolve this ambiguity by being explicit about what parameter type you intend to use. This means changing your Regular Expression /Some other step "([^"]+)"/ to one of the following Cucumber Expressions:

Some other step "{name}"
Some other step "{person}"
```

WDYT?

**Comment by aslakhellesoy** [comment]
I've pushed 5478a06, which should give better feedback when there are ambiguous parameter types. See [these tests](https://github.com/cucumber/cucumber/blob/5478a06794ae8021b93bff76dbdfbe08894206c2/cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ParameterTypeRegistryTest.java#L22-L80) for details.
