### ISSUE TITLE
Direct visitors on GitHub to docs.github.com

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#133]
## Summary

Some of the Markdown doesn't look nice on GitHub:
https://github.com/cucumber/cucumber/blob/master/event-protocol/README.md
On this page, the various example events are not rendered.

However, they are rendered nicely on GitBook:
https://docs.cucumber.io/event-protocol/
This is done with a custom GitBook plugin.

## Possible Solution

* Add a header to every page that doesn't render nicely on GitHub, with a link to GitBook.
* Add a new GitBook plugin that removes this header.

**Comment by mlvandijk** [comment]
This issue will be obsolete once all docs are replaced with docs.cucumber.io. Shouldn't we point them there instead?
