### ISSUE TITLE
Remove stream dependencies from Gherkin

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#1331]
The `@cucumber/gherkin` npm package depends on Node.js streams. This makes it difficult to use the Gherkin parser in a browser (a stream polyfill must be provided).

To make this easier and more lightweight we should move the stream code to `@cucumber/gherkin-utils`

**Comment by aslakhellesoy** [comment]
Thinking about this some more, I think it's better to extract to a new module `@cucumber/gherkin-streams` because `@cucumber/gherkin-utils` is also used in the browser (it's used by `@cucumber/react`).

**Comment by aslakhellesoy** [comment]
And thinking about it even some more, creating a whole new npm module just for this seems overkill. My proposed solution in #1332 is simply not to load the stream code by default.

**Comment by karamosky** [comment]
Hii @aslakhellesoy thanks for the quick fix. Unfortunately, this is not working because `generateMessages` still depends on `@cucumber/messages` and still uses the stream indirectly.

Is there any way to not expose all subclasses that depend on stream in the `index.ts` of `@cucumber/messages`

**Comment by aslakhellesoy** [comment]
Ah - I had forgotten about that. I'll make a similar fix in `@cucumber/messages`

Thanks @karamosky!
