### ISSUE TITLE
gherkin - go (apple) binaries no longer available

### ISSUE THREAD

**Issue by ciaranmcnulty** [cucumber/cucumber#1347]
It looks like the `gherkin-go` post-release action is failing because of no `upx` on the path, so there are no recent binaries since 6.x on tags in that repo.

In the monorepo somewhere between 15.0.2 and 16.0.0 the Apple builds started to fail. A `upx` file gets uploaded  but it doesn't seem to execute. The file extension is strange because my reading of the makefile suggests it would either be renamed or deleted depending on the integrity check

**Comment by aslakhellesoy** [comment]
Fixed by https://github.com/cucumber/cucumber/pull/1348
