### ISSUE TITLE
gherkin: Fix build on go 1.8

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#137]
The build passes on [Go versions up to 1.7](https://travis-ci.org/cucumber/gherkin-go/builds/211545045) but fails on 1.8  (and tip).

**Comment by l3pp4rd** [comment]
will be resolved by #145

**Comment by aslakhellesoy** [comment]
💯 
https://travis-ci.org/cucumber/gherkin-go/builds/213031829
