### ISSUE TITLE
Cucumber JSON Test Corpus

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#1394]
Each Cucumber implementation that produces JSON reports does so inconsistently because the JSON format [does not have a schema](https://github.com/cucumber/cucumber/tree/master/messages#lack-of-a-schema).

To make it easier to test tools that consume Cucumber JSON we would like to have a corpus of JSON documents generated by different Cucumber implementations and versions.

There is an existing corpus in [json-to-messages](https://github.com/cucumber/cucumber/tree/master/json-to-messages). They are not in git, but generated by running `make`.

The proposal is to:

* Add JSON documents to Git to make them easier to consume without having to run any build commands
* Move them out of `json-to-messages` to a separate `json-corpus` directory (separation of concerns)
* Use `make` to orchestrate the (re)generation of JSON files when needed
* Base the corpus on feature files defined in [compatibility-kit](https://github.com/cucumber/cucumber/tree/master/compatibility-kit)

This corpus would be used to test `json-to-messages` as well as some proprietary tools built in SmartBear. The same corpus could be used to test any tool that consumes Cucumber JSON, so we hope to get input from the community here.

**Comment by aslakhellesoy** [comment]
Hi @laxersaz - would you be interested in collaborating on this? I assume you've had to deal with JSON inconsistencies in [Cluecumber](https://github.com/trivago/cluecumber-report-plugin)?

**Comment by aslakhellesoy** [comment]
@laxersaz I see there are some documents in https://github.com/trivago/cluecumber-report-plugin/tree/main/example-project/json - do you have a record of what cucumber implementation/version was used to generate each of these?

**Comment by laxersaz** [comment]
These initially came from your repo: https://github.com/aslakhellesoy/cucumber-json-formatter

**Comment by laxersaz** [comment]
In the example project readme, it is also referenced:

```
The example Cucumber JSON files are located in the project's json directory. These are based on the https://github.com/aslakhellesoy/cucumber-json-formatter project. The report is generated inside the target/cluecumber-report directory.
```

**Comment by aslakhellesoy** [comment]
> These initially came from your repo: https://github.com/aslakhellesoy/cucumber-json-formatter

Aha! And I see I wrote this:

> This repo will document the behaviour of the json formatter for different Cucumber implementations.

I had completely forgotten about this. I also see that this repo is a fork of https://github.com/cucumber/cucumber-json-testdata-generator which has had a little bit of activity recently, the latest one by @tooky.

What do you say - shall we just rubber-stamp https://github.com/cucumber/cucumber-json-testdata-generator as the official one and continue to collaborate there?

**Comment by laxersaz** [comment]
Sure makes sense.

**Comment by aslakhellesoy** [comment]
Ok I'm closing this then. The official repo for Cucumber JSON test data is https://github.com/cucumber/cucumber-json-testdata-generator
