### ISSUE TITLE
Scenario update

### ISSUE THREAD

**Issue by psimanic1** [cucumber/cucumber#141]
Hi I'm using cucumber with protractor, I'm new to it and i couldn't find a way to do this(google didn't help either..)
Every time i run my tests, at first it runs check for feature and stepDef files(if all steps are made and stuff), and they all pass, but when it run tests and lets say it can't find some elements, it still has that scenarios status as "passed" in my JSON output file. Is there a way to update scenario status if there are some errors with tests?

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
