### ISSUE TITLE
Tag not working when run maven command

### ISSUE THREAD

**Issue by pradipyogipacific** [cucumber/cucumber#1410]
When i run below maven command :

mvn test -Dcucumber.filter.tag="@Login"

Then it should only run Login Feature but currently its running all feature.

Test Runner 

@RunWith(Cucumber.class)
@CucumberOptions(
		features = {"src/test/resources/parallel"},
		glue = {"StepDefinationFiles", "AppHooks"},
		plugin = {"pretty",
				"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
				"timeline:test-output-thread/"}
		//tags = "@LinkTest"
)

Feature file : 

Feature: Login Page

  Background:

    Given user open browser and navigate site

  @LinkTest
  Scenario: Login Page all link check
    Given user on login page
    Then user validate privacy policy link
    Then user validate is forgot password present
    And close browser

Feature file : 

Feature: MyLogin

  @Login
  Scenario: MyLogin
    Given user launch browser
    When user open mysite
    Then user send id and pass
    Then user click on login button
    Then close browser
    
    
    
   I'm running from cmd maven command
   Its working fine when i'm run from test runner

**Comment by nhojpatrick** [comment]
You might need to add the following in your surefire config;
<systemProperties combine.children="append">

As described here
https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

As cucumber will only see system properties that surefire/failsafe expose
to them or forward to them.

If you think about it like this;
Maven -> Surefire -> JUnit -> Cucumber

Maven is not directly talking with Cucumber, but via two frameworks used
for testing. Check your using the latest versions of everything as well to
rule out old properties with new framework, or old framework with new
properties.

John

**Comment by mpkorstanje** [comment]
The property is named `cucumber.filter.tags`. Note the additional `s`.

**Comment by pradipyogipacific** [comment]
Can you help ho to do in pom.xml

  <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <includes>
                        <include>**/MyTestRunner.java</include>-->
                    </includes>
                    <parallel>methods</parallel>
                    <threadCount>4</threadCount>
                    <useUnlimitedThreads>false</useUnlimitedThreads>
                    <systemProperties combine.children="append">
                    </systemProperties>
                </configuration>
            </plugin>

**Comment by pradipyogipacific** [comment]
Is it right way :

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <systemProperties combine.children="append">
                        <propertyName>propertyValue</propertyName>
                        <buildDirectory>${project.build.directory}</buildDirectory>
                    </systemProperties>
                    <includes>
                        <include>**/MyTestRunner.java</include>-->
                    </includes>
                    <parallel>methods</parallel>
                    <threadCount>4</threadCount>
                    <useUnlimitedThreads>false</useUnlimitedThreads>
                </configuration>
            </plugin>

**Comment by psrini7** [comment]
@pradipyogipacific I’m facing similar issue could you please let me know how you fixed it ?
