### ISSUE TITLE
Hooks parameters

### ISSUE THREAD

**Issue by camohub** [cucumber/cucumber#1420]
Hooks parameters - tags + order

I need to set up @tag and order parameters to the @After() hook.

If I try to write @After("@test", order=1) it throws me an error: **java: annotation values must be of the form 'name=value'**

I need to run specific hook with parameters in this form @After("not @test", order=1). It is not possible. If I use only one of this params it works, but I am not able to join order and tags with comma. 

* Version used: 6.8.1
* Java 11
* Operating System and version: Win 10

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/tools/cucumber-open/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
