### ISSUE TITLE
gherkin-perl: Update release process

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#143]
## Summary

Update Perl/CPAN release process to be consistent with other libraries.

## Expected Behavior

It should be possible to release `gherkin-perl` using the process currently outlined in `/RELEASE_PROCESS.md`

## Current Behavior

There is a release process implemented and described in `gherkin/perl/Makefile` and `gherkin/perl/CONTRIBUTING` which is inconsistent with `/RELEASE_PROCESS.md`.

## Possible Solution

Remove release targets from `gherkin/perl/Makefile` and update `gherkin/perl/CONTRIBUTING`.

Make sure `scripts/functions.sh` is updated to release Perl projects.

What do you think @pjlsergeant ?

**Comment by pjlsergeant** [comment]
This all looks sensible
