### ISSUE TITLE
Eclipse : Cucumber - No repository found at https://cucumber.github.io/cucumber-eclipse-update-site-snapshot/. In Eclipse

### ISSUE THREAD

**Issue by YenikeRaghuRam** [cucumber/cucumber#1431]
Eclipse : Cucumber - No repository found at https://cucumber.github.io/cucumber-eclipse-update-site-snapshot/. In Eclipse

Refer screenshots
![CucumberEclipseUpdate](https://user-images.githubusercontent.com/81166452/111991172-05680800-8b3a-11eb-82ec-e5299b22d200.PNG)
![cucumbereclipse](https://user-images.githubusercontent.com/81166452/111991176-06993500-8b3a-11eb-84aa-43eb8ae28c00.PNG)

**Comment by aurelien-reeves** [comment]
Hi,

Thanks for reporting the issue.

This repository is related to cucumber itself.
Regarding the eclipse plugin, please open an issue in the following repository: https://github.com/cucumber/cucumber-eclipse/issues

**Comment by YenikeRaghuRam** [comment]
Raised issue in cucumber-eclipse https://github.com/cucumber/cucumber-eclipse/issues/427
hence closing issue
