### ISSUE TITLE
Eclipse : Natural 9.0 - Unable to read repository at http://rlogiacco.github.com/Natural/compositeContent.xml. org.apache.http.client.ClientProtocolException

### ISSUE THREAD

**Issue by YenikeRaghuRam** [cucumber/cucumber#1432]
Eclipse : Natural 9.0 - Unable to read repository at http://rlogiacco.github.com/Natural/compositeContent.xml. org.apache.http.client.ClientProtocolException

Refer screenshots
![natural](https://user-images.githubusercontent.com/81166452/111991615-832c1380-8b3a-11eb-909d-05852a1511ab.PNG)
![natural8](https://user-images.githubusercontent.com/81166452/111991622-845d4080-8b3a-11eb-837b-ff45ccc45b55.PNG)

**Comment by mpkorstanje** [comment]
The natural plugin is maintained http://rlogiacco.github.com.
