### ISSUE TITLE
Ruby protobuf-cucumber: Cucumber to upstream to protobuf?

### ISSUE THREAD

**Issue by jackorp** [cucumber/cucumber#1436]
## Summary
While it's not ideal, would you (the maintainers) mind stepping up as protobuf upstream? Regarding relevant discussion in the issue's #1386 [comment](https://github.com/cucumber/cucumber/issues/1386#issuecomment-785911200).

You are the upstream right now for the pure ruby protobuf implementation. I am asking if you see yourself as the defacto upstream since the original project seems inactive.

Another question is how much do the forks actually diverge right now. Is there any added value beyond the mentioned pull requests?

Would you step up

## Context & Motivation
Protobuf upstream seems unresponsive since the PRs [411](https://github.com/ruby-protobuf/protobuf/pull/411) and [415](https://github.com/ruby-protobuf/protobuf/pull/415) related to cucumber-messages have been sitting there for around a year.

I am currently involved in packaging the update for the cucumber ruby gem, and one of the tasks required is packaging protobuf.
The problem is that to make it work with cucumber-messages, I need the patches from PRs (effectively creating my own fork in the form of the package).

Regarding the diverge in the fork vs. upstream, in the case of some security patches I missed when comparing histories that do not have a PR, I'd have to manually backport them, which is too much work in comparison to just packaging the protobuf-cucumber.

**Comment by mpkorstanje** [comment]
We are not interested in maintaining ruby protobuf and are looking to replace it in our implementation.

https://github.com/cucumber/cucumber/pull/1414

**Comment by aslakhellesoy** [comment]
Thanks for reaching out @jackorp - closing this since we'll no longer be using protobuf at all in one of the next releases.
