### ISSUE TITLE
[gherkin] `@cucumber/messages` release yesterday broke `@cucumber/gherkin` package

### ISSUE THREAD

**Issue by christian-bromann** [cucumber/cucumber#1437]
## Summary

If you install `@cucumber/gherkin` via:

```sh
$ npm install @cucumber/gherkin
```

You download `@cucumber/gherkin@17.0.2` which has a file `node_modules/@cucumber/gherkin/dist/src/stream/GherkinStreams.js` that imports:

```js
var stream_2 = require("@cucumber/messages/dist/src/stream");
```

which doesn't exist anymore after the `@cucumber/messages` release yesterday. I am also a bit confused as to where this code comes from. I looked into:

- https://github.com/cucumber/gherkin-javascript
- https://github.com/cucumber/cucumber/tree/master/gherkin/javascript
- and ultimately found the file here: https://github.com/cucumber/cucumber/blob/master/gherkin-streams/javascript/src/GherkinStreams.ts

which is confusing as it now is part of the `@cucumber/gherkin-streams` package. In the [webdriverio integration](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L9) we made use of the `GherkinStreams` class so I am wondering if `@cucumber/gherkin` got deprecated at some point.

## Expected Behavior

`@cucumber/gherkin` should use an updated version of `@cucumber/messages`.

## Current Behavior

An error is being thrown:

```
Error: Cannot find module '@cucumber/messages/dist/src/stream
Require stack
- /path/to/packages/wdio-cucumber-framework/node_modules/@cucumber/gherkin/dist/src/stream/GherkinStreams.js
- /path/to/packages/wdio-cucumber-framework/build/index.js
```

## Possible Solution

Update use of `@cucumber/messages` in `@cucumber/gherkin` but I have no idea if the code is still up to date and which repo I should look at.

I would love to switch to `@cucumber/gherkin-streams` but that package doesn't exist on NPM yet.

## Steps to Reproduce (for bugs)

1. `$ npm install @cucumber/gherkin`
2. create a file that imports a class from the package, e.g. `import GherkinStreams from '@cucumber/gherkin/dist/src/stream/GherkinStreams'`
3. run the file: `$ node file.js`

## Context & Motivation

https://github.com/webdriverio/webdriverio/issues/6616

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by aslakhellesoy** [comment]
Sorry about this! We're looking into this today.

**Comment by aslakhellesoy** [comment]
Here is where we messed up: We did a *big* refactoring of our TypeScript code in #1372. As part of this big PR we made some breaking changes that we forgot to document in the various changelogs.

Because we had forgotten to document them, we incorrectly assumed we could make a semver *minor* release of `@cucumber/messages` when in fact it should have been a *major* release.

As a quick fix we'll re-release the `14.0.1` release as `14.1.2`, which should be picked up and restore the behaviour. Will confirm here when this is done - shouldn't take long.

**Comment by christian-bromann** [comment]
Pinning `@cucumber/messages` to `14.0.1` also works for us.

**Comment by aslakhellesoy** [comment]
We've released `@cucumber/messages` version `14.1.2` which is identical to `14.0.1`, so everything should be back to normal, even if you don't pin your dependency.

To pick up this version the following should work:

```
npm remove @cucumber/cucumber
npm add --save-dev @cucumber/cucumber
```

Please confirm if this work for you.

**Comment by christian-bromann** [comment]
I can confirm this has fixed the issue. Thank you for the quick turn around 👍

**Comment by aslakhellesoy** [comment]
Great! And thanks for reporting - you saved lots of people from having the same problem 😓
