### ISSUE TITLE
Cannot find name Long error

### ISSUE THREAD

**Issue by Krithikmano** [cucumber/cucumber#1444]
## Summary

Getting the below error after installing "@cucumber/cucumber": "^7.0.0",

node_modules/@cucumber/messages/dist/src/messages.d.ts:642:35 - error TS2304: Cannot find name 'Long'.

642                 seconds?: (number|Long|null);
                                      ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:658:41 - error TS2304: Cannot find name 'Long'.

658                 public seconds: (number|Long);
                                            ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:738:35 - error TS2304: Cannot find name 'Long'.

738                 seconds?: (number|Long|null);
                                      ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:754:41 - error TS2304: Cannot find name 'Long'.

## Expected Behavior

<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->
<!--- Feel free to use Given / Then / Then if that helps, but please add some plain-language context too -->
It should not throw this error while using earlier version of cucumber
## Current Behavior

<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

<!--- If you have got some output place it in the code block below. Otherwise remove it. -->
~~~
~~~

## Possible Solution

<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)

<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context & Motivation

<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment

<!--- If you're reporting a bug, include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Operating System and version:
* Link to your project:

**Comment by aurelien-reeves** [comment]
Thanks for your report

messages@14 should fix that as it does not uses number|Long anymore.

A new release of cucumber-js which will update the dependency to messages will fix that. It is planned soon.

**Comment by aslakhellesoy** [comment]
Does this happen when you:

a) Install Cucumber
b) Transpile your code
c) Run Cucumber

We need more info to reproduce this

**Comment by varshanharshank** [comment]
@aurelien-reeves I am using typescript. After installed cucumber 7.00 and run cucumber and got that message.

**Comment by aslakhellesoy** [comment]
@varshanharshank can you help us with a repo to reproduce this?

**Comment by varshanharshank** [comment]
@aslakhellesoy 

i could not share my project here, because that is private. 

getting above error while running the cucumber scenarios using protractor command (Ex: protractor conf.js

I am using below dependency 

  "dependencies": {
    "@serenity-js/assertions": "^2.25.0",
    "@serenity-js/console-reporter": "^2.25.0",
    "@serenity-js/core": "^2.25.0",
    "@serenity-js/cucumber": "^2.25.0",
    "@serenity-js/local-server": "^2.25.0",
    "@serenity-js/protractor": "^2.25.0",
    "@serenity-js/rest": "^2.25.0",
    "@serenity-js/serenity-bdd": "^2.25.0",
    "@types/chai": "^4.2.14",
    "@types/node": "^14.14.9",
    "@types/xml2js": "^0.4.7",
    "@types/xml2json": "^0.11.3",
    "@types/yargs": "^16.0.0",
    "chai": "^4.2.0",
    "chai-smoothie": "^0.3.2",
    "cucumber-html-reporter": "5.2.0",
    "cucumber-junit": "^1.7.1",
    "hex-and-rgba": "^1.4.2",
    "https": "^1.0.0",
    "js-base64": "^3.6.0",
    "npm-run-all": "^4.1.5",
    "protractor": "^7.0.0",
    "protractor-cucumber-framework": "^7.0.2",
    "protractor-react-selector": "^2.2.4",
    "rgb-hex": "^3.0.0",
    "rimraf": "^3.0.2",
    "ts-node": "^9.0.0",
    "tunnel": "0.0.6",
    "webdriver-manager": "^12.1.7"
  },
  "devDependencies": {
    "@cucumber/cucumber": "^7.0.0",
    "typescript": "^4.2.2"
  }

**tsconfig file**

 {
  "compileOnSave": true,
  "compilerOptions": {
    "lib": ["es2015"],
    "module": "commonjs",
    "target": "es2017",
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "sourceMap": false,
    "declaration": false,
    "removeComments": false,
    "outDir": "binDir",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "types": ["node", "protractor-react-selector"]
  },
  "exclude": ["node_modules"]
}

**Comment by aurelien-reeves** [comment]
I've just tried to setup a minimal project to reproduce your issue, with protractor, cucumber, and typescript.
I did not encounter any issue.

Try to upgrade your packages

If you still encounter any issue, please provide a minimal project which reproduces it. You don't have to share any private data to do so.
