### ISSUE TITLE
Allow David Goss to release Cucumber-JS

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber#1445]
For context, see https://cucumberbdd.slack.com/archives/C612KCP1P/p1616759048003700

**Comment by aslakhellesoy** [comment]
We've been using docker for a while to make `cucumber-js` releases: 

* https://github.com/cucumber/cucumber-js/blob/master/CONTRIBUTING.md#release-process
* https://github.com/cucumber/cucumber-js/blob/master/Makefile

**Comment by luke-hill** [comment]
So is this just to get him onto keybase then?

**Comment by aslakhellesoy** [comment]
Yes, @davidjgoss just DM your keybase username to @mattwynne once you've set it up and he should be able to grant you access. (I can also grant you access, but I want to make sure @mattwynne can do it too).

**Comment by davidjgoss** [comment]
Thanks @mattwynne @aslakhellesoy, I can pull the secrets and run the docker container successfully so happy to close this now.

Once we get https://github.com/cucumber/cucumber-js/pull/1637 merged I'll try doing a minor release.
