### ISSUE TITLE
make hangs on npx sass

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#1448]
Run:

```
git reset --hard HEAD
git clean -dfx
make docker-run
```

Then:

```
make
...
npx sass src/styles/styles.scss > dist/src/styles/cucumber-react.css 
<infinite hang>
```

This doesn't happen in CI, running with:

```
CI=true make
...
npx sass src/styles/styles.scss > dist/src/styles/cucumber-react.css
npm WARN exec The following package was not found and will be installed: sass
```

Presumably because the command is waiting for input:

```
cukebot@22df7f470f34:/app/react/javascript$ npx sass 
Need to install the following packages:
  sass
Ok to proceed? (y) 
```

I guess `sass` should be installed before `npx sass` is ran, not sure how to do this with the new setup.

**Comment by aslakhellesoy** [comment]
Yes, we should add sass if it’s not already there. npx -y will work too, but then we’ll get whatever the latest version is, so better to install it.

**Comment by aslakhellesoy** [comment]
Btw, I think this -y business is new in npm/npx, which come from the docker image, all the more reason to version the docker image, so things don’t change underneath us.

**Comment by aurelien-reeves** [comment]
Why does the message
> Need to install the following packages:
>   sass
> Ok to proceed? (y) 
> 

does not appear in the docker container?

**Comment by aslakhellesoy** [comment]
@aurelien-reeves - I think it does appear in the docker container when the `CI` environment variable is not defined.

https://github.com/npm/cli/blob/dedb9c8f8b0891b30aa76e60cdb1c4f0f9b2f22f/lib/exec.js#L207-L216

**Comment by aurelien-reeves** [comment]
@aslakhellesoy actually, no.
I finally reproduced the non-appearing confirmation message.
It is due to the output redirection in the `Makefile`

To reproduce, without sass installed at all:

```bash
cd react/javascript
npx sass --version # will show the "Need to install" message
npx sass --version > sass.version # hang. Actually, does not hang. Wait for user input, but does not show prompt message
```
