### ISSUE TITLE
Go: Implement CLI

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#145]
_From @aslakhellesoy on December 6, 2016 22:46_

This issue is for remaining work of #240 related to Go:

* [x] Print errors as ndjson
* [x] Replace `bin/gherkin-generate-ast` with a new `bin/gherkin`
* [x] Implement stream API
* [x] Implement a pickles compiler and use it in stream API and `bin/gherkin`

@muhqu / @koterpillar / @l3pp4rd - any takers?

_Copied from original issue: cucumber/gherkin#245_

**Comment by aslakhellesoy** [comment]
_From @koterpillar on December 6, 2016 22:52_

I don't have any Go expertise, sorry.

**Comment by l3pp4rd** [comment]
Sure I can help with **go**, where should I look for all details in order to understand what exactly needs to be done?

**Comment by aslakhellesoy** [comment]
Great @l3pp4rd!

We've moved to a monorepo (this repo), so cd into `gherkin/go`. Uncomment [Makefile:16](https://github.com/cucumber/cucumber/blob/master/gherkin/go/Makefile#L16) (and comment out 15) and run `make`. You'll see errors. So the first thing to do is make sure the AST and errors are printed as the expected results.

When you've got that working, create a new `bin/gherkin` binary which should be able to print out 3 different kinds of events - `source`, `GherkinDocument` (and later `pickle`) events. Gherkin is now both a library and a CLI which people can use. 

The other implementations have added a stream API to the library. This allows other Go libraries (such as godog) to consume the event stream without having to fork the `gherkin` CLI. It also allows events to be consumed as Go objects without the need to use a JSON representation. The JSON representation should only be used by the CLI.

And finally, implement the compiler, which interprets the AST and produces a more compact data structure which is optimised for Cucumber's execution.

The other implementations that support all of this are C, .NET, Java, JavaScript, Python and Ruby, so there are places to look at for inspiration :-)

How does that sound?

**Comment by l3pp4rd** [comment]
Hm, makes sense, I'll start the branch, but not sure I understand the ultimate goal yet. If all cucumber implementations will have a concept of pickles through gherkin, then maybe the idea is to send them to some tool with an updated state (step status, definition, runtime) in order to produce unified formatting? Or will there be other events for such execution state?

**Comment by l3pp4rd** [comment]
Thanks for your time explaining it @aslakhellesoy ;)

**Comment by l3pp4rd** [comment]
hm, found https://github.com/cucumber/gherkin/pull/240 and branched from **cli** as [cli-go](https://github.com/cucumber/gherkin/tree/cli-go). though, currently not sure whether I had to branch from this repo master? If that is so, then I'll just recommit everything here in **cli-go** branch and open a PR.

**Comment by aslakhellesoy** [comment]
Hi @l3pp4rd 

Please create a pull request in this repo (`cucumber/cucumber`). Use `gherkin-go-*` as branch name and `gherkin-go: ***` as PR name.

PRs against this monorepo aren't built by CI yet - I hope to set that up soon. Currently CI will only run after I have merged the PR to master and synced the monorepo to `cucumber/gherkin-go`.
