### ISSUE TITLE
cannot load such file -- gherkin/dialect

### ISSUE THREAD

**Issue by Valentyna** [cucumber/cucumber#1463]
cannot load such file -- gherkin/dialect
Error creating formatter: pretty (LoadError)
/Users/vakalini/.rvm/gems/ruby-2.7.0/gems/cucumber-5.0.0/lib/cucumber/formatter/pretty.rb:4:in `require'

Seeing it on both ruby 2.7.0 and 3.0.0
cucumber 5.3.0, 5.0.0, 4.0.0

I removed `require 'gherkin/dialect'` as a temporary fix

running `require 'gherkin/dialect'` in IRB returns `true`

**Comment by aslakhellesoy** [comment]
Can you confirm what version of Gherkin you have? Your `Gemfile.lock` should say.

We have a [floating dependency](https://github.com/cucumber/cucumber-ruby/blob/ee6ed2ab108151a52b7a3ae0b5190bdebe413f8c/cucumber.gemspec#L26) on `cucumber-gherkin` - I wonder if a recent `cucumber-gherkin` release might have broken this...

**Comment by aslakhellesoy** [comment]
The last `15x` release of `cucumber-gherkin` is `15.0.2`, so `16x` or higher shouldn't be picked up unless you've declared another gem that pulls in a newer incompatible gherkin version.

I think we need a minimal repo to reproduce this so we can investigate.

**Comment by Valentyna** [comment]
There's no `gherkin` or `cucumber` in `Gemfile.lock` (in any word combination). And even before (when cucumber worked) I don't think there were any.
I honestly can't think of anything that changed between then and now what could break it. Few weeks ago it worked and I don't recall updating anything during this time.

**Comment by Valentyna** [comment]
> GEM
>   remote: https://artifactory/.../gem/
>   specs:
>     activesupport (6.1.3.1)
>       concurrent-ruby (~> 1.0, >= 1.0.2)
>       i18n (>= 1.6, < 2)
>       minitest (>= 5.1)
>       tzinfo (~> 2.0)
>       zeitwerk (~> 2.3)
>     addressable (2.7.0)
>       public_suffix (>= 2.0.2, < 5.0)
>     capybara (3.32.1)
>       addressable
>       mini_mime (>= 0.1.3)
>       nokogiri (~> 1.8)
>       rack (>= 1.6.0)
>       rack-test (>= 0.6.3)
>       regexp_parser (~> 1.5)
>       xpath (~> 3.2)
>     capybara_test_helpers (1.0.4)
>       activesupport
>       capybara
>     childprocess (3.0.0)
>     coderay (1.1.3)
>     concurrent-ruby (1.1.8)
>     connection_pool (2.2.2)
>     diff-lcs (1.4.4)
>     domain_name (0.5.20190701)
>       unf (>= 0.0.5, < 1.0.0)
>     excon (0.79.0)
>     faker (2.16.0)
>       i18n (>= 1.6, < 2)
>     flickraw (0.9.10)
>     http-accept (1.7.0)
>     http-cookie (1.0.3)
>       domain_name (~> 0.5)
>     i18n (1.8.9)
>       concurrent-ruby (~> 1.0)
>     method_source (1.0.0)
>     mime-types (3.3.1)
>       mime-types-data (~> 3.2015)
>     mime-types-data (3.2020.0425)
>     mini_mime (1.0.2)
>     mini_portile2 (2.4.0)
>     minitest (5.14.4)
>     multi_json (1.15.0)
>     net-http-persistent (4.0.0)
>       connection_pool (~> 2.2)
>     netrc (0.11.0)
>     nokogiri (1.10.9)
>       mini_portile2 (~> 2.4.0)
>     pry (0.14.0)
>       coderay (~> 1.1)
>       method_source (~> 1.0)
>     public_suffix (4.0.4)
>     rack (2.2.2)
>     rack-test (1.1.0)
>       rack (>= 1.0, < 3)
>     regexp_parser (1.7.0)
>     require_all (2.0.0)
>     rest-client (2.1.0)
>       http-accept (>= 1.7.0, < 2.0)
>       http-cookie (>= 1.0.2, < 2.0)
>       mime-types (>= 1.16, < 4.0)
>       netrc (~> 0.8)
>     results_keeper (1.0.2)
>       flickraw
>       net-http-persistent
>       rest-client
>     rspec (3.10.0)
>       rspec-core (~> 3.10.0)
>       rspec-expectations (~> 3.10.0)
>       rspec-mocks (~> 3.10.0)
>     rspec-core (3.10.1)
>       rspec-support (~> 3.10.0)
>     rspec-expectations (3.10.1)
>       diff-lcs (>= 1.2.0, < 2.0)
>       rspec-support (~> 3.10.0)
>     rspec-mocks (3.10.2)
>       diff-lcs (>= 1.2.0, < 2.0)
>       rspec-support (~> 3.10.0)
>     rspec-support (3.10.2)
>     rubyzip (2.3.0)
>     selenium-webdriver (3.142.7)
>       childprocess (>= 0.5, < 4.0)
>       rubyzip (>= 1.2.2)
>     site_prism (3.7.1)
>       addressable (~> 2.5)
>       capybara (~> 3.8)
>       site_prism-all_there (>= 0.3.1, < 1.0)
>     site_prism-all_there (0.3.2)
>     sw_util (1.2.1)
>       require_all (< 3.0)
>     tzinfo (2.0.4)
>       concurrent-ruby (~> 1.0)
>     unf (0.1.4)
>       unf_ext
>     unf_ext (0.0.7.7)
>     xpath (3.2.0)
>       nokogiri (~> 1.8)
>     zeitwerk (2.4.2)
> 
> PLATFORMS
>   ruby
> 
> DEPENDENCIES
>   capybara (~> 3.31)
>   capybara_test_helpers
>   excon (~> 0.79)
>   faker (~> 2.16)
>   multi_json (~> 1.15)
>   pry
>   require_all (~> 2.0)
>   results_keeper (~> 1.0)
>   rspec (~> 3.10)
>   selenium-webdriver (~> 3.142)
>   site_prism (~> 3.7)
>   sw_util (~> 1.2)
> 
> BUNDLED WITH
>    2.1.4
>

**Comment by aslakhellesoy** [comment]
Thanks for sharing the `Gemfile.lock`. I'm puzzled why `cucumber` (and its dependencies) are not there. Do you have them in your `Gemfile` at all? If not, how do you install Cucumber in your project? If you don't have `cucumber` in your `Gemfile` I suggest you add it and `bundle install` again.

If this doesn't solve your problem, we'll look into this if you share a minimal repo that reproduces this behaviour.
