### ISSUE TITLE
`make` command for gherkin python does not build the module

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/cucumber#1481]
As we can see in the following CI builds, the `make` command does barely nothing by itself in `gherkin/python`.

- https://app.circleci.com/pipelines/github/cucumber/cucumber/5872/workflows/99353b13-28a5-47db-80f3-301d19150d00/jobs/219587
- https://app.circleci.com/pipelines/github/cucumber/cucumber/5872/workflows/99353b13-28a5-47db-80f3-301d19150d00/jobs/219595

I encounter the same behavior on my development computer inside the docker container.

`make default` however is working as expected.

**Comment by brasmusson** [comment]
The problem was introduced in #1458.
