### ISSUE TITLE
Built-in HTML report generates a blank HTML file

### ISSUE THREAD

**Issue by mangjoze** [cucumber/cucumber#1482]
Built-in HTML report generates a blank HTML file

## Summary

Running my test using cucumber's built in html report, it generates a blank html file. viewing the source shows a bunch of css tags and license.

On terminal, if I type _cucumber -t @wip --format html --out report.html._ This runs my test but it generates a blank report.html. I'm not sure if I need to install a 3rd party formatter or an additional ruby gem to cater to this.

## Expected Behavior

I'm expecting it to have the html report where the feature file steps and screenshots are visible.

## Your Environment

* Version used: cucumber 6.0.0
* Operating System and version: Windows 10
ruby 2.7.0

**Comment by luke-hill** [comment]
Hi @mangjoze 

You shouldn't need any 3rd party plugins. Can you try running it using `bundle` and can you also try running it with the cucumber version set to a 5.x version (We just released 6.0 recently)

**Comment by luke-hill** [comment]
Also as you've created duplicate issues. I'll close this one off. And we can continue the conversation on the one on the cucumber-ruby repo.
