### ISSUE TITLE
gherkin-perl: Gherkin uses feature from perl5.12 but only requires perl5.10.1   language:perl

### ISSUE THREAD

**Issue by jwrightecs** [cucumber/cucumber#1494]
gherkin-perl:  Gherkin uses feature from perl5.12 but only requires perl5.10.1

## Summary

When running gherkin on perl 5.10.1 (the minimum supported version), the "..." lines in Gherkin::Pickles::Compiler cause a syntax error, perl minimum version should be increased or '...' feature  not used

## Expected Behavior
'gherkin' command should parse and run and return ndjson formatted messages

## Current Behavior
gherkin command fails with syntax error

~~~
$ gherkin
syntax error at /home/gherkin/perl5/lib/perl5/Gherkin/Pickles/Compiler.pm line 35, near "..."
syntax error at /home/gherkin/perl5/lib/perl5/Gherkin/Pickles/Compiler.pm line 171, near "..."
Compilation failed in require at /home/gherkin/perl5/lib/perl5/Gherkin.pm line 9.
~~~

## Possible Solution
One of
* Gherkin module should have 5.12 as the minimum version, and not be installable on 5.10.1, or
* Gherkin::Pickles::Compiler should use 'die "Unimplemented";' instead of '...', making it 5.10.1 compatible

## Steps to Reproduce (for bugs)

1. perlbrew use 5.10.1
2. cpanm Gherkin
3. gherkin
4.

## Context & Motivation
Trying to use Gherkin to parse files on an old system (Centos 6, Perl 5.10.1)

## Your Environment

* Version used: Gherkin-18.1.1
* Operating System and version: CentOS 6
* Link to your project:

**Comment by ehuelsmann** [comment]
Thanks for the report! We'll get this fixed (back to 5.10.1) and organize a release.
