### ISSUE TITLE
[@cucumber/gherkin]  parser.parse cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by tarkers** [cucumber/cucumber#1496]
## Summary
javascript
it returns **TypeError: Cannot read property 'reset' of undefined**
should i give the custom parser builder and tokermatcher but how to provide id?
```JavaScript
var Gherkin = require("gherkin");
var parser = new Gherkin.Parser();
var gherkinDocument = parser.parse("Feature: ..."); // get error at this line
var pickles = new Gherkin.Compiler().compile(gherkinDocument);
```
 

## Expected Behavior
return gherkinDocument successfully

## Current Behavior
~~~
TypeError: Cannot read property 'reset' of undefined
~~~

## Your Environment

* Version used:"@cucumber/gherkin": "18.1.1"
* Operating System and version: windows 10

**Comment by aurelien-reeves** [comment]
The gherkin parser needs an AstBuilder and a TokenMatcher. Cf. https://github.com/cucumber/cucumber/blob/master/gherkin/javascript/src/Parser.ts#L109

You can take a look at AstBuilder here: https://github.com/cucumber/cucumber/blob/master/gherkin/javascript/src/AstBuilder.ts
And TokenMatcher here: https://github.com/cucumber/cucumber/blob/master/gherkin/javascript/src/TokenMatcher.ts

May I ask: what are you trying to build? What are your needs?

**Comment by tarkers** [comment]
I want to parse the feature file  into  json file.
In python , i use **gherkin-official**
```python
from gherkin.token_scanner import TokenScanner
from gherkin.parser import Parser
parser = Parser()
# text read from my feature file
ff = parser.parse(TokenScanner(text))
```
the ff data is the thing i want ,than i hope if there are also some  function in javascript
i 've check the doc but i can''t figure out what i should do to get such data. 
Seems it doesn't need AstBuilder or a TokenMatcher ?

**Comment by aurelien-reeves** [comment]
Official implementation may be close, they are not identical.
As I said: try instanciating an AstBuilder and a TokenMatcher to properly instanciate the parser.

**Comment by tarkers** [comment]
Ok , i'll give it a try ,thanks your help

**Comment by aurelien-reeves** [comment]
If you encounter any other difficulties, of course you can reopen that issue.
Also, feel free to ask the community: https://cucumber.io/docs/community/

**Comment by aslakhellesoy** [comment]
@aurelien-reeves can you update the `README.md` please? It's still incorrect.

**Comment by aurelien-reeves** [comment]
I missed the fact that the code reported in the issue was actually a snippet from one of our readme.

I'll submit a PR soon. I am afraid we may have to update a lot of the snippets.

**Comment by aurelien-reeves** [comment]
@tarkers in the PR https://github.com/cucumber/cucumber/pull/1497 you should find a better snippet.

Sorry for my previous messages. I missed that you have found your own snippet in a readme in the repo.

**Comment by tarkers** [comment]
@aurelien-reeves  thx, follow  #1497 javascript code 
```javascript
var Gherkin = require("@cucumber/gherkin")
var Messages = require("@cucumber/messages")
var uuidFn = Messages.IdGenerator.uuid;
var builder = new Gherkin.AstBuilder(uuidFn);
var matcher = new Gherkin.TokenMatcher();
var parser = new Gherkin.Parser(builder, matcher);
var gherkinDocument = parser.parse("Feature: ...");
var pickles = Gherkin.compile(gherkinDocument, 'uri_of_the_feature.feature', uuidFn)
```
it works!
