### ISSUE TITLE
Gherkin C tests fail on Alpine Linux

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#165]
## Summary

Approval tests (diffing golden masters) fail on Alpine Linux

## Expected Behavior

I'd expect it to work just as on other Linuxes and OS X.

## Current Behavior

The `uri` property of `gherkin-document` events is empty:

~~~
bin/gherkin --no-source --no-pickles testdata/good/background.feature | jq --sort-keys --compact-output "." > acceptance/testdata/good/background.feature.ast.ndjson
diff --unified <(jq "." testdata/good/background.feature.ast.ndjson) <(jq "." acceptance/testdata/good/background.feature.ast.ndjson)
--- /dev/fd/63	2017-03-21 21:27:34.586342889 +0000
+++ /dev/fd/62	2017-03-21 21:27:34.586342889 +0000
@@ -58,5 +58,5 @@
     "type": "GherkinDocument"
   },
   "type": "gherkin-document",
-  "uri": "testdata/good/background.feature"
+  "uri": ""
 }
make: *** [Makefile:89: acceptance/testdata/good/background.feature.ast.ndjson] Error 1
make: *** Deleting file 'acceptance/testdata/good/background.feature.ast.ndjson'
~~~

## Possible Solution

Don't know

## Steps to Reproduce (for bugs)

```
git clean -dfx gherkin/c
docker run -v $(pwd):/app -it cucumber/cucumber-build:1919bbc16bcd230522be530efc885b29 bash
cd gherkin/c
make .compared
```

## Your Environment

* Version used: `HEAD of master`
* Operating System and version: Alpine Linux 3.5 running in Docker

**Comment by aslakhellesoy** [comment]
Hi @brasmusson - any idea what might be causing this?

**Comment by brasmusson** [comment]
The uri originally comes from the command line arguments, which are passed as arrays of char (as defined by the [signature of `main`](http://stackoverflow.com/questions/4207134/what-is-the-proper-declaration-of-main)). This differs from most other data (originating from the feature files) which is read into arrays of wide-char (`wchar_t`). This is the angle I would explore first
