### ISSUE TITLE
Document build/contributing process for contributors

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#167]
It's a bit daunting for newcomers to find out where and how to make changes.

* Do I contribute in monorepo or subrepo? 
* How do they get synced? 
* What directory?
* How does CI work? 
* What software do I need? 
* How do I run a build on my machine? 
* How can I find issues to help on?
* Where do I send pull requests?
* When do I get commit rights?
* Who's on the core team?
* How do I make a release?

There are some docs about this in the root folder (some of them are out of date). `CONTRIBUTING.md` is too long and boring.

Let's steal shamelessly from these great projects (with credits):
* http://hood.ie/contribute/
* https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md

Some general guides for inspiration:
* https://opensource.guide/
* http://www.firsttimersonly.com/
* https://opensource.com/life/16/3/contributor-guidelines-template-and-tips
* https://guides.github.com/activities/contributing-to-open-source/
* http://contribution-guide-org.readthedocs.io/#
* http://www.writethedocs.org/guide/

**Comment by mlvandijk** [comment]
@aslakhellesoy Should this be in the docs.cucumber.io project? (can an issue be 'moved' or should it be replicated?)
Also, having recently joined this is something I'd like to start on (at least starting from my own experience), possibly with some help (@js?)

**Comment by mlvandijk** [comment]
@aslakhellesoy Still think this is a good idea; maybe move it to the docs project?

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/docs.cucumber.io#67
