### ISSUE TITLE
@Given @When not working properly in JAVA

### ISSUE THREAD

**Issue by brajesheee** [cucumber/cucumber#169]
## Summary

@Given @When not working properly  in Java

## Expected Behavior

When I give @Given("^(.*)$") then it should fetch only the steps defined under Given keyword

## Current Behavior

@Given @When not working when we give the cucumber Anchor as ("^(.*)$"). It is fetching all steps from feature file

## Steps to Reproduce (for bugs)

@Given("^(.*)$") 
	    public void Test(String step)  {
	            System.out.println(step);
	    }
Above code fetches all steps not just the Given Steps
## Context & Motivation

I want to read the Steps given under each keyword in the step definitions.

## Your Environment

* Version used: cucumber-java 1.2.5
* Operating System and version: Windows 7

**Comment by aslakhellesoy** [comment]
Cucumber doesn't distinguish between `Given`, `When` and `Then` when matching steps with Step definitions. We have no plans to change this behaviour.
