### ISSUE TITLE
Cucumber-JS CLI - tag expressions are broken in Cucumber 2.0.0-rc9

### ISSUE THREAD

**Issue by PeterAronZentai** [cucumber/cucumber#178]
using  `Cucumber-js`

- Given following test
```
  @any
  Scenario: Open website
    Given ...

  @skip
  Scenario: Open website - 2
    Given ...
```
- When I invoke `cucumber-js --tags @any,@skip`  
- Then both scenarios should be executed

But the result is no scenario gets executed
```
❯ ./node_modules/.bin/cucumber-js --tags @any,@skip features
0 scenarios
0 steps
0m00.000s
```

**Comment by aslakhellesoy** [comment]
As of [2.0.0-rc.0](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#200-rc0-2016-11-25) Cucumber-JS uses [tag expressions](https://docs.cucumber.io/tag-expressions/).

You'll find a migration guide [here](https://docs.cucumber.io/tag-expressions/#migrating-from-old-style-tags)
