### ISSUE TITLE
how to organize and execute a large number of features

### ISSUE THREAD

**Issue by hzy00** [cucumber/cucumber#18]
My application has many modules. So I want to orgnize my features by module in subdirectory. But,  there is a problem has been harassing me: 
how to execute the featues in my prefered order? Should I rename my features file in order?  However, mayber I just want to execute some modules' features. I may have many different prefered order.  
  Maybe, someone suggests to execute featutre like this:
 "cucumber -r features 1.feature 2.feature..."
 That's good if my features are not too many.  When I have a large number features to execute, it's to inconvenient. Anybody has better suggestion?

**Comment by yigithanyilmaz** [comment]
Hey there,

You should not execute your tests from feature files it is far from practicle. You start using tags. This will help you organize your tests freely. Add a tag to the top of your Feature file like @billing or @important.


Cheers

<pre>
Eg.
cucumber --tags @billing            # Runs both scenarios
cucumber --tags @important          # Runs the first scenario
cucumber --tags ~@important         # Runs the second scenario (Scenarios without @important)

cucumber --tags @billing --tags @important    # Runs the first scenario (Scenarios with @important AND @billing)
cucumber --tags @billing,@important           # Runs both scenarios (Scenarios with @important OR @billing)

</pre>

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
