### ISSUE TITLE
Composite step

### ISSUE THREAD

**Issue by tenebrarum118** [cucumber/cucumber#182]
Is it possible to consider the following enhancement:
Like now we have scenario with a set of steps inside, I want to have some kind of additional entity, lets call it "composite step". Semantically, it should be very similar to scenario, but it should represent a set of atomic actions which are covered by shortcut. 

Lets say like this:

Composite step: When user is logging in into application  <-- this is shortcut
    When user opens browser
    And user opens URL "http://myappurl"
    And user sets "user1" into login text box
    And user sets "password" into password text box
    And user click on "login" button

More input can be found here: https://github.com/techtalk/SpecFlow/issues/813

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
