### ISSUE TITLE
feature tags: Not parsing correctly with comment on tag line

### ISSUE THREAD

**Issue by JakeKaad** [cucumber/cucumber#183]
## Summary

Our project uses a `@known-failure` tag to keep track of tests that recreate a bug or are for WIP features.  We will use a comment to describe why the test is failing. If the comment ends up on the tag line, then the tags will no longer work.

So if we have the test set up as follows
```
@known-failure # This test fails for some reason, see JIRA-1234.
Scenario: Does something ...
step
step
step

# This test fails for some reason, see JIRA-1234.
@known-failure 
Scenario: Does something else ...
step
step
step
```

And then run the tests with:
```
cucumber --tags ~@known-failure
```
Cucumber will run the first scenario but not the second

## Expected Behavior

When a feature's tag line has a comment in it
Then I expect the the feature to respond correctly to the --tags CLI option

I can provide more in depth information if needed but it seems fairly straight forward. Thank you!

**Comment by aslakhellesoy** [comment]
As of [2.0.0-rc.0](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#200-rc0-2016-11-25) Cucumber-JS uses [tag expressions](https://docs.cucumber.io/tag-expressions/).

You'll find a migration guide [here](https://docs.cucumber.io/tag-expressions/#migrating-from-old-style-tags)

**Comment by aslakhellesoy** [comment]
The Gherkin grammar does not allow any content to precede a comment. Comments can only be preceded by whitespace.
