### ISSUE TITLE
Cucumber tags

### ISSUE THREAD

**Issue by reach2jeyan** [cucumber/cucumber#184]
Multiple tags in the cucumber doesnt run the scenarios.

I have two different tags, tagged to two different scenarios under the same feature file. I try to run both the scenarios that are tagged, using the cucumber tags command

`cucumber --tags @billing --tags @important`

When I run this, cucumber doesn't recognize the scenarios, it provides the output like 

```cucumber --tags @billing --tags @important
0 scenarios
0 steps
0m0.000s
```

But when I run the tags individually, like `cucumber --t @billing` the cucumber is able to recognize and runs the scenario. Any idea why?  

Any help is appreciated.

**Comment by brasmusson** [comment]
If you read up on [Tags](https://github.com/cucumber/cucumber/wiki/Tags#running-a-subset-of-scenarios), you see that cucumber does exactly what you are asking it to do, that is to run all the scenarios which each have both the tag `@billing` __and__ the tag `@important`. There you can also read how to combine tags with __or__. 

In the future, please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
