### ISSUE TITLE
Excluding a tag results in no tests being run

### ISSUE THREAD

**Issue by WillemMali** [cucumber/cucumber#189]
## Summary

I invoke Cucumber like so:

    node_modules/cucumber/bin/cucumber.js --tags '~@deprecated'

My features look like this:

`homepage.feature`:

    Feature: homepage
      Scenario: visit homepage
        Given I am on "/"

`homepage-old.feature`:

    @deprecated
    Feature: homepage
      Scenario: visit homepage
        Given I am on "/home"

This results in exactly 0 tests being executed.

## Expected Behavior

The one test without the @deprecated tag is run.

## Current Behavior

No tests are run.

## Possible Solution

??? (Fix the `--tags` CLI impl.)

## Steps to Reproduce (for bugs)

See Summary.

## Your Environment

cucumber: `2.0.0-rc.9`
node: `v7.9.0`
OS: `Debian GNU/Linux 8 (jessie)`

**Comment by brasmusson** [comment]
Note the [breaking changes in 2.0.0-rc.0](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#200-rc0-2016-11-25) with respect to tags.
