### ISSUE TITLE
Change pull request template

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#192]
## Summary

Make it simpler for contributors and more useful for committers.

## Expected Behavior

People know how to fill out the checklist

## Current Behavior

It's a bit elaborate.

## Possible Solution

Use a variant of [nodejs' template](https://github.com/nodejs/node/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

## Context & Motivation

The current one is too complicated.

**Comment by mlvandijk** [comment]
(A link to) commit guidelines would be helpful!
