### ISSUE TITLE
--format information in Cucumber --help could be more helpful

### ISSUE THREAD

**Issue by flashquartermaster** [cucumber/cucumber#196]
"Use --format rerun --out features.txt to write out failing
features. You can rerun them with cucumber @rerun.txt."

If 'features.txt' were 'rerun.txt' then it would be more obvious that there is a match between the output of '-f rerun' and the following input through @rerun.txt

Also,

It might be nice to indicate which formatters can't be output and which don't follow the usual pattern of outputting to a file

e.g.
debug - no output
junit - to directory

**Comment by mattwynne** [comment]
Fixed by 12ac20e1e146aed7276df953d27be1c57d034785
