### ISSUE TITLE
Gherkin: example row taggable

### ISSUE THREAD

**Issue by stengvac** [cucumber/cucumber#199]
Hello,
we are using Cucumber quite a lot for functional tests (FT) at our project. It is quite big project and our usage of Cucummber is quite extensive. Now we are investigating how to work with Cucumber in reporting over time, trends, regresion tests and other statistics. We have even create internal reporting tool. 

## The problem is 
Lets say we have Scenario Outline and it is passing for a realy long time. Scenario Outline looks like following example:
```
Feature:
   Scenario Outline: 
     Given I have cucumber
      When I "<ACTION>" cucumber
      Then Cucumber "<RESULT>"
    Examples:
     | ACTION| RESULT                | 
     | throw    | explode               |
     | hate      | vanish                  |
     | love      | is in love with me |
```
But one day one of scenario run fails. Lets say it was scenario run with data row  | throw  | explode |.
So we would like to add information about new bug occurrence to feature file via @Bug tag.

## Possible Solution
Tag @Bug represent failed scenario run due to bug. So feature file could look like this:
```
Feature:
   Scenario Outline: 
     Given I have cucumber
      When I "<ACTION>" cucumber
      Then Cucumber "<RESULT>"
    @Bug
    Examples:
     | ACTION| RESULT                | 
     | throw    | explode               |
   Examples:
     | ACTION| RESULT                | 
     | hate      | vanish                  |
     | love      | is in love with me |
```
But this solution does not feel right for me.
Lets say we would like to split bugs to (Frond End) FE and BE (Back End) or another division which make more sense.

## Proposed enhancement
Preferable solution: taggable data rows. So we could do something like:
```
Feature:
   Scenario Outline: 
      Given I have cucumber
      When I "<ACTION>" cucumber
       Then Cucumber "<RESULT>"
    

    Examples:
     | ACTION| RESULT                | 
     @Bug - apply only for this row
     | throw    | explode               |
     | hate      | vanish                  |
     | love      | is in love with me |
```

Tags on rows can have only documentation purpose so they will not affect if row is executed or not.

Best regards,
V

**Comment by mattwynne** [comment]
I'd rather see something like

```
Feature:
  Scenario Outline: 
    Given I have cucumber
    When I "<ACTION>" cucumber
    Then Cucumber "<RESULT>"

    Examples:
    | ACTION | RESULT             | 
    | throw  | explode            | @Bug
    | hate   | vanish             |
    | love   | is in love with me |
```

**Comment by aslakhellesoy** [comment]
> But this solution does not feel right for me.

Can you elaborate on why this doesn't feel right to you?

**Comment by stengvac** [comment]
Some mixed reasons.

1, For each combination of tags one Example section is requited. Bug&FE, Bug&BE ,...
2, Until few days ago I did not expect, that one Scenario Outline can support multiple Examples sections it seams weird/unexpected for me. Why should I write multiple Example sections? To divide happy and error scenario runs?  In our project tester team came with idea, that first column in Example section with  predefined name is used instead of scenario name so each scenario run name can be described separatedly in our reporting tool. With this practice I don't see reason for multiple Examples. Are there other reasons for multiple Examples then tags or I am i missing something?

**Comment by stengvac** [comment]
Not so sure about
```
| throw  | explode            | @Bug
```
some Example sections have a lot of columns.

**Comment by brasmusson** [comment]
> Not so sure about
> ```
> | throw  | explode            | @Bug
> ```
> some Example sections have a lot of columns.
> Inserting tags before row will ruin formatting.

@stengvac The proposal was to put the tags at the end of the row, not at the start, so formatting will not be affected.

This issue is a duplicate of https://github.com/cucumber/gherkin/issues/142.

**Comment by stengvac** [comment]
Yeah, but I said some Examples sections have a lot of columns. So they can be long. Like super long.
