### ISSUE TITLE
Test suite for events

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#20]
At #cukenhagen @mattwynne suggested we write a test suite that will validate that a cucumber emits the expected events when executing features.

**Comment by mattwynne** [comment]
Note that, for now, there's a few scenarios emerging in Cucumber-Ruby here: https://github.com/cucumber/cucumber-ruby/blob/event-stream/features/docs/formatters/event_stream_formatter.feature

**Comment by aslakhellesoy** [comment]
Done: https://github.com/cucumber/cucumber/tree/master/event-protocol
