### ISSUE TITLE
How can I write information to xml report

### ISSUE THREAD

**Issue by yJLiGit** [cucumber/cucumber#200]
## Summary

I use the plugin : junit: /report/testreport.xml to output test infomation to xml report.

I use " scenario.write("message to testreport.xm"); ", but the message ""message to testreport.xm"" can not be written into the xml report.

May I know how to add custom information to cucumber junit xml report?

Thank you.

## Expected Behavior

Message : "message to testreport.xm" should be written to report : /report/testreport.xml 

## Current Behavior

~~~
~~~
Message : "message to testreport.xm" is not written to report : /report/testreport.xml 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: info.cukes:cucumber-java:1.2.5, info.cukes:cucumber-junit:1.2.5
* Operating System and version: Mac OS 10.12.4
* Link to your project:

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by yJLiGit** [comment]
Hello Seems no one respond in the chat group, may I know is there any quick solution for this problem
