### ISSUE TITLE
Custom information can not be added to cucumber junit xml report

### ISSUE THREAD

**Issue by yJLiGit** [cucumber/cucumber#203]
## Summary
I use the plugin : junit: /report/testreport.xml to output test infomation to xml report.

I use " scenario.write("message to testreport.xm"); ", but the message ""message to testreport.xm"" can not be written into the xml report.

May I know how to add custom information to cucumber junit xml report?

**I think this is a bug, because I can use scenario.write to add information to json, html, but not xml. And I post the problem  to cucumber support forum, but no one answer**
Thank you.

## Expected Behavior

Message : "message to testreport.xm" should be written to report : /report/testreport.xml

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1. use scenario.write("message to testreport.xm"); to add information to report
2. use junit reporter for running : junit: /report/testreport.xml
3. check the report: /report/testreport.xml to see whether information: "message to testreport.xm" are added to the report.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by aslakhellesoy** [comment]
You could modify [JUnitFormatter](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java) and send a pull request?

**Comment by yJLiGit** [comment]
Hello, actually. I want to know whether the behavior is expected. Yes, modify JUnitFormatter would be an option. Thanks a lot for your help.

**Comment by aslakhellesoy** [comment]
Expected behaviour? Yes, because the plugin's `write` method is empty. 
Desired behaviour? Probably not - it would make sense to store it in the report, as you describe.

**Comment by aslakhellesoy** [comment]
Please send a PR to the cucumber-jvm project if you want to change this.
