### ISSUE TITLE
Can I specify the path to the step_definitions file

### ISSUE THREAD

**Issue by jwtang** [cucumber/cucumber#205]
## Summary
Can I specify the path to the step_definitions file？

I don't want to put the step_definitions file in the step_definitions folder, I created a lib folder to put step_definitions files, can I specify a step_definitions file path for the feature file?

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
