### ISSUE TITLE
gherkin-ruby: The `rule_type` parameter in `AstBuilder#end_rule` is not used?

### ISSUE THREAD

**Issue by drhuffman12** [cucumber/cucumber#208]
## Summary

While working on porting [gherkin-ruby](https://github.com/cucumber/gherkin-ruby) to crystal as [gherkin-cr](https://github.com/drhuffman12/gherkin-cr), I noticed that the `AstBuilder#end_rule` method in `lib/gherkin/ast_builder.rb` looks odd:

```rb
    def end_rule(rule_type)
      node = @stack.pop
      current_node.add(node.rule_type, transform_node(node))
    end
```

## Current Behavior

The `rule_type` parameter passed into `end_rule` is not used. (The `rule_type` in `node.rule_type` is that node's attribute, not the `end_rule` method's parameter.)

## Expected Behavior

I'm not sure which is expected.

## Possible Solution

Should `def end_rule(rule_type)` be just `def end_rule`, or should `rule_type` somehow be used to filter the @stack items?

**Comment by aslakhellesoy** [comment]
Hi @drhuffman12 the parser is generated from a grammar file and a template as described in the [README](https://github.com/cucumber/cucumber/blob/master/gherkin/README.md#architecture).

Are you writing the parser by hand? That would make it very hard to maintain. You're right that the `rule_type` isn't used, and we should probably change all the templates for all the languages, but I'm not too worried about it.

**Comment by aslakhellesoy** [comment]
Closed due to inactivity
