### ISSUE TITLE
results circles are not displaying after upgrading the jenkins to 1.652 version

### ISSUE THREAD

**Issue by ManjunathMuniyapla** [cucumber/cucumber#21]
Hi 

We have "Cucumber Reports Plugin" version 0.0.23 (pretty old) , and we upgraded our jenkins to 1.652 , after upgrading we are seeing that the cucumber results are not displaying the circle form,
It is saying that "This content requires JavaScript." 
Due to some reasons Our QA team is not ready to upgrade the Cucumber Reports Plugin.

Can you please suggest how to fix this issue ??

screen shot attached 

Thanks in Advance
Manjunath
![cucumber_plugin_issue](https://cloud.githubusercontent.com/assets/11041721/14104429/cca46b6a-f5c2-11e5-8c75-5159e0a1ff40.png)

**Comment by brasmusson** [comment]
The ["Cucumber Reports Plugin"](https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin) is not developed or maintained by the team from https://github.com/cucumber. Use the ["project website"](https://github.com/jenkinsci/cucumber-reports-plugin) link on the plugin page to get to the issue tracker to report issues
