### ISSUE TITLE
Cross platform DataTable implementation

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#210]
There are several `DataTable` implementations around, (in order of appearance):

* [data_table.rb](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/multiline_argument/data_table.rb)
* [DataTable.java](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/DataTable.java)
* [data_table.js](https://github.com/cucumber/cucumber-js/blob/master/src/models/step_arguments/data_table.js)

We should take the best parts of all these (slightly divergent) implementations and reimplement it as a standalone (cross platform) library with a shared test suite. This has already been done in [Cucumber Expressions](https://github.com/cucumber/cucumber/tree/master/cucumber-expressions), [Tag Expressions](https://github.com/cucumber/cucumber/tree/master/tag-expressions) and of course, [Gherkin](https://github.com/cucumber/cucumber/tree/master/gherkin).

I think this implementation should be decoupled from the Gherkin library - it should *not* depend on Gherkin's [DataTable](https://github.com/cucumber/cucumber/blob/master/gherkin/java/src/main/java/gherkin/ast/DataTable.java) implementation. Instead, it should be possible to construct a new `DataTable` object with a simple array of array of strings.

For this new implementation I would like data tables to support the Cucumber Expressions' custom [parameter types](https://docs.cucumber.io/cucumber-expressions/#custom-parameters).

This would allow users to define parameter types once, and use them both in steps and data table headers. For example:

```gherkin
Given some stuff:
  | color | currency |
  | red   | GBP      |
  | green | NOK      |
  | blue  | EUR      |
```

The corresponding `DataTable` would then automatically convert columns to the right type.

If you're interested in helping out building this new `DataTable` put your name below!

**Comment by osher** [comment]
im here, my name is Osher
I connect to what you say, but I need you to confirm my understanding.

If I get you right - you want instead of:
```
     | name     | String | Monster Joe |
     | escapes  | Int    | 7           |
     | address  | String | Balfur 413  |
     | district | String | Sohoy       |
     | city     | String | London      |
     | caught   | Bool   | No          |
     | lastSeen | Date   | 1976-06-07  |
```
to write:
```
     | name     | "Monster Joe" |
     | escapes  | 7           |
     | address  | "Balfur 413"  |
     | district | "Sohoy"       |
     | city     | "London"      |
     | caught   | No          |
     | lastSeen | 1976-06-07  |
```

and assume ParameterType like
```
//date
{
  regexp: /\d{4}-\d{2}-\d{2}/,
  transformer: Date.parse,
  typeName: 'date'
}
```

My only fear is that it makes the table too technical to explain: 
Normal people (the target audience for feature files) do not enclose values with quotes, technical people do
Without the quotes, we cannot distinct between "No" that should be interpreted as false, and "No" that should be interpreted as a string

**Comment by osher** [comment]
one more question - I need to clarify I understand how ParameterType works:
Does the regexp list of each parameter type applied on the capture, or against the gherkin line?
Can I use captures in the 2nd regexp and expect them in the transformer?

i.e - I speculate order of operation, can you confirm it?
1 - step regexp tried on line
2 - step regexp matches -> delivers captures
3 - for each capture
     - for each ParamType
        - for each ParamType.regexp
            match? yes - use transformer & break

Can you point me to the relevant code so I can read it?

**Comment by osher** [comment]
About quotes - 
Can we can default to string if no other type is recognized, and allow to specify strings explicitly by enclosing with quotes?

i.e - enclosed string will take precedence, and defaulting to string if no other type is matched

What happens if a capture matches two types? do we intend to throw like we do with matching two step defs?

**Comment by aslakhellesoy** [comment]
I just had an idea for how to use parameter types with tables. We'll require tables to be captured by an output parameter in the Cucumber Expression. This can default to `{table}`, which would produce a regular `DataTable` object, or it could be `{something}` where `something` refers to a parameter type named `something`. The header would be used to inspect the parameter type's `type`, possibly querying about field names and types, so it can transform the individual cells in each row of the body. Each body row then becomes an instance of the `type` associated with `something`, with fields set to the transformed values of the cells.

The original discussion was [in slack](https://cucumberbdd.slack.com/archives/C62GZFLLT/p1505860969000069)

**Comment by osher** [comment]
Not fully clear...
perhaps I'm not up to date with your DSL... 
do you want me to join you on slack?

**Comment by aslakhellesoy** [comment]
I'll try to give an example (in JavaScript):

```javascript
defineParameterType({
  name: 'ingredient',
  transformer: ({name, amount, unit}) => new Person({name, amount, unit}),
  // no regexp - this parameter type is only used for tables, not cucumber expressions
})
```

A class:

```javascript
defineParameterType({
  name: 'ingredient',
  transformer: ({name, amount, unit}) => new Person({name, amount, unit}),
  // no regexp - this parameter type is only used for tables, not cucumber expressions
})
```

A data table:

```gherkin
class Ingredient {
  constructor({name, amount, unit}) {}
}
```

A step definition:

```javascript
Given('the following ingredients:', 'ingredient', function(ingredients) {
  // ingredients is an Array of Ingredient
})
```

This is different from what I said in the comment above (but more aligned with the end of the linked slack discussion)

**Comment by aslakhellesoy** [comment]
ugh typos - correcting...

**Comment by osher** [comment]
Well, I'm not aware of that discussion, however - I can see that this solution does not work out of the box -  it requires users to define transformers.
Generally it does not make me too happy - but I'll go with the flow, and contribute some comments later.

Before that - mind that we started with a PR that aims to let user define data-type of fields **_vertically_**, and we end up discussing defining data-type of a complete object **_horizontally_**

Last groan here - is that the requirement for explicitness and readability is lost, because the Gherkin spec doc does not provide the data-types - they are inferred.

Anyway - I don't see how one is related to the other - these are two different use-cases - we can support both.


Now - to business 😄 
I assume you don't mean
```
  transformer: ({name, amount, unit}) => new Person({name, amount, unit}),
```
but 
```
  transformer: ({name, amount, unit}) => new Ingredient({name, amount, unit}),
```

AFAI understand - here the class `Ingedient` is an implementation detail of the `transformer` handler, and not a requirement of any type.
We could just as well say:
```
defineParameterType({
  name: 'ingredient',
  transformer: ({name, amount, unit}) => ({ name, amount: Number(amount), unit }),
  // no regexp - this parameter type is only used for tables, not cucumber expressions
})
```
or 
```
defineParameterType({
  name: 'itinerary',
  transformer: ({target, fromDate, toDate, fare, curCode}) => ({ 
    target,
    fromDate: moment(fromDate, 'YYYY-MM-DD'),
    toDate: moment(fromDate, 'YYYY-MM-DD'),
    fare: Number(fare),
    currency: currencies[curCode] || `NaC: ${curCode}`
  }),
  // no regexp - this parameter type is only used for tables, not cucumber expressions
})
```
I hope I'm right here... 
By no mean do I wish to impose users work in paradigms they don't like

...


And that the 2nd argument in 
```
Given('the following ingredients:', 'ingredient', function(ingredients) {
```

refers to 
```
defineParameterType({
  name: 'ingredient',
```
which is AFAIK - an API change of a future change.

In that case I would propose to try take the argument name from `func.toString()` and rid of the API change of additional optional argument.

I also can suggest that if we support optional attributes (like `regexp`) - we can support an additional optional attribute that will tell how the variable name is given for list - this will allow users cascade a default behavior that assumes `'ingredients'` is the plural of `'ingredient'` for whatever lingual exception, or whatever user preference (e.g. `'ingredientList'`).
Heck, it can even be a list of such names, if the user needs more flexibility (less consistency).

**Comment by osher** [comment]
one more last cent:

If we really must go for an api change and introducing an additional argument - let it be a destructurable property-bag, and not a string.
this is more extensible and will let us provide any additional directives we wish to provide for a step.

**Comment by akostadinov** [comment]
> Instead, it should be possible to construct a new DataTable object with a simple array of array of strings.

FYI in ruby we already can call in World:
```
my_table = table([["a","b","c"],["v","f","r"]])
```

**Comment by mpkorstanje** [comment]
Some notes for Java.

Currently the ParameterTypeRegistry only contains a mapping of `(name|regex): String => Type`. To make working with DataTables in Java possible `(name): TableRow => Type` is also needed. This has already been proposed above but the lack of types doesn't make this obvious.

Without naming a table row transform lambda step definitions should be able to handle any non generic type as their arguments. When declaring a table row transform they must be able to handle any type. Annotation based step definitions should be able to handle all types without naming a table row transform. Though they may still do so as a form disambiguation.

When no  `TableRow => Type` transform can be found the default should be a bean mapper. This would be equivalent to ` transformer: ({name, amount, unit}) => {name, amount, unit}),` in javascript.

Java provides several mappings from a DataTable. They're currently all Type based but should also get a name based version.

```
   <T> T convert(DataTable dataTable, Type type, boolean transposed);
    <T> List<T> toList(DataTable dataTable, Type itemType);
    <T> List<List<T>> toLists(DataTable dataTable, Type itemType);
    <K, V> Map<K, V> toMap(DataTable dataTable, Type keyType, Type valueType);
    <K, V> List<Map<K, V>> toMaps(DataTable dataTable, Type keyType, Type valueType);
```

To facilitate diffing domain objects against data tables java also provides a transform 

```
    DataTable toTable(List<?> objects, String... columnNames);
```

This would require that the mappings are extended to include a reverse transform. E.g. `(name|regex): (String => Type, Type => String)` and  `(name): (TableRow => Type, Type => TableRow)`. If none is defined they could default to toString and getting bean properties respectively.

**Comment by aslakhellesoy** [comment]
A [ParameterType](https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterType.java) has a `type: Type` field, so it would be trivial to add a `#lookupByType` method to [ParameterTypeRegistry](https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java).

If we do that, the Java API for specifying what `Type` to use for rows could look like this:

```java
Given("the following ingredients:", Ingredient.class, (List<Ingredient> ingredients) -> {
  // ingredients is an Array of Ingredient
})
```

Or if the generic type can be inferred:

```java
Given("the following ingredients:", (List<Ingredient> ingredients) -> {
  // ingredients is an Array of Ingredient
})
```

**Comment by mpkorstanje** [comment]
> A ParameterType has a type: Type field, so it would be trivial to add a #lookupByType method to ParameterTypeRegistry.

Its type is bound to the transform. So the Transform would have to be `Transform<X,T>` where X is either `String` or `Map<String,String>`. We can enforce that in the constructor but the change becomes less trivial. Not too much effort though.

```java
public ParameterType(String name, String regexp, Class<T> type, Transformer<String, T> transformer) {
    this(name, singletonList(regexp), type, transformer, true, false);
}

public ParameterType(String name, Class<T> type, Transformer<Map<String,String>, T> transformer) {
    this(name, emptyList(), type, transformer, false, false);
}
```

> 
> If we do that, the Java API for specifying what `Type` to use for rows could look like this:
> 
> ```java
> Given("the following ingredients:", Ingredient.class, (List<Ingredient> ingredients) -> {
>   // ingredients is an Array of Ingredient
> })
> ```

Yes and when there are multiple ways to create ingredients from a data table we can also use the name based version:

```java
Given("the following english ingredients:", "english-ingredients" (List<Ingredient> ingredients) -> {
  // ingredients is an Array of Ingredient
})

Given("the following spanish ingredients:", "spanish-ingredients" (List<Ingredient> ingredients) -> {
  // ingredients is an Array of Ingredient
})
```

**Comment by mpkorstanje** [comment]
Overall I am not  seeing any disambiguations problems with `(name): (TableRow => Type, Type => TableRow)`. 

I am seeing about disambiguation problems with `(name|regex): (String => Type, Type => String)` For example if I wanted to make a list of `BankNotes(color: Colour, currency: ValutaType)` out of:

```gherkin
 Given some stuff:
  | color | currency |
  | red   | GBP      |
  | green | NOK      |
  | blue  | EUR      |
```

without explicitly defining a transform for BankNotes. Then for ` TableRow => Type` I'd use the the bean mapper. Now the bean mapper have to look up `String => Type`. But there can be multiple transforms registered for `Colour` and `ValutaType`. 

I suppose I could select the one that matches the regex? And if multiple match, throw an exception?

**Comment by aslakhellesoy** [comment]
See e032eba (branch `datatable-spike`) for a spike implementation. I just wanted to get a feel for it. Any comments? WDYT @mpkorstanje?

**Comment by mpkorstanje** [comment]
The code that is now in `asList0` should be in a transform `Map<String,String> => Type` so in `asList0` it might look  something like:

```java
Transform<Map<String,String>, String> rowTransformer =  registry.lookupByType(rowtype);
for (Map<String, String> tableRow : rows) { 
    list.add(rowTransformer.transform(tableRow);
     ...
}
```

It shouldn't be too different from the existing [TableConverter.java](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/table/TableConverter.java). Replace xStream with registry.lookupByType(rowtype).transform(tableRow) and we've got most of it.

**Comment by aslakhellesoy** [comment]
You mean `Transformer` and not `Transform` right?

The existing `ParameterTypeRegistry#lookup*` methods return a `ParameterType`. Are you saying the new `#lookupByType` method should not do that and return a `Transformer` instead?

Could illustrate what you mean by adding some tests and code to my spike branch?

**Comment by mpkorstanje** [comment]
Sure! Just need some time.

**Comment by mpkorstanje** [comment]
Spike got a bit big. Made a new branch. I think this is how it should work:

https://github.com/cucumber/cucumber/blob/50a8edc052ac5286f93b8ff5ea561ffa7c4abe91/cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/DataTableTest.java

**Comment by mpkorstanje** [comment]
I started the data tables/ cucumber expression spike for cucumber-jvm with the assumption that we could use the cucumber expressions to transform single elements in a data table.

For example:

```
| a | 12 |
| b | 13 |
| c | 14 |
```

Should be transformed to a `Map<String, Int>`

This supposedly could be done by looking up an expression for a type say Integer and use the associated transform to transform the field of the data table. In practice however this will run into disambiguation problems and other unexpected chicanery.

For example looking up String forces us to chose between the expressions `{word}` and `{string}` with neither being appropriate. The string need not be a word and may contain escaped characters that `{string}` will unescape.

And this is just the build in types. With custom types it gets even more interesting. So right now I reckon that using cucumber expressions for data tables is just the wrong idea. We might get it to work by force but conceptually the mapping is wrong.

**Comment by mpkorstanje** [comment]
There are three ways in which a table might be converted to an instance of a certain type. 
 * Using the whole table to create a single instance.
 * Using individual rows to create a collection of instances. The first row may be used as header.
 * Using individual cells to a create a collection of instances.

The the transformer that handles this conversion can either be explicitly defined by name or implicitly by the target type. When trying to find a transformer by type they should be considered in order from most (convert the whole table) to least (convert individual cells). 

Dealing with Lists, Lists of Lists and single instances is fairly straightforward. If a single instance is requested. Look up the converter and apply its transform. If a list is is requested lookup the converters in order and apply the first one found. If a list of lists is requested lookup the single instance converter and the cell converter and apply the first one found.

Dealing with maps requires some additional convention. A map consists of a keyset and value set. The key set is created by taking the left column of a data table and transforming it to a list of keys. Note that a single column is also a datatable. The value set is created by taking the other columns and transforming them into a list of values. These two lists are then paired up into a map.

**Comment by aslakhellesoy** [comment]
I would have loved to see this, but I'm closing this issue. 

We're establishing a new [issue triage process](https://github.com/cucumber/cucumber/pull/1326) where we prioritise the oldest issues first.

Given the choice to work on this next or close it, I'm closing it because it's too big. If anyone feels strongly about this, please submit one or more pull requests.
