### ISSUE TITLE
Link to a file/ image within project needed : Gherkin

### ISSUE THREAD

**Issue by Kausthuba** [cucumber/cucumber#222]
## Summary
Clicking on a string / keyword in the Feature file should open the Image / HTML / Table mapped to it.

## Expected Behavior

Its more of an Enhancement you can say. 
Clicking on a string / keyword in the Feature file should open the Image / HTML / Table mapped to it.
The requirement is to link a file / Image / HTML / Table for a keyword or a string mentioned in the scenario of a feature file.  All these files would be maintained withing the project itself.
This would enable us to add more info / data to give clarity for a particular scenario.

## Current Behavior

We have option to give an webpage link within the comment.
But not to a file maintained locally
~~~
~~~

## Possible Solution

1. We could make use of a keyword "Link: " &  explicitly mention the relative path to the file
2. Use a keyword "Link: "& should be able to define the declaration as the file / image path.
3. Enable this functionality within the comment section using #
probably many more solution which you would be able to suggest here.

## Steps to Reproduce (for bugs)

Feature: Outline Sample
  Scenario Outline: Test state
    Given <y> value for <x>
    Examples: **Value**   #clicking on this should open a graph mapping the below plot / atleast a file link
      | x |  y  |
      | 1 | 10 |
      | 2 | 20 |
      | 3 | 45 |
      | 4 | 30 |
or some other keyword as 
:Link #this keyword should allow to link to a file which would be plotting a graph for the below data 

## Context & Motivation

There is a requirement for us to display set of information in a table or a graph. which would explain the behavior of the scenario.

## Your Environment

* Version used: gherkin 3.2.0, Ruby 2.2.4
* Operating System and version: Windows
* Link to your project:
Yet to be created.

**Comment by aslakhellesoy** [comment]
It sounds like this is a feature request for the editor you're using to view feature files.

What editor/IDE are you using?

**Comment by aslakhellesoy** [comment]
Closing this since it is a feature request for an editor/IDE. The feature request should be submitted to the manufacturer of the editor/IDE.

Feel free to reopen this issue if I have misunderstood.
