### ISSUE TITLE
Rerun: Space or new line as feature seperator

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#233]
Are the feature uris to be rerun separated by spaces or new lines?

[rerun.rb](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/rerun.rb) uses spaces:
```
foo/bar.feature:2 foo/bar.feature:4 foo/bar.feature:5
```

While [rerun_formatter.js](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/rerun_formatter.js) and [RerunFormatter.java](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/RerunFormatter.java#L85) both use new lines:
```
foo/bar.feature:2
foo/bar.feature:4
foo/bar.feature:5
```

I find the latter option to be more sane. Space is a valid character in paths.

Is there any spec for this?

**Comment by enkessler** [comment]
I too am a fan of having each test on its own line or at least having each different feature file on its own line.

**Comment by mpkorstanje** [comment]
I've changed the implementation of RerunFormatter.java to use new lines.

**Comment by aslakhellesoy** [comment]
Makes sense, added an issue to cucumber-ruby

**Comment by brasmusson** [comment]
> rerun.rb uses spaces:
> `foo/bar.feature:2 foo/bar.feature:4 foo/bar.feature:5`

Scenarios from the same feature file will not be separated at all:
`foo/bar.feature:2:4:5`

It is only the entries from different feature files that will be separated in different entries:
`foo/bar1.feature:2:4:5 foo/bar2.feature:4:7`

BTW, the parsing of the rerun file in Cucumber-Ruby is already very flexible and it handles:
* spaces in feature file uri:s (`foo bar.feature:3`)
* feature file entries separated by
  * blanks
  * newlines
  * nothing (`foo.feature:3bar.feature:5`)

**Comment by mpkorstanje** [comment]
We should probably use that regex. It is more advanced and much less fragile.

https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/cli/rerun_file.rb
