### ISSUE TITLE
I am trying to throw json query from scenario outline but it is taking below bracket and colons as extra string arguments and throwing implement error that "missing steps with the snippets"

### ISSUE THREAD

**Issue by PratapSingh09** [cucumber/cucumber#236]
This is below scenario outline:

 Scenario Outline: Verify the combination of queries for elastic search
      Given   User request the elastic search endpoint
      When   User post the search"<search>" to get Json response
      Then    User should verify the status of response after posting the search"<search>"

      Examples:
        |search|
        |{\"query\":{\"match_all\": {}}}|

I am posting the rest query by making rest call and calling this query parameter under body.Please find example below:
 rest().given().header("Accept", "application/json")
            .header("Authorization", "")
            .contentType("application/json")
            .header()
            .header()
            .header()
            .body(query)
            .post().then().assertThat().statusCode(200).extract().response().body();

Getting below statement after running the project:

You can implement missing steps with the snippets below:

@When("^User post the search \"([^\"]*)\"query\\\"([^\"]*)\"match_all\\\"([^\"]*)\" to get json response$")
public void user_post_the_search_query_match_all_to_get_json_response(String arg1, String arg2, String arg3) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
