### ISSUE TITLE
Cucumber: Lexing error on line when language is fr

### ISSUE THREAD

**Issue by Labouh** [cucumber/cucumber#238]
Hi

I try to set language to fr in .feature and I get strange charset error regarding file in utf-8, even adding #encoding in the file, it seems it does not like é of Fonctionnalité...
It works well in "en" and replacing keyword BUT in french I get
`[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.5.0-rc.1:aggregate (serenity-reports) on project e2e: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.5.0-rc.1:aggregate failed: Lexing error on line 3: 'Fonctionnalit├®: Creer annonce`

My file is saved as utf-8, as in my pom.xml 
```
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.resources.sourceEncoding>UTF-8</project.resources.sourceEncoding>
        <encoding>UTF-8</encoding>

```
and my OS is windows 10 

(I am using SerenityBDD but it used the standard cucumber parser):
The file first lines :
```
# language: fr
# encoding: utf-8

Fonctionnalité: Creer annonce

```

I try other charset but without success...
What is the issue?
Regards

**Comment by olleolleolle** [comment]
Ensure that you always have encoding as the _first_ line of code, or else it isn't a magic comment, but a common comment.

**Comment by aslakhellesoy** [comment]
Don't use the `# encoding` header. Instead, save the file as UTF-8. You have to tell your editor to do this. I know you said you did, but from the error message it looks like it's not UTF-8.
