### ISSUE TITLE
gherkin: Inline comments don't not work

### ISSUE THREAD

**Issue by enkessler** [cucumber/cucumber#239]
## Summary

Gherkin does not accept inline comments. That is, comments must be on their own line.

`Good`
```
# a comment
@a_tag
```

`Bad`
```
@a_tag # a comment
```
## Expected Behavior

The following gherkin should result in a parsing error
```
@a_tag # a comment
Scenario:
  * some step
```
## Current Behavior

The following gherkin parses cleanly
```
@a_tag # a comment
Scenario:
  * some step
```

but the entire tag line is stored as the name of the tag. This results in no comments being stored in the AST and the wrong tag being stored, thus causing the `cucumber` option `-t @a_tag` to not work as expected because that is not the name of the tag according to `gherkin`.

## Possible Solution

Change that parser so that inline comments are a parsing error.

OR

Change the parser so that it can handle inline comments and generate both the correct tag and the correct comment in the AST

## Steps to Reproduce (for bugs)

1. Make a feature file that has an inline comment after a tag on a test (similar behavior might be seen with inline comments after steps/etc but tags are the only thing that I checked).
2. Attempt to run that test via `cucumber` using a tag filter
3. Watch gherkin not explode when parsing file 
4. Watch cucumber not find the test because gherkin gave it the wrong tag 

## Context & Motivation

I stumbled upon the problem when a team member who didn't know that inline comments aren't part of Gherkin tried to write one. I was surprised that it did not blow up in their face.

## Your Environment

* Version used: gherkin 4.1.3
* Operating System and version: OSX
* Link to your project: N/A

**Comment by aslakhellesoy** [comment]
I think raising a parsing error is easier to implement (and sufficient) - the current design doesn't allow more than one token type per line.

**Comment by vighneshpai-yml** [comment]
I would like to have this feature onboard. Can you guys please open this issue?

**Comment by aslakhellesoy** [comment]
We’ll open it when somebody sends a pull request with a fix.

**Comment by vighneshpai-yml** [comment]
Great! thanks. It will be really nice to have feature.
