### ISSUE TITLE
An easier way to use a different langauge

### ISSUE THREAD

**Issue by esdoppio** [cucumber/cucumber#24]
Say I need to use Japanese as the primary language for my feature files. Do I need to actually put

```
# language: ja
```

at top of each file? That's not really smart to do to be honest.

Can't find a cli option that specifies a spoken language when running tests, and the reference doesn't say anything about this.

**Comment by aslakhellesoy** [comment]
Hi @esdoppio 

There isn't currently a way to specify a language globally, but I really like your idea. It sounds like the lack of this feature really bothers you.

Don't worry - Cucumber is open source, so you can fix this yourself. Just [fork](https://help.github.com/articles/fork-a-repo/) the repo, add support for a new `--language LANGUAGE` option (with tests) and send us a [pull request](https://help.github.com/articles/using-pull-requests/). We'll do our best to help you if you're stuck, and if your contribution is good we might add this in the next release!

Thanks!

**Comment by esdoppio** [comment]
Thanks for the reply.

If we're really going this direction, I think the `--language` option should affects only the feature files that doesn't explicitly specify a spoken language, allowing a project to have tests written in different languages, which is rare, but it doesn't affect users who don't need that complexity.

Do you think this is over-designed? And what do you think of the idea of a configuration file (for cucumber)? @aslakhellesoy

**Comment by aslakhellesoy** [comment]
I agree that a `# language` header in a file should override whatever was specified with `--language`.

Cucumber already has a configuration file - `cucumber.yml`.

Luckily Gherkin already supports specifying a default language - it's just a matter of hooking into it. See https://github.com/cucumber/gherkin/issues/78

**Comment by mattwynne** [comment]
@esdoppio which flavour of Cucumber are you using?

**Comment by esdoppio** [comment]
@mattwynne It's cucumber-ruby.

**Comment by mattwynne** [comment]
OK, in that case let's start with an issue over there: https://github.com/cucumber/cucumber-ruby/issues

Can you raise one, and do your best to describe your acceptance criteria? The very best thing would be if you could create a PR with a new failing feature in https://github.com/cucumber/cucumber-ruby/tree/master/features/docs/cli

**Comment by aslakhellesoy** [comment]
I'm closing this issue since it's in the wrong repo.
