### ISSUE TITLE
Add topics to all cucumber sub projects on Github

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber#241]
## Summary

Add topics to all cucumber sub-projects on Github to add more meta data to projects users can use to find the project which suites their needs best.

* https://github.com/blog/2309-introducing-topics
* https://help.github.com/articles/about-topics/

Example for use in search:
https://github.com/search?utf8=%E2%9C%93&q=topic%3Abdd&type=Repositories

Suggested topics:

* testing-framework
* cucumber
* bdd
* test
* framework
* tdd
* specification-by-example
* test-driven-development
* behaviour-driven-development
* documentation
* communication
* collaboration
* specification
* `<programming language>`

## Expected Behavior

All cucumber sub-projects have topics defined - where relevant.

## Current Behavior

Only some have topics defined.

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mlvandijk** [comment]
You need admin right to be able to do this: https://help.github.com/articles/permission-levels-for-an-organization/
