### ISSUE TITLE
CHANGELOG.md Homogeneity Project

### ISSUE THREAD

**Issue by jaysonesmith** [cucumber/cucumber#251]
# Project

Normalize all `CHANGELOG`/`history` files across all necessary cucumber repos. Please follow the guidelines below and if you have any questions, please ask!

## Guidelines
* Naming: Files must be named `CHANGELOG.md`. If they are anything else, please rename them to fit.
* Line entry format: `[Module] Message ([Issue Link], [Issue Link] Contributor Name One, Contributor Name Two)` (Link to user's github if available) See the [Gherkin CHANGELOG](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md) for an example.
* Entries should be grouped into one of the following: `Removed`, `Added`, `Changed`, `Fixed`. Please prefix with an H3 tag. Aka `###`
* Existing entries in files do not need to be completely updated, but please make sure that mentions to issues/pull requests such as `(PR #123)` are updated to be point to an appropriate Github URL.
  * Example: `(#123)` would turn into `[#123](https://github.com/cucumber/cucumber/pull/123]` or [#123](https://github.com/cucumber/cucumber/pull/123)
  * Don't worry about being correct with pull/issue as they will redirect to one another as needed.
  * [I've created a tool to automatically handle this for you.](https://github.com/jaysonesmith/changelog_updater)
  * Please use the template below for new files or for existing files, make sure that it includes the data below:

```
# CHANGE LOG

All notable changes to this project will be documented in this file.

This project adheres to [Semantic Versioning](http://semver.org).

This document is formatted according to the principles of [Keep A CHANGELOG](http://keepachangelog.com).

Please visit [cucumber/CONTRIBUTING.md](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md) for more info on how to contribute to Cucumber.

----

## [Unreleased] - In Git

### Removed

### Added

* Added this CHANGELOG.md file per [cucumber/cucumber #251](https://github.com/cucumber/cucumber/issues/251)

### Changed

### Fixed

<!-- Releases -->

<!-- Contributors -->
[username]:        https://github.com/username
```

## List of Repos By Current Tracking Type
*All below need to be updated/checked. Please edit the list yourself or let me know when you've completed a repo and I will update the list here.
 (double `~~` on both sides)*

### Changelog.md

* ~~[cucumber-js](https://github.com/cucumber/cucumber-js)~~

### History.md

* ~~[aruba](https://github.com/cucumber/aruba)~~
* ~~[cucumber-cpp](https://github.com/cucumber/cucumber-cpp)~~
* ~~[cucumber-jvm](https://github.com/cucumber/cucumber-jvm)~~
* ~~[cucumber-rails](https://github.com/cucumber/cucumber-rails)~~
* ~~[cucumber-ruby](https://github.com/cucumber/cucumber-ruby)~~
* ~~[cucumber-ruby-core](https://github.com/cucumber/cucumber-ruby-core)~~
* ~~[multi_test](https://github.com/cucumber/multi_test)~~

### No history tracking file

* ~~[aruba-contrib](https://github.com/cucumber/aruba-contrib)~~
* ~~[aruba-website](https://github.com/cucumber/aruba-website)~~
* ~~[commitbit](https://github.com/cucumber/commitbit)~~
* ~~[cucumber-eclipse](https://github.com/cucumber/cucumber-eclipse)~~
* ~~[cucumber-electron](https://github.com/cucumber/cucumber-electron)~~
* ~~[cucumber-html](https://github.com/cucumber/cucumber-html)~~
* ~~[cucumber-jvm-deps](https://github.com/cucumber/cucumber-jvm-deps)~~
* ~~[cucumber-lua](https://github.com/cucumber/cucumber-lua)~~
* ~~[cucumber-react](https://github.com/cucumber/cucumber-react)~~
* ~~[cucumber-ruby-tcl](https://github.com/cucumber/cucumber-ruby-tcl)~~
* ~~[cucumber-ruby-wire](https://github.com/cucumber/cucumber-ruby-wire)~~
* ~~[cucumber-tcl-wire](https://github.com/cucumber/cucumber-tcl-wire)~~
* ~~[github-issue-stats](https://github.com/cucumber/github-issue-stats)~~

-----
-----
## Summary

I've wanted to get various informational documents consistent across our repos as there are pretty significant differences between them. Normalization will help messaging be consistent across the board allowing different users to be able to read all history files across Cucumber regardless of which language specific repo of which they're most familiar.

## Current Implementations

Examples:

* cucumber-ruby uses an `update-history` script to manage their `HISTORY.md` file
* cucumber-js doesn't have a specific format to use for `CHANGELOG.md` but suggests using a specific `git log`.

## Possible Solution

Aslak suggested [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) for our history files. This uses a clear format and groups things by type, similar to what we're doing today.

### Questions/Tuning
1. Naming: Should we use `History.md` or `CHANGELOG.md` across repos? 
  1a. Should what we decide on be in all caps?
2. Every repo (imo) should have some sort of history tracking file so we'll need to go through and add them to repos that don't currently have them. 
  2a. Should we create a day forward file or try to wrangle past commit history into the files we create?
3. Should we change our change 'types' to match KaC's guidance or continue to use our own?
4. KaC does not include a method for including issue numbers, shall we just continue with including them as links at the end with the text being just the issue number?
5. There are a lot of repos below that are listed as read-only, are mirrors, or are just stale overall. Should we be adding tracking files to these ones as well?
6. Guidance: We should include a link at the top of each tracking file pointing to the master contributing file.
7. Guidance: Similar to the Ruby repo, I would like each repo to have a local script that contributors run to update the tracking file with the issue tag. This way we can help keep formatting similar across repos and also enforce a 'newest first' ordering of issues. (Going to make this into its own Issue)

**Comment by aslakhellesoy** [comment]
Great research @jaysonesmith. Some of the repos without a changelog file are read-only mirrors of the `cucumber/cucumber` monorepo:

* gherkin-c
* gherkin-dotnet
* gherkin-go
* gherkin-java
* gherkin-javascript
* gherkin-jvm-deps
* gherkin-lint-javascript
* gherkin-objective-c
* cucumber-expressions-java
* cucumber-expressions-javascript
* cucumber-expressions-ruby
* tag-expressions-java
* tag-expressions-javascript
* tag-expressions-ruby

These repos should not have a changelog - their changelog is in monorepo:

* https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md
* https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/CHANGELOG.md
* https://github.com/cucumber/cucumber/blob/master/tag-expressions/CHANGELOG.md

Some repos don't get tagged and released - they're just "ongoing":

* cucumber (monorepo) - there are many changelogs here, just not at the root
* cucumber-java-skeleton
* aruba-getting-started
* website
* docs.cucumber.io

Some I just moved to the attic:

* cucumber-pretty-formatter
* gherkin
* cucumber-ruby-http

And this one got deleted:

* cucumber-ruby-dev

So I think the remaining ones need a changelog.

Now your questions:

1. Although most projects use `History.md`, I'd be happy to adopt `CHANGELOG.md` as the standard filename. All caps fits well with `README.md` and `CONTRIBUTING.md`.
2. Let's not worry about the past - new `CHANGELOG.md` files should only list what's happened after the file was added.
3. I think we should use a consistent style across all repos. I think the following info is important (see [cucumber-expressions](https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/CHANGELOG.md) and [gherkin](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md) for examples:
    * Change categories (New features, Added, Removed etc)
    * Links to issues/PRs
    * Attributions (links to contributors)
    * Links to a full diff between releases
    * Release date
Each entry is added manually, and it's a little bit tedious, but not too bad IMO. Maybe we can create a small bash script that adds a line with a simple command line.
4. See examples in 3
5. Explained above
6. Agree! The file is there - just needs updating with the process discussed recently on the mailing list.
7. Duplicated scripts are hard to maintain. I suggest adding a bash function to `scripts/functions.sh` in the monorepo

**Comment by jaysonesmith** [comment]
Thanks for the feedback @aslakhellesoy that is all incredibly useful info!

**Comment by mpkorstanje** [comment]
> 1. Naming: Should we use History.md or CHANGELOG.md across repos?
> 1a. Should what we decide on be in all caps?

Looking at `CONTRIBUTING.md`, `LICENSE`, `README.md` and `TODO.md` I reckon `CHANGELOG.md` should be the preferred naming. The capitals appear to indicate these are documentation.

> KaC does not include a method for including issue numbers, shall we just continue with including them as links at the end with the text being just the issue number?

I'm happy with the `[Module] Message ([Issue Link], [Issue Link] Contributor Name One, Contributor Name Two)` format.

I have no strong preference on the other items.

**Comment by jaysonesmith** [comment]
> Let's not worry about the past - new CHANGELOG.md files should only list what's happened after the file was added.

How should we name the old changelog files?

**Comment by mlvandijk** [comment]
Ad 3/4: Wouldn't it be helpful to include one of the keywords to automatically close the related issue? https://help.github.com/articles/closing-issues-using-keywords/

**Comment by jaysonesmith** [comment]
@mlvandijk This wouldn't be touching the Issue/PR directly, only the changelog file so I'm not should (and I could be wrong) that would work?

**Comment by jaysonesmith** [comment]
I wrote a simple ruby script for automatically looking for issue numbers like `[#123]` and adds a full Github url. Save to a file and specify the repo you want it to insert at run time. 

To run: `ruby updater.rb [repo-name] [CHANGELOG.md]`

```ruby
output = ''
File.foreach(ARGV[1]) do |line|
  match = line.match(/\[#(\d{1,3})\]/)
  output += match ? line.gsub(/\[#\d{1,3}\]/, "#{match}(https://github.com/cucumber/#{ARGV[0]}/issues/#{match[1]})") : line
end
File.open("#{ARGV[1]}", "w") {|file| file.puts output }
```

**Comment by brasmusson** [comment]
[Keep a Changelog](http://keepachangelog.com/en/1.0.0/) says that Changelog is "a curated, chronologically ordered list". By their own example it also says the "curated" trumps "chronologically ordered". Using `git blame` on their own Changelog reviles that in
```
- New "Guiding Principles" sub-section to "How do I make a changelog?".
- Simplified and Traditional Chinese translations from @tianshuo. 	
- German translation from @mpbzh & @Art4.
- Italian translation from @azkidenz.
- Swedish translation from @magol.
```
the entries on German and Italian translations was added two months after the entry on new guiding principles. When reading the Changelog to find out what changes were made in a release, I can see that is makes sense to list all added translations together. My take on this is that scrips are handy, but it is still the person using the script to update the Changelog that is responsible that the result is appropriate.

As an example from one of our own project, I think that all ["Fix Metrics/LineLength" PR:s](https://github.com/cucumber/cucumber-ruby/blob/master/History.md#refactoring--developer-experience) (cucumber/cucumber-ruby#1174, cucumber/cucumber-ruby#1175, cucumber/cucumber-ruby#1176 - of which the first is not mentioned in the changelog at all), should rather be grouped into one entry: 
```
* Fix Lint/DuplicateMethods (#1174, #1175, #1176 ...)
```
now they seems to take up an unnecessary amount of real estate in the changelog.

**Comment by brasmusson** [comment]
> This wouldn't be touching the Issue/PR directly, only the changelog

@jaysonesmith @mlvandijk It would be great is the script could detect and add the issues closed by the pull request (which "can" be done by parsing the pull request description), otherwise (at least me that thinks that this information belongs in the changelog) that information needs to be manually added after the script has been executed.

In either case their is still the work of checking (and if necessary adding) that the pull request description closes the appropriate issues, before merging the pull request.

**Comment by mlvandijk** [comment]
@js, for cucumber-jvm, I put: "Please see [CONTRIBUTING.md](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md) on how to contribute to Cucumber." - Let me know if that's ok and it can be merged :)

**Comment by jaysonesmith** [comment]
@mlvandijk That works for me. I've put the same at the top of the file for Aruba.

**Comment by mlvandijk** [comment]
@js You're right, Github won't auto-close from the CHANGELOG. Would it be good practice to include these keywords in commit messages? Or would we prefer to close issues manually?
@brasmusson I was thinking the "Message" part in the line entry format would be the commit message, although I also very much agree with the need for it to be "curated" as the whole point of the changelog is to provide information on notable changes in a way that is easily understandable. It shouldn't be just a chronological list of commits (you can get those from git). Therefore, sometimes it might also be useful to expand on the basic info provided in the line entry format, i.e. in case of breaking changes / wider implications of the change(?)

**Comment by brasmusson** [comment]
> Would it be good practice to include these keywords in commit messages? Or would we prefer to close issues manually?

@mlvandijk I prefer to close issues with pull request descriptions. Yes, in case I would push a fix for an issue directly to master, then that commit would both fix the issue and update the changelog, and its commit message would close the issue. I would not close issues (using those keywords in the commit message) with commits pushed to pull request branches. In that case I think that closing the issues is for the pull request description to do (using those keywords). Closing issues manually is just extra manual work which is to easily to be forgotten, and you will anyway when closing the issue refer to the pull request or commit that did the fix to get that traceability on Github, so it is much better to let Github to create that traceability automatically.

**Comment by jaysonesmith** [comment]
Making good progress tonight though I've realized that I had been formatting the issue and credit section incorrectly, separating the issue/pr numbers and the names with a comma when it was just supposed to be a space. /sigh

**Comment by jaysonesmith** [comment]
> now they seems to take up an unnecessary amount of real estate in the changelog.

I agree and have fixed it.

**Comment by jaysonesmith** [comment]
Since I'm getting into the repos that don't currently track in a CHANGELOG/history file, I'm looking to create a template to be used. In working on this, I grabbed the raw data from the Gherkin CHANGELOG and noticed the contributors section and the release sections sneakily hidden in comments down at the bottom of the file.

Questions: 
1. Is there an easy way to generate a list of current contributors to add to this file upon creation?
2. How do we want to handle repos that don't seem to have blatantly obvious(to me) officially released version? (a-la aruba-contrib)
3. Seeing the Gherkin file also starts off with the CHANGE LOG section, I move that we update our standard CHANGELOG file template to be, to include this as well. (Which means updating the files that I've already updated. Yours too, @mlvandijk & @mpkorstanje) In this header info, we can also point the reader to the monorepo contributing file, 'for more info'. 

Header template:

```
# CHANGE LOG

All notable changes to this project will be documented in this file.

This project adheres to [Semantic Versioning](http://semver.org).

This document is formatted according to the principles of [Keep A CHANGELOG](http://keepachangelog.com).

For more info on how to contribute to Cucumber, please visit our centralized [CONTRIBUTING.md](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md) file in the main Cucumber repository.

----
```
I'm not 100% on the wording of the redirect to the monorepo's file in the header template, so I'm looking for some feedback there, too. 

Thanks all!

**Comment by mpkorstanje** [comment]
I'm thinking this would be better.

```
Please visit [cucumber/CONTRIBUTING.md](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md) for more info on how to contribute to Cucumber.
```

Though cucumber-jvm also has its CONTRIBUTING.md.

**Comment by jaysonesmith** [comment]
@aslakhellesoy How are we going to architect the monorepo's contributing file? Are we going to have sections for the various languages and their nuances/requirements or are we going to have more umbrella data there and let the various repos continue to dictate finer details there?

**Comment by mlvandijk** [comment]
@brasmusson I agree the issue should be closed on merge to master. A PR might not be approved/merged; in that case the issue should remain open.

@js Personally, I think it would be best to have overall guidelines in a central file, and specifics per repo in that repo but also pointing to the central file. Assuming many contributors would contribute to one particular repo/language only.

@aslakhellesoy @plaindocs Related question: Working on https://github.com/cucumber/docs.cucumber.io/issues/15 I noticed that (almost) none of the CONTRIBUTING.md files mention documentation specifically. I did find a general file on contributing to documentation (https://github.com/cucumber/cucumber/blob/master/docs/contributing-to-documentation.md) and added a link there to the new documentation project. Otherwise the process described there sounds good; I would like to merge it with: https://github.com/cucumber/docs.cucumber.io/blob/sw-reorg/CONTRIBUTING.md (preferably on master asap) and then point there from the central (and individual?) CONTRIBUTING.md files.

**Comment by plaindocs** [comment]
> @brasmusson I agree the issue should be closed on merge to master. A PR might not be approved/merged; in that case the issue should remain open.

that is how that usually works afaik

@mlvandijk that sounds totally reasonable to me.

**Comment by mlvandijk** [comment]
@plaindocs I've added a contributing-to-documentation.md to docs.cucumber.io straight to master. It needs to be rebased into sw-reorg and possibly/probably merged with some other info in there, but this way we at least have a place to point to from the other repos...

In general, since we are focusing on cucumber "generic" documentation first, should we make a distinction between BDD/Gherkin/Cucumber documentation which goes here, and implementation specific documentation which would still go in the separate repos?

**Comment by jaysonesmith** [comment]
Got a bunch of the new changelogs done and this issue is almost done, at least initially. (I didn't merge any this time! ;) )

**Comment by jaysonesmith** [comment]
Disregarding my mention of this issue in the above 1194, could I get a review of the open PRs above, please? Just waiting for approval, basically. Thanks!

**Comment by mlvandijk** [comment]
PRs look fine to me as far as the text & links, but I'm not a contributor on these projects so 
1. cannot verify the contributors are correct/complete
2. do not want to take the liberty to merge
3. not all of the checks have completed / passed:
* https://github.com/cucumber/cucumber-electron/pull/15
Some checks haven't completed yet.
* https://github.com/cucumber/cucumber-react/pull/1
Some checks haven't completed yet.
* https://github.com/cucumber/cucumber-ruby/pull/1194
Some checks were not successful
* https://github.com/cucumber/cucumber-ruby-wire/pull/13
Some checks haven't completed yet.
* https://github.com/cucumber/cucumber-tcl-wire/pull/1
Some checks haven't completed yet.

**Comment by jaysonesmith** [comment]
Thanks @mlvandijk! I appreciate the time! WRT contributors, the members listed were pulled directly from Github using the following command and then I added myself to them:

`curl https://api.github.com/repos/cucumber/github-issue-stats/contributors | jq 'sort_by(.login) | [.[] | {user: .login, url: .html_url}]'`

@mattwynne  / @aslakhellesoy Now that these have been approved how would you like me to move forward? Also, are the Ruby tests broken?

**Comment by mlvandijk** [comment]
@js That answers my 1st question. Thnx!

**Comment by jaysonesmith** [comment]
Unless anyone has objections, I'm going to go through and merge things today. I've also got a request from @maxmeyer to add a changelog to aruba-getting-started which I'll do too.

**Comment by jaysonesmith** [comment]
Everything except for the new changelog added in the `aruba-getting-started` repo has been merged! Almost done with this!

**Comment by jaysonesmith** [comment]
I think we're all set here! Going to close this out, we should probably extract the template I wrote above to be a guide for any new repos created?

**Comment by mvz** [comment]
@jaysonesmith I'm currently updating the Aruba change log with new changes, and I'm finding adding all the links for issues and users is becoming quite a chore. Is there any way to automate this?

**Comment by mvz** [comment]
Oh, #255 looks useful!
