### ISSUE TITLE
CHANGELOG.md Update Script

### ISSUE THREAD

**Issue by jaysonesmith** [cucumber/cucumber#255]
## Summary

To ease the task of updating CHANGELOG.md files across the project, a script should be created that can be run to automatically add the needed updates.

## Desired Behavior/Requirements (WIP)

1. BASH script
2. Follow formatting guidelines found in #251 
3. Newest first: Always insert lines at beginning of section. 
4. Utilize the current repo's directory to determine which file to update
5. Take in change type of `Removed`, `Added`, `Changed`, or `Fixed` to match where to input line.
6. Take in a list of at least one issue or pull request.
    * Comma delineated?
7. Take in a list of contributor Github usernames/first & last names.
    * Optional?
    * Comma delineated?
    * Create link if not a first and last name?
8. Add to mono repo's /scripts folder and provide instructions on how to access

## Context & Motivation

Have a script across the project to use for updating would remove any formatting questions and make this task much easier/faster.

**Comment by aslakhellesoy** [comment]
Sounds good to me!

**Comment by mlvandijk** [comment]
Love this idea! (If I knew how, I'd implement it right away)
Ad 7: username would at least be available (full names might not?), a link to user would be nice
cucumber-jvm uses comma's between users (if multiple users)

**Comment by jaysonesmith** [comment]
In checking at least one existing log, there have been notes like, 'credit @{username}' or just a first and last name given. (Check out the earlier section of the [Aruba CHANGELOG](https://github.com/cucumber/aruba/blob/master/CHANGELOG.md)

However, in looking at the Ruby update script, we could possibly just grab the PR data [as done here](https://github.com/cucumber/cucumber-ruby/blob/master/scripts/update-history#L12-L15), but in the bash equivalent.

**Comment by mattwynne** [comment]
+1 for link to user @mlvandijk, and crediting multiple users would also be nice.

**Comment by jaysonesmith** [comment]
@mattwynne If I utilized the data collection similar to what you've got in the Ruby script, I'll definitely include a link to the user. What's a recommended way for handling multiple? Also, what's your input on @brasmusson's comments on #251? Seems like there are a few different ways to cross this bridge.

**Comment by aslakhellesoy** [comment]
My suggestions:

* Don't make use of github token mandatory, but allow users to specify it in case they get throttled. Here is how:
https://github.com/cucumber/github-issue-stats/blob/ffd85e93651a7604aea4d55db473ad314966994c/scripts/functions.sh#L21
Explained here: https://github.com/cucumber/github-issue-stats/blob/master/README.md
* It's ok if the script doesn't *modify* the `CHANGELOG.md` - I'm quite happy to run `chlog --message "Fixed a bad bug" --issue 224,432 --attribution aslakhellesoy,jaysonesmith | pbcopy` to get a nice string on my clipboard that I can paste. That way you can ignore 3) 4) and 5) for now.
* If `--message` is omitted, get the description from the first issue's title (error if --issue not specified)
* If `--issue` not specified, that's ok. Some fixes don't have issues (trunk based development)
* If `--attribution` is omitted, assume it's you (get it with `git config user.username` - and if that's not set - suggest setting it with `git config --global user.username yourgithubuser`)

**Comment by mattwynne** [comment]
@aslakhellesoy personally I really like the flow of having the changelog file updated automatically for me, based on tags. I guess we could have two scripts - one that generated the line, and another one that calls that first script then puts it in the correct place in the changelog.

**Comment by jaysonesmith** [comment]
Added slow burner so that this will stay open. :)

**Comment by aslakhellesoy** [comment]
This is now in `scripts/update_changelog.sh` - currently described in `CONTRIBUTING_NEW.md`
