### ISSUE TITLE
gherkin-dotnet: Support for .NET Standard 2.0

### ISSUE THREAD

**Issue by rafaelromao** [cucumber/cucumber#259]
## Summary

.NET Standard 2.0 is not supported.

Trying to use the Gherkin parser under .NET Core 2.0 and .NET Standard 2.0 will cause a fallback to .NET 4.x and the parser will try and fail to load System.Web.Extensions.

## Expected Behavior

Parse feature files successfully using .NET Core 2.0 and .NET Standard 2.0.

## Current Behavior

Considering a web project targeting <code>netcoreapp2.0</code> that consumes a library targeting <code>netstandard2.0</code> and this library tries to use the Gherkin parser.

The parser try to load System.Web.Extensions on <code>Gherkin.GherkinDialectProvider.ParseJsonContent()</code> and fail with a <code>System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Extensions'</code> exception.

## Possible Solution

Update the project to support .NET Standard 2.0.

## Your Environment

Windows 10, Visual Studio Code, dotnet core SDK 2.0.0, dotnet core 2.0.0.

**Comment by aslakhellesoy** [comment]
This is mostly done in #174 I think

**Comment by rafaelromao** [comment]
Looks like it will be fixed after this PR, but something went wrong in the build, although it passed. The version number was not upgraded and the nuget package was not published. https://ci.appveyor.com/project/aslakhellesoy/gherkin

**Comment by SabotageAndi** [comment]
No idea why AppVeyor does not find the nuget package and uploads it.

**Comment by SabotageAndi** [comment]
Ok, after some small changes in https://github.com/cucumber/gherkin-dotnet/pull/10, the build finds the nuget package and creates a correct looking version number for it.

**Comment by aslakhellesoy** [comment]
I believe this is fixed now. Let me know if I got it wrong.
