### ISSUE TITLE
Cannot save changes to profiles in cucumber.yml

### ISSUE THREAD

**Issue by NahidSiddiqui** [cucumber/cucumber#262]
Cannot save changes to profiles in cucumber.yml

## Summary
I have saved my cucumber.yml file in config directory which lies in the project directory of my calabash tests. I was previously able to save changes and run the profiles, but this is no longer possible. I cannot create new profiles in cucumber.yml and execute them in command line.

My cucumber.yml looks as below:

simulator: --tags ~@device
device:  --tags ~@emulator

stability: --tags @stability
functional: --tags @functional
ui:  --tags @ui_validation
critical_tests: --tags @criticals
all_tests: --tags @functional,@stability,@ui_validation
local_tests: --tags @emulator,
local_report_format: <%= format_standard_report_local %>

ios_cloud_configuration:      -p ios     -p device <%= feature %>  <%= format_standard_report_cloud %>  --tags ~@cloud_android
android_cloud_configuration:  -p android -p device <%= feature %>  <%= format_standard_report_cloud %>  --tags ~@cloud_ios

When I create a new profile as below, its not picked up during execution and says that profile is not defined.

full_ios_test: --@tags regression

## Expected Behavior

Profile created should be picked up from cucumber.yml

## Current Behavior

New profile created is not picked up from cucumber.yml

## Steps to Reproduce (for bugs)

1. Open cucumber.yml in text editor
2. Add new profile in the file
3. Execute profile in cucumber

## Context & Motivation

I am trying to create a new profile to run specific tests in command line

##Additional information

It seems that the cucumber.yml file is picked up from elsewhere, since when I delete the file from the config folder a new one reappears during execution from no where.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-ruby#1188
