### ISSUE TITLE
Broken link in  ReadMe file

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#266]
_From @Pwera on September 9, 2017 16:50_

Broken link in  ReadMe file
[broken link](http://docs.cucumber.io/gherkin/)

_Copied from original issue: cucumber/gherkin-c#1_

**Comment by justrad** [comment]
Another one for [tastedata/good](https://github.com/cucumber-attic/gherkin/tree/master/testdata/good) in https://github.com/cucumber/cucumber/tree/master/gherkin#pickles
