### ISSUE TITLE
[Spring] Exception is thrown complaining about multiple matching beans with version 1.2.5

### ISSUE THREAD

**Issue by EugeneS30** [cucumber/cucumber#268]
In the process of transitioning from version Cucumber 1.1.8 to 1.2.5 I have ran into an issue where the below exception is thrown:

`CucumberException No qualifying bean of type x is defined: expected single matching bean but found 2`

I tried to dig a bit deeper and I see that the `<T> T getInstance(final Class<T> type)` method in `SpringFactory` class had changed and apparently is somehow responsible for that behavior.

I was able to replicate this behavior in a simple project which I uploaded to github and the link is below.

Cucumber Version: 1.2.5
Operating System and version: Windows 7
Link to your project: https://github.com/EugeneS30/cucumber-bean-defect-verification.git

**Comment by mpkorstanje** [comment]
Hey thanks for reporting the issue. The reproducer looks good. But you've reported it against the wrong repository. Could you report it at [cucumber-jvm](https://github.com/cucumber/cucumber-jvm)?

**Comment by EugeneS30** [comment]
@mpkorstanje Hi, sure can. 

Should I delete this one and reopen it there instead or there is a way I can just "move" it?

Thanks,
Eugene

**Comment by mpkorstanje** [comment]
Unfortunately not. If you hit edit here first you can just copy paste the raw ticket.

**Comment by EugeneS30** [comment]
@mpkorstanje Done!

The issue id is: #1225
