### ISSUE TITLE
gherkin: ability to set default language for parser

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#271]
## Summary

Would like to override the default language used by the gherkin parser. Don't know if this is possible at the moment or not. Would like this added to `generateEvents` if its possible.

See cucumber/cucumber-js#929 for original request

**Comment by brasmusson** [comment]
Well the [TokenMatcher](https://github.com/cucumber/cucumber/blob/master/gherkin/javascript/lib/gherkin/token_matcher.js#L5) can be passed the name of the default language to use (if the feature file does not explicitly specify the language), so it is possible to control the default language to use.

**Comment by charlierudolph** [comment]
Thanks! Okay I believe I can implement this then

**Comment by aslakhellesoy** [comment]
Nothing needs to be done in Gherkin, so I'm closing this.
