### ISSUE TITLE
Gherkin: cannot build language update on Ubuntu 16.04

### ISSUE THREAD

**Issue by RomkeVdMeulen** [cucumber/cucumber#272]
I'm trying to build Gherking master on Ubuntu 16.04 after making an update to `gherkin-languages.json`. I followed the [instructions](https://github.com/cucumber/cucumber/blob/master/gherkin/CONTRIBUTING.md#adding-or-updating-an-i18n-language), making sure the prerequisite tools are installed. The instructions seem to be out of date however, since one of the commands launched during `make` uses mono. I installed mono, but the command still fails. Here is what I'm seeing on my console:

```
$ make
cd python && make default
make[1]: Entering directory '/home/romke/workspace/cucumber/gherkin/python'
mono berp/berp.exe -g gherkin.berp -t gherkin-python.razor -o gherkin/parser.py
Can't find custom attr constructor image: /home/romke/workspace/cucumber/gherkin/python/berp/CommandLine.dll mtoken: 0x0a000014
Unhandled loader error: 8, (null) System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (null)
* Assertion: should not be reached at loader.c:298
```

**Comment by RomkeVdMeulen** [comment]
I managed to complete the build by installing `mono-complete`, `pip`, `python-nose` and `golang`, and by installing .NET core 1.0.1 using [these instruction](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md). However, there may be additional dependencies I'm not aware of already present on my system.

However, a lot of files were removed with `make clean` that weren't replaced once `make` completed. Here's my git status:

```
        deleted:    ../c/include/rule_type.h
        deleted:    ../c/src/dialect.c
        deleted:    ../c/src/parser.c
        modified:   ../gherkin-languages.json
        deleted:    ../java/src/main/java/gherkin/Parser.java
        deleted:    ../javascript/dist/gherkin.js
        deleted:    ../javascript/dist/gherkin.min.js
        deleted:    ../javascript/lib/gherkin/parser.js
        deleted:    ../objective-c/Gherkin/GHParser.h
        deleted:    ../objective-c/Gherkin/GHParser.m
        deleted:    ../perl/lib/Gherkin/Generated/Languages.pm
        deleted:    ../perl/lib/Gherkin/Generated/Parser.pm
        deleted:    ../ruby/lib/gherkin/parser.rb
```

**Comment by RomkeVdMeulen** [comment]
Removed `objective-c/Makefile`, installed `cpanminus`, finally got through the build, no changed files except for my edit to `gherkin-languages.json`. So what was the point?

**Comment by brasmusson** [comment]
Yes, the instructions in CONTRIBUTING.md seem to be a bit out of date. However, the intention is for the `gherkin-languages.json` to be copied to the language directories, and at least in the case of Go, as go source file updated, so there is a point in doing something after the `gherkin-languages.json` has been updated.

**Comment by RomkeVdMeulen** [comment]
Hmm, in that case something went wrong: no file was copied during the build as far as I could tell.
