### ISSUE TITLE
cucumber-expressions : failing on using non-capturing regex

### ISSUE THREAD

**Issue by sameer49** [cucumber/cucumber#278]
following is my step defintion

```ruby
Then(/^I should\s*((?:not)?)\s+ see page title as "(.*?)"$/) do |present, title|
  
end
```
which should match following steps
```cucumber
Then I should see page title as "foo"
Then I should not see page title as "foo"
```

but it failing with follow exception

Expression /^I should\s*((?:not)?)\s+see page title as "(.*?)"$/ has 2 capture groups (["not", "Test Page for selenium–cucumber"]), but there were 1 parameter types ([".*?"]) (Cucumber::CucumberExpressions::CucumberExpressionError)

following is configuration 

Ruby version : 
- ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

Cucumber gems:
- cucumber (3.0.1)
- cucumber-core (3.0.0)
- cucumber-expressions (4.0.3)
- cucumber-tag_expressions (1.0.1)
- cucumber-wire (0.0.1)

**Comment by aslakhellesoy** [comment]
Is this still an issue with cucumber-expressions 4.0.4?

**Comment by sameer49** [comment]
thanks, it worked well with cucumber-expressions 4.0.4
