### ISSUE TITLE
step transformations

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber#28]
Hello, right now I see that cucumber does:
1. step regular expression matching
2. step transformation

I am trying to understand why that has been chosen. To me it makes more sense to do it the other  way around. i.e. first transform and then match the steps.

In our test suite we decided to make `<%= ... %>` expressions expand to some ruby expression inside. Issue is that if step for example matches `\w+` then using such expression in place doesn't work. It is not such a big deal as quotes can be used for parameters. Just a little harder to write the quotes.

But I thought to propose making transformation happen before matching unless there are good reasons to keep current approach.

Thank you.

**Comment by brasmusson** [comment]
Are you referring to Cucumber-Ruby (that is the Ruby version of Cucumber)? Then this is the wrong issue tracker. The right one is [here](https://github.com/cucumber/cucumber-ruby/issues).

**Comment by akostadinov** [comment]
@brasmusson , my bad. Thank you!
https://github.com/cucumber/cucumber-ruby/issues/986
