### ISSUE TITLE
gherkin/ruby malware in berp.exe?

### ISSUE THREAD

**Issue by kernow** [cucumber/cucumber#289]
## Summary

I'm running bit defender on my mac and it's just warned me that the berp.exe file included in the gherkin ruby gem (version 4.1.3) is infected with the malware Gen:Variant.Johnnie.69810

This could be a false positive but I wanted to flag it up incase the file has been infected with malware somehow.

**Comment by aslakhellesoy** [comment]
Thanks for reporting that. It's only used as part of the build and shouldn't even be included!

We'll check if it's infected, and in any case, delete it from the gem (and other language pacakes)

@gasparnagy are you able to investigate the exe?

**Comment by makmu** [comment]
We have the same problem with the npm gherkin module (we tested versions 4.1.3 and 5.0.0). G DATA reports Gen:Variant.Johnnie.69810 in https://registry.npmjs.org/gherkin/-/gherkin-5.0.0.tgz

**Comment by makmu** [comment]
Seems to be a false positive. 
GDATA updated their patterns today and now there are no warning. Services like https://www.virustotal.com now also don't show any warnings. (yesterday 7 out of 59 antivirus apps showed malware warnings, today it's 0)

**Comment by aslakhellesoy** [comment]
😅  thanks @makmu!

I'll leave this open though - we shouldn't be including it in the gem.

**Comment by kernow** [comment]
Glad it's a false positive :)

**Comment by aslakhellesoy** [comment]
Removed from the ruby gem (in the upcoming release). Leaving this open until it's removed from other implementations.

**Comment by djdarkbeat** [comment]
Found this today as well with bitdefender.

**Comment by aslakhellesoy** [comment]
Still need to remove form other impls
