### ISSUE TITLE
gherkin: Leading and trailing "\n" are trimmed in DataTable cells

### ISSUE THREAD

**Issue by ncsibra** [cucumber/cucumber#290]
After upgrading from cucumber-jvm 1.2.4 to 2.0.1, some of our tests failed.  
We have steps like this:
```
And the text should be
|something\n|
```
The important thing here is the "**\n**" at the end.  
With the older version, the "\n" was retained, but the new one trims it.  
I tracked down the issue and I think it's caused by an old change here: https://github.com/cucumber/gherkin-java/blob/v4.1.3/src/main/java/gherkin/GherkinLine.java#L67  
It's parsing the line from the feature file and this part of the code handle the new line character perfectly: https://github.com/cucumber/gherkin-java/blob/v4.1.3/src/main/java/gherkin/GherkinLine.java#L90  
But at the end of the line(at the "|" char) it trims the string: https://github.com/cucumber/gherkin-java/blob/v4.1.3/src/main/java/gherkin/GherkinLine.java#L86  
It doesn't make too much sense to me, because the original string as the variable name suggests(*trimmedLineText*) is already trimmed, so I think everything inside the "|" characters should remain the same, with all of the white space.

**Comment by aslakhellesoy** [comment]
I thought we had always been trimming leading and trailing whitespace - I must be wrong.

Maybe related: https://github.com/cucumber-attic/gherkin/pull/114

**Comment by ncsibra** [comment]
Before this commit, it does not trimmed the whitespaces, if I understand correctly:
https://github.com/cucumber/gherkin-java/commit/9b314c36f7dff7c58f6cc58faa822aa4941c64a2  

If you can give me a solution how to keep the new line at the end, that's fine with me. I already tried `\\s` and `\\\s`, but none of them worked.  
The hackish solution is to add it in the java step definition, before comparing the actual and the expected result, but the intention won't be as clear as with the "\n" in the feature file.

**Comment by brasmusson** [comment]
@ncsibra Cucumber-JVM v1.2.4 uses Gherkin v2.12.2, that is https://github.com/cucumber-attic/gherkin2 and not https://github.com/cucumber/gherkin-java, so tracking down this issue to somewhere in https://github.com/cucumber/gherkin-java is not really possible.

**Comment by ncsibra** [comment]
You are right, I missed that, sorry, but tracking down the issue was for the current version, which is using https://github.com/cucumber/gherkin-java.  
So my question is still stands, how can I solve that? Is it a feature or a bug? Is there a way to use special characters in data table in the feature file?

**Comment by brasmusson** [comment]
> I thought we had always been trimming leading and trailing whitespace - I must be wrong.

No, we have always been trimming leading and trailing whitespace in table cells. The caveat here is that the leading and trailing `"\n"` is not whitespace until they are converted to a `newline`. Conceptually Gherkin v2 did trim the whitespace before converting `"\n"` to `newline` which means the the leading and trailing `newline`s are retained. Newer Gherkin versions trim the whitespace after converting `"\n"` to `newline`, so also the leading and trailing `newline`s (which started out as `"\n"`) are trimmed.

**Comment by ncsibra** [comment]
Interesting, so this the expected behavior?

**Comment by brasmusson** [comment]
I think it is a regression that should be fixed.

**Comment by ncsibra** [comment]
Thanks for your help!
