### ISSUE TITLE
[ruby]ParallelTests::Cucumber::FailuresLogger (ArgumentError)

### ISSUE THREAD

**Issue by lefty1975** [cucumber/cucumber#294]
Unable to execute tests in parallelization using Cucumber v.3.0.1 with Parallel_Tests v.2.17.0 because of an Argument Error when using `--format ParallelTests::Cucumber::FailuresLogger` in one of my Cucumber profiles.

Expected: Understanding what I need to refactor in order to run tests successfully using `--format ParallelTests::Cucumber::FailuresLogger` with the gem version mentioned.

I have recently upgraded my these Ruby gems and now I am unable to run my Feature files in parallelization because of the aforementioned argument error. I could probably downgrade both gem versions, but that is not an ideal solution.

Here is the profile I'm trying to execute that utilizes `--format ParallelTests::Cucumber::FailuresLogger`

```
<%
  @time = Time.now.strftime("%Y-%m-%d__%H%M_%Ss")
  Dir.mkdir('./features/reports/') unless File.exists?('./features/reports/')
  @report_path = "./features/reports/#{@time}/"
  @screenshot_path = "./features/reports/#{@time}/"
  @new_dir_setup = -> { Dir.mkdir(@report_path) unless File.exists?(@report_path) }
  ENV['SERVER_URL'] = ENV['SERVER_URL']
%>
```
```
common: RESET_BETWEEN_SCENARIOS=1 SERVER_URL=<%= ENV['SERVER_URL']%> -f progress -r features
parallel: <%@new_dir_setup.call%> --format html --out=<%= @report_path%>web_test_report<%= ENV['TEST_ENV_NUMBER']%>.html SCREENSHOT_PATH=<%= @screenshot_path%> --format ParallelTests::Cucumber::FailuresLogger --out cucumber_failures.log
```

Stacktrace:
```
bin/cucumber:21:in `load'
bin/cucumber:21:in `<main>'
wrong number of arguments (given 3, expected 1)
Error creating formatter: ParallelTests::Cucumber::FailuresLogger (ArgumentError)
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/formatter/rerun.rb:9:in `initialize'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/parallel_tests-2.17.0/lib/parallel_tests/cucumber/failures_logger.rb:10:in `initialize'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:214:in `new'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:214:in `create_formatter'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:197:in `block in formatters'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/configuration.rb:196:in `block in formatter_factories'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/configuration.rb:193:in `map'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/configuration.rb:193:in `formatter_factories'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:196:in `formatters'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:181:in `report'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:71:in `run!'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
```

**Comment by lefty1975** [comment]
How do we get any feedback/prioritization on this issue to determine if it's because of Cucumber the Parallel_tests gem (https://github.com/grosser/parallel_tests/issues/586) because it would be nice to use this FailuresLogger Class and the methods within the class in order to easily rerun failed tests? In its current state, I have to remove this Formatter from my Cucumber yml profiles to successfully use the parallel_tests gem without Cucumber complaining about too many arguments.

**Comment by lefty1975** [comment]
Is there any additional information I can provide in order for someone to maybe take a look at this issue?

**Comment by brasmusson** [comment]
The constructor (method `initialize`) signature for the [rerun](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/rerun.rb#L9) and generally all formatter has changed (the `pretty` and `html` formatter being the exception and have not yet changed the signature). So the Parallel_tests gem need to adapt to the new signature to work with Cucumber-Ruby v3.x.x. From the stacktrace one can see that the call on `parallel_tests/cucumber/failures_logger.rb:10` needs to be changed. I'm afraid depending on internal bits of Cucumber-Ruby like the constructor signature for formatters is going to be brittle.
