### ISSUE TITLE
gherkin-js: Reverse GherkinDocument back to Feature

### ISSUE THREAD

**Issue by mlapeyre3** [cucumber/cucumber#299]
## Summary

Hi there, I am using the gherkin library to parse a .feature file into a GherkinDocument.
```
const Gherkin = require('gherkin');
const parser = new Gherkin.Parser();
var gherkinDocument = parser.parse(feature);
```

I was wondering if there is a way to go back from a GherkinDocument object to a .feature string?

## Expected Behavior

Something like:
```
var feature = parser.getFeature(GherkinDocument);
```

## Current Behavior

~~~
~~~

I did not find any methods like this in the code.

## Context & Motivation

It would be super nice to handle a `getFeature()` method. It's easier to handle the json-formatted GherkinDocument than a pure string like a .feature file.

Thanks !

**Comment by aslakhellesoy** [comment]
I'd like to know in what this context this would be useful, and how this would be better than just reading the source from disk.

**Comment by mlapeyre3** [comment]
Hi @aslakhellesoy ! Ok let me explain a bit more.

I am using
```
const Gherkin = require('gherkin');
const parser = new Gherkin.Parser();
var gherkinDocument = parser.parse(feature);
```
to parse a .feature file on server side and respond to my client application with a json-formatted GherkinDocument.

The client application can easily handle the Feature as a json object and manipulate the properties of the document (for display, editing, ...).

Now, let's say my application has an interface to add/remove tags of a given Scenario, and a button to export a .feature file back from the GherkinDocument.

It's easy to add the tag in the `tags: []` property of the Scenario. However, I want to be able to format the GherkinDocument back to a .feature string so that the user is able to download a new .feature file.

I found [https://www.npmjs.com/package/gherkin-assembler](https://www.npmjs.com/package/gherkin-assembler) to fulfill my need but I have not tested it yet.

**Comment by aslakhellesoy** [comment]
@mlapeyre3 is there anything missing from gherkin-assembler? If not I think we can close this issue.

**Comment by mlapeyre3** [comment]
HI @aslakhellesoy, sorry I did not follow-up my latest post.
https://www.npmjs.com/package/gherkin-assembler did the job so you can close this issue :)
