### ISSUE TITLE
Gherkin Wiki issue: "matched to a Ruby code block called Step Definitions"

### ISSUE THREAD

**Issue by dandv** [cucumber/cucumber#3]
I'm new to Cucumber, so pardon me if this is a stupid question.

At https://github.com/cucumber/cucumber/wiki/Gherkin#gherkin-syntax, I see

> When you run the feature the trailing portion (after the keyword) of each step is matched to a **Ruby** code block called [Step Definitions](https://github.com/cucumber/cucumber/wiki/Step-Definitions).

I'm trying to understand this better. This is my first exposure to Gherkin, from the link at https://github.com/cucumber/cucumber-js#features.

1. Must the code block be Ruby? I arrived here from the JS port.
2. Where is that code located?
3. Should "Step Definitions" be "Step Definition" in that quote?

**Comment by mattwynne** [comment]
Hi Dan,

Sorry this is all so confusing, and thanks indeed for feeding back to us. Try this link instead: https://cucumber.io/docs/reference#step-definitions

We've been gradually trying to migrate the chaotic wiki docs over to the website, but at the moment things are between two places.

**Comment by mattwynne** [comment]
Also, there are no stupid questions!
