### ISSUE TITLE
Obtaining gherkin from AfterScenario or AfterStep

### ISSUE THREAD

**Issue by cartoloupe** [cucumber/cucumber#30]
In Cucumber 1, I was able to obtain the gherkin of a scenario in the After block with something like this:
```
After do |scenario|
  scenario.steps.map(&:to_sexp).map{|a| a[-2..-1].join}
  ...
end
```

this was used to make annotated gifs of each test, step by step.

In Cucumber 2, I'm not observing that you can get the steps from a scenario. I ran across a mailing list thread addressing [a related issue about getting the result from a scenario](https://groups.google.com/forum/#!topic/cukes/uarJwNpJdqk).

Could either the scenario in the After block, or the step in the AfterStep block, be updated to provide the gherkin in Cucumber 2?

**Comment by Cohen-Carlisle** [comment]
This is possible with the following syntax in 2.4
```ruby
AfterStep do |scenario, stp| # stp to avoid collision with pry's #step
  stp.source.last.keyword # => "When "
  stp.name # => "something happens" (or stp.source.last.name)
end

**Comment by cartoloupe** [comment]
Thanks @Cohen-Carlisle! I shall upgrade to 2.4.0.

**Comment by mattwynne** [comment]
For the record, an issue like this needs to go into https://github.com/cucumber/cucumber-ruby rather than this repo. Thanks for helping with the answer @Cohen-Carlisle!
