### ISSUE TITLE
Add keyword "Examples Cross"

### ISSUE THREAD

**Issue by danchukas** [cucumber/cucumber#301]
Good day.

I want add keyword "Examples Cross" for Gherkins.
I already realized it in php project.  And we used it on big project  successfully.
But for merge  functional Examples Cross from my fork to original repository community wait while Cucumber add this keyword to self.

Visually on screenshot  :
http://joxi.ru/Dr8yg8Ou4qnZRm

For exaple:

We write only:
Examples Cross
|a|b|c|d|
|1|1|1|1|
||2|2|2|
| |3|| |

instead of:

Examples:
|a|b|c|d|
|1|1|1|1|
|1|2|1|1|
|1|1|2|1|
|1|2|2|1|
|1|3|1|1|
|1|3|2|1|
|1|1|1|2|
|1|2|1|2|
|1|1|2|2|
|1|2|2|2|
|1|3|1|2|
|1|3|2|2|

more about there:
https://github.com/Behat/Behat/issues/1101

Can you add Examples Cross ?
___

Thanks you for this wonderful idea and soft very much.

**Comment by jenisys** [comment]
@aslakhellesoy @mattwynne 
If I understand the functionality correctly, ``Examples Cross`` is like combination generator for the Examples tables. 

This could be implemented without adding a new keyword in Gherkin by providing tags that act as table-generator / table-transformation on the Examples table. Note that the table-generation / table-transform is like a preprocessing step before the Scenarios are generated from the Scenario-Outline. Such a generic functionality may be useful in many situations, for example for property-based testing.

```gherkin
Scenario Outline:
  ...
  @table_generate.cross_combinations
  Examples:
    |a|b|c|d|
    |1|1|1|1|
    | |2|2|2|
    | |3| | |
```

Similar table-transforms / table-generations:
* ``@table_generate.allpairs``
* ``@table_generate.combinations``
* ``@table_generate.property_based_items=10`` (generates 10 items (as rows) per test-run)
* ...

A user just the needs the ability to register his/her table-generators / table-transforms rather early in the test-run (before the Scenario-Outline is expanded) and bind them to tags. A few common ones can be supported by Gherkin or the cucumber framework.
