### ISSUE TITLE
Dots representing the progress instead checked scenarios description

### ISSUE THREAD

**Issue by Odravison** [cucumber/cucumber#302]
Hey Folks,

Earlier I got this versions of protractor and framework:
```
    ...
    "cucumber": "3.0.2",
    "protractor-cucumber-framework": "4.0.7",
    "protractor-jasmine2-screenshot-reporter": "0.3.2",
    ...
```
now when I run `proctractor:cucumber` task, the output is dots and letters that represents result of each test instead checked scenario descriptions like before the update.

My question is: Is possible use some configuration or flag (in CLI) to use scenario descriptions instead dots?

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-js#988
