### ISSUE TITLE
tag-expression: Supports RPN notation, too

### ISSUE THREAD

**Issue by jenisys** [cucumber/cucumber#304]
## Summary

Tag-expressions seem to support also the RPN notation ( partially with unexpected outcomes) besides the normal documented boolean notation. The RPN notation support seems caused by Shunting-Yard algorithm and its stack-based processing nature. 

I stumbled over this issue while looking at the existing implementations (Java, Javascript, Ruby) and working on a Python implementation. All implementations should be affected. I verified it with the Java implementation and my Python implementation.

## Expected Behavior

Mmh, first it must be decided if the RPN notation parsing is acceptable behaviour.

## Current Behavior

The following tag-expression are valid, meaning: They can be parsed without error.
The following patched test code snippet passes without any problems (using the Java implementation).

```java
// -- FILE: TagExpressionParserTest.java
...
   // -- XXX-JE-PATCHED-AND-EXTENTED: Check RPN notation support
    @Test
    public void rpn_notation_case1() {
        Expression expr = parser.parse("@a @b or");
        String expected = "( @a or @b )";
        assertEquals(expected, expr.toString());
    }

    @Test
    public void rpn_notation_case2() {
        Expression expr = parser.parse("@a and (@b not)");
        String expected = "( @a and not ( @b ) )";
        assertEquals(expected, expr.toString());
    }

    @Test
    public void rpn_notation_case3_oops() {
        Expression expr = parser.parse("@a and (@b @c) or");
        String expected = "( @a or ( @b and @c ) )";    // OOPS
        assertEquals(expected, expr.toString());
    }
}
```

## Possible Solution

This is not easily solvable because it caused by the used algorithm.
A remedy could be to use a parser framework that allows to specify the grammar in more detail. 
NOTE: But first it must be decided if this is an issue or just a weird symptom.

## Steps to Reproduce (for bugs)

1. Patch the Java test file mentioned above 
2. Run the tests (with Maven)
3. Check other implementations, too (Javascript, Ruby)

## Context & Motivation

See above in summary.

## Your Environment

* Version used: Tag Expressions 1.0.2-SNAPSHOT (Repository HEAD)
* Operating System and version: macOS >= 10.11 (not relevant)
* Java: 1.8.x

**Comment by aslakhellesoy** [comment]
The parser is an implementation of [shunting yard](https://en.wikipedia.org/wiki/Shunting-yard_algorithm), an algorithm for parsing infix operations without the need for a parser generator.

I doubt the algorithm accidentally works for postfix, so this is probably a bug in the implementation, not the algorithm. I'll see if I can find it!

**Comment by aslakhellesoy** [comment]
Doing a little more research it seems SY supports postfix too! https://stackoverflow.com/questions/29634992/shunting-yard-validate-expression

So we need to add some validation to the input that’s all.

**Comment by aslakhellesoy** [comment]
Hi @jenisys this should now be fixed on master. Exciting that you're porting it to Python! We'd love to host it in this repo (with a read-only mirror on `cucumber/tag-expressions-python`). That way it's easier to keep all implementations in sync.
