### ISSUE TITLE
Cucumber Expressions: Runtime infinite hang when invalid match with ParameterType

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#307]
_From @luke-hill on November 22, 2017 14:34_

## Summary

When running the following minimal code section RubyMine / command line hangs, and needs killing

## Expected Behavior

Test runs and fails due to it not matching anything

## Current Behavior
Test hangs

## Steps to Reproduce (for bugs)

`test.feature` -Ignore the name, thats something for later should the parser work

``` 
Scenario Outline: Compressed step testing
    Given <query>

    Examples:
    | query                                |
    | I reach Stage4: 1st flight-1st hotl | #Note the typo here
```

`test_steps.rb`
```
Given('I reach Stage4: {optional-flight}-{optional-hotel}') do |flight, hotel|
  puts 'I add normally'
end
```

`support/test.rb`
```
ParameterType(
  name: 'optional-flight',
  regexp: /(1st flight)?/,
  type: String,
  transformer: ->(_) { _ },
)

ParameterType(
  name: 'optional-hotel',
  regexp: /(1st hotel)?/,
  type: String,
  transformer: ->(_) { _ },
)
```

## Context & Motivation

This cropped up when I was (wrongly), trying to convert the following Cucumber 2 step into cucumber 3
`When(/^I reach Stage(?:4|5): ?(#{ACCENTED_CHARACTERS} flight)?\/?(#{ACCENTED_CHARACTERS} hotel)?$/) do |flight, hotel|`

## Your Environment

Cucumber 3, Recent Bundle.
Win7
Ruby 2.3

_Copied from original issue: cucumber/cucumber-ruby#1237_

**Comment by aslakhellesoy** [comment]
In your example, the step doesn't match, because `1st hotl` doesn't match the `{optional-hotel}` parameter type.

The Cucumber Expression gets translated to the following RegExp: `^I reach Stage4: ((1st flight)?)-((1st hotel)?)$`

See http://rubular.com/r/i8KSagzisI

Because the step doesn't match, the step is marked as undefined.

Can you give some examples of Gherkin steps you'd like the stepdef to match? Both with and without flights and hotels?

**Comment by luke-hill** [comment]
Sorry, that's not the issue. The issue is the infinite hang.

As per expected behaviour. I'd expect it to crash and say something like, couldn't find the step

**Comment by aslakhellesoy** [comment]
Can you provide a small repo we can clone to reproduce the behaviour please?

**Comment by aslakhellesoy** [comment]
I want to figure out whether this is an issue with Cucumber Expressions or RubyMine (I suspect the latter)

**Comment by luke-hill** [comment]
Everything above should be enough. I tried running this on the command line and it also seemed to infinite-hang. Do you want me to zip all this up?

**Comment by aslakhellesoy** [comment]
That would be great - or create a git repo if it isn't too much hassle.

**Comment by luke-hill** [comment]
Minimal code folder. Confirmed to hang on command-line running `cucumber` inside `derp` folder.
[derp.zip](https://github.com/cucumber/cucumber/files/1509632/derp.zip)

**Comment by aslakhellesoy** [comment]
Great thanks! I've narrowed this down to a bug in the snippet generator code, probably in the cucumber-expressions library. Maybe an infinite loop. Working on a fix...

**Comment by aslakhellesoy** [comment]
The short term workaround until this is fixed is to set `use_for_snippets: false`
