### ISSUE TITLE
Error in cucumber feature 

### ISSUE THREAD

**Issue by siva90144** [cucumber/cucumber#310]
1.Feature: Hotel Reservation Search
2.#Author: User
3.
4.In order to book the hotel reservation  
5.As a user 
6.I want to launch hotel website and reserve a room

Multiple markers at this line
- Lexing error on line 4: 'In order to book the hotel reservation  
As a user 
I want to launch hotel website and reserve a room

Scenario Outline: Verify User able to apply for credit card by providing personal information

%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
- 17 changed lines

Can you please help me where its wrong?

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
