### ISSUE TITLE
Cucumber 2 - Formatter API 

### ISSUE THREAD

**Issue by stengvac** [cucumber/cucumber#312]
# Summary

Lang: Java
Cucumber: 2.1.0

Hello I am writing my own formatter for Cucumber 2.1.0 and I would like to ask if there is possibilily to provide more data and tools for creation of custom formatters. In Cucumber version 1.2.5 was present Reporter and Formatter interfaces, which provided nearly all information. But some of them were not present like fields from @CucumberOptions - dryRun, strict, features, glue, tags.

Why do i need my own formatter? I am sending colleted data after each tested feature to REST API +  we are collecting other data like used environment, execution datetime.. .

## Current behavior
Event driven Formatter in Cucumber 2.1.0 provide only portion of data and rest of them  is accessed via package protected class cucumber.runtime.formatter.TestSourcesModel in Cucumber formatters.

## Expected Behavior
Formatter API will provide more data or some utility class could be present.
Data from CucumberOptions should be accessible.

Thx for help/answers
 V

**Comment by mpkorstanje** [comment]
The contents of `TestSourcesModel` is entirely derived from the `TestSourceReadEvent`. So in the short term I would recommend copying the `TestSourcesModel`. 

Why it is not part of the current API at this moment:
> **[@brasmusson]( https://github.com/cucumber/cucumber-jvm/pull/1253#issuecomment-347988911) in https://github.com/cucumber/cucumber-jvm/pull/1253**
> Things that are exported as part of the API are in Martin Fowler's terms "Published Interfaces". One of Martin Fowler's guidelines for Published Interfaces is "Publish as little as you can as late as you can". "As late as you can" so that you have had the time to refine the interface to be published. TestSourcesModel is far from being as refined to be part of a "Published Interface". Secondly as mentioned in previous comment, the proper place for a support library for lookup of Gherkin AST data, is most likely a sub-repo of https://github.com/cucumber/cucumber so it can be used by all Cucumber implementations and not only Cucumber-JVM (maybe rather the event-protocol sub-repo rather than the gherkin sub-repo).

Hammering out something to do these linenumber to ast-node lookups would be a good start.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-jvm#1304
