### ISSUE TITLE
cucumber-expressions: non capturing group wildcard parameter type

### ISSUE THREAD

**Issue by mikehaas763** [cucumber/cucumber#317]
I'm using cucumber-js, not sure if this applies to all cucumbers.

Maybe I'm missing this in the docs (https://docs.cucumber.io/cucumber-expressions/#) and can already do this as is. I'd like to use the new CucumberExpression syntax to match any characters, but not be required to add a parameter to the function for the group.

I'm pretty sure I could do this with my own custom `ParameterType` but I think it would be valuable to others if it was baked in. Maybe something like `{*}`?

**Comment by aslakhellesoy** [comment]
Can you give some concrete examples of Gherkin steps that would benefit from this, with associated cucumber expressions?

**Comment by mikehaas763** [comment]
Our POs like to use natural language like `Given a *product* user` ... where *product* is not a finite set. Could be 1-3 words. If relevant, our gherkin is sometimes influenced by the fact that we're at the start of our BDD journey. We're currently bound to many mainframes and many layers of APIs that we can't control, and so we don't have any way to programmatically stage data. We have to manually stage user data in a persistent store ahead of time. I'm all ears if you think we should be doing something different, I just think a wildcard could be useful for companies like mine that are at the beginning of their journey.

**Comment by aslakhellesoy** [comment]
You could use the built-in `{string}` parameter type in your step definition's cucumber expression:

```javascript
Given('a {string} user', function (productName) {
})
```

Here are some example of matching Gherkin steps:

```gherkin
Given a "windsurfing koala" user
Given a 'high net worth individual' user
```

Those single or double quotes may seem a little annoying, but it does help you understand where the product name begins and ends.

Would this work for you? If not, you have to define your own parameter type.

**Comment by aslakhellesoy** [comment]
@mikehaas763 ping :-)

**Comment by mikehaas763** [comment]
haha sorry I guess I missed the notification for your response. That would work for matching the step in the gherkin, but I don't need the actual value that's in the quotes passed into the function. So I'm forced to add parameters that aren't used, but we have compiler settings that prevent unused parameters... I guess I'm not sure if it's cucumber-js or cucumber-tsflow that enforces that there's a function parameter for every parameter in the gherkin.

**Comment by aslakhellesoy** [comment]
If you don't care about the value, why do you have steps with many different values? It would be easier to discuss this if you could share several *actual* concrete examples of what you're trying to do.

**Comment by aslakhellesoy** [comment]
@mikehaas763 ping again

**Comment by aslakhellesoy** [comment]
Closed du to inactivity. @mikehaas763 feel free to reopen if you can provide the information I asked for.
