### ISSUE TITLE
Questions about the Scenario Outlines

### ISSUE THREAD

**Issue by jianzhangbjz** [cucumber/cucumber#318]
Hey, Guys

I walked through the [Scenario Outlines Wiki](https://github.com/cucumber/cucumber/wiki/Scenario-Outlines), but I have some questions about it:

1, For example, as the below shows, the data table values whether support the variables?
```cucumber
Scenario Outline: eating
  Given there are <start> cucumbers
  When I eat <eat> cucumbers
  Then I should have <left> cucumbers

  Examples:
    | start               | eat | left |
    |  <%= cb.prefix %>   |  5  |  7   |
    |  <%= cb.prefix %>   |  5  |  15  |
```

2, The below format whether right? Or I must create a new variable to replace the last `<left>`? In other words, how to re-use these variables, `<start>`, `<eat>`, `<left>`?

```cucumber
Scenario Outline: eating
  Given there are <start> cucumbers
  When I eat <eat> cucumbers
  Then I should have <left> cucumbers
  And there are <left> cucumbers left

  Examples:
    | start | eat | left | left |
    |  12   |  5  |  7   |  7   |
    |  20   |  5  |  15  |   7  |
```

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

Please don't address this community as "guys". I know it is considered gender-neutral by some people, but many people feel it's excluding people who are not male.

**Comment by jianzhangbjz** [comment]
@aslakhellesoy Sorry for the bothering, thanks for your suggestion! :)
