### ISSUE TITLE
Enhancement Request - Add Before and After Hooks at Test and Feature level in addition to scenario hooks

### ISSUE THREAD

**Issue by 599139** [cucumber/cucumber#328]
This is an Enhancement Request -
I've been using Specflow for sometime and before that have used Cucumber for 6 months with Java. One big difference I found in terms of ease of usage is the plethora of Hooks provided by Specflow at various levels :
1. Before/After Test : Hook to execute code block once per test run
2. Before/After Feature : Hook to execute code block once per feature file.
3. Before/After Scenario : This one is covered by cucumber

These helps a lot to configure various initialization methods and consolidate setup logic based on different patterns of usage.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-jvm#1321
