### ISSUE TITLE
TagExpressionParser question

### ISSUE THREAD

**Issue by cliviu** [cucumber/cucumber#338]
As far as I can tell from my tests, the TagExpressionParser does not work for the old style tags
(https://github.com/cucumber/cucumber/tree/master/tag-expressions). Do you have any hint for parsing/evaluating the old style tags ?
Thanks !

**Comment by xtrasimplicity** [comment]
Ideally, I think it would be best to either upgrade your code to use the new expression format, or downgrade your cucumber version to a version compatible with the old form of tag negation.

Alternatively, as a quick fix you could monkey patch   `Cucumber::TagExpressions::Parser.push_expressions` to handle the old form of tag negation?

https://github.com/cucumber/cucumber/blob/master/tag-expressions/ruby/lib/cucumber/tag_expressions/parser.rb

**Comment by aslakhellesoy** [comment]
Here is a migration guide: https://github.com/cucumber/cucumber/tree/master/tag-expressions#migrating-from-old-style-tags

**Comment by cliviu** [comment]
Ok, thanks!

**Comment by amoleb6** [comment]
Hi ,  i am trying to run using and keyword but somehow scenario is not getting exeucted..

tagExpression: '@a and @b'

it doesnt execute any of the scenario simply open and close the browser..  Am i missing anything??

**Comment by mlvandijk** [comment]
@amoleb6 Depending on your Cucumber version, you might need to use the old syntax. See the migration guide linked by Aslak above.
