### ISSUE TITLE
CI process

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#340]
Thoughts on switching to CircleCI instead of TravisCI? You can create separate jobs that run on each build and each can use their own docker image. I think that would nicer as it also segments as you can have a separate job for each project/language combination.

**Comment by aslakhellesoy** [comment]
Let's give it a try! We recently moved [cucumber-ruby](https://circleci.com/gh/cucumber/cucumber-ruby) over and that's worked very well.

Do you have the credentials you need to put it under the cucumber org on CircleCI?

**Comment by xtrasimplicity** [comment]
Is this still in the pipeline?

**Comment by aslakhellesoy** [comment]
Yes it will: https://github.com/cucumber/cucumber/blob/e2d9a9c2c95d532fe1c242edcfc9700c611b5827/.github/stale.yml#L6-L7

**Comment by jaysonesmith** [comment]
Ah awesome. Thanks!

**Comment by aslakhellesoy** [comment]
We're on CircleCI now

**Comment by charlierudolph** [comment]
Great to hear. It looks so good:

![Screen Shot 2019-08-17 at 1 50 11 PM](https://user-images.githubusercontent.com/1676758/63217169-2a8ecc00-c0f6-11e9-99bf-7c9da1dd17b6.png)
