### ISSUE TITLE
CI hidden error in build

### ISSUE THREAD

**Issue by jenisys** [cucumber/cucumber#343]
There seems a hidden error in the CI server build job.

## Summary

The following error occurs in build for pull-requests (and seems to hidden).

```shell
...
[1BDigest: sha256:3c2b0ab0c77ae10ff8fb77c58a803f601c255c8045c18094137bba4af98c730c
Status: Downloaded newer image for cucumber/cucumber-build:39e69ae56ad2861d86a8f26d3cec0285
source scripts/functions.sh && rsync_files
XXX-ERROR: /bin/sh: scripts/functions.sh: line 13: syntax error: bad substitution
XXX-ERROR: fatal: Invalid path '/**': No such file or directory
touch .rsynced
cd event-protocol && make default
make[1]: Entering directory '/app/event-protocol'
yarn install --network-concurrency 1
...
```
## Expected Behavior

The lines marked with prefix "XXX-ERROR: " should not fail.

## Possible Solution

The **root_dir** line in "scripts/function.sh" seems to be causing the problem.

```bash
# -- FILE: scripts/function.sh
...
# The root dir of the monorepo
root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
...
```

## Steps to Reproduce (for bugs)

See pull-request #342 (continuous-integration/travis-ci/pr)

**Comment by aslakhellesoy** [comment]
Still needs to be fixed
