### ISSUE TITLE
Distinguish between "no match" and "match with no groups"

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#358]
I could be wrong, but it seems to me that there is no distinction between "no match":

https://github.com/cucumber/cucumber/blob/662b3662422c5301f685999704d9dd38e6341757/cucumber-expressions/go/regular_expression_test.go#L45-L47

And when there is a match with no groups:

https://github.com/cucumber/cucumber/blob/662b3662422c5301f685999704d9dd38e6341757/cucumber-expressions/go/regular_expression_test.go#L61-L63

The other implementations return `null` for the former and `[]` for the latter. How will Cucumber know which case it is if we always get `[]`?

**Comment by charlierudolph** [comment]
For the first test we should check if nil, and the second could check not nil built is empty.

```golang
require.Nil(t, Match(t, "hello", "world"))
```

```golang
match := Match(t, `Across the line\(s\)`, "Across the line(s)")
require.NotNil(t, match)
require.Empty(t, match)
```

I'll try adding this today

**Comment by charlierudolph** [comment]
I think Empty passes with nil and empty arrays
