### ISSUE TITLE
Question with Russian language description of Gherkin

### ISSUE THREAD

**Issue by cerebellum13** [cucumber/cucumber#365]
Good day! Now in Cucumber gherkin uses Russian description(gherkin_language.json). There are three possible isues: Given, When, Than. In Russian language more preferable for 'Given' use  "Допустим ", "Дано " and "Пусть ", without "Если". And "Если" shift into 'When'. From the point of view of the Russian language, it is more readable and logically understandable.

**Comment by xtrasimplicity** [comment]
Hi @cerebellum13,

Thanks for letting us know about this. Just to confirm:
 * Dopustim = Given,
 * Dano = when, and
 * Pust' = then, 
 * and esli should be removed.

Is this correct?

Thanks!

**Comment by cerebellum13** [comment]
No, I suggest that you leave those words in Russian that are now. And the word "Если" is transferred to the group "When".

**Comment by aslakhellesoy** [comment]
@cerebellum13 can you send us a pull request with your suggestions please?

**Comment by cerebellum13** [comment]
Created a pull request.
