### ISSUE TITLE
What happened to the wiki?

### ISSUE THREAD

**Issue by maxnordlund** [cucumber/cucumber#368]
It looks like it was removed when the repo(s) where moved here. It contained a lot of useful information and it's sad to see it go.

Would it be possible to restore it somehow?

**Comment by aslakhellesoy** [comment]
@maxnordlund - the documentation has moved to https://docs.cucumber.io/

@mattwynne - did you consider https://github.com/cucumber/docs.cucumber.io/issues/144 before you turned off the wiki? It's been around for 8-9 years, and I lots and lots of other web oages are likely to link to it. Many people visit it regularly.

I think the best would be to turn the wiki back on, gradually replace wiki page contents with links to the new pages, and then turn it off completely after a while.

Can you restore it please?

**Comment by mattwynne** [comment]
Hi @maxnordlund. The team working on the new docs site have been painstakingly migrating content off of the wiki and various other sources, so I'd hope that any content you loved has made it over.

Is there anything specific you would like to see there that's missing?

**Comment by aslakhellesoy** [comment]
I've put the wiki back. Over the next few weeks, I will remve contents from every page, and point people to the new docs (to a specific page where relevant). Each wiki page will also have a note reminding people not to add or edit content in the wiki. The wiki is read-only (except for the core team).

After all the existing pages have been "emptied" we'll leave the wiki open for a year or so before we remove it completely.

**Comment by maxnordlund** [comment]
Thank you, this is awesome. Especially hearing the effort of the documentation team @mattwynne 

@aslakhellesoy I suggest leaving the main page with a link directing people to the right place. There's plenty of blog posts linking directly to the wiki, and it would be better if those links doesn't totally rot. 

https://github.com/cucumber/cucumber/blob/a437d54b0420d23265ba27dd39f7f2a01cbb4c10/gherkin/README.md#architecture has a link to https://github.com/cucumber/gherkin/wiki for example.

**Comment by mattwynne** [comment]
Thanks @aslakhellesoy for tidying up after me ❤️

**Comment by mlvandijk** [comment]
@maxnordlund Please let us know what you think of the new docs, what you're missing / could be improved etc. :) You can find the project here: https://github.com/cucumber/docs.cucumber.io
