### ISSUE TITLE
Error when using "acute accent" ´ in Scenario and Scenario Outline name

### ISSUE THREAD

**Issue by christianbaumann** [cucumber/cucumber#371]
## Summary

Error when using "[acute accent](https://unicodelookup.com/#%C2%B4/1)" ´ in Scenario and Scenario Outline name

## Expected Behavior

Scenario being executed

## Current Behavior

Error

```
C:\Ruby23-x64\bin\ruby.exe -EUTF-8 -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby23-x64\bin/cucumber "C:/Users/cbaumann/RubymineProjects/IBE testing/features/3 Passenger Checkout Page/[TIBE-75] B2B Checkout Passenger information collection.feature" --format Teamcity::Cucumber::Formatter --expand --name "^First passenger \(doesn\´t\) equal contact$" --color -r features
invalid multibyte character (ArgumentError)
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/options.rb:112:in `block (2 levels) in parse!'
C:/Ruby23-x64/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
C:/Ruby23-x64/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
C:/Ruby23-x64/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
C:/Ruby23-x64/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
C:/Ruby23-x64/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
C:/Ruby23-x64/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/options.rb:150:in `parse!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/configuration.rb:27:in `parse!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:66:in `block in configuration'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:65:in `tap'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:65:in `configuration'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:30:in `execute!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
C:/Ruby23-x64/bin/cucumber:22:in `load'
C:/Ruby23-x64/bin/cucumber:22:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

Process finished with exit code 2
```

## Steps to Reproduce (for bugs)

Create feature file with Scenario where the names contains an "acute accent", run the scenario.

## Your Environment

* Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
* Cucumber:
cucumber (3.1.0)
cucumber-core (3.1.0)
cucumber-expressions (5.0.17, 5.0.15)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
* Operating System and version: Windows 8.1 Enterprise

**Comment by aslakhellesoy** [comment]
Could you please format output and source code using [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so it's easier to read?

The error should go away if you remove the escape character (`\`) in front of the accent - no escaping is needed.

**Comment by aslakhellesoy** [comment]
You also seem to be mixing regular expressions and cucumber expressions. Regular expressions are delimited with `/` at the beginning and end, while cucumber expressions use `"` or `'` at the beginning and end.

**Comment by christianbaumann** [comment]
Got this from the comments under [364](https://github.com/cucumber/cucumber/issues/364).

But this issue has nothing to do with cucumber or regular expressions.

I have a feature file, containing the following line
```
Scenario Outline: First passenger (doesn't) equal contact
```
When trying to run it, I get the error posted above.

**Comment by aslakhellesoy** [comment]
What are you trying to do @christianbaumann? It looks as though you're trying to use the command line to specify a step definition to run. Cucumber doesn't work that way - you can only specify what scenarios to run.

Can you explain exactly what you're doing? Are you using RubyMine to run a specific scenario? How are you interacting with RubyMine to do that?

**Comment by aslakhellesoy** [comment]
It looks like Cucumber is given command line arguments with incorrect encoding. It's RubyMine supplying the arguments, so I think you have to report the bug with them.

A couple of things to try: 

* Can you run the scenario from the command line, outside RubyMine?
* Can you verify that your feature file is saved with UTF-8 encoding?

**Comment by aslakhellesoy** [comment]
Closed due to inactivity. Sounds like a RubyMine bug.
