### ISSUE TITLE
Testdata intepreted as Step-Definition

### ISSUE THREAD

**Issue by Corji** [cucumber/cucumber#373]
## Summary
We test an app with cucumber. Whe we test some text messages cucumber inteprets the message as method in our step definitions.

Example:

Given The value of the textfield is "the value is 3"

Then we have another method like:

Given The value is "3"

Now cucumber inteprets the first sentence and can't find the correct method because the string we like to test includes the syntax of another step definition.

Can we do something different to avoid this behaviour? The quotes aren't fixing the problem.
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mlvandijk** [comment]
@Corji Can you please provide information on which language, version, etc you are using? That might help us help you :)

**Comment by aslakhellesoy** [comment]
Can you share what regular expressions (or cucumber expressions) you're using in your step definitions @Corji?

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
