### ISSUE TITLE
`$` in example table not escaped correctly

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#374]
## Summary
Given the following gherkin:
```gherkin
Scenario Outline:
  Given <x>

  Examples: 
    | x  |
    | $$ |
```
The step becomes `Given $` instead of `Given $$`.

## Possible Solution

I believe the problem is in the pickle generation [here](https://github.com/cucumber/cucumber/blob/b584f84e6f750fdc3bd9e47476ebfdead798c0ba/gherkin/javascript/lib/gherkin/pickles/compiler.js#L119) as the `$` is a special character in [replacement strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter).

See https://github.com/cucumber/cucumber-js/issues/1077 for the original issue

**Comment by charlierudolph** [comment]
@aslakhellesoy when is a new version of gherkin going to be released? I want to get this fix into cucumber-js

**Comment by aslakhellesoy** [comment]
I'll try to get it done this week
