### ISSUE TITLE
Debugging documentation out-of-date

### ISSUE THREAD

**Issue by cameroncooke** [cucumber/cucumber#376]
## Summary

The debugging documentation on the Wiki is out of date. The `debugging.rb` code does not work with `2.4.0`.

https://github.com/cucumber/cucumber/wiki/Debugging

On running the tests one or more exceptions are thrown from the `debugging.rb` code.

## Expected Behavior

I would expect that the debugging logic not to throw it's own exceptions and perform it's intended function.

## Current Behavior

The following exception is observed in the terminal when running tests.

```bash
 uninitialized constant Rails (NameError)
 ./features/support/debugging.rb:47:in `rescue in failed'
 ./features/support/debugging.rb:41:in `failed'
```

## Steps to Reproduce (for bugs)

1. Add the `debugging.rb` file to your project following the instructions found here: https://github.com/cucumber/cucumber/wiki/Debugging
2. Run the tests using `DEBUG=1` environmental variable

## Context & Motivation

I would like to be able to debug my test code. My main motivation for debugging was to be able to get a breakpoint using `pry` when an exception is thrown in one of my tests.

## Your Environment

* Version used: 2.4.0
* Operating System and version: macOS 10.13.4

**Comment by mlvandijk** [comment]
Note that we have moved the documentation here: https://docs.cucumber.io/
You can find the source [here](https://github.com/cucumber/docs.cucumber.io), if anyone would like to add debugging information.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/docs.cucumber.io#197
