### ISSUE TITLE
how to run all test caes from a line number

### ISSUE THREAD

**Issue by cucushift** [cucumber/cucumber#381]
hi,folks 
    if i want to run all test cases from a line number like 99, how can i achieve it. thx.

now i know follow cmds format:
> cucumber ${file_path}
>cucumber ${file_path}:${num}
>cucumber ${file_path}:${num}:${num}:${num}

if i have lots of test cases , using the third cmd is very Uncomfortable.

**Comment by mlvandijk** [comment]
Hello @cucushift - for questions, please try one of the support channels. You can find them here: https://cucumber.io/support. GitHub issues are for bugs or feature requests.

**Comment by mlvandijk** [comment]
That said, maybe using tags can help you? See the docs: https://docs.cucumber.io/cucumber/api/#tags

**Comment by cucushift** [comment]
@mlvandijk thx, i know tags, it can't offer much help.
