### ISSUE TITLE
gherkin-pretty: new CLI tool

### ISSUE THREAD

**Issue by nfisher** [cucumber/cucumber#384]
I plan to collapse a number of the scenarios below into step level assertions however I want to confirm the  formatting behaviour before proceeding further.
 
```gherkin
Feature: gherkin-pretty consumes an AST pipe and writes feature files to disk.
  As an author of user stories
  I want a tool that is consistent in the way it writes Gherkin AST to feature files
  So that readers of my feature files benefit from uniform formatting.

  Scenario: 1. Valid AST stream should overwrite existing feature files.
    TBD

  Scenario: 2. Single feature with `-out` flag should write feature to path specified by out.
    TBD

  Scenario: 3. Multiple features with `-out` should generate an error if out is a file.
    TBD

  Scenario: 4. The Feature line should not be indented.
    TBD

  Scenario: 5. The Feature description should be indented with 2 spaces.
    TBD

  Scenario: 6. The Background, Examples, Scenario, and Scenario Outline line should be indented with 2 spaces.
    TBD

  Scenario: 7. The Background, Examples, Feature, Scenario, and Scenario Outline label should be followed by a colon and one space.
    TBD

  Scenario: 8. The Background and Scenario steps should be indented with 4 spaces.
    TBD

  Scenario: 9. Data tables should be indented with 6 spaces.
    TBD

  Scenario: 10. Data table columns should be as wide as the longest column element with 1 leading and 1 trailing space.
    TBD

  Scenario: 11. Data tables columns with numeric data should be right aligned.
    TBD

  Scenario: 12. Examples line should be indented with 4 spaces.
    TBD

  Scenario: 13. A Feature tag should not be indented.
    TBD

  Scenario: 14. A Scenario tag should be indented with 2 spaces.
    TBD

  Scenario: 15. A comment should be left as is.
    TBD

  Scenario: 16. i18n right-to-left languages (e.g. Hebrew and Arabic) should be right aligned.
    TBC - not sure current practises with RTL languages.

  Scenario: 17. Last line of a step or data table should have 1 trailing new line.
    TBD

  Scenario: 18. Windows formatting
    TBC is there any desire to support a `windows` flag for CRLF?

  Scenario: 19. All trailing whitespace should be ignored/deleted except for in steps.
    TBD

  Scenario: 20. All double spaces should be collapsed except for in steps.
    TBD

  Scenario: 21. Multiple features with `-out` should write the features to the path specified by out if a directory.
    TBD
```

## Possible Solution

- create gherkin-pretty as command in cucumber project (e.g. gherkin-pretty/go).
- gherkin-pretty reads the AST from stdin/pipe and writes to the associated URI (e.g. `gherkin features/*.feature | gherkin-pretty`).

**Comment by aslakhellesoy** [comment]
Looks great! Some comments:

* `-out` should be `--out`
* ` Multiple features with `--out` as dir should not generate an error.`
* ` Multiple features with `--out` as file should generate an error.`
* 15 is a parse error, so you'll never see that

**Comment by nfisher** [comment]
@aslakhellesoy FYI plan to pick this up the last week of the month when I have a little more time.

**Comment by aslakhellesoy** [comment]
Thanks for the heads up @nfisher - no rush, take your time!

**Comment by nfisher** [comment]
@aslakhellesoy starting to look at the code in https://github.com/nfisher/cucumber/tree/master/gherkin/go

There's a couple of things that I think aren't common for a Go project. Were they done to accommodate the monorepo?

I can work with it as is but would you be open to the following changes (detail/motivations follow)?

1. use cmd project structure instead of cli.
2. use fully qualified import path instead of "..". 

Apologies if you know about everything I'm outlining and have reasons for the structure I'm not privy to. I don't have the initial context of the projects structure so would understand if you're against the proposed changes. I'm assuming the structure is as it is because you don't want to root the monorepo in the GOPATH. 

cmd project
------------

**Refactorings**
```
cli -[rename]-> cmd
cli/main.go -[move]-> cmd/gherkin/main.go
+ cmd/gherkin-pretty/main.go
```

**Motivation**

This would bring it inline with the "command project" layout [1]. In addition this change would result in binaries being generated with their parent folder name without the need to specify -o. So `go install -v ./...` would install `gherkin` and `gerkin-pretty` to `go/bin`.  Also `go build -v ./...` would generate the binaries in their respective directory.

imports
--------

**Refactorings**
```
import ".." -[replace]-> import "github.com/cucumber/cucumber/gherkin/go/"  
```

**Motivation**
import ".." (local package imports) limits the ability to import this project into other projects. go vet will flag the import as illustrated below;
```
go vet -v ./...
cli/main.go:15:2: local import ".." in non-local package
gherkin-generate-tokens/gherkin-generate-tokens.go:9:2: local import ".." in non-local package
```

In Go it's typical to use the package path your PR'ing against and using your fork as an alternative remote [2]. As an example for this PR I would `go get -v github.com/cucumber/cucumber/gherkin/go` which clones the repo. In `go/src/github.com/cucumber/cucumber` I would then set an alternate remote for that clone to my fork  (e.g. `git remote add nfisher https://github.com/nfisher/cucumber`).

1 - https://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project, https://github.com/golang-standards/project-layout
2 - https://splice.com/blog/contributing-open-source-git-repositories-go/

**Comment by nfisher** [comment]
Also the existing re `-out` vs `--out` annoyingly Go stdlib `flag` library departed from the *NIX convention of `--` for long flag `-` for short flag and only uses `-`. The existing `gherkin/cli` uses the stdlib flag library. I can probably find another library that supports *NIX convention if that's what you want as part of the PR.
