### ISSUE TITLE
Step convert matched regex from String to Integer, does it make sense?

### ISSUE THREAD

**Issue by sonncui** [cucumber/cucumber#388]
Step convert matched regex from String to Integer.

We have a step defined as:
```
Then /^I should see a blabla a (\d+) day "([^\"]*)" blabla "([^\"]*)" blabla (\$[\,\d\.]+)$/ do |times, type, title, whatever|
  ...
end
```

And we call the step using:
```
Then I should see a blabla a 2 day feature blabla title blabla whatever
```
We expect we get a **times** "2" but it gives us 2. Is it make sense?
Because in previous version of cucumber, it will give us "2" as **times**

Could you give me a definite reply about what it should be? Thanks a lot!

**Comment by luke-hill** [comment]
What version of cucumber (and all associated dependencies), are you using?

**Comment by aslakhellesoy** [comment]
As of versionn [3.0.0](https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#300-2017-09-27) Cucumber converts `\d+` into `Integer`.

This is because regexps now take advantage of built-in parameter types sucn as `{int}`.
