### ISSUE TITLE
Documentation: Link for Cucumber Expressions for Ruby is wrong

### ISSUE THREAD

**Issue by Donavan** [cucumber/cucumber#389]
The README.md for Cucumber expressions has a link for "The docs are here".  This link points to http://docs.cucumber.io/cucumber-expressions/ however the correct link is http://docs.cucumber.io/cucumber/cucumber-expressions/

Since the readonly copy of this found at https://github.com/cucumber/cucumber-expressions-ruby is the number 1 link when you search for "cucumber expressions ruby" that should probably be updated.

**Comment by xtrasimplicity** [comment]
Thanks @Donavan. If you have a few moments and are able to, it would be great if you could submit a PR on the subrepo. https://github.com/cucumber/docs.cucumber.io

If not, one of us will look into this when we get a moment.

Thanks again for reporting this! :+1:

**Comment by xtrasimplicity** [comment]
Thanks again @Donavan. All updated. :)

**Comment by xtrasimplicity** [comment]
@aslakhellesoy It looks like your latest commits to `cucumber/cucumber-expressions-ruby` have overwritten my changes to the readme file here. I've made the change again - is there any chance we can keep it there? :)

[Old commit](https://github.com/cucumber/cucumber-expressions-ruby/commit/ef29c558730c787c1e7a8c1df7341574b383acad)
[New commit](https://github.com/cucumber/cucumber-expressions-ruby/commit/90cf801ebc090560762c925c94ef56da47d6efb0)

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/docs.cucumber.io#196
