### ISSUE TITLE
[gherkin-c] Consistent build instructions in one place

### ISSUE THREAD

**Issue by cyocum** [cucumber/cucumber#393]
## Summary

README.md and CONTRIBUTING.md have inconsistent build instructions. This is a bit confusing. We should consolidate it, and also make sure it's consistent with what's done in .travis.yml.

## Context & Motivation

This is a copy of a bug from the gherkin-c repo which is now read-only: https://github.com/cucumber/gherkin-c/issues/7

**Comment by aslakhellesoy** [comment]
This is obsolete in the light of #425 - the C parser is most likely going away soon, unless somebody has a really good reason to keep maintaining it :-)
