### ISSUE TITLE
Remove/Hide cucumber steps from feature file in cucumber reports.

### ISSUE THREAD

**Issue by roadrunner0510** [cucumber/cucumber#397]
## Summary

General : Remove/Hide cucumber steps from feature file in cucumber reports.

## Expected Behavior

Expecting to remove few steps mentioned in my feature file to not show up in my Cucumber reports as they contain calls to few third party api calls which are irrelevant to my generated business reports.

## Current Behavior

Currently every line in a feature file is a step in itself.

## Possible Solution

Can we have a possibility to hide certain steps from being shown in business reports.
So that feature file writers can have a separate understanding to feature file as compared to business document.

## Context & Motivation

There are sometimes when you want to provide/write more detailed feature files but they all shows up in business reports which may/may not be required.
The purpose for asking this is to maintain a well written feature file despite of showing business style reports.

**Comment by aslakhellesoy** [comment]
What Cucumber implementation? Ruby? Java? JavaScript? Other?

**Comment by KyleFairns** [comment]
On top of that, what version of Cucumber in that implementation?

If this is about business reports, I'd be surprised if this is something to be handled by the team at Cucumber.

There are some possible alternative solutions that I can suggest (using JavaScript for my examples):

Perhaps putting these API calls within other steps:
```
Given('some step that depends on the third party api',()=>{
   // interact with 3rd party API
  // Do other things afterwards that depend on that output
});
```

 Or in the hooks would achieve this:
```
Before({tags: '@third-party-call and @<specific_call>' },()=>{
   let world = this;
   ...
   return world.api.specificCall = <output to call from api>;
});
```

Either that, or you mask your API calls within those steps.

`Given I have made a call to <third party>'s API requesting <information>`

If you need to have visibility of those calls, you could attach some text to the world object at the point that you make the call, describing what you are doing there, and it should appear on the report, usually in a point where it's able to be toggled to show and hide that text - which may be what you are looking for.

**Comment by aslakhellesoy** [comment]
Closing this because of lack of information. Please reopen in cucumber-ruby, cucumber-jvm or cucumber-js, along with information about what version you're using.
