### ISSUE TITLE
@ character provokes lexig error in block comments

### ISSUE THREAD

**Issue by samassot** [cucumber/cucumber#398]
Try to integrate Plant uml diagram in scenarii.

## Summary

For quick doc purpose, we tried to insert plantUml diagrams in the feature to have an overview of the contained scenarrii, or for complex scenarii documentation.
Using some EDI plugins it alows to display in front of the feature a graphical view of the scenario or any uml diagram.

## Expected Behavior

The feature contains the following :
```
Feature: Bob and Alice sample
"""
    @startuml
    Alice -> Bob: Authentication Request
    Bob --> Alice: Authentication Response

    Alice -> Bob: Another authentication Request
    Alice <-- Bob: another authentication Response
   @enduml
"""
    Background: blahblah

```
We expect gherkin lexer to ignore the content of the block comment and run properly.

## Current Behavior

The lexer fails with 
```
[...]
Caused by: gherkin.lexer.LexingError: Lexing error [...]
```
The problem is the character "@".
if we remove the "@" the scenario runs properly, but the plantUml source is not properly parsed.

## Possible Solution

Solution would be to ignore @ processing in block comments, or create an escape character delimiter that allows any string inside.

## Steps to Reproduce (for bugs)

Add block comment with above example, run feature.

## Context & Motivation

We are implemeting behaviour tests in complex environment, with multiple actors. as the feature files count grows its becomes long to read the scenarii to know what it does exactly.
Creating a sequence diagram prior to write the scenario is often really useful. Storing it with the scenario is the best way to keep it up to date and fasten search and understanding of the feature.
## Your Environment

* Version used: 3.2.1
* Operating System and version: Windows 10
* link to plantUml : http://en.plantuml.com

**Comment by aslakhellesoy** [comment]
Gherkin doesn't have block comments.

`"""` is for [DocStrings](https://docs.cucumber.io/gherkin/reference/#doc-strings), which are intended to be placed underneath [steps](https://docs.cucumber.io/gherkin/reference/#steps), not in the [description](https://docs.cucumber.io/gherkin/reference/#descriptions) section of a feature.

**Comment by samassot** [comment]
Ok I understand you point of view about block comments.
Nevertheless, why the @ character fails in the docstring ?

2018-05-25 15:48 GMT+02:00 Aslak Hellesøy <notifications@github.com>:

**Comment by xtrasimplicity** [comment]
@samassot As @aslakhellesoy mentioned, Gherkin doesn't support DocStrings in that way. They are intended to be used as multiline arguments to a step definition. e.g.
```gherkin
Given I click 'View Message'
Then I should see a message with:
"""
This is a multiline DocString, which will be passed to the `I should see a message with:` step.
"""

**Comment by samassot** [comment]
Ok thanks, I was misunderstanding the way to use docstring.
I tried to use correctly the description section : the @ passes if the line
doesn't start with it.

Unfortunatly to get the plantuml detect the diagram, the line has to begin
with the @startuml tag.

I'm ok with it but it would have been nice to be able to join some sequence
diagrams to our features.
If you'r interested, I could show you a screenshot of what it would look
like.

Thanx for your reactivity.
Regards.
Samuel-Alexandre Massot

2018-05-28 13:19 GMT+02:00 Andrew <notifications@github.com>:
