### ISSUE TITLE
Cucumber Expressions (JS): Optionals at end of line do not match steps when other transformations are involved in the step definition

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber#403]
## Summary

If you have a few optional characters at the end of the step definition, and you have other transformations within that string (optional groups or captured parameters, such as {word}), the optional character does not get transformed properly

## Expected Behavior

For the optional characters to be transformed and allow the step definition to match in these cases.

## Current Behavior

Step Definition is not recognised

## Possible Solution

Possibly ignoring the transformation step for optional characters at the end of the line

## Steps to Reproduce

```gherkin
Given I have these scenarios:
 """
 Scenario: Test
    Given I have optional parameters
    When I use them at the end of my step definition
    Then I should be able to run that step

  Scenario: Test 2
    Given I have optional parameters
    When I use them at the end of my step definitions
    Then I should be able to run those steps
"""

And I have these step definitions:
"""
Given('I have optional parameters', () => {
    return true;
});
When('I use them at the end of my step definition(s)', () => {
    return true;
});
Then('I should be able to run th(ose|at) step(s)', () => {
    return true;
});
"""

When I run cucumber
Then the following steps will be undefined:
    | Then I should be able to run those steps |
    | Then I should be able to run that step   |
```
## Context & Motivation

Just trying to add an optional word character at the end of my step definition

## Your Environment
Node 10.3.0
npm 6.1.0
cucumber 4.2.1

**Comment by aslakhellesoy** [comment]
You seem to be mixing regexp syntax with cukexp syntax. None of the syntax you're used to from regexp will work in cukexp.

In cukexp, `th(ose|at) step(s)` matches the following texts (literally):

* `th step`
* `th steps`
* `those|at step`
* `those|at steps`

What you probably wanted is `those/that step(s)`

See https://docs.cucumber.io/cucumber/cucumber-expressions/#optional-text for the full docs.

**Comment by luke-hill** [comment]
Also just quickly worth adding if you wanted to capture them (No idea why). You can still use regular Regex for your step definition

`/^I should be able to run th(ose|at) step(s)$/`

**Comment by KyleFairns** [comment]
So what would be the syntax for optional words or phrases?

So, “I should be on (the ){string}( page/form)” would match “I should be on the ‘home’ page”, “I should be on ‘settings’” and “I should be on the ‘registration’ form” (all of which would locate the url in the object that we’ve set up)

**Comment by aslakhellesoy** [comment]
You cannot use the alternative text token (`/`) inside optional text `()`. If you really need that level of control you should use Regular Expressions.

I think you're trying too hard to shoe-horn lots of different ways to write a sentence into the same expression. You can use this instead:

```javascript
Given("I should be on the {string} page/form", function (pageOrFormName) {
  assert.equal(currentPage(), pageOrFormName)
})

Given("I should be on {string}", function (pageOrFormName) {
  assert.equal(currentPage(), pageOrFormName)
})
```

Don't worry that this is not DRY. DRY is not a universal law that must be obeyed. Clarity always trumps DRY.
