### ISSUE TITLE
cucumber-expressions: ParameterType doesn't support empty capture group

### ISSUE THREAD

**Issue by ozzyaaron** [cucumber/cucumber#404]
## Summary

Previously ParameterType would still run the transform code if the capture group was empty which was handy when dealing with simple scenarios.

e.g.
```
ParameterType(
  name: "Employer",
  regexp: /Employer(?: "([^"]*)")?/,
  transformer: -> (name = nil) do
    if name.present?
      Employer.find_by(name: name)
    else
      @employer
    end
  end
)
```

Could be used with a step like:

`The Employer can create a Job Offer for "Bob"`
or
`The Employer "Job Centre" can create a Job Offer for "Bob"`

## Expected Behavior

I would expect to retain the ability to have an empty capture group, transforms have worked in this way for as long as I can remember using Cucumber. If this change is intended then I think the documentation needs to call this out. 

## Current Behavior

The transform is not run when the capture group is empty

For the above ParameterType and step definition

`Given("I am viewing the {Employer}") do |employer|`

`Given I am viewing the Employer` doesn't work, no capture group content
`Given I am viewing the Employer "Roland Music"` does work as "Roland Music" fills capture group

## Possible Solution

Putting back the old call at https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type.rb#L38 fixes this issue for me. 

i.e. 

Replacing 
`group_values.empty? ? nil : self_obj.instance_exec(*group_values, &@transformer)`
with
`self_obj.instance_exec(*group_values, &@transformer)`

as it was before

## Context & Motivation

The standard way we use this is that some simple scenarios do not require naming objects

e.g. 

```
Given there is a User
The User can login
```
vs
```
Given there is a User "Super Super"
Then User "Super Duper" can login
```

## Your Environment

* Version used: Cucumber Expressions 6.0.0
* Ruby 2.5.x

**Comment by aslakhellesoy** [comment]
Thanks for reporting this @ozzyaaron. I've been unable to reproduce your issue. See https://github.com/cucumber-attic/cucumber-expressions-404.

If you feel this is still an issue, please prepare a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that reproduces the alleged bug.

**Comment by aslakhellesoy** [comment]
Aha I see. I'll reopen this and do some more invsetigation. Thanks!

**Comment by aslakhellesoy** [comment]
![75893e_e308e88081c84d7eb15c870b27397b51 mv2](https://user-images.githubusercontent.com/1000/41379117-0e3ff690-6f59-11e8-8a97-125a861a44ab.jpg)

**Comment by ozzyaaron** [comment]
Thanks @aslakhellesoy that looks like it will work! You should only hear back from me if it doesn't 😉
