### ISSUE TITLE
Julia: implementation

### ISSUE THREAD

**Issue by taqtiqa-mark** [cucumber/cucumber#407]
Hi, Thanks for all your efforts over the years to get Cucumber,Gherkin and Aruba to the point they are at.
I've used Cucumber and Aruba in Ruby and it looks like I'll have an increasing need to use them in Julia.

I'd appreciate your views on your preferred approach to a Julia implementation.
An initial effort is under way with [ExecutableSpecifications.jl](https://github.com/erikedin/ExecutableSpecifications.jl)

As I understand it this effort would require the following (unordered): 
- [ ] License MIT
- [ ] Gherkin Parser 
- [ ] Cucumber regular expressions 
     - [ ] Cucumber specific expressions
- [ ] Tag Expressions
- [ ] Language-specific DSL for step definitions and hooks
- [ ] Runtime/execution engine
- [ ] Aruba implementation

Currently [ExecutableSpecifications.jl](https://github.com/erikedin/ExecutableSpecifications.jl) is licensed under the Apache License version 2.0.  I assume that would need to change to MIT to be included upstream.  Is that assumption correct?

Is there an objection to using names Cucumber.jl. Gherkin.jl and Aruba.jl, on the condition they point to any upstream implementation by Cucumber Ltd?
Or would you prefer those be reserved for future 'upstream' use?

Are there any plans to have Julia implementations of Cucumber, Gherkin and Aruba under the cucumber organization?

**Comment by erikedin** [comment]
Hi! I'm the creator of ExecutableSpecifications.jl.

Although my package is a BDD framework like Cucumber, it's not meant to be a Cucumber replacement or a Julia implementation of Cucumber itself. ExecutableSpecifications.jl is meant to be a low effort framework that can be used with Julia code without any external dependencies, so it could be executed as part of the normal tests for Julia code. It's not appropriate for upstream inclusion into Cucumber.

A Julia implementation or bindings for Cucumber would be excellent, but very little of my code would be appropriate for that. Unfortunately, I don't have any plans to create such bindings myself.
It's possible that some of my code for a DSL for step definitions would be usable for such bindings, but I imagine that it's probably easier to write that from scratch for Cucumber bindings.

However, if it would help, I'm completely open to adding the MIT license as a dual license.

**Comment by aslakhellesoy** [comment]
I’d recommend basing a new implementation on the new go-based pickle runner by @charlierudolph (tell us more!). It takes care of the general language independent bits and significantly reduces the amount of code to write for a new implementation. It’s also interesting because it makes it easier to keep implementations consistent.

**Comment by taqtiqa-mark** [comment]
Thanks for taking time to look at this, and for the advice @aslakhellesoy.
Will definitely try to find this pickle runner.
Waiting to hear if @erikedin's implementation is targeted for inclusion in Julia's Base.  If so that may rule out a golang dependency.

It has been a few years since I had my head and hands inside the Aruba/Cucumber code..... are the Gherkin spec and feature files sufficient reference, i.e.  completely describe behavior?

**Comment by aslakhellesoy** [comment]
Here it is: https://github.com/cucumber/cucumber-pickle-runner

Regarding the use of «Cucumber», please call it something else. If It matures and attracts a community that can maintain it, we’d be happy to host it under the cucumber github org. You’re free to use the gherkin and aruba names, but you shouldn’t have to implement gherkin.

**Comment by aslakhellesoy** [comment]
> are the Gherkin spec and feature files sufficient reference, i.e. completely describe behavior?

There is a thorough set of [approval tests](http://approvaltests.com/) (using `diff`) that verifies parser behaviour. We have 9 gherkin implementations, and maintaining them all (and adding new implementations) is not sustainable. My goal is to retire all of them (except go and maybe javascript) if the pickle runner turns out to work well in practice.

**Comment by taqtiqa-mark** [comment]
Thanks @aslakhellesoy.  Will do as suggested.
