### ISSUE TITLE
Documentation: Dead link in readme.md

### ISSUE THREAD

**Issue by ithinuel** [cucumber/cucumber#409]
## Summary

the link to [plain language](https://github.com/cucumber/cucumber/blob/master/docs/gherkin.md) in the read me is dead.

## Expected Behavior

Going to the expected location.

## Current Behavior

It currently 404's.

## Steps to Reproduce (for bugs)

1. Go to https://github.com/cucumber/cucumber
2. click on the link `plain language`.

## Context & Motivation

I was trying to understand what a "plain language" is.

**Comment by mlvandijk** [comment]
Thanks for pointing that out @ithinuel! It's fixed now :)
