### ISSUE TITLE
Stop packaging jars as OSGi bundles

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#412]
Several jar files in the Cucumber ecosystem are packaged as OSGi bundles. (Checked means they have been removed already)

* [x] gherkin
* [ ] cucumber-expressions
* [x] tag-expressions
* [x] datatable
* [ ] config
* [x] cucumber-* - https://github.com/cucumber/cucumber-jvm/pull/1404

This introduces significant complexity and difficulty with the build system, so I propose we stop building and publishing OSGi bundles.

Most people using Cucumber don't need OSGi. Those who need it can package the jars they need as OSGi bundles themselves. This is the approach taken by most other Java libraries.

Relevant discussions:

* [Slack](https://cucumberbdd.slack.com/archives/C6RLMP3C4/p1527941144000004)
* https://github.com/cucumber/cucumber-jvm/pull/1345

/cc @rjking99 @mpkorstanje @brasmusson

**Comment by mpkorstanje** [comment]
Also /cc: @HendrikSP

**Comment by HendrikSP** [comment]
I don't see the OSGi related problems (cannot read the slack chat).

I would like to see that cucumber can still run in OSGi.

**Comment by aslakhellesoy** [comment]
I've taken screenshots of the slack conversation:

<img width="1200" alt="screen shot 2018-06-15 at 15 20 16" src="https://user-images.githubusercontent.com/1000/41472991-e88391e8-70af-11e8-86e6-a10af376c7f5.png">
<img width="1195" alt="screen shot 2018-06-15 at 15 20 42" src="https://user-images.githubusercontent.com/1000/41473003-f0fda07a-70af-11e8-9f3b-0bec41c67aec.png">
<img width="1197" alt="screen shot 2018-06-15 at 15 20 58" src="https://user-images.githubusercontent.com/1000/41473008-f411b10c-70af-11e8-869f-40a71588df31.png">
<img width="1192" alt="screen shot 2018-06-15 at 15 21 14" src="https://user-images.githubusercontent.com/1000/41473013-f6d30986-70af-11e8-9068-1e86eea97f3e.png">
<img width="1204" alt="screen shot 2018-06-15 at 15 21 38" src="https://user-images.githubusercontent.com/1000/41473017-f9376b0e-70af-11e8-9162-9edaebe38c5c.png">
