### ISSUE TITLE
Update Gherkin README

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#433]
Some content is out of date:

* The AST diagram needs to reflect the new `Rule` keyword and general Protobuf structure. Maybe generate it? (Wouldn't be as nice).
* The docs need to be updated to reflect the fact that it's using protobuf, and that `--json` will produce NDJSON.

**Comment by mlvandijk** [comment]
@jenisys The Gherkin README should probably also be updated. That might be a better place to describe the grammar rules more explicitly if you want to give that a go?

**Comment by jenisys** [comment]
Thanks for the info. 
I will have a look at it tomorrow.
