### ISSUE TITLE
Support custom cucumber expression types which accept multiple-line arguments, such as doc-strings

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber#440]
Hi,

I need to define a new parameter type which takes as argument a string on multiple lines (such as doc-string)
```
    Given the following json
  """
  {
    "field0": "value0",
    "field1": "value1"
  }
  """
```
```
 typeRegistry.defineParameterType(new ParameterType<>("json",
                "\\s*([^\"\"\\\\]*(\\\\.[^\"\\\\]*)*)\\s*", Json.class, new Transformer<Json>() {
            @Override
            public Json transform(String s) throws Throwable {
                return new Json(s);
            }
        }));
```
```
@Given("the following json{json}")
public void setJson(Json json) {
   scenario.write(json.toString());
}
```

However, this does'n work since the doc-string is passed as second argument:
```
Given a string=                                                                            # SetSymbolsSteps.sets(String)
      cucumber.runtime.CucumberException: Step [the folowing json{json}] is defined with 1 parameters at 'ro.cucumber.core.features.stepdefs.Steps.setJson(Json) 
However, the gherkin step has 2 arguments:
```

This is just an example. I need to make more complex operations within the transform method, before the final argument is passed to the Java method.

Is there a solution to this problem, or any future features for this ?

**Comment by fslev** [comment]
I undertand. However, it's kind of ugly...Then I'll have to use the value with list.get(0)

**Comment by mpkorstanje** [comment]
Data tables can auto convert to a single object. So you can just put that in and it will work.

**Comment by mpkorstanje** [comment]
Okay. Let's leave this ticket open until this has been documented. It's a
bit of an odd behavior.

**Comment by aslakhellesoy** [comment]
I think the modt intuitive option here would be to use `ParameterType` to transform a DocString.

The expression itself would not mention it (as in @fslev’s original example). Instead, the correct parameter type would be looked up based on the stepdef’s parameter.

No change should be necessary in the cucumber expressions library to do this, only in Cucumber-JVM. It would only work in statically typed languages, but I think that’s ok.

**Comment by fslev** [comment]
That's good news. 
Doc strings are a very important cucumber feature, since real life systems are tested by providing input data of type xml, jsons etc. They need to be easy to read inside any test.

**Comment by mpkorstanje** [comment]
Removing the regex would remove one of the things that define it as
parameter type.

It would effectively be a doc string type. Even if you tried to store it in
the parameter registry.

Might as well create a separate type and registry. Would be less hassle.
Could still look like a parameter type in the frontend but that doesn't
matter much I think.

**Comment by danascheider** [comment]
@aslakhellesoy Would we then add the feature to non-statically typed languages? Speaking as a Ruby dev of course.
