### ISSUE TITLE
Broken links in various READMEs

### ISSUE THREAD

**Issue by jackorp** [cucumber/cucumber#450]
## Info

I found multiple broken links to the docs in a few files. I have (correctly I hope) repaired some of them in [my branch](https://github.com/jackorp/cucumber/commit/c0e2a4fb025d12fb51b244815ae90e12572d7d37), but there are other files too which I need help with.

As of now I know these files have broken links:
[html-formatter/nodejs/README.md](https://github.com/cucumber/cucumber/blob/master/html-formatter/nodejs/README.md)
[gherkin/README.md](https://github.com/cucumber/cucumber/blame/master/gherkin/README.md#L45)
[gherkin-lint/javascript/README.md](https://github.com/cucumber/cucumber/blob/master/gherkin-lint/javascript/README.md)
[config/java/README.md](https://github.com/cucumber/cucumber/blob/master/config/java/README.md)

Unfortunately I have no idea where should they point to, so I would appreciate help.

## Summary

Multiple broken links to docs site in files throughout the repo.

Edit: add links to files.

## Expected Behavior

Links should point to correct places.

## Current Behavior

Links are pointing to non-existent places.

**Comment by mlvandijk** [comment]
Hello @jackorp, thank you for pointing that out! Would you be willing to do PR's to fix them?

You can find the docs here: https://docs.cucumber.io
You could use the search option to search for the topic you are trying to link to. If you don't find the topic, it's likely we don't have it (yet). In that case, I'd suggest linking to the main doc page (https://docs.cucumber.io/).
Some suggestions:
* html formatter > https://docs.cucumber.io/cucumber/reporting/
* Cucumber Config for Java > https://docs.cucumber.io/cucumber/configuration/
* Gherkin-Lint (javascript): you might also try [cucumber-js](https://github.com/cucumber/cucumber-js) to see if the info is there

Additionally: if you think there *should* be a page on the topic, but there isn't:
Check the open issues for the docs project: https://github.com/cucumber/docs.cucumber.io/issues 
If it's not there, please create a new issue. (and if you could add the missing information, even better ;))

Let me know if you have any further questions! You can most easily contact me on [Slack](https://cucumber.io/support#slack).

**Comment by jackorp** [comment]
Hi, thanks for the links. I will open PR once I have it done.

**Comment by jackorp** [comment]
I found there is already a mention about Event Protocol docs missing gherkin/README.md in [docs issue#144](https://github.com/cucumber/docs.cucumber.io/issues/144).

**Comment by mlvandijk** [comment]
Thanks for picking this up @jackorp! Please join us on [Slack](https://cucumber.io/support#slack), if you haven't already? If you'd like to contribute more, you can join channels #commiters and/or #docs and/or #help and or the help channel for the language(s) you use. :)

**Comment by jackorp** [comment]
I'll close as the fix was merged.
