### ISSUE TITLE
JavaScript gherkin executable occasionally skips messages

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#456]
The `gherkin-javascript` approval tests [occasionally fails](https://travis-ci.org/cucumber/cucumber).

It only seems to happen for `testdata/good/i18n_fr.feature`. I've managed to reproduce it locally once. To try it out yourself, first run the regular build:

```
cd gherkin/javascript
make
```

Then, run the `gherkin` executable several times and count the messages printed:

```
$ while :; do bin/gherkin --no-source --no-ast testdata/good/i18n_fr.feature | wc -l; done
       3
      11
      11
      11
      11
      11
      11
      11
      11
      11
      11
      11
      11
      11
^C
```

What seems to happen is that *occasionally*, the last 8 pickle messages are not printed. My theory is that the `gherkin-go` executable prints all the messages, but that the Node process exits before they have all been consumed. I don't know why it only seems to happen (on Travis mostly), with the French file.

I could really use some help getting to the bottom of this. /cc @cucumber/cucumber-js

**Comment by aslakhellesoy** [comment]
Here is another failed build (this time from sub repo, not monorepo):

https://travis-ci.org/cucumber/gherkin-javascript/builds/416971455

Why is this happening? And why only with the French feature file?

**Comment by aslakhellesoy** [comment]
This seems to be fixed by flushing STDOUT on the go side. Doh.

**Comment by charlierudolph** [comment]
Great find!
