### ISSUE TITLE
gherkin/go : Underscore in naming

### ISSUE THREAD

**Issue by antham** [cucumber/cucumber#457]
## Summary

I know it would break backward compatibility but convention in go use CamelCase (see https://golang.org/doc/effective_go.html#mixed-caps), consequence is golint report several errors about some naming using underscore. Would you consider releasing a major to change that ?

**Comment by aslakhellesoy** [comment]
Hi @antham we'd happily accept a pull request for that - the next release will be a major bump (6.0.0) so it's OK to break some APIs - we've already broken others.

**Comment by antham** [comment]
I had some hard time to understand what was berp and how it was working, I saw the documentation after I finished...
