### ISSUE TITLE
Not able to hide testdata in cucumber report

### ISSUE THREAD

**Issue by ishubhamjain** [cucumber/cucumber#460]
Hi, I am using cucumber with Java, JUnit and cucumber.
I am trying to set an option by which the certain test data will not show in the report.

I have username and password in cucumber example data for scenario outline.
I do the want that certain data to be included in the report.
I know I can set this information in any config file but there are lots of other data/fields which I do not want to include in cucumber reports.

Is there any way by which I can force cucumber reports to include such data while I also want few data to be included in reports

Any workaround will be helpful.

Suggestion:
Include one key in cucumber option which invokes such setting and there should be some symbol present in feature file which state which example fields show data and which should not include in the test report.

**Comment by xtrasimplicity** [comment]
Are these usernames and passwords legitimate credentials that you'd like to keep private? If so, I would recommend removing them and using fake credentials - and mocking authentication responses, as required.

I'm not a member of the core team, so I can't say for sure, but I really don't believe that this will be implemented.

**Comment by xtrasimplicity** [comment]
Also, github issues are intended exclusively for reporting issues with cucumber and requesting features, and are not intended to be used for support. Please visit the following page to find more information about how to get support.

https://cucumber.io/support
