### ISSUE TITLE
Using a scenario outline variable within the Background section.

### ISSUE THREAD

**Issue by fdefever** [cucumber/cucumber#469]
Today I ran into something I wasn't expected when using scenario variable within the `background` section.

I have multiple `scenario outline`s that use a common `background `section, each `scenario outline` have a set of variables, which some of them are used in the `background `section.

Problem is when running such scenario, the `background` section doesn't get the variable assigned from the current `Example` but instead is treated as is, as a string in this case: `<list>`.

Is there anyway to have such behivour working or this is current framework limitation?

```
Feature: my feature

Background:
  Given I do something
  And I choose from a <list>

Scenario Outline: choice A
  When I click on <something> after the choice A is clicked
  Then .... 

Examples:
  | list | something |
  |  a   |   1  |
  |  b   |   2  |
  |  c   |   3  |
```

**Comment by aslakhellesoy** [comment]
There may be regular `Scenario`s following the `Background`. What would the placeholder value be in that case?

**Comment by fdefever** [comment]
As `Background` is applied to all scenarios in a feature file, it's the responsibility to the person writing it to take care of these things. In the case that a `scenario` is part of that feature file, then I would expect either keep the current behaviour (variable declaration used as is) or an exception/error to be raised by the framework to signal an issue with the scenario description.

I was expecting that when using a `Background` section, it would prefix every `scenario` in that feature file, before variables are substituted to their values and steps evaluated. That would work.

From the example above, that would translate to:
```
Background:
  Given I do something
  And I choose from <list>

Scenario Outline: choice A
  When I click on <something> after the choice A is clicked
  Then .... 

Examples:
  | list | something |
  |  A   |   1  |
  |  B   |   2  |

->
  Given I do something
  And I choose from <list>
  When I click on <something> after the choice A is clicked
  Then .... 

```
_using_
```
  | list | something |
  |  A   |   1       |
```
that would finally evaluate to
```
   Given I do something
   And I choose from A
   When I click on 1 after the choice A is clicked
   Then .... 
```

**Comment by aslakhellesoy** [comment]
If we allow placeholders in `Background`, people are going to mess it up by mixing `Scenario` and `Scenario Outline`. It's not clear to me what Cucumber should do in that case.

Furthermore, this would be a rather big change with deep implications, so we're not going to prioritise this - sorry.
