### ISSUE TITLE
Allow tagging steps

### ISSUE THREAD

**Issue by lsuski** [cucumber/cucumber#474]
## Summary

Currently there is no possibility to tag step in scenarios. This would be very useful, especially for multiplatform (e.g. mobile) scenarios.
I could provide PR in Java.

##  Expected Behavior

- add tag above step
- tagged steps should execute only if tag matches - the same behaviour as for scenarios and features

## Current Behavior

- scenario does not compile with tagged step
- tags for steps are not supported

## Possible Solution

- change parser to allow tags above steps
- support tags in language specific runners

## Context & Motivation

We develop multiplatform and multibrand applications and sometimes we need to copy whole scenarios to change one or two steps for different platform/device and or brand

**Comment by aslakhellesoy** [comment]
You mean so you can include/exclude steps from a scenario?

That’s only necessary if your steps are coupled to implementation, a practice I’ve tried to get people to abandon for years.

I don’t think we’ll add a feature that encourages what i consider bad use.

**Comment by lsuski** [comment]
Coupled to implementation - what exactly do you mean?
In my case:
- I have 2 brands/apps which come from single code base with single test base 
- there are some processes which are almost the same but in one app there is another step
- currently I have to copy whole scenario or check in step implementation which brand it is - I don't like second approach because scenario suggests that this step should execute

**Comment by xtrasimplicity** [comment]
`currently I have to copy whole scenario or check in step implementation which brand it is`

Arguably the most important aspect of cucumber is to simplify discussion and collaboration between technical and non-technical people. The best way to do this is to keep the syntax as tidy and easy to read as possible - adding tags above/between steps would arguably impact on the readability of steps.

Perhaps you could refactor your steps to reduce duplication, if required? 



To keep things readable

**Comment by jenisys** [comment]
Mmh, I don't think that tags for step is a sensible solution.
It would completely clutter the Scenario description (in Gherkin) and makes it less readable.

There are other solutions from my point of view.
You have a build/build-script problem:
* Run it twice via build-script, once for each brand (by specifying which brand to use in each test run)
* Or: Run only the varying parts (Scenarios) again with another set of JAR files that contains the other implementation(s).

NOTE: 
Test report should indicate test configuration info (which brand/factory was used for this test run).

**Comment by aslakhellesoy** [comment]
> Coupled to implementation - what exactly do you mean?

I'm assuming that your Gherkin steps are coupled to the implementation by referring to UI elements. -And that because UIs are different on different devices, you want to include/exclude certain steps using tags.

Here are some articles: 
- http://archive.is/4BODh (so old it's an archive - but still relevant)
- http://www.marcusoft.net/2013/04/PushTheHowDown.html (similar message)

**Comment by mpkorstanje** [comment]
We've recently added `extraGlue` to cucumber-jvm. This might help in this scenario.

For example:

```java
public interface MyScreen {
   void doStuff();
}

public class StepDefs {
   private final MyScreen screen;
}
```
Then in two separate packages you could put

```
public class BrandAScreen extends MyScreen {
   void doStuff(){
   }
}
 
public class BrandBScreen extends MyScreen {
   void doStuff(){
   }
}
```
Then create two runners and use `brandB` or `brandA` package as the extra glue. I believe this works out of the boxy with PicoContainer. Haven't tried it personally.

**Comment by lsuski** [comment]
Ok, thanks for ideas. If this is not recommended then it can be closed
