### ISSUE TITLE
Gherkin: Improve ruby CLI documentation

### ISSUE THREAD

**Issue by jackorp** [cucumber/cucumber#475]
## Summary

Gherkin ruby CLI (maybe other languages too?) suffers from insufficient documentation when displaying `--help` option.

## Expected Behavior

Better document the command line tool for better user experience.

## Current Behavior

Insufficient `--help` documentation. Does not even mention that a file should be supplied as it does in the [readme](https://github.com/cucumber/cucumber/tree/master/gherkin#cli)

## Possible Solution

A start could be looking what could be added from the [readme](https://github.com/cucumber/cucumber/tree/master/gherkin#cli) page, which would already provide info for what is input, output etc.
Or when gherkin is ran bare as `gherkin` only then there could be a message that tells you to supply path to feature files.

## Context & Motivation

Better documenting the `gherkin` CLI could help understanding what should be provided if user wants to work with the tool.

**Comment by aslakhellesoy** [comment]
Happy to take a PR on this @jackorp!
