### ISSUE TITLE
API for message protocol formatters

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#485]
Our strategy for writing reusable formatters is to use Go. We should still make it easy to write formatters in any programming language, while still making them reusable (A Ruby formatter that can be used with e.g. Cucumber-JVM).

We should provide this API for the following languages (at least):

- [ ] Java
- [ ] Ruby
- [ ] JavaScript
- [ ] Go

**Comment by danascheider** [comment]
Is this still something we want to work on?
