### ISSUE TITLE
c21e: npm install is broken, breaks npm install gherkin as well

### ISSUE THREAD

**Issue by eins78** [cucumber/cucumber#487]
## Summary

`$ npm install c21e` is broken. It is a dependency of the `gherkin` package on npm, so that install is also broken.

## Expected Behavior

Installation should work

## Current Behavior

postinstall of `c21e` fails, seemingly because it needs dependencies that are only available on development.

~~~$ npm install c21e

> c21e@1.1.5 postinstall /tmp/test/node_modules/c21e
> node scripts/postinstall.js

/tmp/test/node_modules/c21e/scripts/postinstall.js:8
    if (err) throw err
             ^

Error: Command failed: npm run build
ReferenceError: Unknown plugin "@babel/transform-async-to-generator" specified in "/tmp/test/node_modules/c21e/.babelrc" at 0, attempted to resolve relative to "/tmp/test/node_modules/c21e"
…
~~~

## Possible Solution

- dont build on `npm install`
- or fix the dependencies

## Steps to Reproduce (for bugs)

```
cd tmp && mkdir test && cd test
npm init
npm install gherkin # fails
npm install c21e # fails
```

## Your Environment

```
node -v
# v8.9.2
npm -v
# 6.4.1
uname -a
# Darwin NX-07482 18.0.0 Darwin Kernel Version 18.0.0: Thu Jul 12 19:03:47 PDT 2018; root:xnu-4903.200.304.41.2~2/RELEASE_X86_64 x86_64
```

**Comment by aslakhellesoy** [comment]
Yep we’ll fix and release c21e. Nothing depends on gherkin 6 at the moment (afaik).
