### ISSUE TITLE
Multiple enum ParameterType generates exception

### ISSUE THREAD

**Issue by abhishek8908** [cucumber/cucumber#493]
I am trying to register more than one enum class in the parameter type:

```
public class TypeRegistryConfiguration implements TypeRegistryConfigurer {

    @Override
    public Locale locale() {
        return ENGLISH;
    }

    @Override
    public void configureTypeRegistry(TypeRegistry typeRegistry) {
        typeRegistry.defineParameterType(ParameterType.fromEnum(Color.class));
        typeRegistry.defineParameterType(ParameterType.fromEnum(Shape.class));
    }
}
```

> Exception:
> I couldn't decide which one to use. You have two options:
> 
> 1) Use a Cucumber Expression instead of a Regular Expression. Try one of these:
>    verify {Color}
>    verify  {Shape}
> 
> 2) Make one of the parameters types preferential and continue to use a Regular Expression.

Could you please suggest how to make this enum selection dynamic?

This conversion was not required in ver 2.4

**Comment by mpkorstanje** [comment]
Could you include the full stack trace, contents of the enums and your step definitions?

**Comment by abhishek8908** [comment]
Sure

Stack trace:

> io.cucumber.cucumberexpressions.AmbiguousParameterTypeException: Your Regular Expression /^assert color (CIRCLE|SQUARE)/
> matches multiple parameter types with regexp /CIRCLE|SQUARE/:
>    {SHAPE}
>    {TYPE}
> 
> I couldn't decide which one to use. You have two options:
> 
> 1) Use a Cucumber Expression instead of a Regular Expression. Try one of these:
>    assert shape {SHAPE}
>    assert shape {TYPE}
> 
> 2) Make one of the parameter types preferential and continue to use a Regular Expression.
> 
> 
> 	at io.cucumber.cucumberexpressions.ParameterTypeRegistry.lookupByRegexp(ParameterTypeRegistry.java:129)
> 	at io.cucumber.cucumberexpressions.RegularExpression.match(RegularExpression.java:32)
> 	at io.cucumber.stepexpression.StepExpression.match(StepExpression.java:21)
> 	at io.cucumber.stepexpression.ExpressionArgumentMatcher.argumentsFrom(ExpressionArgumentMatcher.java:20)
> 	at cucumber.runtime.java.JavaStepDefinition.matchedArguments(JavaStepDefinition.java:53)
> 	at cucumber.runner.Glue.stepDefinitionMatches(Glue.java:104)
> 	at cucumber.runner.Glue.stepDefinitionMatch(Glue.java:82)
> 	at cucumber.runner.Runner.addTestStepsForPickleSteps(Runner.java:64)
> 	at cucumber.runner.Runner.createTestCaseForPickle(Runner.java:54)
> 	at cucumber.runner.Runner.runPickle(Runner.java:39)
> 	at cucumber.runtime.Runtime$1.run(Runtime.java:84)
> 	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:220)
> 	at cucumber.runtime.Runtime.run(Runtime.java:81)
> 	at cucumber.api.cli.Main.run(Main.java:26)
> 	at cucumber.api.cli.Main.main(Main.java:8)
> 	at ✽.assert shape CIRCLE(D:/git-projects/fo-htf/htf_tests/src/test/features/TestHTFResponse.feature:38)
> 
> 
> Failed scenarios:
> D:/git-projects/fo-htf/htf_tests/src/test/features/TestHTFResponse.feature:37 # Test shape and color
> 
> 1 Scenarios (1 failed)
> 1 Steps (1 failed)
> 0m1.741s
> 
> io.cucumber.cucumberexpressions.AmbiguousParameterTypeException: Your Regular Expression /^assert color (CIRCLE|SQUARE)/
> matches multiple parameter types with regexp /CIRCLE|SQUARE/:
>    {SHAPE}
>    {TYPE}
> 
> I couldn't decide which one to use. You have two options:
> 
> 1) Use a Cucumber Expression instead of a Regular Expression. Try one of these:
>    assert shape {SHAPE}
>    assert shape {TYPE}
> 
> 2) Make one of the parameters types preferential and continue to use a Regular Expression.
> 
> 
> 	at io.cucumber.cucumberexpressions.ParameterTypeRegistry.lookupByRegexp(ParameterTypeRegistry.java:129)
> 	at io.cucumber.cucumberexpressions.RegularExpression.match(RegularExpression.java:32)
> 	at io.cucumber.stepexpression.StepExpression.match(StepExpression.java:21)
> 	at io.cucumber.stepexpression.ExpressionArgumentMatcher.argumentsFrom(ExpressionArgumentMatcher.java:20)
> 	at cucumber.runtime.java.JavaStepDefinition.matchedArguments(JavaStepDefinition.java:53)
> 	at cucumber.runner.Glue.stepDefinitionMatches(Glue.java:104)
> 	at cucumber.runner.Glue.stepDefinitionMatch(Glue.java:82)
> 	at cucumber.runner.Runner.addTestStepsForPickleSteps(Runner.java:64)
> 	at cucumber.runner.Runner.createTestCaseForPickle(Runner.java:54)
> 	at cucumber.runner.Runner.runPickle(Runner.java:39)
> 	at cucumber.runtime.Runtime$1.run(Runtime.java:84)
> 	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:220)
> 	at cucumber.runtime.Runtime.run(Runtime.java:81)
> 	at cucumber.api.cli.Main.run(Main.java:26)
> 	at cucumber.api.cli.Main.main(Main.java:8)
> 	at ✽.assert shape CIRCLE(D:/git-projects/fo-htf/htf_tests/src/test/features/TestHTFResponse.feature:38)
> 

Enums:

```
public enum SHAPE {
    CIRCLE,
    SQUARE

}

public enum TYPE {

    CIRCLE,
    SQUARE

}
```

Step defs:

```
    @Given("^assert shape (CIRCLE|SQUARE)")
    public void verify_SHAPE(SHAPE shape) {
        Assert.assertEquals(shape.toString(),"CIRCLE");
    }


    @Given("^assert color (CIRCLE|SQUARE)")
    public void assert_color(TYPE TYPE) {
        // Write code here that turns the phrase above into concrete actions
        Assert.assertTrue(true,"tc passed");
    }
```

**Comment by abhishek8908** [comment]
Yes I have this case where two different ENUMs have same value, can't it be used?

**Comment by mpkorstanje** [comment]
Have you tried using a [cucumber expression](https://docs.cucumber.io/cucumber/cucumber-expressions/) instead of a regular expression?

Note the removal of the start of line matcher `^` and replacement of the regular capture group with an cucumber expression argument.

```
    @Given("assert shape {Shape}")
    public void verify_SHAPE(SHAPE shape) {
        Assert.assertEquals(shape.toString(),"CIRCLE");
    }


    @Given("assert color {Color}")
    public void assert_color(TYPE TYPE) {
        // Write code here that turns the phrase above into concrete actions
        Assert.assertTrue(true,"tc passed");
    }
```

**Comment by mpkorstanje** [comment]
Only if no parameter types are registered and if the SimpleDefaultTransformer is made aware of Enums.
