### ISSUE TITLE
cannot load such file -- cucumber/formatter/ordered_xml_markup (LoadError)

### ISSUE THREAD

**Issue by PositiveAlex** [cucumber/cucumber#5]
After update of cucumber gem, I'm getting this error while starting my tests.
cucumber 2.0.2

`cannot load such file -- cucumber/formatter/ordered_xml_markup (LoadError)`

**Comment by PositiveAlex** [comment]
sorry, false alarm

**Comment by mathieujobin** [comment]
it has indeed been removed...
