### ISSUE TITLE
Tags not accessible for Children of Feature 

### ISSUE THREAD

**Issue by manasacharyya25** [cucumber/cucumber#507]
Tags which is a field for each Child of a Feature, is not accessible from code for C# code.

Problem with : Gherkin parser/compiler for .NET.

**Comment by xtrasimplicity** [comment]
Hi @manasacharyya25,

Thanks for reporting this. Could you please post a [Minimal, Complete, Verifiable example](https://stackoverflow.com/help/mcve) demonstrating this issue?

Thanks!

**Comment by manasacharyya25** [comment]
```
Parser p = new Parser();
string fileName="GherkinFeatureFile.feature";
TextReader gherkinReader = File.OpenText(fileName);
var feature = p.Parse(gherkinReader);               
var child0 = feature.Children.ElementAt(0);        //Returns a ScenarioDefinition

child0.Tags;                                                        //Generates Error

child0.Name;                                                   //Other Fields are Accessible
```

This workaround however lets me get the task done :
```
Parser p = new Parser();
string fileName="GherkinFeatureFile.feature";
TextReader gherkinReader = File.OpenText(fileName);
var feature = p.Parse(gherkinReader);               
var child0 = feature.Children.ElementAt(0);               //Returns a ScenarioDefinition
scenario0 = (scenario)child0;                                    //Type Casting to Scenario Type

scenario0.Tags;                                                        //Generates No Error

scenario0.Name;                                                   //Other Fields are Accessible
```

**Comment by SabotageAndi** [comment]
@manasacharyya25 You had always to cast the children items to `Scenario` or `ScenarioOutline` to get access to the tags.

**Comment by manasacharyya25** [comment]
@SabotageAndi  But why is it implemented this way? Any specific reason.

**Comment by SabotageAndi** [comment]
The Gherkin AST is generated from this file: https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp

A feature has different children (FeatureHeader, Background, ScenarioDefinitions and Rules) and not everything has tags. Background as an example.
So you have to do some casting.

**Comment by manasacharyya25** [comment]
@SabotageAndi Ok. That makes sense. Thanks :)
