### ISSUE TITLE
Cucumber-Expression:  (Cucumber::Glue::ArityMismatchError)

### ISSUE THREAD

**Issue by anandchavan** [cucumber/cucumber#509]
## Summary

Previously following step was working smooth, however with upgrade to cucumber 3.1.2, It throws error mentioned in current behavior section

Given(/^I create a foo (5.5|5.4|5.3|5.2) Subscription Allocation( with a( future dated)? subscription attached)?$/) do |version, sub_attached, future|

end

## Expected Behavior
Ability to handle nested optional groups
Sample steps to be accepted by above definition are following-

I create a foo 5.4 Subscription Allocation
I create a  foo 5.5 Subscription with a subscription attached
I create a foo 5.3 Subscription with a future dated subscription attached

## Current Behavior

Your block takes 3 arguments, but the Regexp matched 2 arguments. (Cucumber::Glue::ArityMismatchError)

## Possible Solution
Providing the ability to handle nested Expressions

## Steps to Reproduce (for bugs)

1. Implement the step definition given in summery
2. Add sample step to it
3. run cucumber

## Context & Motivation

We have subscription step which we have written in given format.

## Your Environment

* Cucumber Version used: 3.1.2
* Operating System and version: Linux
* Ruby 2.5.1
* Link to your project:

**Comment by aslakhellesoy** [comment]
Can you paste a full stack trace please?

**Comment by luke-hill** [comment]
This feels like an incorrect usage of regex, but just my personal opinion.

Having nested blocks is fine, but you're then having them both as always capturing, which feels incorrect.

Looking at your original use case something like this would be better imo.

```
# Matches first bracket (forced), 2nd bracket non-captured ignored, 3rd/4th ignored
I foo 5.4 Sub
# Matches first bracket (forced), 2nd bracket non-captured observed, 3rd ignored, 4th captured
I foo 5.5 Sub with a subscription attached
# Matches first bracket (forced), 2nd bracket non-captured observed, 3rd captured, 4th captured
I foo 5.3 Sub with a future dated subscription attached
```

`/^I foo (5.5|5.4|5.3) Sub (?:with a )?(future dated )?(subscription attached)?$/`

**Comment by luke-hill** [comment]
ping @anandchavan
