### ISSUE TITLE
cucumber-expressions: Non maching behavior between CucumberExpression and RegularExpression

### ISSUE THREAD

**Issue by chipironcin** [cucumber/cucumber#511]
## Summary

Using a regular expression with optional capture groups in step definition saves match results in order, returning "undefined" for the positional optional capture group.
This means that using a regex like `(optional capture) (required capture) (optional capture)`, if none of the optional captures are matched, the resulting matching object looks like `[ undefined, 'new', undefined ]`.

But, defining a custom parameter type with the same regular expression won't return non-matching capture groups, leading to inconsistency on parameters position.
This means that using a regex like `(optional capture) (required capture) (optional capture)`, if none of the optional captures are matched, the resulting matching object looks like `[ 'new' ]`.

I would expect both to behave consistently, also matching the way Javascript matches regexes (maintaining positional parameters).

Example:

Regular Expression:
```
/(first|second|third|fourth)? ?(new|existing) user ?(?:with version ([^\s]*))?$/
```

Seen with normal regular expression step definition (expected):
`[ undefined, 'new', undefined ]`

Seen with custom parameter type with same regular expression (non matching behavior):
`[ 'new' ]`

## Expected Behavior

Defining a custom parameter type with a regular expression matches the behavior of regex matching of NodeJS and a normal regular expression step definition by returning the value of matched capturing groups in order, including non matches (undefined).

## Current Behavior

~~~
defineParameterType({
  name: 'user',
  regexp: /(first|second|third|fourth)? ?(new|existing) user ?(?:with version ([^\s]*))?$/,
  type: User,
  transformer: (ordinal, type, version) => {
    // If the first optional capture group is not captured/matched
    // Then 'ordinal' will contain the value expected to be in 'type'
    // whilst 'type' and 'version' would be undefined
  }
});
~~~

## Possible Solution

Update the library (specifically `group.js`) to return undefined values too.
Might need to update other languages and some tests too.
Will try to raise a PR.

## Steps to Reproduce (for bugs)

1. Define a new parameter type and step like:
```
defineParameterType({
  name: 'user',
  regexp: /(first|second|third|fourth)? ?(new|existing) user ?(?:with version ([^\s]*))?$/,
  type: User,
  transformer: (ordinal, type, version) => {
    console.log(`${ordinal}, ${type}, ${version}`);
  }
});

Given('a(n) {user}', async function (user) {
});
```
2. Run with a feature file like:
```
Scenario Outline: User
  Given a new user
  Given an existing user
  Given a second new user
  Then a second existing user
  And a third new user with version 4.1

  Examples:
```
3. Notice how when ordinal is not provided and the type is matched, the transformer function will assign the type to the ordinal parameter as it is the first function parameter.

## Context & Motivation

I am trying to define a custom parameter type with a regex with some optional capturing groups. They way it is currently coded doesn't let me assign the results of the regex match properly to the right parameters.

## Your Environment

* Version used: MacOS High Sierra 10.13.6 and Cucumber 3.2.1 (tried with latest also), 
* Operating System and version: Cucumber-Expresions 5.0.18
* Link to your project:

**Comment by aslakhellesoy** [comment]
Thanks for the detailed description and analysis here @chipironcin! Capture groups are tricky - they fall in 3 categories (I think):

* optional (`(foo)?`)
* required (`(foo)`)
* non-capturing (`(?:foo)`)

I agree with you that optional ones should always provide a value. I think an explicit `null` might be better than `undefined`, but that's a minor detail.

Would you be up to submitting a pull request for this? It would be much appreciated!

Every change must be implemented in the JavaScript/Java/Ruby/Go implementation, but we'd be happy to receive the implementation in a single language - I can easily port it over to the other languages.

**Comment by chipironcin** [comment]
I will raise the PR and give other languages a try.
I agree `null` might be better, but when using Regexp in NodeJS, non-matching optionals are `undefined` (plus regexp step definition also behaves like that). Given that I am more keen to stick to `undefined`.

This issue doesn't require update until I raise a PR.
Cheers
