### ISSUE TITLE
"The gherkin step has 0 arguments" while there is one argument

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cucumber/cucumber#515]
In .feature I've: `When I wait for 2 seconds`,
Cucumber expression: `@And("I wait for (\\d+) seconds")`.
For test execution I get: "the gherkin step has 0 arguments".

**Comment by mlvandijk** [comment]
It looka to me like you are mixing cucumber expressions and regex. Could you please try replacing (\\d+) with {int}?

**Comment by mlvandijk** [comment]
@tomaszwojciechowski Yes, but in that case you need to start your String with ^ and end with $, like this: `@And("^I wait for (\\d+) seconds$").`

**Comment by tomaszwojciechowski** [comment]
@mlvandijk Thank you.

**Comment by CarloWakefield** [comment]
> It looks to me like you are mixing cucumber expressions and regex. Could you please try replacing (\d+) with {int}?

Isn't it possible to mix regular expressions and cucumber expressions?

**Comment by luke-hill** [comment]
It is not no. You need to use one or the other. Because the characters mean different things in the different constructs. I.e. `()` are optional characters in cuke exp, but they are capturing groups in regexp
