### ISSUE TITLE
Tighten CI / automated release process

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#516]
The current release process is documented in [CONTRIBUTING_NEW](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING_NEW.md). It works, but it's fragile. Configuring a new module to take advantage of the process is also error prone.

This issue is here to improve all of this. Let's collect suggestions for what can be improved in the list below. Once we're happy with that list, we should create an issue for each suggestion so they can be chipped away at independently. I'm starting with some suggestions - feel free to update/change the list. When a sub-issue is created (with more detail), check the box and add a link to the issue.

- [x] Use CircleCI and take advantage of its workflows
- [ ] Implement checks before releasing
- [ ] Explore [GitHub Actions](https://github.com/features/actions) (not sure if it's relevant)
- [x] Improve scripts for configuring a new module to take advantage of automated release
- [x] Restrict who can make releases (to make it more secure)
- [x] Figure out how to make branch builds pass, in particular for modules depending on go executables

**Comment by mpkorstanje** [comment]
Another point to the list:

[ ] Release scripts should check if all tools are available:
   [ ] CMake
   [ ] Maven
   [ ] npm (needs to be recent enough to support npx)

**Comment by mpkorstanje** [comment]
Cucumber expressions (and possibly other java modules) are build on both tags and master pushes. They should only build on master. The maven release plugin manages where the deployments will go based on snapshot/non-snapshot versions.

There is a thing in travis-ci.yml that can be used for this.

https://travis-ci.org/cucumber/cucumber-expressions-java/builds/447227281
https://travis-ci.org/cucumber/cucumber-expressions-java/builds/447227141

**Comment by aslakhellesoy** [comment]
This is good enough on master. Closing.
