### ISSUE TITLE
cucumber-expressions: A parser tool that lets us test if our regex captures what we want

### ISSUE THREAD

**Issue by JamesYeoman** [cucumber/cucumber#532]
## Possible Solution
Seeing as though Cucumber-Expressions is a module in itself, it may be possible to use that and just provide a front-end for using it to evaluate an expression

**Comment by aslakhellesoy** [comment]
What kind of tool do you have in mind @JamesYeoman? Command line? Or a web app like http://rubular.com

**Comment by JamesYeoman** [comment]
@aslakhellesoy I see a progression for this. 

1. an executable JAR that runs on the CLI
2. The JAR having an option to expose a localhost rest-endpoint that recieves a payload with the regex to test and strings as test cases
3. Using said endpoint as the backend for a web interface
4. Wrapping the CLI program into a Maven Execution Plugin (`mvn cucumber:validate-regex`)

Stage 2 means that people will be free to create their own UI and would make Stage 3 significantly easier to do (feedback could be collected regarding the endpoint and it could be refined before creating an entire site that uses it)

Stage 4 would be an optional thing that would probably start off as a community plugin and then become adopted by the cucumber team.

**Comment by aslakhellesoy** [comment]
The title mentions "regex", but you mean "Cucumber Expressions" I assume?

If we were to build something like this under the Cucumber project, it would probably have to be a single page web application without the need for a server at all. Just some HTML and JavaScript. It's easier to host that way.

You're of course free to proceed with the architecture you're suggesting, but it's probably not something we'd be hosting under this project.
