### ISSUE TITLE
Using problem

### ISSUE THREAD

**Issue by johanntony** [cucumber/cucumber#534]
if these is a customView like upgrade view, I wrote the click close event and then the upgrade view dismiss.
but if the upgrade view did not appear, the event that click close does not execute，and next step would failed!
so I want to know if these is a way to execute no matter it failed or succeed , the next step will still go!

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
