### ISSUE TITLE
datatable-java: Header only datatable does not convert to empty list

### ISSUE THREAD

**Issue by lsuski** [cucumber/cucumber#537]
## Summary

In cucumber v2 header only datatables `| firstName | lastName | birthDate |` converts to empty list. In cucumber v4.2.0 there is exception thrown in such case. 
This could have changed in be42d309e0a2ee65967a25c4db02793e68e25ffc. @mpkorstanje could you tell if this is really a bug or expected behaviour currently.
However converting `List<Map<String, Integer>>` in such case works.

## Possible Solution

Change `DataTableTypeRegistryTableConverter` to handle this situation

**Comment by mpkorstanje** [comment]
I'm having trouble working out why you'd get an error. Can you include the error, your step definition and your type registry configuration?

**Comment by lsuski** [comment]
I'm using only default converters. Add this test to `DataTableTypeRegistryTableConverterTest`

```
 @Test
    public void convert_to_empty_list__only_header() {
        final DataTable table = parse("",
                                      " | firstName | lastName | birthDate |"
        );
        assertEquals(emptyList(), converter.convert(table, LIST_OF_AUTHOR));
    }
```

It fails although this test `convert_to_empty_maps__only_header` passes

**Comment by mpkorstanje** [comment]
Cheers. That made it easy to spot. I'll have to think about the solution. It's a bit hard to explain.

**Comment by mpkorstanje** [comment]
What do you think of this?  https://github.com/cucumber/cucumber/pull/540/files

Because of it `convert_to_list_of_primitive` will no longer works for tables that are too wide. Those couldn't ever be lists of primitives anyway. But we were doing it anyway.

**Comment by lsuski** [comment]
Looks good for me
