### ISSUE TITLE
Run scenario outline more than once

### ISSUE THREAD

**Issue by sumit-global** [cucumber/cucumber#538]
Hi,
I know it's not a right platform to ask questions.
I want to run my scenario outline examples with different set of data and data is dynamic for examples.

**For eg:**
I am having java List say L which contains values of country like USA, INDIA UK and so on.(which will generated dynamically) and I want to run my examples with set of data for eg:

Examples:
|Country| State| Region|
|USA | ABC | DEF |
|USA | GHI | JKL |
|USA | MNO | PQR |

Now I want above examples will run for first USA and then for INDIA and so on(as per data in list)

I tried to make it run by using following

**public class ABC {
@test(junit)
public void run() throws Throwable {
for(String s: L){
cucumber.api.cli.Main.main(new String[] { "-g", "Path of Step Defs","Path of feature file" });
}
}
}**

and running above class as "clean verify -Dit.test=Abc.java"

It is running fine for first data from list not for all values in from List. Please suggest how can I achieve above part.

Thanks in advance.

**Comment by mlvandijk** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

The reason for this is, that if you create an issue, this goes to the maintainers who are spending their spare time maintaining Cucumber projects. If you try any of the support options, you reach the *entire user community* with a lot more people able to help you. This will probably help you get an answer more quickly.
