### ISSUE TITLE
[Feature Request] Ability to specify a reason for ignored tests

### ISSUE THREAD

**Issue by Stephen-Mc** [cucumber/cucumber#545]
## Summary

I'm part of the SpecFlow team, which uses the Gherkin parser. A SpecFlow user contacted us asking for the ability to specify a reason for tests being ignored using the `@ignore` tag. This would provide more context to other users, and would be something that can be included in reports/logs.

We think this sounds like a reasonable feature request, but that this should be a feature of the Gherkin parser, and not exclusive to SpecFlow.

## Expected Behavior

The user can include free text that contains an explanation for why the test is currently flagged as ignored. This text would be included in any logging output/reports to provide additional context.

## Current Behavior

It is currently not possible to include reasons for why a test is being ignored.

## Possible Solution

The parser would need to be able to differentiate between tags (prefixed with '@') and an additional string associated with the tag.

One way of handliing this would be to treat any string following a tag ('@') and whitespace to be interpreted as a "comment" on the preceding tag, e.g.
@ignore Causes a BSOD

Where "Causes a BSOD" is the reason for the ignore tag. Any subsequent @ characters on the line would presumably indicate the beginning of another tag. Obviously there are many different ways this could be formatted; in quotes, with a prefix etc. It should be realtively simple and legible. We're happy for alternative suggestions for the syntax, this is just to get the ball rolling.

The "reason" or "comment" would need to be available for logging etc.

Open questions include:
* should these "comments" be available for all tags or only the @ignore tag, i.e. is @ignore is a special case, or should users have the ability to add information on any tag (generic approach for all tags)?
* Should the @ character be permitted in the comment/reason?

## Context & Motivation

Provide users (especially other users in bigger teams) with immediate context as to why a test is flagged as ignored. This allows any decisions about the test (Should it really be ignored? Do we still need this test if it's been ignored for 5 years?) to be evaluated in context and provides documentation on the decision-making behind ignoring the test. This can save time and effort when trying to discover the reasoning, especially if a significant period of time has elapsed since the test was tagged with @ignore.

While comments can be added to provide context in the feature files themselves, there is an overhead with digging through the source files; immediately providing context during the test run would be preferable.

**Comment by SabotageAndi** [comment]
ping @aslakhellesoy @gasparnagy

**Comment by luke-hill** [comment]
Apologies if this isn't valid for your use case, however in Ruby You can by throwing a pending exception mid-test flow (Which has an optional argument as a reason - Output to stdout), by simply calling the pending method.

Are you able to manually use the same method `pending`?

Usage in Ruby is for example.
```
Given('Step I want to skip always') do
  pending 'This should always be skipped'
end
```

```
Given('I should only skip this step on live') do
  pending 'I am on live, do NOT do this test' if live?
end
```

**Comment by vvolverine** [comment]
Hey!
In my opinion tags it is a free form to express some notes for scenarios and Gherkin parser should treat them as a strings - like it happens right now. May be for future they should be treated as a key value pairs. 
I may recommend to take a look for [Allure Results](https://docs.qameta.io/allure/#__net) reports framework. They include features to specify some tags with values that will be visible in reports like `Links` . 
For general purpose I'm not sure that Gherkin parser should be tied to some specific anchors in tags, that can be also language dependent. This parser should expose all tags as it doing today and then report systems/orchestration engines(like CucumberJVM) should have ability to be configurable to treat tags and parse them depend on some logic.
