### ISSUE TITLE
cucumber-jvm - JUnit5 support?

### ISSUE THREAD

**Issue by ckstettler** [cucumber/cucumber#547]
## Summary

I have been trying to find working examples of JUnit5 and cucumber.  I saw on doc.cucumber.io that cucumber does not support JUnit5.

Is it planned?

**Comment by mpkorstanje** [comment]
Plenty of work to do! This project mostly developed by contributions so feel free to help out: https://github.com/cucumber/cucumber-jvm/issues/1149

Meanwhile you can still use the JUnit Vintage provided by JUnit 5 to run Cucumber with the JUnit 4 runner. https://github.com/cucumber/cucumber-jvm/tree/master/junit
