### ISSUE TITLE
Transform steps should also apply to Data Table elements

### ISSUE THREAD

**Issue by famished-tiger** [cucumber/cucumber#558]
Steps arguments are not created equal.
For instance, 'normal' step arguments that are created as capturing group
in the regular expression of a StepDefinition can be subjected to a Transform step.
Oddly enough, step arguments that come from an AST::Table cannot be Transformed.
This is annoying when, like my team mates, Transforms are used to do text substitutions
and the expectations are that the substitutions are performed for every step data value.
As a workaround to that weird limitation, I wrote long time ago a method for the World object that
invoked the Transform upon the AST::Table elements.

This worked fine until recently we got the warning:
[warning] map_column! will be deprecated

Then I realize that the idea of making Data Table immutable will only break the workaround
but will make the Transform steps completely ineffective for AST::Table.

What one needs is an implementation that follows the Principle of Least Surprise:
-One should be able to perform the same operations/transformations on step arguments
regardless the syntax used to create them (i.e. via a regexp capturing group, a multiline text or a data table).

**Comment by tooky** [comment]
We think this is solved now with latest 2.0. If there's any further problems please reopen.
