### ISSUE TITLE
Sonar Scanner Importing cucumber.json results

### ISSUE THREAD

**Issue by gsexton** [cucumber/cucumber#558]
Does anyone know if there is a Sonar Scanner that will take cucumber.json output and bring it into Sonar?

I'm not looking to scan the Gherkin feature files with Sonar, but to take the BDD testing results and place them into Sonar. Does anyone have any idea how to do this? I asked on the Sonar side, and they thought there had been a plugin at one time but that it had been withdrawn.

Thanks
George

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
