### ISSUE TITLE
tag-expressions-ruby (broken-link)

### ISSUE THREAD

**Issue by AlonzoRicardo** [cucumber/cucumber#560]
Iv'e been trying to use this [gem](https://rubygems.org/gems/cucumber-tag_expressions/versions/1.1.1), its cucumber's tag expression tool for ruby.

There are no docs to help people get started with it

when i tried to go to the [docs](http://docs.cucumber.io/cucumber/tag-expressions/) page i got 404.

I managed to get it working on my own by looking at the gem's repo, but still i think nobody has noticed that the page is down since there aren't any other issues opened.

Good day y'all!

**Comment by jenisys** [comment]
Tag expression docs seem to have moved.
Search them in the docs or use: https://docs.cucumber.io/cucumber/api/#tag-expressions

NOTES:
- Should be marked as doc-problem (broken-link)
- Cucumber docs maybe need to be checked, too.

**Comment by mlvandijk** [comment]
The "Documentation" link on page https://www.rubydoc.info/gems/cucumber-tag_expressions/1.1.1 links to http://docs.cucumber.io/cucumber/tag-expressions/ but the docs for tag-expressions have moved to https://docs.cucumber.io/cucumber/api/#tag-expressions.
Not sure if and how the Rubydocs should be updated

**Comment by jenisys** [comment]
ACCORDING TO SHELL COMMAND (in: cucumber/tag-expressions): `grep -R docs.cucumber.io *`
This is true for (using: http://docs.cucumber.io/cucumber/tag-expressions/ <http://docs.cucumber.io/cucumber/tag-expressions/>):

* tag-expressions-ruby
* tag-expressions-java
* tag-expressions-python (where I fixed the doc-link already twice in the README.md)
* tag-expressions-go

Only tag-expression-javascript links to the current page in the docs.

@mlvandijk @aslakhellesoy
MAYBE: We should have stable “landing pages” for READMEs, etc. into the docs.
When the docs change, we can keep the “landing page” and let it redirect to the new location in the docs.

ALTERNATIVE:
I (or someone else) fixes the READMEs in the projects above.

**Comment by luke-hill** [comment]
This is a fairly simple one-line fix modifying the gemspec.

If you're comfortable doing this on your own I can review / merge accordingly, or if you know the direct link you think it should be I can amend accordingly.

**Comment by dinarabs** [comment]
Same broken link issue for standard library link in tag-expressions https://github.com/cucumber/cucumber/blob/master/docs/standard-library.adoc#implementations
