### ISSUE TITLE
Is any way to get result with error in after hook ?

### ISSUE THREAD

**Issue by cgaulay** [cucumber/cucumber#562]
## Summary
I try to make logs with some information about test. But, i don't know how to get result with error with a hook annotation.
I would like to use Result class but it's not possible

## Expected Behavior
 Something like this : 
```
@After(order = 1)
    public void buildHistoricLogRule(final Result result) {
        buildHistoricLogs(result);
    }

private void buildHistoricLogs(final Result result) {
        historicLogs.setError(result.getError().toString());
        HISTORIC_LOGGER.info(historicLogs.generateJsonLog());
    }
```

## Current Behavior

When i do this, i've got this issue : 

> cucumber.runtime.CucumberException: When a hook declares an argument it must be of type cucumber.api.Scenario. public void step.definition.HooksStepDefinition.buildHistoricLogRule(cucumber.api.Result)

## Your Environment
* Version used: cucumber java 4.2.0

**Comment by mpkorstanje** [comment]
Please have a look at the plugin architecture. The progress formatter would be a good place to start.

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/ProgressFormatter.java
