### ISSUE TITLE
UTF-8 encoding does not work properly in Javadoc to describe annotations with an element of type String for not in english

### ISSUE THREAD

**Issue by Antonppavlov** [cucumber/cucumber#563]
We have a method in java-cucumber with @Когда annotation containing one element in String type and a description for JavaDoc. Annotation element is String value in Cyrillic alphabet. When uploading to HTML JavaDoc the UTF-8 encoding was recognized for the annotation @Когда as a sequence of UTF-8 codes, the rest of the method description is displayed correctly for the Cyrillic alphabet.

Uploading is performed by this command: javadoc -encoding UTF-8 -docencoding UTF-8 -charset UTF-8

/**
 * Метод получает значение атрубута из найденного элемента и сохраняет его в переменную для дальнейшего использования переменной.
 */
@Когда("^пользователь сохраняет значение атрибута \"(.*?)\" из элемента \"(.*?)\" в переменную \"(.*?)\"$")
public void UserSaveElementAttrToStash(String attrName, String elementTitle, String param) {}
Expected: UserSaveElementAttrToStash

@Когда(value= "^пользователь сохраняет значение атрибута \"(.*?)\" из элемента \"(.*?)\" в переменную \"(.*?)\"$")
Actual result:

UserSaveElementAttrToStash
@Когда(value="^\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u0441\u043e\u0445\u0440\u0430\u043d\u044f\u0435\u0442 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430 \"(.?)\" \u0438\u0437 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u0430 \"(.?)\" \u0432 \u043f\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u0443\u044e \"(.?)\"$"*)

**Comment by mpkorstanje** [comment]
I don't think this is a Cucumber problem. Seems like a java doc problem.
