### ISSUE TITLE
[Feature Request] Gherkin: Accept multiline example cell

### ISSUE THREAD

**Issue by cbou** [cucumber/cucumber#565]
## Summary

`Scenario Outline` are very useful. The provide a way to quickly run the same scenario several times. I currently miss one feature, the ability to have multiple lines in the table.

## Current Behavior

There are no multiple lines in `Example` table at the moment. Which means you have two possibilities.

Either you combine the two lines in one and separate it with a separator (e.g. ; ):

```gherkins
Feature:

  Scenario Outline: Move layer
    Given dummy given <a>
     When I do dummy thing <b>
     Then The feature to work <multiline>
  
    Examples: 
      | a     | b     | multiline | 
      | hello | world | foo;bar   | 
```

This makes  the table really hard to read.

Or you can add too lines:

```
    Feature:

    Scenario Outline: Move layer
      Given dummy given <a>
      When I do dummy thing <b>
      Then The feature to work <multiline>

    Examples:
      | a     | b     | multiline | 
      | hello | world | foo       | 
      | hello | world | bar       | 
```

This force the test to be run twice.

## Possible Solution

A possible solution could be to allow multiple lines in `Examples` table

```
    Feature:

    Scenario Outline: Move layer
      Given dummy given <a>
      When I do dummy thing <b>
      Then The feature to work <multiline>

    Examples:
      | a     | b     | multiline | 
      | hello | world | foo       | 
                      | bar       | 
```

or

```
    Feature:

    Scenario Outline: Move layer
      Given dummy given <a>
      When I do dummy thing <b>
      Then The feature to work <multiline>

    Examples:
      | a     | b       | multiline | 
      | hello | world   | foo       | 
                        | bar       | 
                        | bar       | 
      | hello | world   | foo       | 
              | monde   |
      | hello | world   | foo       | 
              | monde   | bar       | 
                        | baz       | 
```

The input variable in the steps would be an array.

## Context & Motivation

Using this syntax combine the advantages of both way. The test is run only once and the readability is improved.

**Comment by danascheider** [comment]
Thanks for the detailed issue report @cbou! For me, I think the syntax you're proposing is much more confusing than the current syntax, but I'm curious to see what other maintainers think.

**Comment by chethanrao** [comment]
I agree the syntax would be confusing. Also curious to know how gherkin parser would know which column the following lines belong to?

**Comment by cbou** [comment]
> Also curious to know how gherkin parser would know which column the following lines belong to?
You are right, maybe it's not the best syntax. For sure there is a better solution.

I was looking for a way to get an array of strings as an input instead of a string. Is that a valid feature for you or more an edge case?

**Comment by godomainz** [comment]
Is it possible to pass data to "Examples"  from an external file ?

**Comment by aslakhellesoy** [comment]
We won't be adding support for this. It makes the syntax too confusing.
