### ISSUE TITLE
c21e-java: Parsing large feature file simply hangs

### ISSUE THREAD

**Issue by ArjanKranenburg** [cucumber/cucumber#566]
## Summary
I have a large feature file, but when I try to read it, it just hangs.

## Expected Behavior
At least a return in some sort. Preferably OK and a read file, but otherwise an exception or so.

## Current Behavior
It hangs in the exe class, method execute, line 'process.waitFor();'

## Steps to Reproduce (for bugs)
I use this to read the Feature-file ([long.feature.txt](https://github.com/cucumber/cucumber/files/2871022/long.feature.txt)):
```
        List<Messages.Wrapper> messages = Gherkin.fromPaths(singletonList(featureFile.toString()), false, true, false);
```

## Context & Motivation
I wanted to read in all feature files of our project to create an overview of features. But it hang on a feature file of a 1000 lines. I could reproduce that with a synthesized long feature file (the attached file)

## Your Environment
* Version used: io.cucumber.cucumber-java:4.2.0
                           io.cucumber.gherkin:6.0.14
* Operating System and version: MacOS (10.14.2), but also on Linux inside a Docker-container (openjdk:8-jdk-alpine) with the file mounted from windows.
* Link to your project: https://github.com/AWK-Test-Services/featr

**Comment by mpkorstanje** [comment]
The combination of `io.cucumber:cucumber-java:4.2.0` and `io.cucumber:gherkin:6.0.14` does not seem right to me. `cucumber-java` has `gherkin:5.10` as a transitive dependency. So I don't think `cucumber-java` is relevant to this report.

**Comment by ArjanKranenburg** [comment]
True. I removed the cucumber-java from the POM. But the issue remains.
I guess the issue is in the c21e-java package.

**Comment by mpkorstanje** [comment]
I think the the gherkin parser might be choking either because the file takes up too much memory when parsed or because the the outpustream of `Process` is not consumed.  But I don't have any spare cycles to investigate.

For the time being it might be an option to use gherkin 5 instead.

@aslakhellesoy @charlierudolph do you have time to spare?

**Comment by aslakhellesoy** [comment]
I've started looking into this - I have reproduced the hanging behaviour with the supplied file - thanks! I think we need to introducuce some threading here, or NIO.
