### ISSUE TITLE
Add support Ruby 2.6 for cucumber-message

### ISSUE THREAD

**Issue by tadashi0713** [cucumber/cucumber#571]
## Summary
From google-protobuf 3.7.0, it will support Ruby 2.6.

I wanted to upgrade cucumber-messages dependencies for supporting Ruby 2.6, but JRuby issue does not solved yet

https://github.com/cucumber/cucumber/blob/master/cucumber-messages/ruby/cucumber-messages.gemspec#L33

I will make PR for this if any solution exists.

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by koic** [comment]
@aslakhellesoy Would you please new release cucumber-messages 2.1.2 or higher.
cucumber-messages wants google-protobuf 3.7.0 (rc or higher) when using Ruby 2.6.  The following commit can solve the issue https://github.com/protocolbuffers/protobuf/issues/5161.
https://github.com/cucumber/cucumber-messages-ruby/commit/1d063babd074514f9a04c329965fbe395fd36d36#diff-ff32aee7aa91dc83803a3aedf576441b

**Comment by koic** [comment]
And cucumber-formatter-dots 1.1.2 (latest) requires cucumber-messages ~> 2.0.0. But version 2.0.0 is already old.
Would you please release cucumber-formatter-dots gem so that it depends on the latest cucumber-messages if edge cucumber-formatter-dots has not problems?

**Comment by luke-hill** [comment]
I'm going to close this as fixed in `master`. There are too many "similar" issue trackers all regarding Ruby 2.6 and JRuby. Which just clouds the other issues.
