### ISSUE TITLE
cucumber-messages: Fix JRuby build

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber#579]
## Summary

Cucumber Messages Gem doesn't like working on Ruby 2.6 & JRuby at the same time. This is due to the google-protobuf gem (Dependency), having a later version which works on one version, but a lower version working on JRuby

## Current Behavior

Gem has issues on JRuby

## Possible Solution

#578 attempted to fix this, but didn't get very far. We need to have different restrictions for JRuby and Ruby 2.6 (Strictly tied to google-protobuf)

## Steps to Reproduce (for bugs)

Build the gem locally on JRuby, try to get it working on there and 2.6

cc/ @mvz

**Comment by aslakhellesoy** [comment]
I believe this is fixed now. https://travis-ci.org/cucumber/cucumber-messages-ruby/jobs/520874690
