### ISSUE TITLE
Cucumber- Test Runner :  java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter exception while running TestRunner class.

### ISSUE THREAD

**Issue by ank1006** [cucumber/cucumber#583]
I have created a TestRunner file for my cucumber tests but on executing test runner fiile as JunitTest i keep getting below exception

![image](https://user-images.githubusercontent.com/47805449/54652183-0ceb1580-4b0a-11e9-99b1-65695f86c2c4.png)

Here is the TestRunner class
![image](https://user-images.githubusercontent.com/47805449/54652210-2be9a780-4b0a-11e9-91cd-f46c212ca725.png)

Project structure and dependencies
![image](https://user-images.githubusercontent.com/47805449/54652226-3e63e100-4b0a-11e9-8f14-1efc7ba947e0.png)

Thanks in advance

**Comment by mpkorstanje** [comment]
It would appear that:

1) You are using JUnit 5 in combination with `cucumber-junit` which depends on JUnit 4. But JUnit 4 is not present in your dependencies.

If you want to use JUnit 5 incombination with `cucumber-junit` you'll have to use JUnit Vintage. Please see the [JUnit 5 User Guide](https://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5) on the exact steps to take.

2) You are using manual dependency management. I would strongly discourage this.

If you must use manual dependency management I would strongly recommend checking the dependencies in the Maven pom files and ensure that all dependencies are available on your class path. You can find this info in Maven Central.
