### ISSUE TITLE
Data Driven testing with cucumber protractor and typescript

### ISSUE THREAD

**Issue by godomainz** [cucumber/cucumber#588]
Lets say I have a scenario in my demo.feature file

Scenario Outline: Gather and load all submenus
Given I will login using <username> and <password>
When I will click all links
Examples :
| username | password |
| user1 | pass1 |
| use2 | pass2 |
lets say i have a file called users.json

How can i get those usernames and passwords from that external file to my demo.feature ? 
Can I catch the file by passing parameters to my npm script like below ? 
npm run cucumber -- --params.environment.file=usernames.json

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
