### ISSUE TITLE
Gherkin 6/7 executable problems

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#589]
Gherkin 6 bundles go executables inside packages (gems, npm modules, jars), and we're not yet sure whether or not this causes problems for users.

If it does, please comment on this issue with as much detail as you can:

* Operating system
* Platform/programming language and version
* Whether you have problems installing/downloading Cucumber
* Whether you have problems running Cucumber
* Any error messages you are seeing

**Comment by alfonso-presa** [comment]
Looks like this might be related:

* Operating System: Linux MP005F8F 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Using this as Java depency in a Maven Project:
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>6.0.17</version>
        </dependency>

* Error messages: io.cucumber.c21e.ExeException: No gherkin executable for gherkin-go-linux-amd64. Please submit an issue to https://github.com/cucumber/cucumber/issues

**Comment by aslakhellesoy** [comment]
Thanks @alfonso-presa - I will look i to this.

**Comment by alfonso-presa** [comment]
Thank you @aslakhellesoy. Let me know if you need any further information to get context of the error. I'm using the gherkin parser in a java project to extract meta-data from the gherkin files in order to perform a later distributed execution (in separate processes and machines) using cucumber. I guess this is not the regular use case for this tool so I might have hitten an edge case.

I'm doing researches myself and will let you know if I get any insights or findings. I'll also be happy to PR if I can help.

Keep it up!

**Comment by alfonso-presa** [comment]
Oh, @aslakhellesoy. BTW, I'm sorry to be fussy, but there's a typo in the issue title that might make difficult for people to find it as reference for the matter.... You might like to fix it just in case

**Comment by alfonso-presa** [comment]
Looks like the `io.cucumber:gherkin:6.0.17:jar` is missing the folder called `gherkin-go`, that I can find in for example the `io.cucumber:gherkin:6.0.10:har` release. My whole process is working against `6.0.10` but it's not with `6.0.17`. I've checked and it's missing also in `6:0.16` but it's present in `6.0.14` (I'm unable to download `6.0.15` for some reason so I cannot check there).

**Comment by aslakhellesoy** [comment]
Thanks for investigating that @alfonso-presa - that means there is a problem with our build/release process.

**Comment by aslakhellesoy** [comment]
Looking at the [release build](https://travis-ci.org/cucumber/gherkin-java/builds/513752345):

* The executables were downloaded in the [build job](https://travis-ci.org/cucumber/gherkin-java/jobs/513752346)
* They were *not* downloaded in the [deploy job](https://travis-ci.org/cucumber/gherkin-java/jobs/513752348)

I think the fix is to:

* Add `skip_cleanup: true` to the Travis deploy job config
* Make maven's `jar` target fail if there are no executables

**Comment by alfonso-presa** [comment]
May be using `<useStrictFiltering>true</useStrictFiltering>` in the `assembly.xml` file here could help: https://github.com/cucumber/cucumber/blob/master/gherkin/java/assembly.xml#L21

About the `skip_cleanup: true` I guess it would do the job :-). I'm not sure about how the whole pipeline is supposed to work....

**Comment by aslakhellesoy** [comment]
> May be using `<useStrictFiltering>true</useStrictFiltering>` ...

Thanks for the pointer - that's very helpful

We use `skip_cleanup: true` in `gherkin-ruby` and `gherkin-javascript` so I'm pretty sure that's the problem.

**Comment by alfonso-presa** [comment]
Perfect then. Let me know if you want me to PR, although I guess it will be way faster for you to patch it :-).

**Comment by aslakhellesoy** [comment]
Leave it to me - I'll make similar changes to other modules too in the same commit. Thanks!

**Comment by aslakhellesoy** [comment]
@alfonso-presa the latest `6.0.18-SNAPSHOT` has a fix for this - see https://docs.cucumber.io/installation/java/ for details on how to access it.

I'm reopening this issue since it's a more general placeholder for other issues related to Gherkin 6.

**Comment by alfonso-presa** [comment]
@aslakhellesoy great!! Thank you very much! Keep it up!

**Comment by mpkorstanje** [comment]
> Gherkin 6 bundles go executables inside packages (gems, npm modules, jars), and we're not yet sure whether or not this causes problems for users.

The latest versions of Gherkin no longer bundle executables.
