### ISSUE TITLE
Gherkin Lint - New project?

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#59]
A recent discussion in the [cucumber/gherkin gitter room](https://gitter.im/cucumber/gherkin?at=57a62059d097eb6b2ccacc0b) revealed that there are (at least) 3 Cucumber linters out there:
- [cuke_sniffer - Ruby](https://github.com/r-cochran/cuke_sniffer)
- [gherkin-lint - JavaScript](https://github.com/vsiakka/gherkin-lint)
- [gherkin-lint - Ruby](https://github.com/cucumber-ltd/gherkin-lint)

The projects are similar, and I think there are some great unique things in each one of them.

What do you think about joining forces to create a single one to rule them all? Ideally in JavaScript since it's easier to use on the web, and also relatively easy to embed into other libraries as well as editors and IDEs.

If you're interested, just reply here and fill out [this doodle](http://doodle.com/poll/xae79nkgu3zsrt2c) for a google hangout kickoff meeting.

/cc @enkessler @allustin @vsiakka @r-cochran

**Comment by allustin** [comment]
i am interested.

found another projects

may be dead

https://github.com/wimpheling/codemirror-gherkin-linter
https://github.com/mekentosj/ling

on ruby with some usefull checks

https://github.com/funkwerk/gherkin_lint#checks

**Comment by vsiakka** [comment]
I am interested!

**Comment by Pr-Mex** [comment]
+1

**Comment by r-cochran** [comment]
I am interested

**Comment by aslakhellesoy** [comment]
Thanks for doodling everyone. [I've picked a time](https://plus.google.com/events/c9pfebe9tvibj8hn8csoj9ogjp4?authkey=CKf3hPzYn5CGywE) the upcoming Friday.

## Proposed agenda
* Introduce ourselves quickly
* Agree on high level goals for the project
* Decide what to do next and who does what

We'll take lo-fi minutes in [gitter](https://gitter.im/cucumber/contributors) and paste a summary in this ticket later.

## Homework before hangout

Study the various implementations listed above and write down a list of things you'd
like to see in the official implementation. This will help us come up with better goals.

Thanks for participating everyone - I'm really excited about this!

**Comment by AlexeyBuzdin** [comment]
Will be glad to join!

**Comment by enkessler** [comment]
Good to go!

**Comment by aslakhellesoy** [comment]
There is also @charlierudolph's https://github.com/charlierudolph/cucumber_lint that we can use as inspiration

**Comment by aslakhellesoy** [comment]
Some of us ran a Google Hangout meeting on 12th Aug 2016. The minutes [are here](https://docs.google.com/document/d/16phGnd-hd2GcN118Irn1ccpm-4JqBB9wfBVB9cXDIIo).

**Comment by aslakhellesoy** [comment]
I just fixed the sharing access of that google doc. Anyone with the link can see it and comment on it.

**Comment by gmk1217** [comment]
Hi Cukes,
https://github.com/cucumber/gherkin-lint

Is this link working?
got 404 error.


---


Mohan Krishna Gundala
[image: https://]about.me/gmk.india
<https://about.me/gmk.india?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by aslakhellesoy** [comment]
@gmk1217 where did you find a broken link to https://github.com/cucumber/gherkin-lint ?

(The correct link is https://github.com/cucumber/gherkin-lint-javascript)

**Comment by gmk1217** [comment]
it's the google doc which you have shared

https://docs.google.com/document/d/16phGnd-hd2GcN118Irn1ccpm-4JqBB9wfBVB9cXDIIo/edit#

---


Mohan Krishna Gundala
[image: https://]about.me/gmk.india
<https://about.me/gmk.india?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by aslakhellesoy** [comment]
Here is another one: https://github.com/wesovilabs/gherkinize by @ivancorrales

I'll let everyone in this issue know when gherkin-lint is open for contribution - been busy doing other things (such as adding event protocol support to gherkin, which will simplify gherkin-lint architecture considerably)

**Comment by igas** [comment]
@aslakhellesoy it's great that you are working on consolidation of linters. Thanks for all your work. Do you have any project updates?

**Comment by aslakhellesoy** [comment]
I haven't made any progress I'm afraid. Too many other responsibilities.

**Comment by enkessler** [comment]
One more [gherkin linter](https://github.com/funkwerk/gherkin_lint). This is one is also in Ruby but is actively maintained.

**Comment by DwordPtr** [comment]
As I created the issue above. I am interested. How much work/process would it take to bring the gherkin-lint npm package into the monorepo?

Doubtless there will be stuff we don't like but having a starting spot that already works. 

Goes without saying I don't mind helping out where I can (and am qualified to)

**Comment by enkessler** [comment]
Setting aside the risk of my participation giving the project the touch of death, I remain more than happy to help in a limited capacity (I've never made an NPM package before).

**Comment by DwordPtr** [comment]
I made a [super simple one](https://www.npmjs.com/package/git-config-display-demo) to try it out.  The tooling is pretty nice. The hardest part is knowing what the ast will look like in a dynamically typed language.
