### ISSUE TITLE
cucumber-messages: user message with "Attachments"

### ISSUE THREAD

**Issue by SabotageAndi** [cucumber/cucumber#591]
## Summary

A lot of users of the SpecFlow+Runner want to add screenshots to their report. As cucumber-messages will be the datastruct for the formatters, which are used for reporting.
Currently there is no message that can be provided by the user. Ideally it can contain one to many attachments/files.

## Expected Behavior

User can send custom messages with attachments that are processed by the formatters.

## Current Behavior

There is no message for this.

## Possible Solution

Add an additional message type to https://github.com/cucumber/cucumber/blob/master/cucumber-messages/messages.proto

## Context & Motivation

Users want custom messages and images in their report.

**Comment by aslakhellesoy** [comment]
There is already an `Attachment` message in https://github.com/cucumber/cucumber/blob/master/cucumber-messages/messages.proto

**Comment by SabotageAndi** [comment]
https://github.com/cucumber/cucumber/blob/master/cucumber-messages/messages.proto#L17 this one (index 4)?

I understand the proto definition so, that this is only a file. There isn't a message field.

**Comment by aslakhellesoy** [comment]
If you want to add a screnshot, send a `Wrapper` message wrapping an `Attachment` message with the screenshot data (probably base64 encoded).

Sorry if I misunderstood the question.

**Comment by aslakhellesoy** [comment]
@SabotageAndi is there anything that is preventing you from using the existing `Attachment` message to embed screenshots?

**Comment by SabotageAndi** [comment]
Sure, we can use Attachment for the image.
I had image + text as one message in my head, but these will be 2 messages.

image = Attachment, with media = image/png
text = Attachment, with media = text/plain

**Comment by aslakhellesoy** [comment]
Exactly. Can I close this issue then?

**Comment by SabotageAndi** [comment]
Done
