### ISSUE TITLE
Pluggable behaviour / extension points

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#595]
Users often request new features that would make it behave differently. Such as:

* Run Background only once
* Run scenarios many times (regression testing)
* Pull in tables from Excel sheets
* Etc etc

Catering to all of those requests would turn Cucumber into a Frankenstein's monster. It would also increase the complexity of the codebase and configuration options and make it harder to maintain and use.

Instead of doing this, we may add "extension points" where users can plug into various parts of Cucumber and implement custom behaviour. This ticket is a place to gather all these suggestions, so we have a better idea what extension APIs to provide when/if this becomes a priority.

**Comment by jacek99** [comment]
Thank you for this. 

If there is any suggestion on how you think this could be accomplished, I would be glad to get involved and help with this.

**Comment by jacek99** [comment]
A high level technical design and suggestion on where those extension points could be added in the code would be very useful, I could dig into the code more from that point on.

**Comment by aslakhellesoy** [comment]
Controlling whether or not a Background is run for a scenario can be solved in two ways:

The first option is to control this at the Gherkin level, when a Gherkin AST is "compiled" to pickles. A pickle is a "test" which consists of a list of steps where any background steps are "inlined".

The second option is to control this at the Cucumber level, where Cucumber chooses not to execute certain steps.

I think the first option is the cleanest option. This would mean implementing a new compiler. The compiler is simple: https://github.com/cucumber/gherkin-java/blob/v5.1.0/src/main/java/gherkin/pickles/Compiler.java

The next version of Cucumber-JVM will use Gherkin 6, which uses a different API. In order to implement "Run Bacground Once" we could expose an API to plug in your owj Gherkin compiler.

**Comment by jacek99** [comment]
OK, let me check into that. When is the Gherkin 6 support coming in?
Would seem prudent to use that as the starting point.

**Comment by aslakhellesoy** [comment]
We don't do ETAs or estimates (since nobody does this on paid time), so I have no idea when Gherkin 6 will land in Cucumber-JVM.

Gherkin 6 is released, but integrating it into Cucumber-JVM is a very big effort (some background [here](https://docs.google.com/document/d/12Y3Ut-SVSGdw9L_aW6NGQY9JaCcn3z0alY4d7kzOndU/edit#))

I don't think I can even start thinking about how to provide this extension point until Gherkin 6 has landed in Cucumber-JVM. Maybe this summer, maybe next summer, maybe never.

**Comment by jacek99** [comment]
OK, so let me look at the current infrastructure and understand it.
