### ISSUE TITLE
Problem with cyrillic symbol И

### ISSUE THREAD

**Issue by PositiveAlex** [cucumber/cucumber#6]
1. I have feature
2. set up # encoding: utf-8 (and encoding of feature file is utf-8)
3. I run my step with parameter "some string with И symbol"
4. but when step code runs, it gets currupted parameter value inside.

`some string with �? symbol`
1. let's test all cyrillic letters on keyboard: 

`йцукенгшщзхъфывапролджэячсмитьбю.ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМ�?ТЬБЮ,`
1. As you can see, the problem appears only on И symbol and only in uppercase.

Seems like a bug...

ruby -v
ruby 2.0.0p643 (2015-02-25) [i386-mingw32]

cucumber --version
2.0.2

64bit operating system, windows 7

**Comment by aslakhellesoy** [comment]
Please create an issue in the cucumber-ruby project, ideally supplemented by a PR with a failing test
