### ISSUE TITLE
Rule support - documentation and update diagram

### ISSUE THREAD

**Issue by ttutisani** [cucumber/cucumber#602]
I'm referencing the AST diagram provided on this page: https://github.com/cucumber/cucumber/tree/master/gherkin

It does not mention the support for `Rule` in it, and so it's unclear how exactly to use it.
Please provide the `Rule` documentation if it's already supported (I heard it's supported already?).

**Comment by luke-hill** [comment]
Just as an update `Rule` is something which is only experimentally supported at the moment whilst all of the relevant language bindings work towards the next major release of cucumber.

There is a little bit of information dotted around. More will be forthcoming once more of it is nailed on.

**Comment by ttutisani** [comment]
Hi guys,

I just tried to upgrade to Gherkin 6 and I see that there is a big difference between what the AST diagram (https://github.com/cucumber/cucumber/tree/master/gherkin) shows and what the code looks like. I am rolling back the version upgrade because it's very confusing for me without knowing which classes I need to use instead of old ones (e.g., `ScenarioOutline` and `ScenarioDefinition` are gone and I don't see anything that would replace them).

It would help a lot if you could provide the updated AST diagram at least so that I understand how to handle the new classes and so on.

I am using Gherkin in .net core.

**Comment by SierraNL** [comment]
I would also like to see some guidance for upgrading from Gherkin 5.* to 6.*.
I understand that ScenarioOutline is now the same a Scenario, but what about ScenarioDefinition?

**Comment by mpkorstanje** [comment]
@SierraNL the AST  described as part of the Cucumber messages:

https://github.com/cucumber/cucumber/blob/master/messages/messages.proto#L170

`ScenarioDefinition` was a super class of `Scenario` and `ScenarioOutline`. Because they've been merged this type doesn't exist any more.
