### ISSUE TITLE
Java System.setProperty("cucumber.options", "--features <path>) is not working

### ISSUE THREAD

**Issue by VivekLande** [cucumber/cucumber#609]
Hello,
I am using Cucumber for JAVA (Cucumber-JVM)
I wanted to conditionally set 'features' files directory path for which I am trying to use
System.setProperty("cucumber.options", "--features <path>), but it is not working.
while same time setting for 'tag' with the same way as System.setProperty("cucumber.options", "--tags <tags>) is working.
Can you please help us to resolve this.
Thanks.

**Comment by tommywo** [comment]
Hello @VivekLande 
Try to specify your feature path without `--features` prefix.

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
