### ISSUE TITLE
Question about generating step file with reference language (english) functions names from translated Gherkin (french).

### ISSUE THREAD

**Issue by eric-gagnon** [cucumber/cucumber#614]
## Summary

Generating step file using reference language (english) from translated Gherkin (french).

See https://github.com/Codeception/CodeceptJS/issues/1647

Codeceptjs use Gherkin and have it's own command to generate the step file. The problem I have is that the generated code is using the attribute type to generated the function name so I get a unusable french function name.

```
      return `
${step.keyword}('${step}', () => {
  // From "${step.file}" ${JSON.stringify(step.location)}
  throw new Error('Not implemented yet');
});`;
```
So I get

```
Alors('je vois une licorne', () => {
  // From "codeceptjs-e2e\features\setup.feature" {"line":14,"column":1}
  throw new Error('Not implemented yet');
});

```
Instead of 

```
Then('je vois une licorne', () => {
  // From "codeceptjs-e2e\features\setup.feature" {"line":14,"column":1}
  throw new Error('Not implemented yet');
});
```
The generated ast from Gherkin parser look like this
```
Loaded 1 files
{ type: 'GherkinDocument',
  feature:
   { type: 'Feature',
     tags: [],
     location: { line: 2, column: 1 },
     language: 'fr',
     keyword: 'Fonctionnalité',
     name: 'test gherkin',
     description: undefined,
     children: [ [Object], [Object], [Object] ] },
  comments: [] }
[ { [String: 'je vois une licorne']
    type: 'Alors',
    location: { line: 14, column: 1 },
    file: 'codeceptjs-e2e\\features\\setup.feature' } ]
Snippets generated: 1
```
Is there a predefined way to get the reference language type identifier from a localised one (or another way to use the parser?)

I will try to figure it out but would gladly take a pointer as I'm new to Gherkin.

Thanks,

Eric

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by eric-gagnon** [comment]
Ok, thanks sorry for missing that one.

**Comment by aslakhellesoy** [comment]
No problem :-)
