### ISSUE TITLE
cucumber-expressions: Missing releases in NPM

### ISSUE THREAD

**Issue by badeball** [cucumber/cucumber#618]
## Summary

There seems to be a bunch of tagged releases of `cucumber-expressions` that haven't been published on NPM. Is this intentional or have they merely been forgotten?

- https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv6.1.1
- https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv6.1.2
- https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv6.2.0
- https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv6.2.1
- https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv6.2.2
- https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv6.2.3

## Expected Behavior

`npm install cucumber-expressions@6.2.3` shouldn't fail.

## Current Behavior

```
$ npm install cucumber-expressions@6.2.3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cucumber-expressions@6.2.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/..../.npm/_logs/2019-05-23T12_58_54_446Z-debug.log
```

**Comment by aslakhellesoy** [comment]
Our release process was broken for a while without anyone noticing. 7.0.0 is there, and hopefully future releases will not have this problem.

**Comment by badeball** [comment]
I see. I was hoping to make use of 77d5831f8b610f57bec7440f796156c33ffb4919, but [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) currently has `cucumber-expressions` locked to `^6.0.1`. Is it possible to release the other versions manually?

**Comment by aslakhellesoy** [comment]
Not sure what's going on here. I tried publishing again and got this:

```
✨  Done in 0.79s.
error Couldn't publish package: "https://registry.yarnpkg.com/cucumber-expressions: You cannot publish over the previously published versions: 6.0.1."
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

Looks like it *was* published but then it disappeared from npm?

**Comment by aslakhellesoy** [comment]
Oh wait a minute, 6.0.1 *is* on npm, but you're asking for the versions above? That's not semver-compatible with `^6.0.1` though.

Please clarify what exact version you need.

**Comment by aslakhellesoy** [comment]
My point is, I could publish `6.1.1` - `6.2.3`, but that won't get picked up by `^6.0.1` - only `6.0.X` will.

**Comment by badeball** [comment]
Are you sure about that? I believe carrot matches on minor, while tilde matches on patch, as shown below.

```
require('semver').satisfies("6.2.3", "^6.0.1") // => true
require('semver').satisfies("6.2.3", "~6.0.1") // => false
```

**Comment by aslakhellesoy** [comment]
You are right - got ^ and ~ mixed up :-)

I just released 6.6.2 on npm. Will that work for you?

**Comment by badeball** [comment]
Yes, thank you so much! :tada: :heart:

**Comment by aslakhellesoy** [comment]
Fett - bare hyggelig :-P
