### ISSUE TITLE
Co-related example tables

### ISSUE THREAD

**Issue by SSMaruvada** [cucumber/cucumber#623]
## Summary

No construct available to use multi-level examples.

## Context & Motivation

Consider a simplistic scenario where I have two sets of related data that I need to verify in a scenario, how can I define them in a readable way and also link them through reference column(s) during scenario execution? Not trying to build a RDBMS within the examples but just want to group related information while presenting it in a clean-readable format.

Please note that: 
- there could be many more columns,
- they can be combined into one examples table which I am trying to avoid due to the large and varying number columns in second table ( 1- many mapping)

| Order Number | Name      | Address                       | Date            |
| O1                    | Peter       | 101 Main street, PA     | 05/01/2019 |
| O2                    | John        | 111 Dale Ave, CA        | 05/01/2019 |
| O3                    | David      | 233 ZizZag street, NY  | 05/01/2019 |

| Order Number | Product Name           | Quantity | Unit Price |
| O1                    | Wiper Blades - 16-B  | 200         | 3.54          |
| O1                    | Wiper Blades - 16      | 400         | 2.26          |
| O2                    | Wiper Blades - 22      | 1400       | 1.92          |
| O2                    | Wiper Blades - 26      | 800         | 2.11          |
| O2                    | Wiper Blades - 16      | 900         | 2.26          |
| O2                    | Wiper Blades - 16-B  | 400         | 3.54          |
| O3                    | Wiper Blades - 16      | 1200       | 2.26          |

## Current Behavior

- Tried two examples but it executes them sequentially, getting nulls until the second table is read.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
