### ISSUE TITLE
gherkin 6(JavaScript): differientiate between scenario and scenario outline

### ISSUE THREAD

**Issue by xgbuils** [cucumber/cucumber#627]
Given a feature with a scenario:
``` gherkin
Feature: feature name
Scenario:
```
And other with a scenario outline:
``` gherkin
Feature: feature name
Scenario Outline:
```
There is not an easy way to differentiate if the parsed scenario is outline or not.

Scenario:
```
FeatureChild {
   scenario: 
    Scenario {
      tags: [],
      steps: [],
      examples: [],
      location: Location { line: 2, column: 1 },
      keyword: 'Scenario' } }
```
Scenario Outline:
```
FeatureChild {
   scenario: 
    Scenario {
      tags: [],
      steps: [],
      examples: [],
      location: Location { line: 2, column: 1 },
      keyword: 'Scenario Outline' } }
```

## Motivation:
Differentiating between scenario types is necessary for [gherkin-lint](https://github.com/vsiakka/gherkin-lint) which applies rules over scenario outlines (`no-scenario-outlines-without-examples` rule) that are not applicable over simple scenarios.

## Possible Solution
As you can see, we can differentiate scenario types using keyword property. However, the keyword depends on the used language and we can't rely on that. gherkin@5 also exports a `DIALECTS` object that could be useful for get the scenario type based on scenario keyword. But I don't think it's the best solution.

Could it be possible adding a type prop in scenarios for differentiating between scenario types?

## Environment

* Version used: gherkin@6 vs gherkin@5
* Operating System and version: Linux 64-bit - Ubuntu 18.04

**Comment by xgbuils** [comment]
Any update about it?

**Comment by aslakhellesoy** [comment]
As of Gherkin v6, `Scenario` and `Scenario Outline` are synonyms. They have the same AST type. The way we determine whether or not a scenario is an "outline" is to see whether or not it has `Examples` underneath. For example, the pickles compiler uses [this strategy](https://github.com/cucumber/cucumber/blob/731f7ae31c7aa0227014d64f2be94d4c49455b1f/gherkin/go/pickles.go#L71) when it compiles the AST to pickles.

With this design, the  `no-scenario-outlines-without-examples` rule is obsolete.

See the [6.0.13 CHANGELOG](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#6013---2018-09-25)

**Comment by xgbuils** [comment]
Thanks @aslakhellesoy
