### ISSUE TITLE
Named output hook

### ISSUE THREAD

**Issue by RobertoPegoraro** [cucumber/cucumber#633]
cucumber-jvm: Named output hook

I need to be able show personalized output in reports.
I have created the implementation to be able to add name in scenario.write (https://github.com/cucumber/cucumber-jvm/pull/1657), the implementation is in cucumber-jvm but according to @mpkorstanje it would need to be replicated to other projects, what do you think of this new feature?

**Comment by mpkorstanje** [comment]
So given @aslakhellesoy  reply I think this unlikely to happen. You may have to maintain your own implementation of the JSON formatter.

https://github.com/cucumber/cucumber-jvm/issues/1661#issuecomment-501259804
> We're going to deprecate the JSON formatter in favour of a new message protocol:
> 
>     * https://github.com/cucumber/cucumber/tree/master/cucumber-messages
> 
>     * https://docs.google.com/document/d/12Y3Ut-SVSGdw9L_aW6NGQY9JaCcn3z0alY4d7kzOndU/edit#
> 
> 
> We might build a tool that can consume the new message protocol and create a cucumber JSON file, but we'll encourage people to start using the new message protocol instead.
> 
> It's probably 6-12 months away before we see the protocol implemented in all Cucumbers, but I wouldn't recommend putting more work into the current JSON formatter at this point.
