### ISSUE TITLE
DataTable.unorderedDiff is not symmetric and does not take row count into account

### ISSUE THREAD

**Issue by tvo** [cucumber/cucumber#646]
## Summary

`DataTable.unorderedDiff` semantics are ill-defined and arguable wrong

## Expected Behavior

I was expecting that `unorderedDiff`:

 * is symmetric, i.e. `a.unorderedDiff(b)` behaves the same as `b.unorderedDiff(a)` except that +/- signs are swapped in the output when a and b are different,
 * either behaves as an actual set difference, or (much better) as a multiset difference, i.e. given the current name, I'd expect it to throw if one datatable has 10 equal records and the other datatable has 1 record, also equal to those 10 records.
 * outputs diffs that include the correct number of +/- lines.

## Current Behavior

Currently, it is neither symmetric, nor behaves like set difference nor multiset difference.

Specifically, for `a.unorderedDiff(b)`, if b has more equal records than a, it throws, but if a has more records than b, it passes. Thus, it's not symmetric and only behaves like set difference in one direction.

~~~
~~~

## Possible Solution

I may come up with something later, but I think at least someone ought to decide on what the semantics should be, and then the method can be fixed to stick to those semantics.

I think making it a symmetric multiset difference reduces surprises the most, given the name, but obviously that makes it stricter than the current behavior, so it would be a breaking change. 

Alternatively, it may be an idea to deprecate this method and add new methods with more well defined semantics, e.g. `setDiff` and `multisetDiff`, the first disregarding both order and count, and the second only disregarding order.

## Steps to Reproduce (for bugs)

This code shows some of the inconsistencies:

```java
  private static final DataTable DT1 = DataTable.create(ImmutableList.of(
      ImmutableList.of("foo"),
      ImmutableList.of("bar")
  ));

  private static final DataTable DT2 = DataTable.create(ImmutableList.of(
      ImmutableList.of("foo"),
      ImmutableList.of("foo"),
      ImmutableList.of("bar"),
      ImmutableList.of("bar")
  ));

  private static final DataTable DT3 = DataTable.create(ImmutableList.of(
      ImmutableList.of("foo"),
      ImmutableList.of("bar"),
      ImmutableList.of("bar"),
      ImmutableList.of("bar")
  ));

  @Test public void testDirection1() {
    DT1.unorderedDiff(DT2); // throws as expected
  }

  @Test public void testDirection2() {
    DT2.unorderedDiff(DT1); // passes despite the tables being different
  }

  @Test public void isItEvenASetDifference() {
    DT2.unorderedDiff(DT3); // throws despite Set(DT2) == Set(DT3)
    // also prints a diff that seems to suggest one of the tables should have 5 records?!?
  }
```

## Your Environment

* Version used: datatable-1.1.12 / cucumber 4.4.0

**Comment by tvo** [comment]
If the desired semantics should be a diff that disregards order, but takes cardinality into account, then an approach like this may be the solution:

```
public static void unorderedDiff(DataTable expected, DataTable actual) {
    // Sort actual rows by their index in expectedRows. This lets us use an ordered diff, with the
    // nice side effect that the printed diff, if any, is in the same order as the expected rows.
    var expectedRows = expected.cells();
    var actualRows = new ArrayList<>(actual.cells());
    actualRows.sort(Comparator.comparing(o -> {
      int index = expectedRows.indexOf(o);
      return index == -1 ? Integer.MAX_VALUE : index;
    }));
    expected.diff(DataTable.create(actualRows));
  }
```

**Comment by mpkorstanje** [comment]
> I think making it a symmetric multiset difference reduces surprises the most, given the name, but obviously that makes it stricter than the current behavior, so it would be a breaking change.

Agreed.

Good thing is that Cucumber JVM v5 is on the horizon. Barring any unexpected events sometimes around September. 

So now would be a good time to make this change. Would you like and be able to make a PR?

**Comment by tvo** [comment]
Yeah, I can take a stab at it!

**Comment by mpkorstanje** [comment]
Cool! If you need java8 feel free to use it. V5 will be java 8.

**Comment by tvo** [comment]
Turns out the implemented logic was almost correct -- I just had to do the containment check on `extraRows` so that each row in `to` can only be used once. Added a test that failed with the original implementation and s/diff_set/unordered_diff/g test method name prefix.

**Comment by tvo** [comment]
Shall I close this, now that the fix has been merged? Or do you keep issues open until the fix has been released?

**Comment by mpkorstanje** [comment]
Forgot about it. There is an issue in cucumber-jvm to track this now.
