### ISSUE TITLE
Only suggest parameter types when text is surrounded by whitespace

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#657]
Imagine the following parameter type is defined:

```ruby
ParameterType(
  name: 'direction',
  regexp: /(up|down)/,
  transformer: ->(s) { s }
)
```

This could be used with the following step definition:

```ruby
When("the sun goes {direction}") do |direction|
end
```

However, if we add two new undefined Gherkin steps:

```gherkin
Given the sun has gone down
When Aslak downloads a picture
```

That should suggest:

```ruby
Given("the sun has gone {direction}") do |direction|
end
```

But it should *not* suggest:

```ruby
When("Aslak {direction}loads a picture") do |direction|
end
```

Instead, it should simply suggest:

```ruby
When("Aslak downloads a picture") do |direction|
end
```

Parameters should only be suggested when the text is surrounded by whitespace, or when it's at the beginning or end of the step. That's what users would expect.

**Comment by sebrose** [comment]
Perhaps an unintended consequence, but now numerical parameters with units are not recognised by the snippet generator:
Given Sean is 15m from Lucy -> "Sean is 15m from Lucy", but should be "Sean is {int}m from Lucy"

**Comment by vincent-psarga** [comment]
Maybe it could be interesting to have some built-in "units" type (`\d+(d|h|m|s`, `\d+(m|km)`, `\d+('|")`) but I think it would be pretty hard to have something easily translatable/portable for multiple languages.
