### ISSUE TITLE
messages: Go generated proto messages not checked in

### ISSUE THREAD

**Issue by dixonwille** [cucumber/cucumber#660]
## Summary

I think that the generated code from `messages.proto` should be checked into GitHub so that the go packages can be used in generators being created.

## Expected Behavior

I would expect for the latest gherkin parser to be "go gettable". 

## Current Behavior

Whenever I am trying to run `go get github.com/cucumber/cucumber/gherkin/go` to get the latest code the following is the output:

```
go: finding github.com/cucumber/cucumber/gherkin/go latest
go: finding github.com/cucumber/cucumber/cucumber-messages/go/v3 v3.0.0
go: github.com/cucumber/cucumber/cucumber-messages/go/v3@v3.0.0: unknown revision cucumber-messages/go/v3.0.0
go: error loading module requirements
```

## Possible Solution

Check the generated files into GitHub. You could have the CI check to see if the files have diverged by running the generator on the CI and then running `git diff` to see if there are any changes. If so don't allow that code in.

I understand this was done on purpose https://github.com/cucumber/cucumber/blob/master/cucumber-messages/go/v3/.gitignore suggest that. But since Go's "package repository" is GitHub (really any source control system) it needs all the files to be compilable (including generated files).

## Steps to Reproduce (for bugs)

1. Start a new go module. `go mod init some/package/path`
2. Run `go get github.com/cucumber/cucumber/gherkin/go` to add it to the `go.mod` file

## Context & Motivation

I am trying to create a generator that parses the gherkin syntax. https://github.com/cucumber/gherkin-go was updated but if you look at the `go.mod` file in that repo you will notice that it says the package import is actually in this repository not that. I think consolidating everything down to use gherkin-go is great (https://github.com/cucumber/cucumber/issues/425) but right now, even if I used precompiled binaries to create the proto message binary, I can not unmarshal it into the correct proto message as it is not published.

## Your Environment

* Version used: latest (go mods is using its version of "latest" which usually mean last tagged)
* Operating System and version: Mac OS 10.14.5
* Link to your project: Not Public

**Comment by aslakhellesoy** [comment]
We used to have them checked in actually (for all languages). I agree we should add them back for go.

**Comment by aslakhellesoy** [comment]
Fixed on master!
