### ISSUE TITLE
Handling nested groups in regular expression for backward compatibility in Cucumber 4

### ISSUE THREAD

**Issue by Shiridish-BK** [cucumber/cucumber#666]
My project used info.cukes.cucumber-java 1.2.4 and several steps (500+) were written so far with a regular expression pattern for step definitions like in below sample.

```
@When("^(Hello (.*))$")
    public void sampleMethod(String stepText, String input){
 } 
```
As you can see, I have nested groups, one to get the step text and second for the input. The stepText parameter is used while reporting in my custom reporter class.

Recently I started migrating to the io.cucumber.cucumber-java 4.3.1 and see that with the introduction of Cucumber Expressions in Cucumber 3, nested groups are no longer directly supported in regular expression patterns. I see some issues were also reported - [375](https://github.com/cucumber/cucumber/issues/375) and some blogs such as [this](https://makandracards.com/makandra/72371-cucumber_factory-how-to-keep-using-cucumber-2-transforms-in-cucumber-3) and [this ](https://cucumber.io/blog/announcing-cucumber-jvm-3-0-0/) discuss about it.

Currently, it looks like I either have to change the regular expressions of all my existing step definitions to remove nested groups and modify the method signature accordingly, or either change to cucumber expressions. Both of these approaches can be cumbersome and can have potential unforeseen end-user impact.

Looking for any solutions to handle this smoothly.

**Comment by Shiridish-BK** [comment]
Thanks for the response. We used the Formatter interface as well to handle reporting in v1. However, for additional logging and reporting within the step definitions, the step text was captured as mentioned above which is now causing problems with our migration. I'd keep this ticket open to look for any more suggestions.

**Comment by luke-hill** [comment]
A solution (But *not* a good one), is to implement each step as a unique cukeexp, with arity of 1 around the whole step which is then passed to your reporter, and then whatever other captures as required.

This is very much a bazooka approach though, and I would avoid it if at all possible. Also you could just use normal regex (I know you've linked to some possible failures, are these still not working in your version of cucumber?)

**Comment by mpkorstanje** [comment]
I do not believe it is possible to solve this. With the way parameter types work converting anything but the top level capture groups into `Argument` objects is going to lead to strange behaviour.

@Shiridish-BK if you are still in need of this and can come up with a solution feel free to suggest one. However given that you are using this mostly for reporting purposes I believe you may be better of investing your time in using Cucumbers plugin system.
