### ISSUE TITLE
Cucumber Custom Plugin cause no feature read

### ISSUE THREAD

**Issue by peterwkc85** [cucumber/cucumber#674]
## Summary
I wrote a custom plugin to initialize chrome and firefox web driver causes no feature file been executed. 

## Expected Behavior
Feature File executed
Chrome open and close
Firefox open and close

## Current Behavior
Feature File no executed
Chrome open but no close
Firefox open but no close

## Possible Solution
No

## Steps to Reproduce (for bugs)
Attach google drive code 

## Your Environment
* Version used: Cucumber 4.2
* Operating System and version: MS Windows 10
* Link to your project: https://drive.google.com/open?id=1ycwBNZi9st-dkmdDfKaBxqU2mLchRWfM

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.

**Comment by mpkorstanje** [comment]
If you do think it's a bug please follow these guidelines and make sure to describe the problem beyond it doesn't work.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by peterwkc85** [comment]
This is a strange issue where creating custom plugin cause no cucumber being read. Thus, it is consider a bug.
