### ISSUE TITLE
Option for Cucumber Expression or RegEx in generated snippet

### ISSUE THREAD

**Issue by kathyrollo** [cucumber/cucumber#678]
## Summary

New option in `@CucumberOptions` in runner class.

## Expected Behavior

Can choose between Cucumber Expression or the usual regex when generating snippets.

## Current Behavior

Only generates Cucumber Expressions since 3.x.x (I believe).

## Possible Solution

Something like:
```
@CucumberOptions(... , snippets = SnippetType.UNDERSCORE, annotation = AnnotationType.REGEX)
public class RunCukesTest extends AbstractTestNGCucumberTests { // or JUnit
}
```

## Context & Motivation

Useful to be able to generate both annotations. Though less intuitive, regex can handle complex matching conditions if need be.

**Comment by mpkorstanje** [comment]
I've moved this to the mono repo. This would require a change to the way cucumber expressions generate its expressions.

**Comment by aslakhellesoy** [comment]
I'm closing this as nobody has volunteered to do it. It's not a priority.
