### ISSUE TITLE
export typescript types for subrepos like (cucumber-expressions)

### ISSUE THREAD

**Issue by npenin** [cucumber/cucumber#683]
## Summary

Can you please add declarations to the published packages and reference them from the package.json file so that vscode and typescript can identify them ?

**Comment by aslakhellesoy** [comment]
Could you please provide a pull request? AFAIK they all have exported types, e.g:

https://github.com/cucumber/cucumber/blob/812d837922b3b352548d2d2151853976a60ea2c0/cucumber-expressions/javascript/package.json#L6

**Comment by npenin** [comment]
i have just seen it was published with new packages from few days ago
