### ISSUE TITLE
Replacing the translated keyword "background" in turkish language

### ISSUE THREAD

**Issue by pLotoniC** [cucumber/cucumber#704]
The keyword "background" is not really "Geçmiş" in this context. It should be "Temel" or "Zemin", which is much more meaningful. In german language "backround" is equivalent to "Grundlage", which is exactly "Temel" or "Zemin" in turkish language.

**Comment by aslakhellesoy** [comment]
I've moved this to the cucumber repo. If anyone wants to send a PR it would be agains `gherkin/gherkin-languages.json`

**Comment by pLotoniC** [comment]
Yes, I'm a native speaker. I'll create a PR in a few days. Thanks for your effort.
