### ISSUE TITLE
Cucumber integration with aws codepipeline

### ISSUE THREAD

**Issue by foobar123-del** [cucumber/cucumber#710]
Is it possible to integrate cucumber with aws codepipeline
if yes please provide some documentation or high level overview

**Comment by aslakhellesoy** [comment]
We should add a `continuous-integration` page explaining how to run Cucumber.

**Comment by derwasp** [comment]
@foobar123-del I will not exactly answer your question, but maybe it will be something interesting for you.
We are not using CodePipeline, but CodeBuild and we have a JUnit4 based runner of Cucumber tests in parallel.
You can check out a demo project [here](https://github.com/albumprinter/junit-synnefo-demo) or an article about it [here](https://medium.com/@denys.zhuravel/synnefo-running-cucumber-jvm-tests-in-parallel-in-aws-codebuild-bc80646c0c70).
