### ISSUE TITLE
Use protobuf instead of ndjson in gherkin acceptance tests

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#712]
It's currently possible to pass the Gherkin acceptance test suite without implementing support for cucumber-messages (protobuf).

By making the test suite compare binary protobuf output instead of ndjson we'd be forcing implementations to implement cucumber-messages.

This may sound a little strict, but I think it is the right thing to do in order to achieve better platform compatibility and interop with e.g. standalone formatters such as the new [html-formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter) and [json-formatter](https://github.com/cucumber/cucumber/tree/master/json-formatter).

I propose we start a `gherkin-protobuf-tests` branch where we collaborate on bringing gherkin-dotnet and gherkin-perl uptodate. gherkin-java, gherkin-javascript and gherkin-ruby already are.

WDYT @ehuelsmann @gasparnagy @SabotageAndi ?

**Comment by SabotageAndi** [comment]
As said on Slack, it is on our backlog. It will happen when we implement the rest of the cucumber-messages.

**Comment by ehuelsmann** [comment]
Yea. I'll work on adding that functionality to gherkin-perl. Since it requires an external dependency (which needs to be made available outside the Perl ecosystem), I'd like to make it optional though: the JSON libraries we currently depend on are based on C code too, but that comes with those libraries themselves and gets built upon installation on the target (which makes them much easier to install from "inside the Perl ecosystem").

**Comment by aslakhellesoy** [comment]
@ehuelsmann we have removed the dependency on the protobuf stdlib `Timestamp` and `Duration` and replaced them with our own implementation. Isn't that what stopped you from using a perl protobuf library?

We could also make it optional and officially allow [ndjson](http://ndjson.org/) encoding instead of varint-separated protobuf binady messages. Parsing JSON into messages seems to be supported by most implementations.

**Comment by ehuelsmann** [comment]
The `Timestamp` and `Duration` were indeed a limitation of the Perl protobuf library. With those removed, that library will now work and I'll see how to fit the `cucumber-messages` Perl library into the mono-repo.

My point is more that the Perl library which adds the [protobuf support (Google::ProtocolBuffers::Dynamic)](https://metacpan.org/release/Google-ProtocolBuffers-Dynamic)  itself depends on `libprotobuf` being available. The Perl ecosystem doesn't know how to install it when it's missing.
On the other hand the JSON libraries Gherkin-Perl depends on [(JSON::PP or JSON::XS)](https://metacpan.org/pod/JSON::MaybeXS) are either pure Perl (no dependencies at all) or C-code-distributed-with-the-Perl-Library (XS code); the latter depends on a C compiler being available at installation time, but no external libraries. By consequence I estimate that it adds value (simplifies the Perl Gherkin installation) if we support JSON always and strongly recommend installation of `libprotobuf` for full compliant support, but that we don't *fail* when it's not there. (i.e. making it optional).

**Comment by aslakhellesoy** [comment]
All of that makes sense to me @ehuelsmann 👍
