### ISSUE TITLE
Feature Request: Nested steps

### ISSUE THREAD

**Issue by amitguptagwl** [cucumber/cucumber#713]
## Summary
When I select a particular section and next 4-5 steps are related to the selected section only, I need to repeat some phrase to identify the section

```Gherkin
And calculator is visible
When I click 3 in calculator
And  I click + in calculator
And  I click 5 in calculator
And  I click = in calculator
Then I should see 8 as result in calculator
```

I need not repeat the phrase if the steps are unique or if they are in scope step definition file. 

<small>Please note that it is just an example to describe the problem.</small>

## Expected Behavior
We can write context aware steps

## Current Behavior
Currently all the scenario steps are unique and has no context information

## Possible Solution

Indented steps

```Gherkin
And calculator is visible
   When I click 3
   And  I click +
   And  I click 5
   And  I click =
   Then I should see 8 as result
```
or steps with special keyword

```Gherkin
And calculator is visible
Within When I click 3
Within And  I click +
Within And  I click 5
Within And  I click =
Within Then I should see 8 as result
```

**Comment by luke-hill** [comment]
This feels more like an API specific context you require and not cucumber.

If you're using cucumber ruby you can scope within a section (Assuming you are doing browser automation), using the API there, for example capybara or selenium webdriver.

Also you shouldn't have steps that define a specific portion of code, your steps should describe behaviour. So something like `When I type 3+5 into the calculator` or suchlike.

I'm closing this as a non-issue. There is some further reading you can do on the docs, specifically the "not-cucumber" portion here: https://cucumber.io/docs/community/not-cucumber/
