### ISSUE TITLE
cucumber-expressions js: error in node 8

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#725]
## Summary

The javascript version of cucumber-expressions does not work on node 8

## Expected Behavior

I expect the javascript version of cucumber-expressions to work on all supported node versions. Currently only 8, 10, 12

## Current Behavior

Error as seen in the screenshot.

<img width="998" alt="cucumber-expressions-node-8-error" src="https://user-images.githubusercontent.com/1676758/66085548-c6518b80-e52e-11e9-86fe-ed09fcedb6dd.png">

~~~
~~~

## Possible Solution

Appears `\p` is not supported in node 8. Can we switch to something that is supported? Can't currently find documentation as to what regex meta characters are supported on each node version

## Steps to Reproduce (for bugs)

1. Clone cucumber-js repo
2. Update cucumber-expressions to node 8
3. Run `yarn test`
4. See error in screenshot

## Context & Motivation

cucumber-js wants to support all maintained node versions.

## Your Environment

* Version used: cucumber-expressions v8.0.0
* Operating System and version: mac 10.14.6
* Link to your project: https://github.com/cucumber/cucumber-js

**Comment by aslakhellesoy** [comment]
We need to bring back testing on different node versions, which is a bit tricky in the current CircleCI setup. Need to think about this one...

**Comment by charlierudolph** [comment]
I don't think it'd be too difficult. Just need to add a couple more executors. I can try making that update if you'd like

**Comment by aslakhellesoy** [comment]
Ah of course - yes that would be great @charlierudolph !
