### ISSUE TITLE
cucumber-expressions: escaped nested parens

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#726]
## Summary

From cucumber/cucumber-js#1233. It appears escaped nested parens do not work with cucumber-expressions

## Expected Behavior

Can have a cucumber expressions of the form
`'r <- ray\\(point\\({int}, {int}, {int}), vector\\({int}, {int}, {int}))'`.

## Current Behavior
A step with a cucumber expression `'r <- ray\\(point\\({int}, {int}, {int}), vector\\({int}, {int}, {int}))'` does not match a step `Given r <- ray(point(2, 3, 4), vector(1, 0, 0))` and it instead suggests creating a step with the above cucumber expression.

Note: it appears escaping parens in cucumber expressions works as long as they are not nested. 

## Possible Solution

Unsure how complex this would be to implement or if we think this will be a limitation of cucumber-expressions

## Steps to Reproduce (for bugs)

1. Follow steps as outlined on cucumber/cucumber-js#1233

## Context & Motivation

Prevents a user from using cucumber-expressions when they would like to.

## Your Environment

* Version used: cucumber-expressions 7.0.2
* Operating System and version: mac 10.14.6
* Link to your project: https://github.com/cucumber/cucumber-js

**Comment by mpkorstanje** [comment]
To handle optionals we use a regex to find the pattern that we need to replace. It's only applied once so if there is an optional inside the optional the inner optional won't be escaped. Perhaps we can invoke it recursively?

https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpression.java#L83

**Comment by luke-hill** [comment]
I'll dive into this next week in ruby. It's likely an issue in all.

What happens if you only use regular captures. so `(\d+)` for example instead of the `{}`. Maybe something to do with that?

**Comment by mpkorstanje** [comment]
This will be fixed by https://github.com/cucumber/cucumber/pull/771
