### ISSUE TITLE
C# example is misleading

### ISSUE THREAD

**Issue by hendrik-w** [cucumber/cucumber#736]
Topic: cucumber/gherkin/README.md wrong C# example

## Summary
Tuning issue: README.md provides a C# example that does not work out of the box.

## Expected Behavior
As with in you readme: 
`// C#  
var parser = new Parser();  
var gherkinDocument = parser.Parse("Feature: ...");`

Parsing .feature file content as a string.

## Current Behavior

Gherkin.Parser has two Members:
`       public GherkinDocument Parse(TextReader reader);  
        public GherkinDocument Parse(string sourceFile);`

Second Parse method takes a string but as a path to the source file, not as the content of the .feature file.

## Possible Solution

Change README.md to the following:
`// C#  \
var parser = new Parser();  
var gherkinDocument = parser.Parse(@"C:\PathToGherkinFile\gherkinFile.feature");`

## Steps to Reproduce (for bugs)

Open README.md and try sample code in .NET environment.

## Context & Motivation

Just a tuning issue.

## Your Environment

* Version used: Gherkin 6.0.0.0 
* Runtime version: v4.0.30319

**Comment by luke-hill** [comment]
Hi @hendrik-w 

Do you feel comfortable maybe having a go at fixing it up? If you're a regular user this would be a great way to give back to the community.

Given it's a documentation issue, the turnaround time would be quite quick, and some of the folks at SpecFlow would probably be able to quickly review and approve

cc/ @SabotageAndi

**Comment by hendrik-w** [comment]
Hi @luke-hill,

sure, I'm happy to do that. I haven't had the time to check whether the other examples are correct, as I assume that the same problem exists there. I'll check it out this evening.

Cheers
Hendrik
