### ISSUE TITLE
Feature request: A Pickle Tree

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#753]
The introduction of Pickles removed the need for Cucumber implementations to interpret the structure of a Gherkin document. Pickles could simply be executed.

However with Pickles we also lost something. The users of Cucumber organizes their scenarios in a hierarchical structure and his hierarchy should be be reflected in their reports. 

For example a good rendition of a cucumber execution would be:

```
╷
└─ Cucumber ✔
   ├─ A feature with a single scenario ✔
   │  └─ A single scenario ✔
   ├─ A feature with scenario outlines ✔
   │  ├─ A scenario ✔
   │  └─ A scenario outline ✔
   │     ├─ Example #1 ✔
   │     ├─ Example #2 ✔
   │     ├─ Example #3 ✔
   │     └─ Example #4 ✔
   └─ A feature in classpath root ✔
      └─ A single scenario ✔
```

Removing some information, for example the outline makes the feature less clear:

```
╷
└─ Cucumber ✔
   ├─ A feature with a single scenario ✔
   │  └─ A single scenario ✔
   ├─ A feature with scenario outlines ✔
   │  ├─ A scenario ✔into tree structure. 
   │  ├─ A scenario outline ✔
   │  ├─ A scenario outline ✔
   │  ├─ A scenario outline ✔
   │  └─ A scenario outline ✔
   └─ A feature in classpath root ✔
      └─ A single scenario ✔
```

And going further by only rendering the pickle names we've lost most comprehension:

```
╷
├─ A single scenario ✔
├─ A scenario ✔
├─ A scenario outline ✔
├─ A scenario outline ✔
├─ A scenario outline ✔
├─ A scenario outline ✔
└─ A single scenario ✔
```

This shows that the hierarchy provides important context that helps understanding what a scenario is about. This is even more so true with the introduction of the Rule keyword in Gherkin 6. It adds new node type in the hierarchy.

To recreate this hierarchy Cucumber JVM and reporting tools for Cucumber need to have some understanding of the Gherkin AST. We could assist both providing pickles in a tree structure. 

By removing the need to recreate this pickle tree we can reduce the problem that Cucumber JVM and reporting tools need to solve. They'd only need to concern themselves with mapping the Pickle tree to their desired output (i.e. test structure or human report).

The implementation of the Pickle Tree wouldn't need to be very complicated. Adding a `List<Node> getChildren()` method to the `Node` class would allow us to easily visit the AST using recursive descent. The `location` of a node would let us match the node to the compiled pickles.

Adding a `getKeyWord` and `getDescription` to the `Node` class would provide sufficient information to create most intermediate nodes without being concerned out their exact semantics. For`TableRow` `getDescription` should return the row index.

**Comment by aslakhellesoy** [comment]
I might be tackling this one this week. I am moving some of the functionality from `CucumberQuery` into the Gherkin library (in a new `GherkinQuery` class) and as I am doing this it might make sense to do the tree too.

The reason I need to move some code into `GherkinQuery` is that `fake-cucumber` will need it to compute stack frames for `.feature` files, and we can't depend directly on `CucumberQuery` since its tests already depend on `fake-cucumber`.

**Comment by mpkorstanje** [comment]
No rush. I've got two use cases now, but they're covered by the compatibility layer for now.

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java#L181

Find the path from Feature --> Rule --> Scenario --> Example --> Pickle 

https://github.com/cucumber/cucumber-jvm/blob/master/junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureDescriptor.java#L39

Map the the elements in the pickle tree to another tree structure.
