### ISSUE TITLE
Implement usage formatter in Go

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#755]
Just like the [html formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter) and [json formatter](https://github.com/cucumber/cucumber/tree/master/json-formatter) we should implement a standalone `usage` formatter (in Go). 

It should implement the functionality from the existing implementations:

* [Java implementation](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/io/cucumber/core/plugin/UsageFormatter.java)
* [Ruby implementation](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/usage.rb).
* [JavaScript implementation](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/usage_formatter.js)

The motivation for doing this is that we need to remove the `UsageFormatter` from cucumber-jvm. The reason we need to remove it is that it's tightly coupled to Gherkin v5, and that makes it difficult to upgrade Cucumber-JVM to Gherkin 8. Another motivation is to reduce the amount of code we need to maintain across implementations.

/cc @mpkorstanje @vincent-psarga @charlierudolph

**Comment by charlierudolph** [comment]
The Java implementation links to the HTML formatter, was that intended? Also how does the cucumber-js usage formatter compare to these? Also cucumber-js has a usage-json formatter which is the usage data in json format.

**Comment by aslakhellesoy** [comment]
Hi @charlierudolph - Updated the Java link and also added a link to the JavaScript implementation.

I think there are two use cases for a usage formatter:
* Command line use - eyeballing the result in the terminal
* Editor use - consuming machine-readable output (JSON?) and implement "display/go to usage" shortcuts

So I think it would be nice to be able to specify either `--format=text` or `--format=json`.

For JSON, I think it would be nice to have a schema. Not having a schema for the JSON formatter has caused a lot of inconsistencies, and I'd rather not repeat that mistake.

Protobuf gives us a schema (and is also able to output JSON), so maybe this formatter could define the schema for its output with a `usage.proto` file?

**Comment by charlierudolph** [comment]
Yeah I think a usage.proto would be a good idea
