### ISSUE TITLE
Feature request: A Pickle Query API

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#764]
People who write plugins (us included) will need an easy way to map pickles back to AST nodes - the whole reason `TestSourcesModel` exists in Cucumber JVM. 

The API would have to provide a set of methods like `GherkinDocument.getStuffAtLine(int line)`. 

This API should be provided by Gherkin but neither Gherkin 5 nor Gherkin 8 provide anything like it. A stable representation in Java of the `GherkinDocument` decoupled from any parsing or messaging concerns should also make our lives a bit easier in terms of migration and upgrades.

In essence: a query API for each input AST to make it easier to look up AST nodes from pickles.

**Comment by aslakhellesoy** [comment]
I think this should be implemented in the `cucumber-messages` library, not in `gherkin`

**Comment by mpkorstanje** [comment]
Ah. I didn't realize they were shaded in to gherkin.

**Comment by aslakhellesoy** [comment]
`cucumber-messages` are not shaded in `gherkin`. The reason I think this belongs in `cucumber-messages` is that the logic operates directly on the messages, and I prefer to put logic close to the data.

**Comment by aslakhellesoy** [comment]
We have the `cucumber-query` lib for this now. I’m in the procesd of moving some of it into `gherkin`. Currently just for JavaScript (fake-cucumber needs it for stack traces). We’ll port to other languages when the dust settles.
