### ISSUE TITLE
gherkin/javascript: v5.x unsafe iteration over array (I have a fix, not sure how to open a PR for old version)

### ISSUE THREAD

**Issue by jmadson** [cucumber/cucumber#772]
## Summary

I have a separate 3rd-party library installed on a javascript/typescript project where we're using Cucumber v5 (via webdriver.io), which uses Gherkin v5.x. Unfortunately, this 3rd party library adds `flatten` to the `Array.prototype`. Normally, this wouldn't be an issue, but it's causing `Gherkin.generateEvents` to incorrectly pick up `flatten` as a Cucumber "pickle" when it iterates over the array. Since `flatten` is a function and not an object in the shape expected by Cucumber, this causes our e2e tests to fail.

## Expected Behavior

`Gherkin.generateEvents` should return the correct array of pickles when a .feature file is processed.

## Current Behavior

Gherkin v5.x incorrectly picks up functions added to the `Array` prototype when iterating over the array of pickles in `Gherkin.generateEvents`, causing it to incorrectly include those functions as pickles.

## Possible Solution

I have a solution available here: https://github.com/jmadson/cucumber/tree/fix-array-iteration
See commit: https://github.com/jmadson/cucumber/commit/0aadfd059e7c53bb90bc861a296aa92f2c9364c7

Note that branch is off of the `v5.2` git tag. I want to open a PR but I'm not sure which branch I should target, as this obviously would not get merged into `master`. There was no mention of how to open a PR for an old version track in the `CONTRIBUTERS.md` documentation.

## Steps to Reproduce (for bugs)

See the unit test I added here: https://github.com/jmadson/cucumber/commit/0aadfd059e7c53bb90bc861a296aa92f2c9364c7#diff-432dfdb22484f63723016aeb6fa76a6fR6

**Comment by jmadson** [comment]
@luke-hill Any advice on how I can open a PR for the above fix against the 5.x tag? Obviously I cannot point the PR at `master`

**Comment by aslakhellesoy** [comment]
Hi @jmadson - I think we'd first have to create a maintenance branch based on the [gherkin/v5.2.0](https://github.com/cucumber/cucumber/tree/gherkin/v5.2.0) tag, and then you could submit a PR against that branch.

However, I cannot guarantee that we'd prioritise merging it and making a new 5.x release as we're a small team with low capacity.

**Comment by aslakhellesoy** [comment]
I have created a `gherkin/v5` branch now, so you can target that for your PR. Thanks!
