### ISSUE TITLE
invalid option: -r

### ISSUE THREAD

**Issue by zedtux** [cucumber/cucumber#784]
Therefor there is an issue as I have always the following output at the end of the executing of my tests no matter the test pass or not:

````
invalid option: -r

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /pattern/ or string.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
````

This return a code different than 0 so mark my build as failed while it should not.

This behaviour seems to be since the use of the 2.0.0.beta.3. With my branch I don't have this issue.

**Comment by tooky** [comment]
@zedtux did you manage to create a minimal repository demonstrating this?

**Comment by zedtux** [comment]
Sorry @tooky I will try by tomorrow or during next week.

**Comment by tooky** [comment]
@zedtux that would be great. Thanks.

**Comment by zedtux** [comment]
@mattwynne @tooky I've tried to upgrade my brewformulas.org project to the latest version of all the gems, including the version `2.0.0.rc3` of Cucumber and I don't see the reported issue.

Or I don't have this issue in this project or the issue has been solved since.
I can try with the version `2.0.0.beta3` in order to check if the issue is present or not.

**Comment by zedtux** [comment]
Well I have this error with the beta 3:

> lib/cucumber/mappings.rb:208:in `<class:MapStep>': undefined method `initializer' for Cucumber:Module (NoMethodError)

**Comment by mattwynne** [comment]
Yeah that's probably because of an incompatibility in the new version of the core with that beta version of cucumber. To be honest, I suggest we just close this and move on with our lives. If it comes up again we can tackle it then.

OK with you @zedtux?

**Comment by zedtux** [comment]
I'm fine and I do it :)

**Comment by tooky** [comment]
Thanks @zedtux!
