### ISSUE TITLE
Release json-formatter as Docker image

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#785]
This will remove some of the portability problems using the standalone formatter

**Comment by iomedico-beyer** [comment]
I just created an image myself and documented it here:
https://stackoverflow.com/a/72868618/1948252

**Comment by aurelien-reeves** [comment]
Hey @iomedico-beyer 

Nice to see that you figured out a simple solution by yourself.

I would like to ask: why do you need the cucumber-json-formatter? I understood that you need it to convert NDJSON messages into the "legacy" JSON format.

What don't you generate the JSON directly from cucumber itself?

I know, at some point we have deprecated the JSON formatter. But it is not the case anymore, you will be able to rely on it in future version, as usual
