### ISSUE TITLE
Terminology change proposal

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#787]
People often mix up data tables with example tables. Both conceptually and how they name them.

Since `Scenario Outline` became a synonym of `Scenario` and scenarios can have example tables, it makes little sense to talk about "scenario outlines".

I quite like the Gauge terminology here. They call them [Table driven scenario](https://docs.gauge.org/writing-specifications.html?os=macos&language=java&ide=intellij#table-driven-scenario). The syntax and semantics are undeniably inspired from Gherkin, so let's take some inspiration back.

**I propose we adopt "Table driven scenario" and remove references to "Scenario Outline" everywhere**

With this terminology it also makes sense to **replace "examples table" with "Scenario Table"**

When we talk about Scenario Tables it might also make sense to talk about **"Step Tables" instead of "Data Tables"**.

What do you think about this proposal? It would require a pretty wide search-replace/rename in our docs and repos. We could keep the old classes as subclasses of the new ones and deprecate them.
 
/cc @mpkorstanje @mlvandijk @mattwynne @sebrose @charlierudolph @vincent-psarga

**Comment by marnen** [comment]
I’m aware that I may be missing some context here...but, knowing nothing further about this terminology change, my first reaction is that I don’t like it. I’d expect a “scenario table” to contain scenarios, and I’d expect a “step table” to contain steps, so I find these proposed changes rather confusing. (I use ~scenario outlines~table-driven scenarios more than most Cucumber users I know, so I can imagine these terminologisch changes making it harder for me to explain how my Cucumber features work...)

**Comment by laeubi** [comment]
Maybe it would be better to improve the docs to make difference more clear instead of renaming things?
One might propose to rename "javascript" to "browserscript" so people don't confuse it with java, but that does not solve the real issue that people use wrong terms for things :-)

**Comment by mpkorstanje** [comment]
Searching through the docs I can't find the term "Example Table". We only have an "Example section" mentioned in the Gherkin reference. So perhaps we can start by properly defining "Example Table" as part of the Gherkin reference?

https://cucumber.io/docs/gherkin/reference/

**Comment by aslakhellesoy** [comment]
Maybe I should have made a different issue for each proposed name change.

The name that bothers me the most is "Scenario Outline" because it doesn't really exist anymore.

What do you think about table driven scenario?

**Comment by mpkorstanje** [comment]
If Scenario and Scenario Outlines are now the same thing then you can't really create a new name for Scenario Outline. It would run into all the same problems. Perhaps we can consider them both Scenarios and consider the example table an optional part of a Scenario?

**Comment by aslakhellesoy** [comment]
When you put an example table under a scenario, it becomes something else. It behaves differently. It's a different beast.

I think different beasts ought to have different names.

**Comment by mattwynne** [comment]
I might be hanging on to the past, but I think all the old words (and some of those new ones) are still relevant at some level.

You use the Scenario keyword to tell Cucumber about an example.
Within a scenario, you can pass rich data to a step with a Data Table.

If you want to run a scenario multiple times with different values, you can add an Examples Table at the end. Cucumber will then treat the Scenario as a template, or Scenario Outline, which is used to generate Table Driven Scenarios.

**Comment by mpkorstanje** [comment]
@aslakhellesoy you seem to be in two minds about this. Scenario and Scenario Outline are two different beast that need different names. And at the same time what bothers you most about the Scenario Outline is that it doesn't exist anymore because it has been renamed to Scenario.

Regardless of that, if anything introducing a second name for Scenario Outline is going to add more confusion. We already have an established but undocumented terminology.

**Comment by aslakhellesoy** [comment]
Imagine you're explaining Gherkin to someone who is new to it. What words would you use to describe this and how it works?

```gherkin
Scenario: compute insurance premium
  Given a new customer born in <born_year>
  And the customer obtained their license in <license_year>
  When the premium is caculated
  Then the value should be <premium>

  Examples:
    | born_year | license_year | premium |
    |      1980 |         2000 |     109 |
    |      1990 |         2000 |     123 |
```

**Comment by mattwynne** [comment]
If you want to run your scenario multiple times with different values, use these angle brackets together with an examples table. Cucumber will use the table of examples at the bottom to generate a scenario for every row in the table.

**Comment by mattwynne** [comment]
I don't think "table driven scenario" adds much, unless we need a way to name the two different kinds of pickles under the hood. From a user perspective I don't think it helps.

**Comment by aslakhellesoy** [comment]
You didn't use "scenario outline" in that explanation, which is great.

I think that if we resort to using that term, confusion will arise when the learner realises that it is just a synonym. If it's just a synonym and behaves the same, why use it?

**Comment by mpkorstanje** [comment]
>  If it's just a synonym and behaves the same, why use it?

Okay so:
- Scenario ==> Scenario
- Scenario Outline with Example ==> Scenario Outline
- Scenario with Example ==> Scenario Outline
- Scenario Outline without Examples  ==> Confusion?

Perhaps we shouldn't completely treat it as a synonym?

Or use Scenario with Examples as the term?

**Comment by aslakhellesoy** [comment]
To be clear: I am suggesting we stop using thew term "Scenario Outline" altogether. In docs, conversations etc. The reason being that it is identical to "Scenario" and pretending it's different is just confusing.

**Comment by aslakhellesoy** [comment]
If we can just use "Scenario" everywhere we previously used "Scenario Outline" - great! But I have a feeling we are going to come up with a new term for it...

**Comment by davidjgoss** [comment]
> Imagine you're explaining Gherkin to someone who is new to it. What words would you use to describe this and how it works?

Happened to be in a room with a couple of BAs new to Gherkin when I saw this. Consensus:

- Describing it as a "template" with "examples|scenarios" seemed to land best
- Both suggested it was a "data-driven scenario"
- Both agreed "Scenario Outline" is confusing, suggests a more concise form which it's not

**Comment by aslakhellesoy** [comment]
Interesting. I like "data-driven scenario"!

**Comment by davidjgoss** [comment]
I think the Rule/Example grammar adds another angle to this. Given, from the docs:

> The keyword `Scenario` is a synonym of the keyword `Example`.

And, from above:

> `Scenario Outline` became a synonym of `Scenario`

Then would the following be valid?

```gherkin
Feature: Premium calculation

  Rule: Discriminate on age and experience

    Example:
      Given a new customer born in <born_year>
      And the customer obtained their license in <license_year>
      When the premium is calculated
      Then the value should be <premium>
      Examples:
        | born_year | license_year | premium |
        |      1980    |         2000    |          109 |
        |      1990    |         2000    |          123 |
```

Or are the forms mutually exclusive? (I haven't actually tried to run this)

**Comment by mattwynne** [comment]
@davidjgoss as I understand it that would be valid, yes.

@aslakhellesoy reviewing this proposal with some distance, I think I'd come down on the side of disagreeing with this part of it:

> I propose we adopt "Table driven scenario" and remove references to "Scenario Outline" everywhere

Although we've allowed people the flexibility to omit the word "outline" in their Gherkin, we still have a thing in our domain that is not yet a scenario, merely a template that can be used to generate scenarios. I think "scenario outline" is a fine name for talking about that thing, and I think we should stick with it.

I do recognise the problem about people confusing data tables and examples tables, I'm just not convinved that these changes will really solve that problem.
