### ISSUE TITLE
cukes.info maven

### ISSUE THREAD

**Issue by saiharish** [cucumber/cucumber#790]
Hello,

Unable to install using the command "mvn -Dcucumber.installGems=true cuke4duke:cucumber" because the repository cukes.info/maven does not exist.

Thanks,
Harish

**Comment by aslakhellesoy** [comment]
This bug tracker is for the ruby version of Cucumber. Cuke4Duke was retired three years ago in favour of [cucumber-jvm](https://github.com/cucumber/cucumber-jvm).

If you have further questions, please ask on the cukes google group.
