### ISSUE TITLE
Visit method adds /content/index-m.php at the end of my URL

### ISSUE THREAD

**Issue by toshidavila** [cucumber/cucumber#794]
It happens from time to time and I don't know why.

It randomly adds /content/index-m.php at the end of my URL which makes the scenario fail because the page is never loaded because that specific url doesn't exists.
![screen shot 2015-01-21 at 16 45 25](https://cloud.githubusercontent.com/assets/3664943/5846369/0f75f148-a191-11e4-8d1d-bfbe2585aeab.png)

**Comment by mattwynne** [comment]
Can you explain why you think it's Cucumber that's doing this?

**Comment by toshidavila** [comment]
Hi Matt,

Because sometimes the `<visit>` method works as expected. Meaning my variable is www.assembla.com and it redirects me there but sometimes it adds this text `</content/index-m.php>` with apparently no reason and randomly.

I don't know what's causing this. Do you have any idea?

**Comment by mattwynne** [comment]
Do you know which application implements the `visit` method?

**Comment by toshidavila** [comment]
Hi Matt,

I must say I am new with cucumber. This is the code in my steps.rb file
```#BACKGROUND:
Given (/^I am on login page$/) do
  visit $page
end
```
It works OK most of the time but as I mentioned, sometimes that text is added at the end of the URL.

**Comment by mattwynne** [comment]
The `visit` method you're using is probably the one implemented by http://github.com/jnicklas/capybara. Do you have that gem as a dependency in your project?

Cucumber's responsibility only goes as far as finding step definition to match the words you used in your feature file, and then executing the code in the step definition block. The code that runs in the block is not really anything to do with Cucumber, sorry.

My guess is that either your app is doing a redirect, or whatever logic sets the `$page` variable is behaving unexpectedly. Either way, I can't see how Cucumber could be responsible for this. :smile:

**Comment by toshidavila** [comment]
Hi Matt,

I see. Thank you so much for your help. I'll start looking at other places to get this resolved.

Again thank you!

**Comment by mattwynne** [comment]
No problem, I know it's confusing when you're new to something. Good luck!
