### ISSUE TITLE
cucumber-glue: What are the differences between `cucumber-glue` scope and step member variables?

### ISSUE THREAD

**Issue by noel-yap** [cucumber/cucumber#797]
This question is also at https://stackoverflow.com/questions/58863442/what-are-the-main-differences-between-cucumber-glue-scope-and-step-member-vari.

AFAICT, there's not much difference between using `cucumber-glue` scope and instantiating member variables in step classes other than where the instantiation code resides.

For example, using `cucumber-glue` scope:

```
@Configuration
public class MyConfiguration {
  @Bean
  @Scope("cucumber-glue")
  public MyContext myContext() {
    return new MyContext();
  }
}

@SpringBootTest
public class MySteps {
  @Autowired
  private MyContext myContext;
}
```

versus member variables:

```
@SpringBootTest
public class MySteps {
  private final MyContext myContext = new MyContext();
}
```

Are there other differences I'm missing?

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.

I answered you on SO btw.

**Comment by noel-yap** [comment]
Thanks!

FYI, https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md says
`Log an issue for any question or problem you might have.` I might've
missed it but in case I didn't, it'd be good to have a pointer in the docs
to that support page.
