### ISSUE TITLE
Using @tag with Examples block does not run hooks

### ISSUE THREAD

**Issue by blagh** [cucumber/cucumber#799]
I'm running into this issue where hooks do not run if the tags are placed above examples blocks.  I have the exact same test, but some of the setup is subtly different if the system is in a different country, for example. We've been using tags for this so far.

But in the following scenario, neither of the `Before` tags are run. The tags do still work for things like filtering which tests are run.

I'm running ruby 2.1.5, and cucumber 1.3.17

    Before('@tag') do
      create_system
    end

    Before('@tag_other') do
      create_different_system
    end

    Scenario outline: Create some systems
       Create a system in <Country>
    @tag
    Examples:
       | Country |
       | US      |
    @tag_other
    Examples:
       | Country |
       | Canada  |

**Comment by blagh** [comment]
Ah, I forgot to search in closed issues. Looking forward to 2.0!

**Comment by mattwynne** [comment]
You can try 2.0 now if you point your Gemfile to version 2.0.0.rc.3

Let us know how you get on...
