### ISSUE TITLE
Feature request: Rerun support without forcing users to choose an output formatter.

### ISSUE THREAD

**Issue by iMerica** [cucumber/cucumber#801]
I want to do the following:
- Rerun a failure up to n times until it passes
- See stdout like normal
- Optionally write results to a JUnit xml file

Rerunning failures is useful, but the way in which Cucumber allows you to do it is a bit limited. Here's how I have to do reruns currently:

`cucumber -t @my_test_suite -f rerun --out rerun.txt || cucumber @rerun.txt`

As a consequence of this,
- I can't see what's happening (maybe I can use `tee` ?)
- I'm limited to rerunning only once (sure I can wrap it in a while loop, but that's a bit much)
- I have to choose between rerunning or writing to a more useful format.

Is there a better way I'm unaware of? Sorry if this is an existing limitation that has been documented, I wasn't able to find it. As an example, [Pytest reruns](https://github.com/klrmn/pytest-rerunfailures) provide the exact functionality I'm looking for. I can work around these problems in bash, but it's another point of failure and it seems more appropriate for cucumber to handle, not custom bash scripts.

**Comment by brasmusson** [comment]
@iMerica As Cucumber supports multiple formatters, I don't see why you can't use something like
```
cucumber -t @my_test_suite -f rerun --out rerun.txt -f pretty || cucumber @rerun.txt
```
or
```
cucumber -t @my_test_suite -f rerun --out rerun.txt -f pretty -f junit --out result.xml || cucumber @rerun.txt
```
to see what's happening, and optionally write the results to a JUnit xml file.

**Comment by iMerica** [comment]
Oh cool. Didn't know you could use two formatters. Thanks! Would it be worth my time to submit a PR on the rerun N times feature (assuming I can figure it out)?

**Comment by mattwynne** [comment]
> Would it be worth my time to submit a PR on the rerun N times feature (assuming I can figure it out)?

That sounds like a useful feature. Why not start by writing a new feature file that describes how you'd expect it to work, push that to a PR, and we can discuss it there?
