### ISSUE TITLE
React Native example

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#807]
An example of using Cucumber.js with React Native would be useful to have! It could live in a separate repo. It should be TDD'ed rather than building upon some 3rd party hello world app.

It should ideally use some sort of screenplay variant, and use techniques from https://github.com/subsecondtdd/todo-subsecond - just using TypeScript.

**Comment by kerbe** [comment]
PingPong, problem / need for this hasn't disappeared.

**Comment by aslakhellesoy** [comment]
@kerbe I‘m getting the impression you expect someone else solve your problem. Am I right?

**Comment by aslakhellesoy** [comment]
Sorry if that sounded flippant. It’s just not something I have capacity to look into at the moment, and if you want this to be done you probably have to do it yourself.

**Comment by kerbe** [comment]
@aslakhellesoy well, you made it sound like most open source projects sound.

I would love to do this by myself, but as I have brought up my skill level and problem in slack, I have been waiting some help & pointing right direction.
As of now it is best to state that cucumber-js doesn't work with React Native, or at least with Expo. Saves others time, and they can look for alternatives, or be prepared to make it work if they have necessary skills, and provide good PR's.

Unless I gain miraculously some insight how to solve this on my own, I will let this issue to sink in peace. For time being, I will remain in cucumber slack.
