### ISSUE TITLE
cucumber-tag-expressions library naming

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/cucumber#809]
## Summary

Naming of the `tag-expressions` library is inconsistent:
 - folder in monorepo is `tag-expressions`
 - npm package is [`cucumber-tag-expressions`](https://www.npmjs.com/package/cucumber-tag-expressions)
 - ruby gem is [`cucumber-tag_expressions`](https://rubygems.org/gems/cucumber-tag_expressions/versions/1.1.1)
  - Java package is [`tag-expressions`](https://mvnrepository.com/artifact/io.cucumber/tag-expressions)

A linked problem is that we can not use file `.internal-dependencies` to link the package in the mono-repo as it will create a symlink in `node_modules/tag-expressions` which won't replace `node_modules/cucumber-tag-expressions`

## Expected Behavior

The name of the folder should reflect the name of the package (which should be unique, not depending on implementations)

## Possible Solution

Rename all "packages" as `tag-expressions` or `cucumber-tag-expressions`

**Comment by aslakhellesoy** [comment]
Good writeup. We should prefix all packages with `cucumber-`. For NPM we could also use the `@cucumber` org - that would be cool. We just need to reclaim the org first - see https://cucumberbdd.slack.com/archives/C612KCP1P/p1574951184001100

**Comment by aslakhellesoy** [comment]
Fixed by https://github.com/cucumber/cucumber/pull/825
