### ISSUE TITLE
Option to run cucumber scenarios in parallel

### ISSUE THREAD

**Issue by nnarendravijay** [cucumber/cucumber#811]
I have made each of my test scenarios completely independent by using cucumber-guice ScenarioScoped objects. Now, I have the ability to run my cucumber scenarios in parallel. I have tried setting up the forkEvery and maxParallelForks in my gradle task. That doesn't seem to do the magic with JUnit. I am running my Cucumber feature files using the JUnit @Runwith option.

Please suggest if there are any options that I could try in being able to run my cucumber scenarios in parallel. Also, I am interested in running the scenarios in a multi-threaded fashion rather than running them in multiple JVMs.

**Comment by mattwynne** [comment]
Please ask for help on the mailing list - http://groups.google.com/cukes

Typed with my Thumbs.

**Comment by nnarendravijay** [comment]
Did that, thanks!
