### ISSUE TITLE
Exit code is 0 when run cucumber with custom profile

### ISSUE THREAD

**Issue by ka8725** [cucumber/cucumber#812]
Steps to reproduce:

- create a custom profile with a failed feature
- run the custom profile

Expected result: exit code is 0
Actual result exit code is 1

**Comment by aslakhellesoy** [comment]
What cucumber version? Is this related to #810?

**Comment by ka8725** [comment]
Checked on "v1.3.19" and "v1.3.17"

**Comment by aslakhellesoy** [comment]
Please add details about how to reproduce.

**Comment by ka8725** [comment]
Tried to do this on the new Rails project. The problem is not reproduced. Seems the problem is in a third party library... Thanks for the reponse@

**Comment by mattwynne** [comment]
Can you please close the ticket? Thanks.

Typed with my Thumbs.

**Comment by ka8725** [comment]
It's closed already. By the way, the problem was in `watir-webdriver` - it worked as a second child process and the 0 exit code was its.

**Comment by mattwynne** [comment]
Thanks for closing.

So is this a problem with at_exit hook ordering?

Typed with my Thumbs.

**Comment by ka8725** [comment]
Not exactly. Actually I'm not sure how the status gets into the terminal, but this is how to fix it:

```ruby
@browser = Watir::Browser.new
@exit_code = 0

After do |scenario|
  @exit_code = 1 if scenario.failed?
end

at_exit do
  @browser.close
  exit(@exit_code)
end
```
