### ISSUE TITLE
[wire] end_scenario command is not being sent to wire client

### ISSUE THREAD

**Issue by evakili** [cucumber/cucumber#813]
It maybe related to #131, but the scenario is much simpler. Only use [addition.feature](https://github.com/cucumber/cucumber-cpp/blob/master/examples/Calc/features/addition.feature) in Calc example of cucumber-cpp. No end_scenario command is received in wire client. This happend in cucumber 2.0.0.rc.4 and not in 1.3.15.

**Comment by mattwynne** [comment]
Okay, yes I see the problem. We're no longer calling `WireLanguage#end_scenario` (or indeed `RbLanguage#end_scenario` either) from the new runtime.

I think we need to wait until #807 is merged. Oh wait - it's just been merged! Right, let me rebase my master and take another look...
