### ISSUE TITLE
multiple tags

### ISSUE THREAD

**Issue by robpark** [cucumber/cucumber#815]
I seem to be running into a problem of no scenarios found when running 
````cucumber --tags @rob````
when my scenario is tagged like:
````
@wip @rob
Scenario: foo me twice
````
If I remove the @wip and just have the single tag it's found OK. ???

version 2.0.0.rc.4

**Comment by rajeshgalla** [comment]
Wip tag will make the cucmber ignore that test case while running.

On Monday, March 9, 2015, Rob Park <notifications@github.com> wrote:

> I seem to be running into a problem of no scenarios found when running
> cucumber --tags @rob
> when my scenario is tagged like:
>
> @wip @rob
> Scenario: foo me twice
>
> If I remove the @wip <https://github.com/wip> and just have the single
> tag it's found OK. ???
>
> version 2.0.0.rc.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cucumber/cucumber/issues/815>.
>


-- 
Sent from Gmail Mobile

**Comment by mattwynne** [comment]
Interesting, thanks for reporting @robpark. If you have time, a failing test case would help us fix it more quickly.

**Comment by aslakhellesoy** [comment]
@rajeshgalla there are no "special" tags. If you want Cucumber to ignore certain scenarios you have to tell it explicitly to do so. For example `--tags ~@wip`

**Comment by robpark** [comment]
Yeah, I wasn't using the wip profile either.

I'll see if I can make a failing localized test this weekend.

@rob

**Comment by tooky** [comment]
@robpark we haven't been able to reproduce this. Could you create a minimal repo demonstrating it?

Do you have a default profile in your cucumber.yml with `--tags ~@wip` defined.

I'm going to close this issue, but please reopen it if you can show us a way to reproduce the error.

**Comment by robpark** [comment]
Ok will do. Saw it again yesterday, so I'd like to know what I'm doing
wrong. Thx
