### ISSUE TITLE
Hide test duration in `--quiet` mode

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber#816]
This just occurred to me.

At the very end of Cucumber's pretty output, there's a line that shows the duration of the test run.

e.g.
```
➤ cucumber features/docs/getting_started.feature -f pretty
Using the default profile...
Feature: Getting started

  To get started, just open a command prompt in an empty directory and run
  `cucumber`. You'll be prompted for what to do next.

  @spawn
  Scenario: Run Cucumber in an empty directory                              # features/docs/getting_started.feature:7
    Given a directory without standard Cucumber project directory structure # features/lib/step_definitions/cucumber_steps.rb:1
    When I run `cucumber`                                                   # aruba-0.6.1/lib/aruba/cucumber.rb:93
    Then it should fail with:                                               # aruba-0.6.1/lib/aruba/cucumber.rb:205
      """
      No such file or directory - features. You can use `cucumber --init` to get started.
      """

  Scenario: Accidentally run Cucumber in a folder with Ruby files in it.    # features/docs/getting_started.feature:15
    Given a directory without standard Cucumber project directory structure # features/lib/step_definitions/cucumber_steps.rb:1
    And a file named "should_not_load.rb" with:                             # aruba-0.6.1/lib/aruba/cucumber.rb:29
      """
      puts 'this will not be shown'
      """
    When I run `cucumber`                                                   # aruba-0.6.1/lib/aruba/cucumber.rb:93
    Then the exit status should be 1                                        # aruba-0.6.1/lib/aruba/cucumber.rb:197
    And the output should not contain:                                      # aruba-0.6.1/lib/aruba/cucumber.rb:160
      """
      this will not be shown

      """

2 scenarios (2 passed)
8 steps (8 passed)
0m0.641s
```

That `0m0.641s` is what I propose to remove in quiet mode.

It would mean we can use `Then it should pass with exactly:` in our tests, which gives much better feedback than `Then it should pass with:` and not need [this hack](https://github.com/cucumber/cucumber/blob/master/features/lib/support/normalise_output.rb#L11).

**Comment by richarda** [comment]
@mattwynne I started a [PR](#822) to implement this behavior.  What should be done about the [Dry Run feature](https://github.com/cucumber/cucumber/blob/master/features/docs/cli/dry_run.feature#L26)?

 `Then it should pass with exactly:` is currently being used and a `0m0.012s` duration expected and is being put in by `normalise_output.rb` ([the hack](https://github.com/cucumber/cucumber/blob/master/features/lib/support/normalise_output.rb#L11))

**Comment by brasmusson** [comment]
@mattwynne I do not understand. Because of [this hack](https://github.com/cucumber/cucumber/blob/master/features/lib/support/normalise_output.rb#L11) we already can use `Then it should pass with exactly:`, right? And even if the quiet mode does not print the duration, we still need "this hack", because there will be features that specify/test the behaviour of the non-quiet mode.

So, if it is not needed for the test, what is the benefit of not printing the duration in quiet mode? (well, a small benefit would be that `0m0.012s` is not needed when using `Then it should pass with exactly:` - and understanding why the duration always is expected to be `0m0.12s` requires knowledge of "this hack".)

**Comment by richarda** [comment]
Not to be too dense, but it is quieter to not print the duration.  I agree there are a few different ways to specify details in the tests.  I'm not totally clear on when quiet mode is important to people.  Is quiet mode helpful with some kind of continuous test runner where you just want to know red or green, pass or fail?

**Comment by mattwynne** [comment]
Main reason I noticed the need for this was writing tests for https://github.com/cucumber/cucumber-ruby-tcl <https://github.com/cucumber/cucumber-ruby-tcl> which would be simpler if we had this feature - otherwise we’ll have to duplicate the hack over there.

**Comment by brasmusson** [comment]
I see. In this code base we need the hack anyway, to be able to use `Then is should pass with exactly:` for those case when we actually want to verify for instance snippets and source output, but other code bases can benefit from being able to turn of the duration output.

**Comment by sebrose** [comment]
Would a step `Then is should pass with output matching:` be a useful addition to avoid the hack and the original problem?

**Comment by mattwynne** [comment]
[There is already something like that in Aruba](https://github.com/cucumber/aruba/blob/master/lib/aruba/cucumber.rb#L206) Seb. The problem is that the looser comparison that RSpec does in that case does not give nearly such a useful failure message. The exact string matcher shows you a line-by-line diff, which makes it much easier to spot mistakes.
