### ISSUE TITLE
Having trouble with Table and diff

### ISSUE THREAD

**Issue by dkmdnielsen** [cucumber/cucumber#819]
What I am trying to do is iterate over a list of columns, run a function against that column, save the result, the using .diff to compare expected results with actual results.  That way I guess a pretty table of green and red depending on how the test completed.

So I have a table that looks like the following:
```cucumber
  |     COLUMN_NAME         |     result |
  |     RecordNum           |     pass   |
  |     MasterCompanyTicker |     pass   |
```
A sql script is executed against each column name, returning 'pass' or 'fail' depending on the outcome.  The function is as follows:
```ruby
Then(/^these columns are expected to be not null$/) do |columns|
  # expected is an instance of Cucumber::Ast::Table
  WorkTable.logger.info title_line('Columns cannot be null')

  sql = File.readlines(File.join(ENV['ms_home'],'db','scripts','test','pass_or_fail_template.sql'))
  sql = (sql.map {|l| l.strip}).join(' ')

  results = columns.clone
  results.hashes.each {|row|
    st = sprintf(sql,"#{WorkTable.table_name}","#{WorkTable.table_name}.#{row['COLUMN_NAME']}")
    row['result'] = WorkTable.connection.select_all(st.encode('utf-8')).first['result']
  }
  columns.diff!(results,surplus_row: false)
end
```
The sql script is running correctly; there is one that returns the string 'fail'.  So I am expecting row['result'] to be 'fail'.  If I do pp right after assignment, I indeed see that row['result'] == 'fail'.  
```ruby
{"COLUMN_NAME"=>"TermDate", "result"=>"fail"}
```
However, if I do "pp results" against the whole table after the "results.hashes" block, it is not 'fail'.  It is its original value, 'pass'.
```cucumber
  |     TermDate            |     pass   |
```
What am I doing incorrectly?  I thought this was an ingenious way of collecting all the results in on swoop, the comparing them using table.diff.  But it is not working as I thought it would

Your time and consideration is appreciated,
dvn

**Comment by dkmdnielsen** [comment]
Good Lord, I am so sorry.  I have the solution after I posted the question (with a truncated subject line.)  The solution is as follows:
```ruby
      results = []
      columns.hashes.each {|row|
        st = sprintf(sql,"#{WorkTable.table_name}","#{WorkTable.table_name}.#{row['COLUMN_NAME']}")
        results << {
            'COLUMN_NAME' => row['COLUMN_NAME'],
            'result' => WorkTable.connection.select_all(st.encode('utf-8')).first['result']
        }
      }
    
      columns.diff!(results,surplus_row: false)
```
I was trying to diff a table against another table.  That is not the correct thing to do.  I need to diff a table against an array of hashes.  When I do that correctly, I get the following output:
```cucumber
       | ActiveDate          | pass   |
       | TermDate            | pass   |  <<
       | TermDate            | fail   |  <<
       | create_user         | pass   |
       | create_dt           | pass   |
```
That is what I was looking for.

Sorry to bother. Hopefully this helps someone else.
dvn

**Comment by mattwynne** [comment]
:)
