### ISSUE TITLE
Please make example_rows in Cucumber::Core::Ast::ExamplesTable public

### ISSUE THREAD

**Issue by jfinkhaeuser** [cucumber/cucumber#824]
Version: 2.0.0

In https://github.com/spriteCloud/lapis-lazuli we have a feature for automatically closing & restarting a Watir browser after e.g. every scenario, feature file, etc. There are a bunch of reasons for it, none of which have to do with cucumber, though...

But in order to do this, we have to detect whether the scenario in an AfterStep hook is the last scenario in a feature file. Cucumber 1.3.x had some way for doing so, but in 2.0.0 the only thing we've found is this quite horrible hack: https://github.com/spriteCloud/lapis-lazuli/blob/master/lib/lapis_lazuli/ast.rb lines 10-22.

[The entire file is a little hacky because we're dealing with internal differences between 1.3 and 2.0, but the hacks have been stable.]

Now this use-case is fairly specific, but to be frank, I don't see a reason why you should expose *most* of the parsed-up file as a fairly nicely usable tree, except for example rows.

If you have better suggestions - by all means, we're all ears :)

**Comment by mattwynne** [comment]
Out of interest @jfinkhaeuser, where are you calling this code from? Is it from a hook or a formatter?

**Comment by jfinkhaeuser** [comment]
Mostly from AfterStep hooks, but also from within steps. Either way, it's for decisions to be made at run-time of a test suite, not at parse time or output time.

The hope is to not have to provide formatters. Essentially the formatter API is far too large and (in older times too badly documented; I didn't check out 2.0.x for this yet) to warrant the effort of maintaining one. Besides, we're not trying to format anything, so formatters are a little bit of a crutch.

I could turn this into a much bigger feature request, and that would be to provide a more event based API for hooking into different phases of what cucumber does. AfterStep and BeforeStep are close, but for the most common use-case for us, a more generic functionality would be interesting:

```ruby
After(event) do |foo|
end
```

Where `event` would (to begin with) include options indicating entire test suites, features, scenarios, scenario outlines and steps -- essentially mirroring the Gherkin structure. On the other hand, `foo` would be the object most closely related to what you specified as `event` rather than always scenarios, with the ability to inspect the parents and children of the entire test suite structure.

That's *really* what I'd love to see, but the code in the linked file manages to get most of that out of cucumber, with the exception of looking into example rows.

**Comment by mattwynne** [comment]
Yeah I've been thinking about this too, and now that the complexity of the code is reduced I'm definitely keen to start adding APIs like this.

The new formatter API is much more simple, it goes like this:

`before_test_case`
`before_test_step`
`after_test_case`
`after_test_step`
`done`

Each gets passed an instance of the `Cucumber::Core::Test::Case` or `Cucumber::Core::Test::Step`, each of which has a `#source` collection you can look in to get at the AST nodes. The `after_*` methods get a result.

If we made it easier to subscribe to these events, would that help?

**Comment by jfinkhaeuser** [comment]
It would, very much! We may be getting *slightly* sidetracked here, though.

The issue I am really reporting is that for a scenario outline, you can't really inspect the example table(s) other than with the hack at the beginning of the file I posted (or I missed something).

What we use it for is for detecting the last scenario (from an outline or a single scenario) in a feature, by comparing the passed scenario's location to the feature's last element's last example table's *last row's* location (that's a mouthful). That's essentially our `AfterFeature` hook, though we've not called it that to avoid name clashes.

I don't think the formatter API would allow us to do this unless we can also inspect example table rows.

[As an aside: I really like how much more cleaned up `Cucumber::Core::Test::Case`, etc. are!]

**Comment by jfinkhaeuser** [comment]
Hence, by the way, my preference for an API that works like this:

```ruby
After(Cucumber::FEATURE, "@some @optional @tags") do |feature|
end

After (Cucumber::OUTLINE, "@tags") do |outline|
end

After (Cucumber::SCENARIO, "@tags") do |scenario|
end

After (Cucumber::STEP, "@tags") do |step|
end
```

It would make a bunch of LapisLazuli hacks obsolete :)

**Comment by mattwynne** [comment]
For detecting a change in feature, you should be able to subscribe to the `after_test_case` event, then look at `test_case.source.first` to get the feature and compare it to the current one. That would tell you whether you're looking at a test case from a new feature or not.

For your immediate needs I've made this change: https://github.com/cucumber/cucumber-ruby-core/commit/ca7e218f91061b7a66332bcabf9a309006668e86 which should help.

**Comment by jfinkhaeuser** [comment]
Yep, I saw cucumber/cucumber-ruby-core@ca7e218f91061b7a66332bcabf9a309006668e86 - many thanks for that!

That will still be necessary with `after_test_case`, though. Comparing what you say triggers stuff after the first test case in a new feature, and we're really interested in triggering stuff after the last test case of the previous feature - or before the first test case in the new feature.

Doing much the same in `before_test_case` solves this for all but the last feature in a suite. That case requires looking at the last of the last of the last of the children of the current feature again, hence needs example rows.

One way or another, the ugliest of our hacks is no longer necessary with that change you made, so thank you very much again!

**Comment by mattwynne** [comment]
Yeah you'd need to run the same logic in `done` as well as `before_test_case` I think.

Keep pushing at us for better APIs @jfinkhaeuser until you don't need any hacks at all!

**Comment by jfinkhaeuser** [comment]
I like the sound of that!
