### ISSUE TITLE
Cucumber-React: Do not highlight placeholders

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#826]
The report below is generated from one of cucumber-jvm's example projects:

```
cat examples/java-calculator/target/results.ndjson | ../cucumber/cucumber-html-formatter/javascript/bin/cucumber-html-formatter.js --format ndjson > index.html
```

The `<a>`, `<b>` and `<c>` placeholders should remain unchanged. And I think the scenario itself should be `unknown` if the results vary per row.

<img width="903" alt="Screenshot 2019-12-10 at 16 34 01" src="https://user-images.githubusercontent.com/1000/70549107-94caf100-1b6b-11ea-9736-64fdf6dafbe8.png">

**Comment by mpkorstanje** [comment]
>  And I think the scenario itself should be unknown if the results vary per row

I would prefer to take the worst result. It presents the most critical information first.

**Comment by aslakhellesoy** [comment]
Yeah that's probably better. We do that elsewhere too, to compute the status of a scenario or entire file for example.
