### ISSUE TITLE
Produce exception backtrace for formatters without using Cucumber::Formatter::LegacyApi

### ISSUE THREAD

**Issue by brasmusson** [cucumber/cucumber#833]
The exception backtrace in the output from formatters is structured as ([example from junit_formatter.feature](https://github.com/cucumber/cucumber/blob/13c621d2ea30733ddffdbfac42e2db0b39694f07/features/docs/formatters/junit_formatter.feature#L261-L263)):
```
 (RuntimeError)
./features/step_definitions/steps.rb:4:in `/^this step fails$/'
features/scenario_outline.feature:9:in `Given this step fails'
features/scenario_outline.feature:4:in `Given this step <type>'
```

To produce this backtrace code in `Cucumber::Formatter::LegacyApi` is used ([this code in lib/cucumber/formatter/legacy_api/adapter.rb](https://github.com/cucumber/cucumber/blob/13c621d2ea30733ddffdbfac42e2db0b39694f07/lib/cucumber/formatter/legacy_api/adapter.rb#L994-L1056)). 

This functionality should either be moved to a helper module in `Cucumber::Formatter` or to Cucumber-Ruby-Core. For the new formatter api to be easy to use, it should be possible to get from `Cucumber::Core::Test::Result` to the exception backtrace used the formatter output without using code in `Cucumber::Formatter::LegacyApi`. Doing so right now will instead produce the following exception backtrace:
```
 (RuntimeError)
./features/step_definitions/steps.rb:4:in `/^this step fails$/'
```

**Comment by mattwynne** [comment]
Agreed @brasmusson. [For 3.0, I'd like to get rid of all the legacy formatters](https://github.com/cucumber/cucumber/issues/839), and we need to gradually recycle these kinds of useful fragments out of the legacy adapter into places we can re-use them from newer formatters.
