### ISSUE TITLE
Html report is green despite scenario has failed

### ISSUE THREAD

**Issue by balpet** [cucumber/cucumber#835]
Hi,

I'm investigating an error that might be a cucumber bug as well. Could you please also check?
So our framework checks before starting executing a scenario's steps if the server that the tests should be running against is up and available. If it's not then the scenario's steps does not even get executed and our framework raises different kind of exceptions.
And the html report of it says correctly that the scneario has failed but still it's color will be green instead of red.

Have you ever experienced it, do you know what might be the root cause?

Thanks,
Peter

![2015-04-14_1815](https://cloud.githubusercontent.com/assets/11946755/7141503/597ce08a-e2d2-11e4-9a84-d7ef09d98343.png)
![2015-04-14_1817](https://cloud.githubusercontent.com/assets/11946755/7141541/8c7bcdca-e2d2-11e4-83b4-68a610dfa27c.png)

**Comment by mattwynne** [comment]
This could easily be a bug in the HTML formatter, yes. What we need is a new [spec](https://github.com/cucumber/cucumber/blob/master/spec/cucumber/formatter/pretty_spec.rb) for the case where the before hook fails.

**Comment by brasmusson** [comment]
@balpet Are you using Cucumber v2.0 or Cucumber v1.3.x?

**Comment by balpet** [comment]
@brasmusson I was using 1.3.17

**Comment by brasmusson** [comment]
It is likely that this is a bug in the HTML formatter in Cucumber v1.3.x. This problem is maybe fixed in Cucumber v2.0, but to be sure I need to test it there.

**Comment by balpet** [comment]
Thanks @brasmusson and @mattwynne for looking into this

**Comment by mattwynne** [comment]
@balpet are you able to upgrade to 2.0 and try with that?

**Comment by mattwynne** [comment]
Thanks Bjorn.
