### ISSUE TITLE
cannot load such file -- rspec (LoadError)

### ISSUE THREAD

**Issue by dwd4bc** [cucumber/cucumber#837]
When running the calabash-android command I come across an error that says something about my rspec file being unable to load. 

I'm using cucumber 1.3.19, ruby 2.0.0 p481, calabash-android v0.5.8
Running on Mac OS X Yosemite 10.10.2
------------------------------------------------------Error details---------------------------------------------------------------------
cannot load such file -- rspec (LoadError)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/.../features/support/env.rb:2:in `<top (required)>'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:42:in `run!'
/Users/.../.calabash/gems/cucumber-1.3.19/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/.../.calabash/gems/cucumber-1.3.19/bin/cucumber:13:in `<top (required)>'
/usr/bin/cucumber:23:in `load'
/usr/bin/cucumber:23:in `<main>'

---------------------------------------------------------Gems installed--------------------------------------------------------------
*** LOCAL GEMS ***
awesome_print (1.6.1)
bigdecimal (1.2.0)
builder (3.2.2)
bundler (1.9.4)
calabash-android (0.5.8)
calabash-common (0.0.1)
calabash-cucumber (0.14.0)
CFPropertyList (2.3.1)
cucumber (1.3.19)
diff-lcs (1.2.5)
domain_name (0.5.23)
edn (1.0.6)
escape (0.0.4)
geocoder (1.2.8)
gherkin (2.12.2)
http-cookie (1.0.2)
httpclient (2.6.0.1)
io-console (0.4.2)
json (1.8.2, 1.7.7)
mime-types (1.25.1)
minitest (4.3.2)
multi_json (1.11.0)
multi_test (0.1.2)
netrc (0.10.3)
psych (2.0.0)
rack (1.6.0)
rack-protection (1.5.3)
rake (0.9.6)
rdoc (4.0.0)
rest-client (1.8.0)
retriable (1.4.1)
rubyzip (1.1.7)
run_loop (1.3.1)
sim_launcher (0.4.13)
sinatra (1.4.6)
slowhandcuke (0.0.3)
test-unit (2.0.0.0)
thor (0.19.1)
tilt (2.0.1)
unf (0.1.4)
unf_ext (0.0.6)
xamarin-test-cloud (1.1.1)

**Comment by mattwynne** [comment]
Hi,

Looks to me like you need to `gem install rspec`.
