### ISSUE TITLE
Cucumber_AccessIssue_parameterised_featureFile

### ISSUE THREAD

**Issue by PritiSathe04** [cucumber/cucumber#84]
## Summary

Feature: Contact Us Page
  As an end user
  I want a contact us page
  So that I can find out more about QAWorks exciting services!!

Scenario: Valid Submission
    Given I am on the "QAWorks" on "Chrome"
    When I click on "Contacttab" 
    And I enter "<name>" with "namelocate"
    And I enter "<email>" with "emailocate"
    And I enter "<message>" with "messagelocate"
    And I click on the "SendButton" 
    Then I should be able to contact QAWorks with the following information    
	| name     | email                             | message                                                      |
	|j.Bloggs  | j.Bloggs@qaworks.com | please contact me I want to find out more |

## Expected Behavior
1)It should open contact us page
2)It should able to send name,email,message to the text box
3)Click on send button and the data should get sent to qaworks.

Bug:
It is not able to send the data to name,email,message field.Instead of capturing data it is sending it as <name> in the text box.

Function written for the featurefile
The following funtion doesnot work.
	**@And("^I enter \"([a-zA-Z]{1,})\" with \"([^\"]*)\"$")
	       public void I_enter_name(String text,String object){
		system.out.println("I Click On "+ object);
		selenium.type(text, object);		 
	}**
	
Locators for name,email,message respectively):

namelocate=//input[@id='ctl00_MainContent_NameBox']
emailocate=//input[@id='ctl00_MainContent_EmailBox']
messagelocate= //*[@id='ctl00_MainContent_MessageBox']

Utility functions:
locator has passed to objectname 
<Name>,<email>,<message> has sent to Text in the following function.

public void type(String Text, String objectName)
		{
			driver.findElement(By.xpath(OR.getProperty(objectName))).sendKeys(Text);
			 
		}

 Possible solution: 
change the regular expression to accept the paratemeter in step definition.

**Comment by mattwynne** [comment]
Hi @PritiSathe04,

I think you have opened this ticket because you need help using Cucumber, is that correct?

Please understand that this is not a support forum. We use this issue tracker exclusively for tracking defects and new features in Cucumber itself.

For support using Cucumber you need to visit http://cucumber.io/support where there are signposts to our community forum and chatroom. I hope that helps!

**Comment by PritiSathe04** [comment]
Please can you grant me the permission to join I have sent the request.

Emailaddress- priti.sathe04@gmail.com
