### ISSUE TITLE
Properly support symbol keys in table hashes

### ISSUE THREAD

**Issue by dmorgan3405** [cucumber/cucumber#840]
I would like to reopen the discussion around #313 

To solve the issue, I have been using a monkey patch for some time, and wrapped it up in a gem ([cucumber-symbolic-hashes](https://github.com/dmorgan3405/cucumber-symbolic-hashes)) 

```ruby 
class Cucumber::Ast::Table

  def symbolic_hashes
    @header_conversion_proc = lambda {|h| symbolize_key(h)}
    @symbolic_hashes ||= build_hashes
  end

  private

  def symbolize_key(key)
    key.downcase.gsub(' ','_').to_sym
  end

end
```

I know there was a solution discussed in #313 around a hash factory, and that may be a better solution to move forward with. Or possibly there are better options. 

I would love to see this ability added to cucumber, as when working in the test data arrangement world it allows me to use factory girl more effectively without having to handling the conversion elsewhere. 

If anyone else is interested in seeing a solution added for this I would love discuss it.

**Comment by mattwynne** [comment]
@dmorgan3405 thanks for taking an interest. If you can put together a pull request with your solution and specs from dmorgan3405/cucumber-symbolic-hashes I'll be happy to merge it in. The hash factory idea was a lovely idea, but working code is much more valuable than nice ideas :)

**Comment by dmorgan3405** [comment]
Let me know if any revision is needed!
