### ISSUE TITLE
Snippet generator - don't enforce whitespace rule for numerical parameters

### ISSUE THREAD

**Issue by sebrose** [cucumber/cucumber#844]
## Summary

#657 has changed the behaviour of the snippet generator such that it no longer behaves as expected with numerical parameters.

## Expected Behavior

"Given Sean is 15m from Lucy" -> "Sean is {int}m from Lucy"
"Given a coffee costs $2.50" -> "a coffee costs ${double}" - or maybe {float}, or historically {int}.{int}

## Current Behavior

"Given Sean is 15m from Lucy" -> "Sean is 15m from Lucy"
"Given a coffee costs $2.50" -> "a coffee costs $2.{int}"
~~~
~~~

## Possible Solution

Numerical parameters should be bounded by whitespace at one side at least.

* $1.50 -> ${double} or ${int}.{int}
* 15m -> {int}m
* 500ms -> {int}ms
* i18n -> i18n
* $15m -> $15m

Careful consideration of whether punctuation counts as whitespace is needed. "." and "," are used differently by locale.

## Context & Motivation

This change results in non-intuitive Cucumber expressions in snippets.

## Your Environment

* Version used: Cucumber-JVM 4.7.4
* Operating System and version: Macos Catalina
* Link to your project: https://github.com/cucumber-ltd/cucumber-school-java

**Comment by luke-hill** [comment]
Good spot. I think the possible solution also makes a lot of sense. And is reasonably easy to interpret (Albeit it might be a bit cumbersome to check the 2 permutations, but don't know yet).

For now a custom one with a letter (Assuming you mean time / distance), would work nicely so `\d+\w` for example.

**Comment by sebrose** [comment]
That wouldn't work for, say, milliseconds: ms

**Comment by sebrose** [comment]
Wouldn't that also match "C3PO"?

**Comment by luke-hill** [comment]
I assumed it was only one letter, so `\w` would be fine, or you could use a range `[]` to pass in all valid chars.

It's something I'd happily work on. I know Rien did most of the work alongside aslak, so I might wait to see if they're better placed. But it's quite comprehensively explained by yourself.

**Comment by sebrose** [comment]
I don't think we should assume a single letter. Consider milliseconds, for example: ms

**Comment by aslakhellesoy** [comment]
We should complete https://github.com/cucumber/cucumber/pull/771 before tackling this.

**Comment by mpkorstanje** [comment]
This isn't blocked by #771. The generation of expressions is a different component.

**Comment by mpkorstanje** [comment]
> Numerical parameters should be bounded by whitespace at one side at least.
@sebrose referencing a few style guides I found that units are not always supposed to be attached to the number.

 * https://developers.google.com/style/units-of-measure
 * https://ukmetric.files.wordpress.com/2017/07/ukma-style-guide.pdf
 * https://www.manula.com/manuals/dmp/dmp-writers-style-guide/1/en/topic/units-of-measurement
 * https://physics.nist.gov/cuu/Units/checklist.html

Only for angles, percentages and some currencies (USD, but not the Euro) the symbol is attached to the number.

So I think all parameters should be bounded on both sides by whitespace, punctuation or symbols.

**Comment by mpkorstanje** [comment]
And writing that in a mono-spaced font makes me think that the style guide might not be applicable. here. :laughing:

**Comment by mpkorstanje** [comment]
A good counter to only requiring a word boundary on one side would be:

```
Given I take flight KLM404 --> I take flight KLM404
```

Rather then:

```
Given I take flight KLM404 --> I take flight KLM{int}
```

**Comment by mpkorstanje** [comment]
I'm going to err on the side of caution for now.

We've got the currency use case covered. Just not the measurements use case.

**Comment by marnen** [comment]
My take: “KLM404” isn’t an integer; it’s a different thing with its own syntax (just as a phone number is). It should probably not use an `{int}` parameter type. 

OTOH, my experience has been that declaring a custom parameter type is harder than I wish it were (which is why I still write most of my steps with regexes). Perhaps that’s where to focus effort (or perhaps I’m behind the times; I’m not programming full-time these days).

**Comment by mpkorstanje** [comment]
So I've merged https://github.com/cucumber/cucumber/pull/1108 because its an improvement already.

@marnen perhaps you could check a few of your projects for the `[\d.,]+[^\d]+`  and  `[^\d]+[\d.,]+` patterns and see what typical examples might be?

I've checked a few projects myself and with the exception of currency the pattern simply did not occur. But this is ofcourse highly domain specific.

**Comment by marnen** [comment]
@mpkorstanje I use integers moderately frequently in my step definitions. I’ll find some examples and post links here.
