### ISSUE TITLE
Documentation :: Invalid link to cukes.info/step-definitions from Multiline Step Arguments page

### ISSUE THREAD

**Issue by MironovDmitry** [cucumber/cucumber#847]
the page https://github.com/cucumber/cucumber/wiki/multiline-step-arguments
has link to cukes.info/step-definitions, which cannot be found.

Suppose the correct link should be: https://cukes.info/docs/reference#step-arguments

**Comment by mattwynne** [comment]
Thanks, I've updated the wiki page.

I'm curious - were you unable to edit the wiki page yourself, or did you not want to for some reason?

**Comment by MironovDmitry** [comment]
Hi Matt.

I was not sure that the supposed url was correct. That is why I decided not to edit it myself.
I'm new to cucumber and did not want to mess something in the documentation.

**Comment by mattwynne** [comment]
Well you may be new but you’re already contributing, thanks!
