### ISSUE TITLE
[cucumber-expressions] Node 4 support

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#85]
cucumber-expressions is written in ES6 which isn't as supported in earlier versions of node. I'm fine dropping support for node 0.10 and node 0.12 whose long term support ends at the end of October and December of this year, but definitely want to continue supporting node 4.

Hitting the following on travis CI for node 4:

```
/home/travis/build/cucumber/cucumber-js/node_modules/cucumber-expressions/lib/cucumber_expression.js:3
class CucumberExpression {
^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

I hope we just need to add `'use strict';` to the top of the files and that's it. I'll try that out

**Comment by aslakhellesoy** [comment]
I'll make a babelised release

**Comment by aslakhellesoy** [comment]
Ok, this should be fixed now. While you're developing you should be able to pull it in like this:

```json
"dependencies": {
    "cucumber-expressions": "cucumber/cucumber-expressions-javascript"
}
```

(You'll probably need the same `babel*` devDependencies to build it)
When you confirm that works OK i can create a new release and you can pull it in like so:

```json
"dependencies": {
    "cucumber-expressions": "cucumber/cucumber-expressions-javascript"
}
```

At this point, no `babel*` devDependencies should be required to use this lib.

**Comment by charlierudolph** [comment]
Works as expected. Please release 1.0.2 when you can

**Comment by charlierudolph** [comment]
@aslakhellesoy reopening until 1.0.2 is released.

**Comment by charlierudolph** [comment]
@aslakhellesoy bump on this. This is one of the last blockers for cucumber-js 2.0

**Comment by aslakhellesoy** [comment]
Thanks for the heads up, will try to do this week. Very excited to try out 2.0!!!

**Comment by aslakhellesoy** [comment]
@jimmywarting what's not to like about a babelised release? What it means is that the release will be transpiled to "old" JavaScript

**Comment by jimmywarting** [comment]
I don't need a old javascript code on my up to date node v7.0 version

**Comment by aslakhellesoy** [comment]
@jimmywarting one of the goals of Cucumber.js (and all the libraries it depends on) is to be able to run inside a browser, not just Node.

It would be impractical to release npm modules in both old JavaScript and es6.

I suppose we could release all libraries (such as cucumber-expressions) as es6 modules, and only use Babel in Cucumber.js, when building it for the browser.

Is that what you mean?

**Comment by aslakhellesoy** [comment]
@charlierudolph since Cucumber.js 2.0 is ES6, it should be possible to use ES6. What about releasing cucumber-expressions as ES6, and instead, Cucumber.js could provide an alternative babelised build for Node 4 and browsers?

**Comment by charlierudolph** [comment]
I'm fine with going extra babelification for the browser but would really like this to support node 4 out of the box. I don't like the idea of having to do version detection to serve different variants for node 4 and node 6.

With how simple this library is I don't think using babel is a problem. Looking at the compiled code the main thing that gets converted is classes and destructing (the import statements also get converted but those support by node out of the box anyway). These are pretty minimal and they give us support more easily all the way down.

**Comment by charlierudolph** [comment]
@aslakhellesoy bump as still need this.

**Comment by aslakhellesoy** [comment]
@charlierudolph cucumber-expressions 1.0.2 is released. cucumber-js 2.0.0 Go!

**Comment by charlierudolph** [comment]
Not sure what happened but 1.0.2 does not contain a `dist` directory.

**Comment by aslakhellesoy** [comment]
Ah crap. I'll look into that. It's tricky to bulld a babelised module that works both as prebuilt tarball and git module

**Comment by charlierudolph** [comment]
The prepublish script looks correct, I don't see how it got published without a `dist` directory

**Comment by aslakhellesoy** [comment]
It's [complicated](https://blog.greenkeeper.io/what-is-npm-s-prepublish-and-why-is-it-so-confusing-a948373e6be1)... I haven't found any npm documentation describing what files are included in the package by default, if there is no `files` section in `package.json` and no `.npmignore` files.

In any case, I have an upcoming fix.

**Comment by aslakhellesoy** [comment]
Allright - 1.0.3 is released, and I've checked it contains the `dist` directory
