### ISSUE TITLE
Running cucumber while requesting a html format output causes a scenario to fail

### ISSUE THREAD

**Issue by theirishpenguin** [cucumber/cucumber#850]
I understand this is not a good test case. Please feel free to close this if this bug report is of no use.

I get the following error...

``` [JavaScript Error: "h is null" {file: "file:///tmp/webdriver-profile20150514-6516-bwzu3o/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 8478}]'[JavaScript Error: "h is null" {file: "file:///tmp/webdriver-profile20150514-6516-bwzu3o/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 8478}]' when calling method: [nsICommandProcessor::execute] (Selenium::WebDriver::Error::UnknownError)```

... when I run
```ephemeral-x.sh bundle exec cucumber --format json -o out/cucumber.json --format html -o out/cucumber.html features/my_lovely.feature```

or

```ephemeral-x.sh bundle exec cucumber --format html -o out/cucumber.html features/my_lovely.feature```

... but not when I run
```ephemeral-x.sh bundle exec cucumber --format json -o out/cucumber.json features/my_lovely.feature```

or

```ephemeral-x.sh bundle exec cucumber features/my_lovely.feature```

This makes me think it could be a problem with how cucumber handles the --format option rather than in the selenium webdriver.

**Comment by mattwynne** [comment]
Hi,

Is this consistent? The only cause that springs to mind is that the formatters are called synchronously with the steps, so running multiple formatters will have a marginal effect on how long each step takes to run. It could be triggering a race condition in your javascript code maybe?

It would be interesting to understand what that error means, in terms of what has or hasn't happened on your app that you would have expected it to. Have you tried to figure that out?

**Comment by theirishpenguin** [comment]
It's consistent. It only happens on a Jenkins CI server. I haven't deep dived this issue - just done enough to ensure that it the error happens consistently. I was thinking that the extra writing of the HTML format might have been a cause (even though it seems unlikely) but you've nicely described what the problem could be in your description of the potential race condition, thanks.

I will try to get a chance to look into this again soon. But for now, if you want to close this then just do (I can live without the HTML output for a while).

**Comment by mattwynne** [comment]
Yeah, these things are a nightmare to debug. One quick hack to test my theory could be to put a well-positioned `sleep` in your steps to simulate the delaying effect of the formatter.

I don't think there's much we can do right now, so I will close it if that's OK with you. If you get the energy to do any more investigation though I'll be happy to help. You could also hop onto https://gitter.im/cucumber/cucumber for some live support :smile:

**Comment by theirishpenguin** [comment]
Thanks a million @mattwynne. I will update this ticket when I return to the debug nightmare :-)

Much appreciated,
Dec
