### ISSUE TITLE
How to get the line number of where the scenario's got stopped from the feature files [eg:- scenario.getLine() instead of scenario.GetLines()]

### ISSUE THREAD

**Issue by adityabhargav** [cucumber/cucumber#852]
## Summary
How to get the line number of where the scenario's got stopped from the feature files [eg:- scenario.getLine() instead of scenario.GetLines()] (or) how can i get the exact line number in feature file when cucumber step fails

## Expected Behavior

Need to get the specific line number ,where the test got failed ,if @ after tag's scenario.getLine() is called
## Current Behavior

After the end of execution (Passed or failed), in @ after tags scenario.getLines() getting only line number of the entire scenario's
## Example:-

1.Feature: Sample

2.Scenario: sampleTest
3.Given I logged in
4.When the dashboard appears
5. Then go to the item's menu

if any of the steps(Say 3-5) get failed
Actual behavior:: in @ after tag's scenario.getLines() is generating line no. 2, which is only the line number of the given scenario

Expected:: in @ after tag, are there any ways to get exact and specific line number of scenario step in the scenario from the feature file.

## Your Environment

* Version used:2.4.0
* Operating System and version:Mac Osx

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/) forums (scroll down) for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
