### ISSUE TITLE
gherkin-query: provide more useful information when a node location is not found

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/cucumber#855]
## Summary

When querying `Gherkin::Query.location` and that the `id` of the node is unknown, we get an exception raised with message:

```
"No location found for eee. Known: aaa bbb ccc ddd fff
```
(with `aaa`, `bbb` etc being UIDs).

A nice-to-have (in order to ease debugging) would be information about which kind of AST node is referenced by each uid.

This was raised by @mattwynne on Slack.

**Comment by mattwynne** [comment]
It occured to me that maybe the best thing to do would be to include the type of node in the ID when generating it. Stripe do this, for example, so you get and ID like `cus_GYzg2BNpHsySOt` for a customer, or `ch_1G1riU2eZvKYlo2CyEYBYoLr` for a charge.
