### ISSUE TITLE
Regexp flag expressions incorrectly recognised as capture groups.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#856]
Using the `(?i)` flag expression to turn on case insensitive matching causes runtime errors because `TreeRegexp` mistakenly considers it to be a capturing group.

I didn't even know about flag expressions. Here is a list of what's supported:

* [Ruby](https://ruby-doc.org/core-2.7.0/Regexp.html#class-Regexp-label-Options)
* [Java](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) - search for "embedded flag expression"
* Go - not sure what's supported
* [General List](https://www.regular-expressions.info/refmodifiers.html)

JavaScript does not appear to support them, but I think we should implement this in JavaScript as well, as if they were. The different implementations are more similar that way.

**Comment by aslakhellesoy** [comment]
Relevant discussion: https://groups.google.com/d/msgid/cukes/58e2a324-bfe3-4696-ac79-32d4036a7365%40googlegroups.com

**Comment by mpkorstanje** [comment]
Go supports: RE2  https://github.com/google/re2/wiki/Syntax

Which basically supports nothing.

**Comment by luke-hill** [comment]
Yeh I know it doesn't support `?!` as when I was fixing something around Cukenfest 2019, the processor just blew up with like a Perl error or something. I also know the others were a bit patchy when I tried to use some of the variants.

**Comment by mpkorstanje** [comment]
You'll like this solution:

https://github.com/cucumber/cucumber/pull/1069/files#diff-9656e48cf559695284ceab5787e4a18fR66

Find the longest prefix and check if it is matching or non-matching.
