### ISSUE TITLE
Accents letters are not printed properly

### ISSUE THREAD

**Issue by selvavaithi** [cucumber/cucumber#857]
Hi Cucumber Team,

First of all, Thanks for this wonderfull cucumber framework.

In this framework in Featuer file i have a step like this

When I Creates Transaction "meublée"

but on running the Java code the text is returns like this "meubl�e.
Please help me on this.

I use Selenium Java in Eclipse.

**Comment by dkowis** [comment]
Please use the forum at cukes@googlegroups.com or https://groups.google.com/forum/#!overview , you'll find better support there.

This isn't a support forum.
