### ISSUE TITLE
TypeError: Gherkin.fromPaths is not a function && TypeError: gherkin.fromPaths is not a function (gherkin-javascript)

### ISSUE THREAD

**Issue by mikesalvia** [cucumber/cucumber#857]
## Summary

When using `gherkin-javascript` standalone in a Node.JS script `fromPaths` seems non-accessible

## Expected Behavior

I should be able to use `fromPaths`

## Current Behavior

Can't use `fromPaths`

~~~
(node:60095) UnhandledPromiseRejectionWarning: TypeError: Gherkin.fromPaths is not a function
    at parseConfigs (/Users/msalvia/repos/jwplayer-mobile-sdk-workspace/mobileqa/wdio/makeCoverageReport.js:14:17)
    at Object.<anonymous> (/Users/msalvia/repos/jwplayer-mobile-sdk-workspace/mobileqa/wdio/makeCoverageReport.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:60095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:60095) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~~~

## Possible Solution
8.2.1 does work properly and `fromPaths` is valid

## Steps to Reproduce (for bugs)

1. Write vanilla JS file using `.fromPaths`
2. Run file

```
const Gherkin = require('gherkin');
const fs = require('fs');

const options = {
    defaultDialect: 'en',
    includeSource: true,
    includeGherkinDocument: true,
    includePickles: true,
    createReadStream: (path) => fs.createReadStream(path, {encoding: 'utf-8'})
};

async function parseConfigs() {
    const envelopes = await streamToArray(
        Gherkin.fromPaths(['features/basic/basic_mp4.feature'], options)
    )
}

async function streamToArray(readableStream) {
    return new Promise((resolve, reject) => {
            const items = [];
            readableStream.on('data', items.push.bind(items));
            readableStream.on('error', (err) => reject(err));
            readableStream.on('end', () => resolve(items));
        }
    )
}

parseConfigs().then(r =>
    console.log(`Parsing: ${r}.`)
);
```
## Context & Motivation
I am attempting to create statistics regarding Cucumber features.

## Your Environment

* Version used: 9.0.0
* Operating System and version: macOS
* Link to your project: Private

**Comment by karamosky** [comment]
Hello @mikesalvia,
To mitigate this issue you can change `require('gherkin')` to `require('gherkin').default`
I think this is due to the incompatibility of CommonJS and ES Modules (which are used by gherkin 9)

**Comment by aslakhellesoy** [comment]
Thanks for the workaround @karamosky. I do think we should change the top level export to be a regular `export` rather than a `export default`. This would require a new major release, since you would have to do this:

```javascript
const { Gherkin } = require('gherkin')
```

The reason being that we also need to export `GherkinQuery`:

```javascript
const { GherkinQuery } = require('gherkin')
```

**Comment by karamosky** [comment]
Hi @aslakhellesoy,
I have been doing some research on this and found this article about keeping backward compatibility between CommonJS and ES modules: https://2ality.com/2019/10/hybrid-npm-packages.html

I don't know if this is something that can be done with gherkin-js :)

Knowing that Node.js v13 is officially supporting ES modules (https://nodejs.org/api/esm.html)

I am wondering why not keeping default export?

I'd rather prefer having

```js
import Gherkin, { GherkinQuery } from 'gherkin'
```

Than

```js
import { Gherkin, GherkinQuery } from 'gherkin'
```

**Comment by mikesalvia** [comment]
I will try with latest, as previously mentioned rolling back worked so this fell off the plate a bit.
