### ISSUE TITLE
Running Scenarios in Parallel

### ISSUE THREAD

**Issue by enroxorz** [cucumber/cucumber#861]
I know that parallel_cucumber allows us to run feature files in tandem, but what about running individual scenarios in parallel? I have a scenario outline that can have a lot of examples, but since I need to use parallel_cucumber I need to split them up between different files which makes it redundant. Any idea how we can do this? Is there a part of cucumber's source code that might allow us to pull specific scenarios at a time and fork a process for each?

**Comment by mattwynne** [comment]
It depends on how deep you want to go. You could have a look at [the core](http://github.com/cucumber/cucumber-ruby-core) and see if there's anything from there you can use. I don't have an easy answer for you I'm afraid.

Please follow this up on the mailing list if you have more questions. We like to keep this issue tracker for discussing bugs or new features.
