### ISSUE TITLE
Cucumber-React: Render description sections as Markdown

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#863]
We should pass them through a Markdown processor such as [Marked](https://marked.js.org)

**Comment by codemrkay** [comment]
Hi, I'm new in this project. Changes are in Pull Request #909

**Comment by codemrkay** [comment]
@aslakhellesoy as a reporter of this issue could you confirm that after the merge it can be closed now?

**Comment by aslakhellesoy** [comment]
Hi @codemrkay. Yes - this is merged - just forgot to close this issue. Thanks a lot for your contribution!

I made some changes to your code to simplify it a little, and also fix some bugs (sanitisation should be done on the generated HTML, not the markdown source). See 5217f4044eaa599717241520bcc221e67e8484d7.

Today I also found a small bug: #925.
