### ISSUE TITLE
Gherkin: nested triple backticks in doc strings are escaped in the AST

### ISSUE THREAD

**Issue by rayjolt** [cucumber/cucumber#865]
## Summary

When parsing the following feature using the Python Gherkin parser, the nested doc string is escaped in the AST, when it should not be.

    Feature: A feature
      Scenario: A scenario
        Given I have a doc string
          ```
            \`\`\`
            Nested doc string
            \`\`\`
          ```

## Steps to Reproduce

1. Save the above feature file as "test.feature".
2. Parse the feature file using the following Python code, changing the path to the feature file as necessary:

```python
from pathlib import Path
from gherkin.parser import Parser

text = Path("/path/to/test.feature").read_text(encoding="utf-8")
parser = Parser()
ast = parser.parse(text)
print(ast)
```

## Current Behavior

The following AST is produced. Note that the backticks `` \`\`\` `` in the doc string content are escaped.

```python
 {'type': 'GherkinDocument', 'feature': {'type': 'Feature', 'tags': [], 'location': {'line': 1, 'column': 1}, 'language': 'en', 'keyword': 'Feature', 'name': 'A feature', 'children': [{'type': 'Scenario', 'tags': [], 'location': {'line': 2, 'column': 3}, 'keyword': 'Scenario', 'name': 'A scenario', 'steps': [{'type': 'Step', 'location': {'line': 3, 'column': 5}, 'keyword': 'Given ', 'text': 'I have a doc string', 'argument': {'type': 'DocString', 'location': {'line': 4, 'column': 7}, 'content': '  \\`\\`\\`\n  Nested doc string\n  \\`\\`\\`'}}]}]}, 'comments': []}
```

## Expected Behavior

I was expecting this to produce the following AST. Note that the backticks `` ``` `` in the doc string content are not escaped.

```python
 {'type': 'GherkinDocument', 'feature': {'type': 'Feature', 'tags': [], 'location': {'line': 1, 'column': 1}, 'language': 'en', 'keyword': 'Feature', 'name': 'A feature', 'children': [{'type': 'Scenario', 'tags': [], 'location': {'line': 2, 'column': 3}, 'keyword': 'Scenario', 'name': 'A scenario', 'steps': [{'type': 'Step', 'location': {'line': 3, 'column': 5}, 'keyword': 'Given ', 'text': 'I have a doc string', 'argument': {'type': 'DocString', 'location': {'line': 4, 'column': 7}, 'content': '  ```\n  Nested doc string\n  ```'}}]}]}, 'comments': []}
```

## Context & Motivation

This will be used in [ducminh-phan/reformat-gherkin](https://github.com/ducminh-phan/reformat-gherkin) to reformat Gherkin files. At the moment, the doc strings in these two features produce identical ASTs.

Number one:

    Feature: A feature
      Scenario: A scenario
        Given I have a doc string
          ```
            \`\`\`
            Nested doc string
            \`\`\`
          ```

Number two:

    Feature: A feature
      Scenario: A scenario
        Given I have a doc string
          """
            \`\`\`
            Nested doc string
            \`\`\`
          """

In the first case, we should reformat the doc string like this:

    Feature: A feature
      Scenario: A scenario
        Given I have a doc string
          """
            ```
            Nested doc string
            ```
          """

However, in the second case, we should leave it as it is. The problem is, there is no way of knowing which we should do because of the extra escaping of backticks in the Gherkin AST.

## Environment

* Version used: gherkin-python 5.0.0
* Operating System and version: Ubuntu 18.04.3 LTS

**Comment by mpkorstanje** [comment]
Confirmed in master. 

Looks like all languages have the same problem in the token matcher. Rather then escaping the active doc string separator, the standard doc string separator is always escaped. For example:

```
return activeDocStringSeparator != null ? text.replace("\\\"\\\"\\\"", "\"\"\"") : text;
```

I would at this point say that using the alternative doc string separator is not supported.

**Comment by mpkorstanje** [comment]
@aslakhellesoy I don't see any recent versions of Gherkin in the `gherkin-official` in python packages and there cukebot doesn't have any credentials. Are we not releasing there any more?

**Comment by aslakhellesoy** [comment]
We haven’t released Gherkin for Python in a while because we don’t have an active maintainer.

Evolution of the Gherkin API and messages has required us to also disable the build of Gherkin for Python because the shared test suite has not been passing in a while.

The same has happened for all the other implementations except Java/Go/JavaScript/Ruby.

I suppose we should have created a GitHub issue when we disabled it.
