### ISSUE TITLE
Ordinal execution of features

### ISSUE THREAD

**Issue by magicalbanana** [cucumber/cucumber#867]
What's the best way to ordinalize feature execution?

Let's say I have these features:

registration.feature
approve_registration.feature
deny_registration.feature
pend_registration.feature

Let's say I want to execute registration before any of the three below it, what would be the best way to approach this?

Is it currently possible to call a feature inside a feature?

**Comment by aslakhellesoy** [comment]
Please use one if the [support](https://cucumber.io/support) channels for questions. This is a bug tracker.
