### ISSUE TITLE
meta: Rule support across Cucumber implementations

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber#869]
A central issue to track state of support for Gherkin's `Rule` keyword across official Cucumber implementations.

- **Java** - Limited support in 5.0.0, full support coming soon ([project](https://github.com/orgs/cucumber/projects/6#card-27917518))
- **JavaScript** - Coming soon in 7.0.0 ([pull request](https://github.com/cucumber/cucumber-js/pull/1273))
- **Ruby** - Coming soon in 4.0.0
- **.NET** - Since SpecFlow 3.1
- **Go** - Not supported yet

**Comment by davidjgoss** [comment]
This issue can be linked from the docs (see https://github.com/cucumber/docs.cucumber.io/pull/440) and closed once all implementations have `Rule` support in their latest stable version.

I'm not exactly clear on the status/outlok for .NET and Go, maybe someone could update those?

**Comment by justindwyer6** [comment]
Is there any update on Ruby support for this?

**Comment by luke-hill** [comment]
@justindwyer6 - At the moment Cucumber4 was just released, primarily this changed a lot of auto-loading algorithm stuff and it also started to use the new formatters. That was always the plan for v4. It's likely this won't hit ruby in the short term, but it could hit at some point during the v4 life-cycle. I've been a bit out of the loop recently, but I will be getting back involved a lot more soon.

**Comment by p2635** [comment]
Any news on the .NET side?

**Comment by luke-hill** [comment]
ping @sabotageandi

**Comment by SabotageAndi** [comment]
@p2635 

It is there since SpecFlow 3.1:

https://specflow.org/blog/specflow-specflowrunner-3-1-are-here/
https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html#rule

There are still limitations in the VS Extensions with it, but at runtime it is working.

**Comment by SabotageAndi** [comment]
I adjusted the issue description

**Comment by p2635** [comment]
Thanks @SabotageAndi , how can I follow the updates with the syntax highlighting? I've subscribed to this issue so I hope that is enough.

**Comment by SabotageAndi** [comment]
@p2635 No, subscribing to this issue will not be enough. Without @luke-hill ping, I would never notice this issue. The SpecFlow development happens in its own GitHub organization. We don't monitor the cucumber repositories. The best way to notice if there is an update to it is to follow us on Twitter or our Blog.

**Comment by p2635** [comment]
That's great @SabotageAndi , I'm already subscribed to the blog so it's all good.

**Comment by luke-hill** [comment]
Given this is implemented in most other languages. And gherkin has for several versions had Rule working stably, I'll close this issue.
