### ISSUE TITLE
How to  Do Gherkin Page Objects Integration

### ISSUE THREAD

**Issue by pravinmitta** [cucumber/cucumber#878]
Hi All,

How we can create / do page object integration in Gherkin and how we can work with or create tags in Gherkin. Can you give me a brief how to do these above issues/tasks

Regards,
PraveenMSV

**Comment by sgrillon14** [comment]
your Gerkin file:

 ```
    Then 'camunda.CamundaPage-tasklist' is visible
 ```

Your java class:

 ```
    @Then("{page-element} is visible")
    public void waitVisibilityOf(PageElement pageElement) {
        ....
    }
```

your custom configure Type Registry:

 ```
    @Override
    public void configureTypeRegistry(TypeRegistry registry) {
        registry.defineParameterType(new ParameterType<Page>("page", "\\'(.+\\..+)\\'", Page.class, (final String strPage) -> { return Page.getInstance(strPage); }));
    }

 ```

You can find a more simple sample here: https://grasshopper.tech/311/

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/tools/cucumber-open/support/) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
