### ISSUE TITLE
Gherkin: Feature or Rule level parameterization

### ISSUE THREAD

**Issue by modelarious** [cucumber/cucumber#879]
## Summary

I have a situation where I'm using the same set of parameters for every Scenario Outline in my test suite:

```
Feature: Check functionA()

  Scenario Outline: functionA() is called - correct page type returned --  <type>
    Given I load the site and go to a <type> page
    Then the page type is <type>

    Examples:
      | type |
      | "product" |
      | "home" |
      | "collection" |
      ... several more entries ...

  Scenario Outline: functionA() - no errors -- <type>
    Given I load the site and go to a <type> page
    Then I should see no errors are thrown

    Examples:
      | type |
      | "product" |
      | "home" |
      | "collection" |
      ... several more entries ...

  Scenario Outline: functionA() - minimal delay -- <type>
    Given I load the site and go to a <type> page
    Then there is a minimal delay before calling functionA()

    Examples:
      | type |
      | "product" |
      | "home" |
      | "collection" |
      ... several more entries ...

  ...many more tests using an identical Examples array
```

I'm looking to improve the structure of this code and the best way I can see to do that would be to be able to put the `Examples` section outside of the individual `Scenario Outlines` as global params that parameterize either a Feature or a Rule.  Essentially I'm looking to run each of these `Scenarios` with each of the entries in `Examples` without having to repeat the `Examples` array for each `Scenario`.

Essentially parameterizing a test **suite** instead of individual test **cases** inside of a test suite

## Expected Behavior

Perhaps something like a `Feature Outline` would be a good solution, where I could define what I want the value of `<type>` to be for the entire run of a `Feature`.   Code like the following:
```
Feature Outline: Check functionA() for page type <type>

  Examples:
    | type |
    | "product" |
    | "home" |
    | "collection" |
    ... several more entries ...

  Scenario: functionA() is called - correct page type returned
    Given I load the site and go to a <type> page
    Then the page type is <type>

  Scenario: functionA() - no errors
    Given I load the site and go to a <type> page
    Then I should see no errors are thrown

  Scenario: functionA() - minimal delay
    Given I load the site and go to a <type> page
    Then there is a minimal delay before calling functionA()
  
  ...many more tests using an identical Examples array
```

could produce the following run:

```
Feature: Check functionA() for page type "product"
      - Scenario: functionA() is called - correct page type returned
      - Scenario: functionA() - no errors
      - Scenario: functionA() - minimal delay
      - ...

Feature: Check functionA() for page type "home"
      - Scenario: functionA() is called - correct page type returned
      - Scenario: functionA() - no errors
      - Scenario: functionA() - minimal delay
      - ...

Feature: Check functionA() for page type "collection"
      - Scenario: functionA() is called - correct page type returned
      - Scenario: functionA() - no errors
      - Scenario: functionA() - minimal delay
      - ...
...
```

Or something like a `Rule Outline`, where I could define what I want the value of `<type>` to be for the entire run of a `Rule`.   Code like the following:
```
Feature: Check functionA()

  Rule Outline: verify functionA() on page type <type>

    Examples:
      | type |
      | "product" |
      | "home" |
      | "collection" |
      ... several more entries ...

    Scenario: functionA() is called - correct page type returned
      Given I load the site and go to a <type> page
      Then the page type is <type>

    Scenario: functionA() - no errors
      Given I load the site and go to a <type> page
      Then I should see no errors are thrown

    Scenario: functionA() - minimal delay
      Given I load the site and go to a <type> page
      Then there is a minimal delay before calling functionA()
  
    ...many more tests in the same rule using an identical Examples array
```
could produce the following run:

```
Feature: Check functionA()
      - Rule: verify functionA() on page type "product"
          - Scenario: functionA() is called - correct page type returned
          - Scenario: functionA() - no errors
          - Scenario: functionA() - minimal delay
          - ...
      - Rule: verify functionA() on page type "home"
          - Scenario: functionA() is called - correct page type returned
          - Scenario: functionA() - no errors
          - Scenario: functionA() - minimal delay
          - ...
      - Rule: verify functionA() on page type "collection"
          - Scenario: functionA() is called - correct page type returned
          - Scenario: functionA() - no errors
          - Scenario: functionA() - minimal delay
          - ...
      -...
```

NOTE: I'd expect to also be able to parameterize a `Scenario Outline` inside the `Rule Outline` or `Feature Outline`. Meaning I could do the following:

```
Feature: Check functionA()

  Rule Outline: verify functionA() errors on page type <type>

    Examples:
      | type |
      | "product" |
      | "home" |
      | "collection" |
      ... several more entries ...

    Scenario Outline: functionA() - Doesn't return <error>
      Given I load the site and go to a <type> page
      Then I should see <error> is not thrown
      
      Examples:
        | error |
        | IDMissingError |
        | PasswordMissingError |
        | TimeMissingError |
        ...

    Scenario: functionA() is called - correct page type returned
      Given I load the site and go to a <type> page
      Then the page type is <type>

    Scenario: functionA() - minimal delay
      Given I load the site and go to a <type> page
      Then there is a minimal delay before calling functionA()
```

which would create a run like:

```
Feature: Check functionA()
      - Rule: verify functionA() on page type "product"
          - Scenario: functionA() - Doesn't return IDMissingError
          - Scenario: functionA() - Doesn't return PasswordMissingError
          - Scenario: functionA() - Doesn't return TimeMissingError
          - ... rest of errors
          - Scenario: functionA() is called - correct page type returned
          - Scenario: functionA() - minimal delay
          - ...
      - Rule: verify functionA() on page type "home"
          - Scenario: functionA() - Doesn't return IDMissingError
          - Scenario: functionA() - Doesn't return PasswordMissingError
          - Scenario: functionA() - Doesn't return TimeMissingError
          - ... rest of errors
          - Scenario: functionA() is called - correct page type returned
          - Scenario: functionA() - minimal delay
          - ...
      - Rule: verify functionA() on page type "collection"
          - Scenario: functionA() - Doesn't return IDMissingError
          - Scenario: functionA() - Doesn't return PasswordMissingError
          - Scenario: functionA() - Doesn't return TimeMissingError
          - ... rest of errors
          - Scenario: functionA() is called - correct page type returned
          - Scenario: functionA() - minimal delay
          - ...
      -...
```

## Context & Motivation

I'm trying to repeat code less to reduce editing time in the future.  Also really like being able to get a lot of tests out of a little amount of code.

Currently I'm using bash to generate each version of the feature file that I want (In my above example that means I have a different feature file for each type of page), but I'd much rather be able to write it concisely and avoid using code that generates other code.

Should mention that I'm working in Javascript.

**Comment by jenisys** [comment]
There are alternative solutions beside extending Gherkin (that you should be aware of):

* Gherkin feature files are TEXT. 
  Therefore, you can use a textual template engine as build step before the test run w/ Cucumber.

* Provide a different kind of steps (dialect) that can have the for-loop inside the step implementation (harder and depends on your exact use case if this approach is feasible), like:

```Gherkin 
Check/Ensure that ALL_PAGES on my website do not have any of the following errors (specified as table)

HINTS: 
ALL_PAGES specifies the internally known group of pages.
You can add other groups of pages, too (as long as the group name is understandable).
```

**Comment by aslakhellesoy** [comment]
I agree with @jenisys here. You could generate your feature file from a template, and keep the examples table in a separate file.

I'm not keen on changing the grammar to support this natively - it would have huge ripple effects.

**Comment by MeyerNils** [comment]
I can imagine that there are quite some effects to expect when changing the grammar. But nevertheless like to mention here that I can fully understand @modelarious request and have as well situations where I'd like to re-use same Examples in different scenarios within one feature. I could implement the templating approach but I'd loose the advantage of business users being immediately able to understand what is actually tested by only looking at a .feature file.

**Comment by enkessler** [comment]
Putting aside the knee-jerk reaction of "but effort, though" on either side of the debate, I'm curious:

What is fundamentally different between a template scoped to one Gherkin element (e.g. an outline) and a template scoped to a different Gherkin element (e.g. a feature). What's the argument for/against one of them that wouldn't also suggest that the other one should also be treated the same way?

**Comment by enkessler** [comment]
To put it another way: should we start discussing getting rid of outline templates too?

**Comment by MeyerNils** [comment]
I didn't meant to offend anybody with my "effort, but nevertheless", but just wanted to explain why I'm re-discussing an already closed issue. Sorry, if you got me wrong there. But let's put this aside. 

I think both `Scenarios` and `Features` should have the possibility to define `Examples` to replace `< >` delimited parameters. I like the way how it's possible with `Scenario Outlines` / `Scenario Templates` but I miss the possibility to re-use same `Examples` for different Outlines.  To be consistent and treat different Gherkin elements in the same manner this could possibly mean allowing `< >`delimited placeholders as well in `Backgrounds`, although I can't imagine a real need for this in my use cases. 

These `Scenario Outlines` / `Scenario Templates` with the corresponding examples in the .feature file are from my point of view business-user-understandable templates, as you can find placeholders and replacement values directly at the same place. It's different from my point of view if some build logic is combining different source files like with the "textual template engine as build step" approach mentioned above. When I was writing "templating approach" I was referencing the "textual template engine as build step", not the `Scenario Templates` (having `Scenario Outlines` in mind as the keyword that I'm usually using). Sorry for being not precise here. 

So answering your last question - no, I don't think `Outline Templates` should be removed, I think it's useful to have an option to run same tests over variations of data.

**Comment by enkessler** [comment]
No worries. No offense was taken. Heck, my comment wasn't even directed at you specifically. It was more an out loud musing in order to prompt some conversation about why some design decisions are taken and others are avoided. Admittedly, this is an old issue and we might be the only two people in the conversation.

"Effort" is just often a common theme in such conversations, where both sides would be happier if the other side would just do something in a different way which, coincidentally, means that they don't have to change. Meanwhile, I stand off to the side asking "Okay, but what actually makes sense within the system?". ;)
