### ISSUE TITLE
Suggestion: Background with Examples Table (like Scenario Outline)

### ISSUE THREAD

**Issue by lflucasferreira** [cucumber/cucumber#899]
Hi there,

I do not know it the following will be possible but I am trying to pass a table of users to the Given steps located in the Background section. But as expected, it does not work. Because of that, I need to repeat the same Given step for each scenario and pass the same example table as well.

Is there any way to implement this or should I create one feature for each user and use the Background section to specify the user I want to use in order to log in and perform the required actions?

Another thing I miss the most is the possibility to use the same step gherkin description without using the same step definition. I mean, sometimes I need to specify different actions to a step but I cannot unless I use an if-else or case statement, ugly.

Thank you in advance.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/tools/cucumber-open/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

When you do, please give an example of the Gherkin you expected to work.
