### ISSUE TITLE
Feature Request: Undefined step, leading to suggested alternative(s) from current glue

### ISSUE THREAD

**Issue by sebrose** [cucumber/cucumber#90]
## Summary

Wouldn't it be nice if Cucumber could suggest step definitions from the current project's glue that are similar to the undefined step that is currently being matched.
## Possible Solution

There are fuzzy regex matching libraries available e.g. http://laurikari.net/tre/
## Context & Motivation

When a step fails to match an undefined error is thrown and a snippet emitted. Often the failure is due to simple mistyping by the user. It would be nice if Cucumber could suggest step definitions that _almost_ matched.

This could make it much simpler to pick up many categories of error, such as missing spaces and/or misspelt words

**Comment by mattwynne** [comment]
That's a lovely idea!

**Comment by gmk1217** [comment]
Excellent...!

**Comment by LaAzteca** [comment]
++
