### ISSUE TITLE
gherkin-javascript: parse gherkin file from stream via command line

### ISSUE THREAD

**Issue by matthyy** [cucumber/cucumber#904]
## Summary

When trying to use the binary "gherkin-javascript" through command line, without indicating any path to the file but passing a file through pipe and process.stdin, it fails with the error "Callback must be a function".  The exact command was the following one "cat hello.feature | ./node_modules/.bin/gherkin-javascript"

To give you some context, the overall goal is to create a prettier plugin for gherkin files with ".feature" extension. Therefore prettier opens every file and pass the text to our plugin responsible of giving back an AST. We would like to use the command the process the text through a stream which will give us back the AST for a given text. 

However the command fails with the error "Callback must be a function".  I'm very interested in getting to know what I did wrong. Just to mention it, I used to command with indicating a path to the same file, and the command worked. I obtained AST as expected

## Expected Behavior

All my options were set to true meaning "includeSource", "includeGherkinDocument", and "includePickles", I expected to get a AST with Document, Pickles and source document. 

## Current Behavior

What I got was an error which was the following one "Callback must be a function"

## Possible Solution

I cloned the repo and went into the code to see what could have gone wrong. From what I understood, one the problem comes from the fact there is no callback passed to the method "pipeline" used in the cli command. I added one to see the result and rebuilt the project. I got rid of the error "Callback must be a function"  but I got a second error regarding the decode method saying that "this.decode" was not a function. In my opinion and when I compared to the test scenarios, it made kind of sense and we might have bind the method "BinaryToMessageStream" as it is done in test scenarios. I made the change and bind the method to "this" but it didn't work, too. I'm then very interested in getting your opinion on the subject.

## Steps to Reproduce (for bugs)

1. I created a projet
2. I installed via npm the gherkin-javascript package
3. I created a basic gherkin file. I actually copied the file "datatables.feature" present in test scenrios in your projet.
4. I played the following command "cat hello.feature | ./node_modules/.bin/gherkin-javascript"
5. I obtained the error "Callback must be a function"
6. I added a callback to the pipeline method
7. I got the error "node_modules/cucumber-messages/dist/src/cucumber-messages.js:968 / return this.decode(reader, reader.uint32()); /this.decode is not a function"

## Your Environment
OS: Mac
Node : v12.14.0
gherkin: 9.0.0

I'm of course available to discuss and give your more information if needed.

Bests.
Matthieu

**Comment by KnorpelSenf** [comment]
You're not the only one. I ended up creating a temporary file, piping my contents in there, running the parser `fromPaths`, and then deleting my temporary file again. This is so ugly …

**Comment by msilveus1** [comment]
This is still an issue in 2021.  Is there any timeline of this bug being fixed?
