### ISSUE TITLE
Cucumber report version 4.11.0 in Jenkins

### ISSUE THREAD

**Issue by Anju-sys** [cucumber/cucumber#917]
## Summary

After generated html report from Json report using the Cucumber Reports plugin, I found that for hooks we see the following names: Before $_noescape_stepName  in Jenkins,how to avoid this? 

## Expected Behavior

It should show Scenarion Name (or nothing) in Before () hook 

## Current Behavior

Before $_noescape_stepName  **OR**  Before <last scenario's last step name>

## Possible Solution

Before <scenario name>

## Steps to Reproduce (for bugs)

1.Used **CucucmberJS** Report ( ie Cucumber-html-reporter) locally ,it is working fine ,but using Cucumber reports version 4.11.0 in Jenkins ,which is displaying as **Before $_noescape_stepName  **OR**  Before <last scenario's last step name>**

2.
3.
4.

## Your Environment

* Version used:
* Operating System and version: Windows 10 
* Link to your project:

**Comment by mpkorstanje** [comment]
The Cucumber Reports Plugin is not maintained by the Cucumber project. Try:

https://github.com/jenkinsci/cucumber-reports-plugin

**Comment by Anju-sys** [comment]
Thanks for quick reply , :) Sorry ,am new to installation of plugins ,so where is  the **.hpi** file in this folder ,which I can upload in Jenkins

**Comment by aslakhellesoy** [comment]
@Anju-sys the Cucumber project doesn't support Jenkins or any of its plugins. Please ask the Jenkins community.
