### ISSUE TITLE
Multiple broken links in docs

### ISSUE THREAD

**Issue by hirad** [cucumber/cucumber#92]
## Summary

Most of the links on [this](https://github.com/cucumber/cucumber/blob/master/docs/architecture/writing-a-new-cucumber.md) page are broken.

## Expected Behavior

Links in docs point at valid and up-to-date pages.

## Current Behavior

The link to "Gherkin" on the page linked to above doesn't go anywhere.
The 3 links titled "JavaScript" under a "Here's how it's done" subheadings point to invalid addresses (404). The same is true to the link to the Cucumber mailing list.

## Possible Solution

Someone who knows where these additional docs have moved to can update the links.

## Steps to Reproduce (for bugs)

1. Visit the [page](https://github.com/cucumber/cucumber/blob/master/docs/architecture/writing-a-new-cucumber.md).
2. Click on any of the links mentioned above.

## Context & Motivation

This was my first encounter with Cucumber and I was curious to learn more about the implementation. I was hoping the docs would help me understand how cucumber is built for different platforms.

## Your Environment

N/A

**Comment by its-poole** [comment]
In the README, `testdata/good` should also point to `https://github.com/cucumber/cucumber/tree/master/gherkin/testdata/good` instead of `https://github.com/cucumber/gherkin/tree/master/testdata/good`

**Comment by mlvandijk** [comment]
Note 'testdata/good' link was fixed

**Comment by mlvandijk** [comment]
For latest documentation, please see: https://github.com/mlvandijk/docs.cucumber.io
Any changes/updates can be made there.

**Comment by its-poole** [comment]
👍
