### ISSUE TITLE
gherkin: Attachment should not be reused for parse errors

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#936]
Parse errors are a specific event that needs to be acted upon. Reusing attachment for parse errors is awkward to say the least.

It means that fields in attachment must be optional because parse errors don't have a `test_step_id`, `test_case_started_id` or `media_type`. At the same time attachments in java don't ever have a `source`.

It is preferable to have as few optional fields as possible.

**Comment by aslakhellesoy** [comment]
Yeah I agree!
