### ISSUE TITLE
gherkin: `go get github.com/cucumber/cucumber/gherkin/go` not working

### ISSUE THREAD

**Issue by W-R-Ramirez** [cucumber/cucumber#941]
Trying to use gherkin in go, but 'go get github.com/cucumber/cucumber/gherkin/go' is returning
""
go get github.com/cucumber/cucumber/gherkin/go: module github.com/cucumber/cucumber@upgrade found (v0.0.0-20200318141525-aea94e0de737), but does not contain package github.com/cucumber/cucumber/gherkin/go
""

Not sure what I'm doing wrong or how to fix this any help would be appreciated!

**Comment by mpkorstanje** [comment]
Try the read only sub-repo. Go needs all the stuff to be in the root of the repo.

https://github.com/cucumber/gherkin-go
