### ISSUE TITLE
messages: Clean up unsued message prior to release

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#951]
The message protocol still contains a number of messages that are related to Cucumber Engine that currently go unused. Separating these out now, will:
 * Make it easier to evolve the protocol later
 * Make it easier for people to understand the current implementation
 * Remove a large amount of effectively unused code and documentation.

Once they're included in a release from Cucumber this will all become harder to reason about.

**Comment by aslakhellesoy** [comment]
I agree. I will make a PR to remove messages that aren't referenced by any of the producers or consumers in the monorepo:

* Producers: `gherkin`, `fake-cucumber` and `json-to-features` (#938)
* Consumers: `*-formatter` and `react`

This means the messages that are only referenced [cucumber-engine](https://github.com/cucumber/cucumber-engine) would have to be moved elsewhere. But that project seems to have fallen by the wayside now. Thoughts @charlierudolph?

**Comment by charlierudolph** [comment]
I'm good with removing them. I can pull them from history if I need them for cucumber-engine but think that may not be used with the current evolution. Was fun to write and can maybe be used a bit in cucumber-go

**Comment by aslakhellesoy** [comment]
Fixed by #962
