### ISSUE TITLE
build: Language specific build is broken

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#954]
A while ago we introduced the ability to only build specific language implementations. E.g. by using `LANGUAGES=java make`. With the introduction of the `html-formatter` and  this no longer works as the `html-formatter/java` has a dependency on `react/javascript`.

**Comment by aslakhellesoy** [comment]
I wouldn't call it broken. All it does is to build just one particular language, which is often useful, but will fail when there are dependencies from one language to another.

So for java you have to build javascript first.

Do you have a fix in mind?

**Comment by mpkorstanje** [comment]
Something that would build the dependencies as needed would be nice but I'm not sure how to do that in make.  

So make targets for `java`, `javascript`, ect. Where `java` would have `javascript` as a prerequisite. So you can do `make java`. 

--

Owh btw. `LANGUAGES=javascripot make` seems to have a dependency on `ruby`. Might be good to add these commands to the CI too.
