### ISSUE TITLE
json-to-messages build hangs indefinitely

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#961]
Here is the output before it starts hanging:

```
✘ acceptance/java/parameters/parameters.ndjson
make[2]: [acceptance/java/parameters/parameters.ndjson.json] Error 1 (ignored)
mkdir -p acceptance/java/statuses
../../compatibility-kit/scripts/run-formatter \
                -e .json \
                -o acceptance/java/statuses \
                -c "../../compatibility-kit/scripts/cucumber-json-formatter" \
                acceptance/java/statuses/statuses.ndjson
✔ acceptance/java/statuses/statuses.ndjson
mkdir -p acceptance/java
cat acceptance/java/hooks/hooks.ndjson acceptance/java/parameters/parameters.ndjson acceptance/java/statuses/statuses.ndjson > acceptance/java/all.ndjson
mkdir -p acceptance/java
../../compatibility-kit/scripts/run-formatter \
                -e .html \
                -o acceptance/java \
                -c "../../compatibility-kit/scripts/cucumber-html-formatter" \
                acceptance/java/all.ndjson
✔ acceptance/java/all.ndjson
mkdir -p acceptance/python
cat  > acceptance/python/all.ndjson
```

Note that the last `cat` isn't catting a file (which I expect it should), and therefore it's waiting indefinitely for input from STDIN.

I think this needs to be stricter and fail if the variable is empty. I've just done a `make clean` which might explain why this variable is empty. I haven't looked in detail.

**Comment by aslakhellesoy** [comment]
Or maybe it fails because I don't have behave installed. If that's the case, the build should tell me I need to install it.

**Comment by vincent-psarga** [comment]
Humpfff, I had seen that before and thought I solved it :/ I'm having a look.

**Comment by mpkorstanje** [comment]
Sounds like an dependency order problem

You'll have to check if the files being catted are there. They may depend on another project being build.


I fixed a problem exactly like this here:
https://github.com/cucumber/cucumber/pull/955

**Comment by vincent-psarga** [comment]
Well, the acceptance tests for this library rely on JSON reports produced by `cucumber-ruby`, `cucumber-jvm`, `cucumber-js` and `behave`.
It doe not rely on another library but the other languages need to have been built properly. I'm on it (a soon a I get the monorepo up and running :D )
