### ISSUE TITLE
Doc: Things that are not Cucumber problems

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#97]
## Summary

People frequently use Cucumber alongside other tools. For various reasons, many end up asking questions about other tools in the Cucumber forums.

By providing a list of these tools, people are more likely to ask in the right place, and contributors can spend time explaining the same things over and over again.

i got the idea from this page: ~http://gitolite.com/gitolite/gitolite.html#ngp~

http://gitolite.com/gitolite/emergencies/#things-that-are-not-gitolite-problems

## Expected Behavior

1) 
User has a question about Selenium
Finds this page
Asks question in most appropriate place

2)
User has a question about Selenium
Asks in Cucumber forum
Contributor sends short email pointing to this page

## Current Behavior

User has a question about Selenium
Asks in Cucumber forum (can't find info suggesting a different forum)
May get a reply, may not, because it takes effort to write

~~~
~~~

## Possible Solution

Have a dedicated page to the unrelated thing, linking to this page.

## Context & Motivation

Users get more efficient at troubleshooting. Contributors get fewer irrelevant questions.

**Comment by olleolleolle** [comment]
@aslakhellesoy I in-place updated your URL to the Gitolite "not gitolite problem" page. The URL is: http://gitolite.com/gitolite/emergencies/#things-that-are-not-gitolite-problems

**Comment by mlvandijk** [comment]
@aslakhellesoy Should this be in the docs.cucumber.io project? (can an issue be 'moved' or should it be replicated?)

**Comment by mlvandijk** [comment]
Regarding Selenium, they also use Slack: https://seleniumhq.herokuapp.com/

**Comment by mlvandijk** [comment]
@aslakhellesoy I do rather like this idea, let's move it to the docs project?

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/docs.cucumber.io#68
