### ISSUE TITLE
Proposal: JSON reports to support a hierarchy of Steps

### ISSUE THREAD

**Issue by Kausam** [cucumber/cucumber#979]
## Summary
Test-automation tools like `karate` allow us to call a `Scenario` from a `Step`. It would be awesome if the json output supports having multiple `Step`s inside a `Step`. This would enable reporting tools to create more readable reports.

## Expected Behavior
If we allow a single `Step` to contain all the nested `Step`s it calls,
Reporting tools can then leverage this and display the result in a much more readable format. A [short json snippet](https://ideone.com/Oiefm6) highlighting the proposed change.
<img width="1072" alt="ProposedReport" src="https://user-images.githubusercontent.com/19550684/79882057-a5d81880-840f-11ea-84f6-5a08574544a8.png">
The above report can be generated by using [this](https://ideone.com/ewBxm0) json and a slightly modified version of the [cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting) tool.

## Current Behavior
Currently, all the steps (including the steps from nested features) are put at the same level in the json output. This means that the generated report can potentially show thousands of steps all at once.
[Current json file](https://ideone.com/Ien4vy) plugged into the existing reporting tool generates the following report:
<img width="1095" alt="CurrentReport" src="https://user-images.githubusercontent.com/19550684/79881169-8391cb00-840e-11ea-933b-3729346b6882.png">
## Possible Solution

We can add `childSteps` array to the existing json structure definitions. For example, we'd need to add the line ``Steps       []*jsonStep `json:"steps"` `` in the [jsonStep struct](https://github.com/cucumber/cucumber/blob/1c427551710c911092413eadbf22c46cbdd93f7a/json-formatter/go/json_elements.go#L31)
## Context & Motivation

I found it hard to understand/go through a 4000 line html report. The few important(top level) steps were getting lost among a myriad of irrelevant steps. Having an option to hide nested steps would make the report easier to deal with. For reporting tools to allow this, the json should support `Step` hierarchy.

**Comment by marnen** [comment]
It looks to me like you may be trying to map steps one-to-one to low-level setup operations, which is really not how steps are supposed to work AFAIK (though if the core team wants to correct me on any of this, listen to them, not me). Each step is supposed to be one atomic operation from the perspective of the *user*, not that of the *programmer*.

So in this case, most of this could probably go in a Before hook, or perhaps in a single setup step, rather than cluttering up the human-readable scenario description at all:

```gherkin
Background:
  Given I am configured for the "us" locale

Scenario:
  When I read the car data
  Then I should see a vehicle called "Mercedes"
  And I should see a vehicle called "Chevrolet"
  # or whatever you're actually trying to test here
```

Does that make sense?

**Comment by aslakhellesoy** [comment]
Cucumber will be phasing out the JSON report. The next major releases of the Java/Ruby/JavaScript implementations will use [cucumber-messages](https://github.com/cucumber/cucumber/tree/master/messages) instead.

We encourage all tool vendors depending on the JSON format to start migrating to the new message protocol, and will discourage any more changes to the JSON format.

**Comment by aslakhellesoy** [comment]
I'm closing this since the JSON format will no longer evolve.
