### ISSUE TITLE
Lexing error  'Then: I should see the same metadata with new document id

### ISSUE THREAD

**Issue by halladey** [cucumber/cucumber#98]
Lexing error on line 21: 'Then: I should see the same metadata with new document id
  Examples:
        |DocumentId|Version Number|Customer Id|Utr|Updated Date|
        |090007c28002dde2 |1.1      |customer3 |3456789012|    
        |file_type|file_size|
        |FileToUpload.doc|.09|
%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
- 26 changed lines

Running this in Eclipse, working okay in InteelJ but throwing errors in Eclipse.

**Comment by aslakhellesoy** [comment]
Please paste the source of the Gherkin document that fails to parse. Mark it up with triple backticks before and after the source to make it readable.
