### ISSUE TITLE
Create visible anchors for headers

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#983]
When people browse a big document it should be possible to link to a particular scenario with an `#anchor`. Similar to how GitHub renders Markdown headers.

It should expand the accordion if necessary.

@bastienmalatier maybe something for you to work on next?

**Comment by bastienmalatier** [comment]
Yes ! I finish the work on hooks and then i will look at this !

**Comment by aslakhellesoy** [comment]
Bump!
