### ISSUE TITLE
json-formatter: Confusing name for this tool

### ISSUE THREAD

**Issue by sebrose** [cucumber/cucumber#985]
## Summary

This tool is not used as a formatter/plugin within Cucumber. Instead it is intended to help with the transition to protobuf messages by acting as a post-processor, consuming messages and emitting JSON.

Calling the tool json-formatter doesn't give a clear indication that it transforms messages into JSON.

## Expected Behavior

A name that clearly indicates that the tool transforms protobuf messages into JSON.

## Current Behavior

The name implies (to me) that it acts as a Cucumber formatter

## Possible Solution

protobuf-to-json-convertor
protobuf-to-json-transformer
protobuf-to-json-adapter

**Comment by vincent-psarga** [comment]
`messages-to-json` to mirror the name of the tool doing the opposite work ?

**Comment by aslakhellesoy** [comment]
With the new message architecture we have decided on the following for "new" formatters.

* All formatters are consumers of cucumber messages and producers of whatever they like (html, json, junit-xml, terminal output...)
* Formatters are implemented as libraries, with a function that accepts a readable message stream.
* Formatters *may* ship with a command line tool that consumes messages from STDIN
* Cucumber implementations use formatter libraries, hooking them up to their internal message stream.

This is how the [html-formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter) works.

It's also how the json-formatter works. It is a library. It also has a CLI. It could have been used in Godog (but it's not).

I think we should use a consistent naming convention for all of the formatters. All formatters in this new architecture are going to be consumers of cucumber messages, transforming them to some other representation.

We could abandon the "formatter name" completely and settle for some kind of prefix:

* `cucumber-messages-to-json`
* `cucumber-messages-to-html`
* `cucumber-messages-to-junit-xml`
* `cucumber-messages-to-pretty`
* `cucumber-messages-to-progress`

(I don't think we should use "protobuf" as part of the name - that's an implementation detail)

WDYT?

**Comment by LukasRypl** [comment]
I find it confusing as well ... I am at the beginning of converting multiple test projects from cucumber 3 to cucumber 4 (ruby) and this is the warning:
```
WARNING: --format=json is deprecated and will be removed after version 5.0.0.
Please use --format=message and stand-alone json-formatter.
json-formatter homepage: https://github.com/cucumber/cucumber/tree/master/json-formatter#cucumber-json-formatter.
```

So far I think users should do the following:
1.  Get binary (is it included in any package?) e.g on linux:
```
curl -Lkfo /usr/local/bin/cucumber-json-formatter \
    https://github.com/cucumber/cucumber/releases/download/cucumber-json-formatter%2Fv5.1.0/cucumber-json-formatter-linux-amd64 \
    && chmod a+x /usr/local/bin/cucumber-json-formatter
```
(thanks to https://github.com/cucumber/cucumber/issues/1105#issuecomment-655380720)

2.  Run cucumber and cucumber-json-formatter:
```
cucumber --format message | cucumber-json-formatter -format ndjson >cucumber-report.json
```
(thanks to https://github.com/cucumber/cucumber-ruby/issues/1439#issuecomment-652813791)

3. Now you can use `cucumber-report.json` as  before e.g as input to https://github.com/damianszczepanik/cucumber-reporting
