### ISSUE TITLE
react: Step parameters are clickable links

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber#996]
## Summary

Step parameters are rendered as clickable links while there is nothing to link to. I would expect the underline to be applied via a style rather then by using the link styling.

![image](https://user-images.githubusercontent.com/6946919/81657003-d1ab5480-9437-11ea-8a43-ffa765292bf0.png)

```
<h3><span class="keyword">When </span><span class="step-text">the string </span><a class="step-param" href="#" title="string">"hello"</a><span class="step-text"> is attached as </span><a class="step-param" href="#" title="string">"application/octet-stream"</a></h3>
```

**Comment by aslakhellesoy** [comment]
I think my half-baked idea was that clicking a parameter would take you to some sort of glossary page (where all the parameters are listed), but it's too half-baked.

So I agree with you :-)
